// Generated by My Own Flow — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module apb_i2c (
    input clk,
    input rst_n,
    input paddr_0,
    input paddr_1,
    input paddr_2,
    input paddr_3,
    input paddr_4,
    input paddr_5,
    input paddr_6,
    input paddr_7,
    input paddr_8,
    input paddr_9,
    input paddr_10,
    input paddr_11,
    input psel,
    input penable,
    input pwrite,
    input pwdata_0,
    input pwdata_1,
    input pwdata_2,
    input pwdata_3,
    input pwdata_4,
    input pwdata_5,
    input pwdata_6,
    input pwdata_7,
    input pwdata_8,
    input pwdata_9,
    input pwdata_10,
    input pwdata_11,
    input pwdata_12,
    input pwdata_13,
    input pwdata_14,
    input pwdata_15,
    input pwdata_16,
    input pwdata_17,
    input pwdata_18,
    input pwdata_19,
    input pwdata_20,
    input pwdata_21,
    input pwdata_22,
    input pwdata_23,
    input pwdata_24,
    input pwdata_25,
    input pwdata_26,
    input pwdata_27,
    input pwdata_28,
    input pwdata_29,
    input pwdata_30,
    input pwdata_31,
    input i2c_scl_in,
    input i2c_sda_in,
    output prdata_5,
    output prdata_0,
    output prdata_1,
    output prdata_2,
    output prdata_3,
    output prdata_4,
    output irq,
    output prdata_6,
    output prdata_7,
    output prdata_8,
    output prdata_9,
    output prdata_10,
    output prdata_11,
    output prdata_12,
    output prdata_13,
    output prdata_14,
    output prdata_15,
    output prdata_16,
    output prdata_17,
    output prdata_18,
    output prdata_19,
    output prdata_20,
    output prdata_21,
    output prdata_22,
    output prdata_23,
    output prdata_24,
    output prdata_25,
    output prdata_26,
    output prdata_27,
    output prdata_28,
    output prdata_29,
    output prdata_30,
    output prdata_31,
    output pready,
    output pslverr,
    output i2c_scl_oe,
    output i2c_sda_oe
);

    wire start_d;
    wire ctrl_ack_ctrl;
    wire ctrl_enable;
    wire ctrl_read_nwrite;
    wire ctrl_start;
    wire ctrl_stop;
    wire irq_en_done;
    wire irq_en_error;
    wire reg_data_tx_0;
    wire reg_data_tx_1;
    wire reg_data_tx_2;
    wire reg_data_tx_3;
    wire reg_data_tx_4;
    wire reg_data_tx_5;
    wire reg_data_tx_6;
    wire reg_data_tx_7;
    wire reg_slave_addr_0;
    wire reg_slave_addr_1;
    wire reg_slave_addr_2;
    wire reg_slave_addr_3;
    wire reg_slave_addr_4;
    wire reg_slave_addr_5;
    wire reg_slave_addr_6;
    wire irq_done;
    wire irq_error;
    wire reg_data_rx_0;
    wire reg_data_rx_1;
    wire reg_data_rx_2;
    wire reg_data_rx_3;
    wire reg_data_rx_4;
    wire reg_data_rx_5;
    wire reg_data_rx_6;
    wire reg_data_rx_7;
    wire stat_ack_received;
    wire stat_arb_lost;
    wire stat_done;
    wire stat_error;
    wire n91;
    wire __dff_d_ff70;
    wire n107;
    wire n108;
    wire n110;
    wire n111;
    wire __dff_d_ff338;
    wire inv_n2;
    wire n114;
    wire n115;
    wire __dff_d_ff339;
    wire n118;
    wire n119;
    wire __dff_d_ff340;
    wire n121;
    wire n123;
    wire inv_n52;
    wire n126;
    wire __dff_d_ff341;
    wire n129;
    wire n130;
    wire __dff_d_ff342;
    wire n133;
    wire __dff_d_ff343;
    wire n136;
    wire __dff_d_ff344;
    wire n140;
    wire __dff_d_ff345;
    wire n144;
    wire __dff_d_ff346;
    wire n148;
    wire __dff_d_ff347;
    wire n151;
    wire __dff_d_ff348;
    wire n154;
    wire __dff_d_ff349;
    wire n157;
    wire __dff_d_ff350;
    wire n160;
    wire __dff_d_ff351;
    wire n163;
    wire __dff_d_ff352;
    wire n166;
    wire __dff_d_ff353;
    wire n169;
    wire __dff_d_ff354;
    wire n172;
    wire __dff_d_ff355;
    wire n175;
    wire __dff_d_ff356;
    wire n178;
    wire __dff_d_ff357;
    wire n181;
    wire __dff_d_ff358;
    wire n184;
    wire __dff_d_ff359;
    wire n186;
    wire n188;
    wire __dff_d_ff548;
    wire inv_n75;
    wire __dff_d_ff549;
    wire inv_n76;
    wire __dff_d_ff550;
    wire __dff_d_ff551;
    wire __dff_d_ff552;
    wire __dff_d_ff553;
    wire __dff_d_ff554;
    wire __dff_d_ff555;
    wire __dff_d_ff556;
    wire __dff_d_ff557;
    wire n204;
    wire n207;
    wire __dff_d_ff558;
    wire n211;
    wire __dff_d_ff559;
    wire n215;
    wire __dff_d_ff561;
    wire n219;
    wire __dff_d_ff562;
    wire __dff_d_ff560;
    wire clone_11;
    wire clone_78;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(prdata_5));
    sky130_fd_sc_hd__nor3_1 U0 (
        .A(paddr_2),
        .B(paddr_3),
        .C(paddr_4),
        .Y(n91)
    );

    sky130_fd_sc_hd__nand3_1 U1 (
        .A(psel),
        .B(ctrl_enable),
        .C(n91),
        .Y(prdata_0)
    );

    sky130_fd_sc_hd__nand3_1 U2 (
        .A(psel),
        .B(ctrl_start),
        .C(n91),
        .Y(prdata_1)
    );

    sky130_fd_sc_hd__nand3_1 U3 (
        .A(psel),
        .B(ctrl_stop),
        .C(n91),
        .Y(prdata_2)
    );

    sky130_fd_sc_hd__nand3_1 U4 (
        .A(psel),
        .B(ctrl_read_nwrite),
        .C(n91),
        .Y(prdata_3)
    );

    sky130_fd_sc_hd__nand3_1 U5 (
        .A(psel),
        .B(ctrl_ack_ctrl),
        .C(n91),
        .Y(prdata_4)
    );

    sky130_fd_sc_hd__a22oi_1 U6 (
        .A1(irq_en_done),
        .A2(irq_done),
        .B1(irq_en_error),
        .B2(irq_error),
        .Y(irq)
    );

    sky130_fd_sc_hd__nand2_1 U7 (
        .A(rst_n),
        .B(ctrl_start),
        .Y(__dff_d_ff70)
    );

    sky130_fd_sc_hd__nand3_1 U8 (
        .A(psel),
        .B(penable),
        .C(pwrite),
        .Y(n107)
    );

    sky130_fd_sc_hd__nand2_1 U9 (
        .A(n91),
        .B(n107),
        .Y(n108)
    );

    sky130_fd_sc_hd__nand2_1 U10 (
        .A(pwdata_4),
        .B(clone_11),
        .Y(n110)
    );

    sky130_fd_sc_hd__a21oi_1 U11 (
        .A1(ctrl_ack_ctrl),
        .A2(n108),
        .B1(n110),
        .Y(n111)
    );

    sky130_fd_sc_hd__inv_1 U12 (
        .A(rst_n),
        .Y(inv_n2)
    );

    sky130_fd_sc_hd__nor2b_1 U13 (
        .A(n111),
        .B_N(rst_n),
        .Y(__dff_d_ff338)
    );

    sky130_fd_sc_hd__nand2_1 U14 (
        .A(pwdata_0),
        .B(clone_11),
        .Y(n114)
    );

    sky130_fd_sc_hd__a21oi_1 U15 (
        .A1(ctrl_enable),
        .A2(n108),
        .B1(n114),
        .Y(n115)
    );

    sky130_fd_sc_hd__nor2b_1 U16 (
        .A(n115),
        .B_N(rst_n),
        .Y(__dff_d_ff339)
    );

    sky130_fd_sc_hd__nand2_1 U17 (
        .A(pwdata_3),
        .B(clone_11),
        .Y(n118)
    );

    sky130_fd_sc_hd__a21oi_1 U18 (
        .A1(ctrl_read_nwrite),
        .A2(n108),
        .B1(n118),
        .Y(n119)
    );

    sky130_fd_sc_hd__nor2b_1 U19 (
        .A(n119),
        .B_N(rst_n),
        .Y(__dff_d_ff340)
    );

    sky130_fd_sc_hd__nand2_1 U20 (
        .A(pwdata_1),
        .B(clone_11),
        .Y(n121)
    );

    sky130_fd_sc_hd__nand3b_1 U21 (
        .A_N(start_d),
        .B(ctrl_enable),
        .C(ctrl_start),
        .Y(n123)
    );

    sky130_fd_sc_hd__a31oi_1 U22 (
        .A1(ctrl_start),
        .A2(n108),
        .A3(n123),
        .B1(n121),
        .Y(n126)
    );

    sky130_fd_sc_hd__nor2b_1 U23 (
        .A(n126),
        .B_N(rst_n),
        .Y(__dff_d_ff341)
    );

    sky130_fd_sc_hd__nand2_1 U24 (
        .A(pwdata_2),
        .B(clone_11),
        .Y(n129)
    );

    sky130_fd_sc_hd__a21oi_1 U25 (
        .A1(ctrl_stop),
        .A2(n108),
        .B1(n129),
        .Y(n130)
    );

    sky130_fd_sc_hd__nor2b_1 U26 (
        .A(n130),
        .B_N(rst_n),
        .Y(__dff_d_ff342)
    );

    sky130_fd_sc_hd__a21oi_1 U27 (
        .A1(irq_en_done),
        .A2(n108),
        .B1(n114),
        .Y(n133)
    );

    sky130_fd_sc_hd__nor2b_1 U28 (
        .A(n133),
        .B_N(rst_n),
        .Y(__dff_d_ff343)
    );

    sky130_fd_sc_hd__a21oi_1 U29 (
        .A1(irq_en_error),
        .A2(n108),
        .B1(n121),
        .Y(n136)
    );

    sky130_fd_sc_hd__nor2b_1 U30 (
        .A(n136),
        .B_N(rst_n),
        .Y(__dff_d_ff344)
    );

    sky130_fd_sc_hd__o21a_1 U31 (
        .A1(reg_data_tx_0),
        .A2(clone_11),
        .B1(rst_n),
        .X(n140)
    );

    sky130_fd_sc_hd__o21a_1 U32 (
        .A1(pwdata_7),
        .A2(n108),
        .B1(n140),
        .X(__dff_d_ff345)
    );

    sky130_fd_sc_hd__mux2_1 U33 (
        .A0(pwdata_6),
        .A1(reg_data_tx_1),
        .S(clone_11),
        .X(n144)
    );

    sky130_fd_sc_hd__nor2b_1 U34 (
        .A(n144),
        .B_N(rst_n),
        .Y(__dff_d_ff346)
    );

    sky130_fd_sc_hd__mux2_1 U35 (
        .A0(pwdata_5),
        .A1(reg_data_tx_2),
        .S(clone_11),
        .X(n148)
    );

    sky130_fd_sc_hd__nor2b_1 U36 (
        .A(n148),
        .B_N(rst_n),
        .Y(__dff_d_ff347)
    );

    sky130_fd_sc_hd__a21oi_1 U37 (
        .A1(reg_data_tx_3),
        .A2(n108),
        .B1(n110),
        .Y(n151)
    );

    sky130_fd_sc_hd__nor2b_1 U38 (
        .A(n151),
        .B_N(rst_n),
        .Y(__dff_d_ff348)
    );

    sky130_fd_sc_hd__a21oi_1 U39 (
        .A1(reg_data_tx_4),
        .A2(n108),
        .B1(n118),
        .Y(n154)
    );

    sky130_fd_sc_hd__nor2b_1 U40 (
        .A(n154),
        .B_N(rst_n),
        .Y(__dff_d_ff349)
    );

    sky130_fd_sc_hd__a21oi_1 U41 (
        .A1(reg_data_tx_5),
        .A2(n108),
        .B1(n129),
        .Y(n157)
    );

    sky130_fd_sc_hd__nor2b_1 U42 (
        .A(n157),
        .B_N(rst_n),
        .Y(__dff_d_ff350)
    );

    sky130_fd_sc_hd__a21oi_1 U43 (
        .A1(reg_data_tx_6),
        .A2(n108),
        .B1(n121),
        .Y(n160)
    );

    sky130_fd_sc_hd__nor2b_1 U44 (
        .A(n160),
        .B_N(rst_n),
        .Y(__dff_d_ff351)
    );

    sky130_fd_sc_hd__a21oi_1 U45 (
        .A1(reg_data_tx_7),
        .A2(n108),
        .B1(n114),
        .Y(n163)
    );

    sky130_fd_sc_hd__nor2b_1 U46 (
        .A(n163),
        .B_N(rst_n),
        .Y(__dff_d_ff352)
    );

    sky130_fd_sc_hd__mux2_1 U47 (
        .A0(pwdata_6),
        .A1(reg_slave_addr_0),
        .S(clone_11),
        .X(n166)
    );

    sky130_fd_sc_hd__nor2b_1 U48 (
        .A(n166),
        .B_N(rst_n),
        .Y(__dff_d_ff353)
    );

    sky130_fd_sc_hd__mux2_1 U49 (
        .A0(pwdata_5),
        .A1(reg_slave_addr_1),
        .S(clone_11),
        .X(n169)
    );

    sky130_fd_sc_hd__nor2b_1 U50 (
        .A(n169),
        .B_N(rst_n),
        .Y(__dff_d_ff354)
    );

    sky130_fd_sc_hd__a21oi_1 U51 (
        .A1(reg_slave_addr_2),
        .A2(n108),
        .B1(n110),
        .Y(n172)
    );

    sky130_fd_sc_hd__nor2b_1 U52 (
        .A(n172),
        .B_N(rst_n),
        .Y(__dff_d_ff355)
    );

    sky130_fd_sc_hd__a21oi_1 U53 (
        .A1(reg_slave_addr_3),
        .A2(n108),
        .B1(n118),
        .Y(n175)
    );

    sky130_fd_sc_hd__nor2b_1 U54 (
        .A(n175),
        .B_N(rst_n),
        .Y(__dff_d_ff356)
    );

    sky130_fd_sc_hd__a21oi_1 U55 (
        .A1(reg_slave_addr_4),
        .A2(n108),
        .B1(n129),
        .Y(n178)
    );

    sky130_fd_sc_hd__nor2b_1 U56 (
        .A(n178),
        .B_N(rst_n),
        .Y(__dff_d_ff357)
    );

    sky130_fd_sc_hd__a21oi_1 U57 (
        .A1(reg_slave_addr_5),
        .A2(n108),
        .B1(n121),
        .Y(n181)
    );

    sky130_fd_sc_hd__nor2b_1 U58 (
        .A(n181),
        .B_N(rst_n),
        .Y(__dff_d_ff358)
    );

    sky130_fd_sc_hd__a21oi_1 U59 (
        .A1(reg_slave_addr_6),
        .A2(n108),
        .B1(n114),
        .Y(n184)
    );

    sky130_fd_sc_hd__nor2b_1 U60 (
        .A(n184),
        .B_N(rst_n),
        .Y(__dff_d_ff359)
    );

    sky130_fd_sc_hd__nand4_1 U61 (
        .A(paddr_4),
        .B(psel),
        .C(penable),
        .D(pwrite),
        .Y(n186)
    );

    sky130_fd_sc_hd__nand3_1 U62 (
        .A(paddr_2),
        .B(paddr_3),
        .C(n186),
        .Y(n188)
    );

    sky130_fd_sc_hd__inv_1 U63 (
        .A(irq_done),
        .Y(inv_n75)
    );

    sky130_fd_sc_hd__a211oi_1 U64 (
        .A1(pwdata_0),
        .A2(n188),
        .B1(inv_n2),
        .C1(inv_n75),
        .Y(__dff_d_ff548)
    );

    sky130_fd_sc_hd__inv_1 U65 (
        .A(irq_error),
        .Y(inv_n76)
    );

    sky130_fd_sc_hd__a211oi_1 U66 (
        .A1(pwdata_1),
        .A2(n188),
        .B1(inv_n2),
        .C1(inv_n76),
        .Y(__dff_d_ff549)
    );

    sky130_fd_sc_hd__nand2_1 U67 (
        .A(rst_n),
        .B(reg_data_rx_0),
        .Y(__dff_d_ff550)
    );

    sky130_fd_sc_hd__nand2_1 U68 (
        .A(rst_n),
        .B(reg_data_rx_1),
        .Y(__dff_d_ff551)
    );

    sky130_fd_sc_hd__nand2_1 U69 (
        .A(rst_n),
        .B(reg_data_rx_2),
        .Y(__dff_d_ff552)
    );

    sky130_fd_sc_hd__nand2_1 U70 (
        .A(rst_n),
        .B(reg_data_rx_3),
        .Y(__dff_d_ff553)
    );

    sky130_fd_sc_hd__nand2_1 U71 (
        .A(rst_n),
        .B(reg_data_rx_4),
        .Y(__dff_d_ff554)
    );

    sky130_fd_sc_hd__nand2_1 U72 (
        .A(rst_n),
        .B(reg_data_rx_5),
        .Y(__dff_d_ff555)
    );

    sky130_fd_sc_hd__nand2_1 U73 (
        .A(rst_n),
        .B(reg_data_rx_6),
        .Y(__dff_d_ff556)
    );

    sky130_fd_sc_hd__nand2_1 U74 (
        .A(rst_n),
        .B(reg_data_rx_7),
        .Y(__dff_d_ff557)
    );

    sky130_fd_sc_hd__nor3_1 U75 (
        .A(paddr_2),
        .B(paddr_3),
        .C(clone_78),
        .Y(n204)
    );

    sky130_fd_sc_hd__nand3_1 U76 (
        .A(rst_n),
        .B(stat_ack_received),
        .C(n123),
        .Y(n207)
    );

    sky130_fd_sc_hd__a21oi_1 U77 (
        .A1(pwdata_2),
        .A2(n204),
        .B1(n207),
        .Y(__dff_d_ff558)
    );

    sky130_fd_sc_hd__nand3_1 U78 (
        .A(rst_n),
        .B(stat_arb_lost),
        .C(n123),
        .Y(n211)
    );

    sky130_fd_sc_hd__a21oi_1 U79 (
        .A1(pwdata_3),
        .A2(n204),
        .B1(n211),
        .Y(__dff_d_ff559)
    );

    sky130_fd_sc_hd__nand3_1 U80 (
        .A(rst_n),
        .B(stat_done),
        .C(n123),
        .Y(n215)
    );

    sky130_fd_sc_hd__a21oi_1 U81 (
        .A1(pwdata_1),
        .A2(n204),
        .B1(n215),
        .Y(__dff_d_ff561)
    );

    sky130_fd_sc_hd__nand3_1 U82 (
        .A(rst_n),
        .B(stat_error),
        .C(n123),
        .Y(n219)
    );

    sky130_fd_sc_hd__a21oi_1 U83 (
        .A1(pwdata_4),
        .A2(n204),
        .B1(n219),
        .Y(__dff_d_ff562)
    );

    sky130_fd_sc_hd__buf_1 U84 (
        .A(prdata_5),
        .X(prdata_6)
    );

    sky130_fd_sc_hd__buf_1 U85 (
        .A(prdata_5),
        .X(prdata_7)
    );

    sky130_fd_sc_hd__buf_1 U86 (
        .A(prdata_5),
        .X(prdata_8)
    );

    sky130_fd_sc_hd__buf_1 U87 (
        .A(prdata_5),
        .X(prdata_9)
    );

    sky130_fd_sc_hd__buf_1 U88 (
        .A(prdata_5),
        .X(prdata_10)
    );

    sky130_fd_sc_hd__buf_1 U89 (
        .A(prdata_5),
        .X(prdata_11)
    );

    sky130_fd_sc_hd__buf_1 U90 (
        .A(prdata_5),
        .X(prdata_12)
    );

    sky130_fd_sc_hd__buf_1 U91 (
        .A(prdata_5),
        .X(prdata_13)
    );

    sky130_fd_sc_hd__buf_1 U92 (
        .A(prdata_5),
        .X(prdata_14)
    );

    sky130_fd_sc_hd__buf_1 U93 (
        .A(prdata_5),
        .X(prdata_15)
    );

    sky130_fd_sc_hd__buf_1 U94 (
        .A(prdata_5),
        .X(prdata_16)
    );

    sky130_fd_sc_hd__buf_1 U95 (
        .A(prdata_5),
        .X(prdata_17)
    );

    sky130_fd_sc_hd__buf_1 U96 (
        .A(prdata_5),
        .X(prdata_18)
    );

    sky130_fd_sc_hd__buf_1 U97 (
        .A(prdata_5),
        .X(prdata_19)
    );

    sky130_fd_sc_hd__buf_1 U98 (
        .A(prdata_5),
        .X(prdata_20)
    );

    sky130_fd_sc_hd__buf_1 U99 (
        .A(prdata_5),
        .X(prdata_21)
    );

    sky130_fd_sc_hd__buf_1 U100 (
        .A(prdata_5),
        .X(prdata_22)
    );

    sky130_fd_sc_hd__buf_1 U101 (
        .A(prdata_5),
        .X(prdata_23)
    );

    sky130_fd_sc_hd__buf_1 U102 (
        .A(prdata_5),
        .X(prdata_24)
    );

    sky130_fd_sc_hd__buf_1 U103 (
        .A(prdata_5),
        .X(prdata_25)
    );

    sky130_fd_sc_hd__buf_1 U104 (
        .A(prdata_5),
        .X(prdata_26)
    );

    sky130_fd_sc_hd__buf_1 U105 (
        .A(prdata_5),
        .X(prdata_27)
    );

    sky130_fd_sc_hd__buf_1 U106 (
        .A(prdata_5),
        .X(prdata_28)
    );

    sky130_fd_sc_hd__buf_1 U107 (
        .A(prdata_5),
        .X(prdata_29)
    );

    sky130_fd_sc_hd__buf_1 U108 (
        .A(prdata_5),
        .X(prdata_30)
    );

    sky130_fd_sc_hd__buf_1 U109 (
        .A(prdata_5),
        .X(prdata_31)
    );

    sky130_fd_sc_hd__buf_1 U110 (
        .A(prdata_5),
        .X(pslverr)
    );

    sky130_fd_sc_hd__buf_1 U111 (
        .A(prdata_5),
        .X(i2c_scl_oe)
    );

    sky130_fd_sc_hd__buf_1 U112 (
        .A(prdata_5),
        .X(i2c_sda_oe)
    );

    sky130_fd_sc_hd__buf_1 U113 (
        .A(prdata_5),
        .X(__dff_d_ff560)
    );

    sky130_fd_sc_hd__and2_1 U114 (
        .A(n91),
        .B(n107),
        .X(clone_11)
    );

    sky130_fd_sc_hd__and4_1 U115 (
        .A(paddr_4),
        .B(psel),
        .C(penable),
        .D(pwrite),
        .X(clone_78)
    );

    sky130_fd_sc_hd__dfrtp_1 U116 (
        .D(__dff_d_ff70),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(start_d)
    );

    sky130_fd_sc_hd__dfrtp_1 U117 (
        .D(__dff_d_ff338),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(ctrl_ack_ctrl)
    );

    sky130_fd_sc_hd__dfrtp_1 U118 (
        .D(__dff_d_ff339),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(ctrl_enable)
    );

    sky130_fd_sc_hd__dfrtp_1 U119 (
        .D(__dff_d_ff340),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(ctrl_read_nwrite)
    );

    sky130_fd_sc_hd__dfrtp_1 U120 (
        .D(__dff_d_ff341),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(ctrl_start)
    );

    sky130_fd_sc_hd__dfrtp_1 U121 (
        .D(__dff_d_ff342),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(ctrl_stop)
    );

    sky130_fd_sc_hd__dfrtp_1 U122 (
        .D(__dff_d_ff343),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(irq_en_done)
    );

    sky130_fd_sc_hd__dfrtp_1 U123 (
        .D(__dff_d_ff344),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(irq_en_error)
    );

    sky130_fd_sc_hd__dfrtp_1 U124 (
        .D(__dff_d_ff345),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U125 (
        .D(__dff_d_ff346),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U126 (
        .D(__dff_d_ff347),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U127 (
        .D(__dff_d_ff348),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U128 (
        .D(__dff_d_ff349),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U129 (
        .D(__dff_d_ff350),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U130 (
        .D(__dff_d_ff351),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U131 (
        .D(__dff_d_ff352),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_tx_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U132 (
        .D(__dff_d_ff353),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U133 (
        .D(__dff_d_ff354),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U134 (
        .D(__dff_d_ff355),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U135 (
        .D(__dff_d_ff356),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U136 (
        .D(__dff_d_ff357),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U137 (
        .D(__dff_d_ff358),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U138 (
        .D(__dff_d_ff359),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_slave_addr_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U139 (
        .D(__dff_d_ff548),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(irq_done)
    );

    sky130_fd_sc_hd__dfrtp_1 U140 (
        .D(__dff_d_ff549),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(irq_error)
    );

    sky130_fd_sc_hd__dfrtp_1 U141 (
        .D(__dff_d_ff550),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U142 (
        .D(__dff_d_ff551),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U143 (
        .D(__dff_d_ff552),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U144 (
        .D(__dff_d_ff553),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U145 (
        .D(__dff_d_ff554),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U146 (
        .D(__dff_d_ff555),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U147 (
        .D(__dff_d_ff556),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U148 (
        .D(__dff_d_ff557),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_data_rx_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U149 (
        .D(__dff_d_ff558),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(stat_ack_received)
    );

    sky130_fd_sc_hd__dfrtp_1 U150 (
        .D(__dff_d_ff559),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(stat_arb_lost)
    );

    sky130_fd_sc_hd__dfrtp_1 U151 (
        .D(__dff_d_ff561),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(stat_done)
    );

    sky130_fd_sc_hd__dfrtp_1 U152 (
        .D(__dff_d_ff562),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(stat_error)
    );

endmodule
