// Generated by My Own Flow — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module apb_watchdog (
    input clk,
    input rst_n,
    input paddr_0,
    input paddr_1,
    input paddr_2,
    input paddr_3,
    input paddr_4,
    input paddr_5,
    input paddr_6,
    input paddr_7,
    input paddr_8,
    input paddr_9,
    input paddr_10,
    input paddr_11,
    input psel,
    input penable,
    input pwrite,
    input pwdata_0,
    input pwdata_1,
    input pwdata_2,
    input pwdata_3,
    input pwdata_4,
    input pwdata_5,
    input pwdata_6,
    input pwdata_7,
    input pwdata_8,
    input pwdata_9,
    input pwdata_10,
    input pwdata_11,
    input pwdata_12,
    input pwdata_13,
    input pwdata_14,
    input pwdata_15,
    input pwdata_16,
    input pwdata_17,
    input pwdata_18,
    input pwdata_19,
    input pwdata_20,
    input pwdata_21,
    input pwdata_22,
    input pwdata_23,
    input pwdata_24,
    input pwdata_25,
    input pwdata_26,
    input pwdata_27,
    input pwdata_28,
    input pwdata_29,
    input pwdata_30,
    input pwdata_31,
    output wdt_reset,
    output prdata_0,
    output prdata_1,
    output prdata_2,
    output prdata_3,
    output prdata_4,
    output prdata_5,
    output prdata_6,
    output prdata_7,
    output prdata_8,
    output prdata_9,
    output prdata_10,
    output prdata_11,
    output prdata_12,
    output prdata_13,
    output prdata_14,
    output prdata_15,
    output prdata_16,
    output prdata_17,
    output prdata_18,
    output prdata_19,
    output prdata_20,
    output prdata_21,
    output prdata_22,
    output prdata_23,
    output prdata_24,
    output prdata_25,
    output prdata_26,
    output prdata_27,
    output prdata_28,
    output prdata_29,
    output prdata_30,
    output prdata_31,
    output wdt_irq,
    output pready,
    output pslverr
);

    wire key_valid;
    wire reg_count_0;
    wire reg_count_1;
    wire reg_count_2;
    wire reg_count_3;
    wire reg_count_4;
    wire reg_count_5;
    wire reg_count_6;
    wire reg_count_7;
    wire reg_count_8;
    wire reg_count_9;
    wire reg_count_10;
    wire reg_count_11;
    wire reg_count_12;
    wire reg_count_13;
    wire reg_count_14;
    wire reg_count_15;
    wire reg_count_16;
    wire reg_count_17;
    wire reg_count_18;
    wire reg_count_19;
    wire reg_count_20;
    wire reg_count_21;
    wire reg_count_22;
    wire reg_count_23;
    wire reg_count_24;
    wire reg_count_25;
    wire reg_count_26;
    wire reg_count_27;
    wire reg_count_28;
    wire reg_count_29;
    wire reg_count_30;
    wire reg_count_31;
    wire reg_ctrl_0;
    wire reg_ctrl_1;
    wire reg_ctrl_2;
    wire reg_ctrl_3;
    wire reg_load_0;
    wire reg_load_1;
    wire reg_load_2;
    wire reg_load_3;
    wire reg_load_4;
    wire reg_load_5;
    wire reg_load_6;
    wire reg_load_7;
    wire reg_load_8;
    wire reg_load_9;
    wire reg_load_10;
    wire reg_load_11;
    wire reg_load_12;
    wire reg_load_13;
    wire reg_load_14;
    wire reg_load_15;
    wire reg_load_16;
    wire reg_load_17;
    wire reg_load_18;
    wire reg_load_19;
    wire reg_load_20;
    wire reg_load_21;
    wire reg_load_22;
    wire reg_load_23;
    wire reg_load_24;
    wire reg_load_25;
    wire reg_load_26;
    wire reg_load_27;
    wire reg_load_28;
    wire reg_load_29;
    wire reg_load_30;
    wire reg_load_31;
    wire reg_status_0;
    wire reg_status_1;
    wire GND;
    wire n123;
    wire n126;
    wire inv_n7;
    wire n127;
    wire inv_n5;
    wire n130;
    wire inv_n6;
    wire n132;
    wire n136;
    wire n141;
    wire n145;
    wire n149;
    wire n156;
    wire __dff_d_ff66;
    wire n249;
    wire n251;
    wire n253;
    wire n257;
    wire inv_n18;
    wire n258;
    wire n259;
    wire n260;
    wire n261;
    wire n262;
    wire n263;
    wire n264;
    wire n265;
    wire n266;
    wire n267;
    wire n268;
    wire n269;
    wire n270;
    wire n271;
    wire n272;
    wire n273;
    wire n274;
    wire n275;
    wire n276;
    wire n277;
    wire n278;
    wire n279;
    wire n280;
    wire n281;
    wire n282;
    wire n283;
    wire n284;
    wire n285;
    wire n286;
    wire n287;
    wire __dff_d_ff199;
    wire inv_n2;
    wire n289;
    wire n290;
    wire n291;
    wire n294;
    wire n295;
    wire n298;
    wire n299;
    wire n301;
    wire n302;
    wire n305;
    wire n306;
    wire n307;
    wire n308;
    wire n309;
    wire n310;
    wire n311;
    wire n312;
    wire n313;
    wire n314;
    wire n315;
    wire n316;
    wire n317;
    wire n318;
    wire n319;
    wire n320;
    wire n321;
    wire n322;
    wire n323;
    wire n324;
    wire n327;
    wire inv_n84;
    wire n328;
    wire n329;
    wire n330;
    wire n331;
    wire __dff_d_ff2011;
    wire n334;
    wire n336;
    wire n338;
    wire n339;
    wire n340;
    wire n343;
    wire n348;
    wire __dff_d_ff2012;
    wire n352;
    wire n353;
    wire n354;
    wire inv_n54;
    wire n357;
    wire inv_n90;
    wire n358;
    wire n359;
    wire n360;
    wire __dff_d_ff2013;
    wire n366;
    wire n367;
    wire n368;
    wire inv_n55;
    wire n371;
    wire inv_n91;
    wire n372;
    wire n373;
    wire n374;
    wire __dff_d_ff2014;
    wire n379;
    wire n380;
    wire n381;
    wire n382;
    wire inv_n56;
    wire n385;
    wire inv_n92;
    wire n386;
    wire n387;
    wire n388;
    wire __dff_d_ff2015;
    wire n393;
    wire n394;
    wire n395;
    wire n396;
    wire inv_n57;
    wire n399;
    wire inv_n93;
    wire n400;
    wire n401;
    wire n402;
    wire __dff_d_ff2016;
    wire n407;
    wire n408;
    wire n409;
    wire inv_n58;
    wire n412;
    wire inv_n94;
    wire n413;
    wire n414;
    wire n415;
    wire __dff_d_ff2017;
    wire n419;
    wire n421;
    wire n422;
    wire n423;
    wire inv_n59;
    wire n426;
    wire inv_n95;
    wire n427;
    wire n428;
    wire n429;
    wire __dff_d_ff2018;
    wire n433;
    wire n434;
    wire n435;
    wire n437;
    wire n438;
    wire n439;
    wire inv_n60;
    wire n442;
    wire inv_n96;
    wire n443;
    wire n444;
    wire n445;
    wire __dff_d_ff2019;
    wire n451;
    wire n452;
    wire n453;
    wire inv_n61;
    wire n456;
    wire inv_n97;
    wire n457;
    wire n458;
    wire n459;
    wire __dff_d_ff2020;
    wire n465;
    wire n466;
    wire n467;
    wire inv_n62;
    wire n470;
    wire inv_n98;
    wire n471;
    wire n472;
    wire n473;
    wire __dff_d_ff2021;
    wire n478;
    wire n479;
    wire n480;
    wire n482;
    wire n483;
    wire n484;
    wire inv_n63;
    wire n487;
    wire inv_n99;
    wire n488;
    wire n489;
    wire n490;
    wire __dff_d_ff2022;
    wire n495;
    wire n496;
    wire n497;
    wire n499;
    wire n500;
    wire n501;
    wire inv_n64;
    wire n504;
    wire inv_n100;
    wire n505;
    wire n506;
    wire n507;
    wire __dff_d_ff2023;
    wire n512;
    wire n513;
    wire n514;
    wire n516;
    wire n517;
    wire n518;
    wire inv_n65;
    wire n521;
    wire inv_n101;
    wire n522;
    wire n523;
    wire n524;
    wire __dff_d_ff2024;
    wire n529;
    wire n530;
    wire n531;
    wire n533;
    wire n534;
    wire n535;
    wire inv_n66;
    wire n538;
    wire inv_n102;
    wire n539;
    wire n540;
    wire n541;
    wire __dff_d_ff2025;
    wire n546;
    wire n547;
    wire n548;
    wire n550;
    wire n551;
    wire n552;
    wire inv_n67;
    wire n555;
    wire inv_n103;
    wire n556;
    wire n557;
    wire n558;
    wire __dff_d_ff2026;
    wire n563;
    wire n564;
    wire n565;
    wire n567;
    wire n568;
    wire n569;
    wire inv_n68;
    wire n572;
    wire inv_n104;
    wire n573;
    wire n574;
    wire n575;
    wire __dff_d_ff2027;
    wire n580;
    wire n581;
    wire n582;
    wire n584;
    wire n585;
    wire n586;
    wire inv_n69;
    wire n589;
    wire inv_n105;
    wire n590;
    wire n591;
    wire n592;
    wire __dff_d_ff2028;
    wire n597;
    wire n598;
    wire n599;
    wire n601;
    wire n602;
    wire n603;
    wire inv_n70;
    wire n606;
    wire inv_n106;
    wire n607;
    wire n608;
    wire n609;
    wire __dff_d_ff2029;
    wire n614;
    wire n615;
    wire n616;
    wire n618;
    wire n619;
    wire n620;
    wire inv_n71;
    wire n623;
    wire inv_n107;
    wire n624;
    wire n625;
    wire n626;
    wire __dff_d_ff2030;
    wire n631;
    wire n632;
    wire n633;
    wire n635;
    wire n636;
    wire n637;
    wire inv_n72;
    wire n640;
    wire inv_n108;
    wire n641;
    wire n642;
    wire n643;
    wire __dff_d_ff2031;
    wire n648;
    wire n649;
    wire n650;
    wire n652;
    wire n653;
    wire n654;
    wire inv_n73;
    wire n657;
    wire inv_n109;
    wire n658;
    wire n659;
    wire n660;
    wire __dff_d_ff2032;
    wire n665;
    wire n666;
    wire n667;
    wire n669;
    wire n670;
    wire n671;
    wire inv_n74;
    wire n674;
    wire inv_n110;
    wire n675;
    wire n676;
    wire n677;
    wire __dff_d_ff2033;
    wire n682;
    wire n683;
    wire n684;
    wire n686;
    wire n687;
    wire n688;
    wire inv_n75;
    wire n691;
    wire inv_n111;
    wire n692;
    wire n693;
    wire n694;
    wire __dff_d_ff2034;
    wire n699;
    wire n700;
    wire n701;
    wire n703;
    wire n704;
    wire n705;
    wire inv_n76;
    wire n708;
    wire inv_n112;
    wire n709;
    wire n710;
    wire n711;
    wire __dff_d_ff2035;
    wire n716;
    wire n717;
    wire n718;
    wire n720;
    wire n721;
    wire n722;
    wire inv_n77;
    wire n725;
    wire inv_n113;
    wire n726;
    wire n727;
    wire n728;
    wire __dff_d_ff2036;
    wire n733;
    wire n734;
    wire n735;
    wire n737;
    wire n738;
    wire n739;
    wire inv_n78;
    wire n742;
    wire inv_n114;
    wire n743;
    wire n744;
    wire n745;
    wire __dff_d_ff2037;
    wire n750;
    wire n751;
    wire n752;
    wire n754;
    wire n755;
    wire n756;
    wire inv_n79;
    wire n759;
    wire inv_n115;
    wire n760;
    wire n761;
    wire n762;
    wire __dff_d_ff2038;
    wire n766;
    wire n768;
    wire n769;
    wire n770;
    wire n772;
    wire n773;
    wire n774;
    wire inv_n80;
    wire n777;
    wire inv_n116;
    wire n778;
    wire n779;
    wire n780;
    wire __dff_d_ff2039;
    wire n784;
    wire n786;
    wire n787;
    wire n788;
    wire n790;
    wire n791;
    wire n792;
    wire inv_n81;
    wire n795;
    wire inv_n117;
    wire n796;
    wire n797;
    wire n798;
    wire __dff_d_ff2040;
    wire n803;
    wire n804;
    wire n805;
    wire n806;
    wire n808;
    wire n809;
    wire n810;
    wire inv_n82;
    wire n813;
    wire inv_n118;
    wire n814;
    wire n815;
    wire n816;
    wire __dff_d_ff2041;
    wire n821;
    wire n822;
    wire n824;
    wire n825;
    wire n826;
    wire n828;
    wire n829;
    wire n830;
    wire inv_n83;
    wire n833;
    wire inv_n119;
    wire n834;
    wire n835;
    wire n836;
    wire __dff_d_ff2042;
    wire n838;
    wire n841;
    wire __dff_d_ff2043;
    wire n845;
    wire __dff_d_ff2044;
    wire n849;
    wire __dff_d_ff2045;
    wire n853;
    wire __dff_d_ff2046;
    wire n857;
    wire inv_n88;
    wire __dff_d_ff2047;
    wire n861;
    wire inv_n89;
    wire __dff_d_ff2048;
    wire n865;
    wire __dff_d_ff2049;
    wire n869;
    wire __dff_d_ff2050;
    wire n873;
    wire __dff_d_ff2051;
    wire n877;
    wire __dff_d_ff2052;
    wire n881;
    wire __dff_d_ff2053;
    wire n885;
    wire __dff_d_ff2054;
    wire n889;
    wire __dff_d_ff2055;
    wire n893;
    wire __dff_d_ff2056;
    wire n897;
    wire __dff_d_ff2057;
    wire n901;
    wire __dff_d_ff2058;
    wire n905;
    wire __dff_d_ff2059;
    wire n909;
    wire __dff_d_ff2060;
    wire n913;
    wire __dff_d_ff2061;
    wire n917;
    wire __dff_d_ff2062;
    wire n921;
    wire __dff_d_ff2063;
    wire n925;
    wire __dff_d_ff2064;
    wire n929;
    wire __dff_d_ff2065;
    wire n933;
    wire __dff_d_ff2066;
    wire n937;
    wire __dff_d_ff2067;
    wire n941;
    wire __dff_d_ff2068;
    wire n945;
    wire __dff_d_ff2069;
    wire n949;
    wire __dff_d_ff2070;
    wire n953;
    wire __dff_d_ff2071;
    wire n957;
    wire __dff_d_ff2072;
    wire n961;
    wire __dff_d_ff2073;
    wire n965;
    wire __dff_d_ff2074;
    wire n969;
    wire __dff_d_ff2075;
    wire n973;
    wire __dff_d_ff2076;
    wire n977;
    wire __dff_d_ff2077;
    wire n981;
    wire __dff_d_ff2078;
    wire n983;
    wire n984;
    wire __dff_d_ff2079;
    wire inv_n120;
    wire __dff_d_ff2080;
    wire inv_n121;
    wire clone_50;
    wire clone_92;
    wire clone_94;
    wire clone_96;
    wire clone_98;
    wire clone_126;
    wire clone_157;
    wire clone_233;
    wire clone_260;
    wire clone_274;
    wire clone_484;
    wire clone_499;
    wire clone_517;
    wire buf_rst_n_0;
    wire buf_rst_n_1;
    wire buf_n290_0;
    wire buf_n324_0;
    wire buf_n324_1;
    wire glitch_bal_514_0_n;
    wire glitch_bal_498_0_n;
    wire glitch_bal_483_0_n;
    wire glitch_bal_469_0_n;
    wire glitch_bal_455_0_n;
    wire glitch_bal_442_0_n;
    wire glitch_bal_429_0_n;
    wire glitch_bal_416_0_n;
    wire glitch_bal_403_0_n;
    wire glitch_bal_390_0_n;
    wire glitch_bal_377_0_n;
    wire glitch_bal_364_0_n;
    wire glitch_bal_351_0_n;
    wire glitch_bal_338_0_n;
    wire glitch_bal_325_0_n;
    wire glitch_bal_312_0_n;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(GND));
    sky130_fd_sc_hd__nor3_1 U0 (
        .A(paddr_2),
        .B(paddr_3),
        .C(paddr_4),
        .Y(n123)
    );

    sky130_fd_sc_hd__nor3b_1 U1 (
        .A(paddr_2),
        .B(paddr_3),
        .C_N(paddr_4),
        .Y(n126)
    );

    sky130_fd_sc_hd__nor3b_1 U2 (
        .A(paddr_3),
        .B(paddr_4),
        .C_N(paddr_2),
        .Y(n127)
    );

    sky130_fd_sc_hd__nor3b_1 U3 (
        .A(paddr_2),
        .B(paddr_4),
        .C_N(paddr_3),
        .Y(n130)
    );

    sky130_fd_sc_hd__a22oi_1 U4 (
        .A1(reg_count_0),
        .A2(n130),
        .B1(reg_status_0),
        .B2(n127),
        .Y(n132)
    );

    sky130_fd_sc_hd__a21oi_1 U5 (
        .A1(reg_load_0),
        .A2(n126),
        .B1(n132),
        .Y(n136)
    );

    sky130_fd_sc_hd__a21oi_1 U6 (
        .A1(reg_ctrl_0),
        .A2(n123),
        .B1(n136),
        .Y(prdata_0)
    );

    sky130_fd_sc_hd__a22oi_1 U7 (
        .A1(reg_count_1),
        .A2(n130),
        .B1(reg_status_1),
        .B2(n127),
        .Y(n141)
    );

    sky130_fd_sc_hd__a21oi_1 U8 (
        .A1(reg_load_1),
        .A2(n126),
        .B1(n141),
        .Y(n145)
    );

    sky130_fd_sc_hd__a21oi_1 U9 (
        .A1(reg_ctrl_1),
        .A2(n123),
        .B1(n145),
        .Y(prdata_1)
    );

    sky130_fd_sc_hd__a22oi_1 U10 (
        .A1(reg_count_2),
        .A2(n130),
        .B1(reg_load_2),
        .B2(n126),
        .Y(n149)
    );

    sky130_fd_sc_hd__a21oi_1 U11 (
        .A1(reg_ctrl_2),
        .A2(n123),
        .B1(n149),
        .Y(prdata_2)
    );

    sky130_fd_sc_hd__a22oi_1 U12 (
        .A1(reg_count_3),
        .A2(n130),
        .B1(reg_load_3),
        .B2(n126),
        .Y(n156)
    );

    sky130_fd_sc_hd__a21oi_1 U13 (
        .A1(reg_ctrl_3),
        .A2(n123),
        .B1(n156),
        .Y(prdata_3)
    );

    sky130_fd_sc_hd__a22oi_1 U14 (
        .A1(reg_count_4),
        .A2(n130),
        .B1(reg_load_4),
        .B2(n126),
        .Y(prdata_4)
    );

    sky130_fd_sc_hd__a22oi_1 U15 (
        .A1(reg_count_5),
        .A2(n130),
        .B1(reg_load_5),
        .B2(n126),
        .Y(prdata_5)
    );

    sky130_fd_sc_hd__a22oi_1 U16 (
        .A1(reg_count_6),
        .A2(n130),
        .B1(reg_load_6),
        .B2(n126),
        .Y(prdata_6)
    );

    sky130_fd_sc_hd__a22oi_1 U17 (
        .A1(reg_count_7),
        .A2(n130),
        .B1(reg_load_7),
        .B2(n126),
        .Y(prdata_7)
    );

    sky130_fd_sc_hd__a22oi_1 U18 (
        .A1(reg_count_8),
        .A2(n130),
        .B1(reg_load_8),
        .B2(n126),
        .Y(prdata_8)
    );

    sky130_fd_sc_hd__a22oi_1 U19 (
        .A1(reg_count_9),
        .A2(n130),
        .B1(reg_load_9),
        .B2(n126),
        .Y(prdata_9)
    );

    sky130_fd_sc_hd__a22oi_1 U20 (
        .A1(reg_count_10),
        .A2(n130),
        .B1(reg_load_10),
        .B2(n126),
        .Y(prdata_10)
    );

    sky130_fd_sc_hd__a22oi_1 U21 (
        .A1(reg_count_11),
        .A2(n130),
        .B1(reg_load_11),
        .B2(n126),
        .Y(prdata_11)
    );

    sky130_fd_sc_hd__a22oi_1 U22 (
        .A1(reg_count_12),
        .A2(n130),
        .B1(reg_load_12),
        .B2(n126),
        .Y(prdata_12)
    );

    sky130_fd_sc_hd__a22oi_1 U23 (
        .A1(reg_count_13),
        .A2(n130),
        .B1(reg_load_13),
        .B2(n126),
        .Y(prdata_13)
    );

    sky130_fd_sc_hd__a22oi_1 U24 (
        .A1(reg_count_14),
        .A2(n130),
        .B1(reg_load_14),
        .B2(n126),
        .Y(prdata_14)
    );

    sky130_fd_sc_hd__a22oi_1 U25 (
        .A1(reg_count_15),
        .A2(n130),
        .B1(reg_load_15),
        .B2(n126),
        .Y(prdata_15)
    );

    sky130_fd_sc_hd__a22oi_1 U26 (
        .A1(reg_count_16),
        .A2(n130),
        .B1(reg_load_16),
        .B2(n126),
        .Y(prdata_16)
    );

    sky130_fd_sc_hd__a22oi_1 U27 (
        .A1(reg_count_17),
        .A2(n130),
        .B1(reg_load_17),
        .B2(n126),
        .Y(prdata_17)
    );

    sky130_fd_sc_hd__a22oi_1 U28 (
        .A1(reg_count_18),
        .A2(n130),
        .B1(reg_load_18),
        .B2(n126),
        .Y(prdata_18)
    );

    sky130_fd_sc_hd__a22oi_1 U29 (
        .A1(reg_count_19),
        .A2(n130),
        .B1(reg_load_19),
        .B2(n126),
        .Y(prdata_19)
    );

    sky130_fd_sc_hd__a22oi_1 U30 (
        .A1(reg_count_20),
        .A2(n130),
        .B1(reg_load_20),
        .B2(n126),
        .Y(prdata_20)
    );

    sky130_fd_sc_hd__a22oi_1 U31 (
        .A1(reg_count_21),
        .A2(n130),
        .B1(reg_load_21),
        .B2(n126),
        .Y(prdata_21)
    );

    sky130_fd_sc_hd__a22oi_1 U32 (
        .A1(reg_count_22),
        .A2(n130),
        .B1(reg_load_22),
        .B2(n126),
        .Y(prdata_22)
    );

    sky130_fd_sc_hd__a22oi_1 U33 (
        .A1(reg_count_23),
        .A2(n130),
        .B1(reg_load_23),
        .B2(n126),
        .Y(prdata_23)
    );

    sky130_fd_sc_hd__a22oi_1 U34 (
        .A1(reg_count_24),
        .A2(n130),
        .B1(reg_load_24),
        .B2(n126),
        .Y(prdata_24)
    );

    sky130_fd_sc_hd__a22oi_1 U35 (
        .A1(reg_count_25),
        .A2(n130),
        .B1(reg_load_25),
        .B2(n126),
        .Y(prdata_25)
    );

    sky130_fd_sc_hd__a22oi_1 U36 (
        .A1(reg_count_26),
        .A2(n130),
        .B1(reg_load_26),
        .B2(n126),
        .Y(prdata_26)
    );

    sky130_fd_sc_hd__a22oi_1 U37 (
        .A1(reg_count_27),
        .A2(n130),
        .B1(reg_load_27),
        .B2(n126),
        .Y(prdata_27)
    );

    sky130_fd_sc_hd__a22oi_1 U38 (
        .A1(reg_count_28),
        .A2(n130),
        .B1(reg_load_28),
        .B2(n126),
        .Y(prdata_28)
    );

    sky130_fd_sc_hd__a22oi_1 U39 (
        .A1(reg_count_29),
        .A2(n130),
        .B1(reg_load_29),
        .B2(n126),
        .Y(prdata_29)
    );

    sky130_fd_sc_hd__a22oi_1 U40 (
        .A1(reg_count_30),
        .A2(n130),
        .B1(reg_load_30),
        .B2(n126),
        .Y(prdata_30)
    );

    sky130_fd_sc_hd__a22oi_1 U41 (
        .A1(reg_count_31),
        .A2(n130),
        .B1(reg_load_31),
        .B2(n126),
        .Y(prdata_31)
    );

    sky130_fd_sc_hd__nand2_1 U42 (
        .A(reg_ctrl_2),
        .B(reg_status_0),
        .Y(wdt_irq)
    );

    sky130_fd_sc_hd__nand3b_1 U43 (
        .A_N(paddr_2),
        .B(paddr_3),
        .C(paddr_4),
        .Y(n249)
    );

    sky130_fd_sc_hd__nand3_1 U44 (
        .A(psel),
        .B(penable),
        .C(pwrite),
        .Y(n251)
    );

    sky130_fd_sc_hd__o21a_1 U45 (
        .A1(n249),
        .A2(clone_50),
        .B1(key_valid),
        .X(n253)
    );

    sky130_fd_sc_hd__inv_1 U46 (
        .A(pwdata_0),
        .Y(inv_n18)
    );

    sky130_fd_sc_hd__nor4_1 U47 (
        .A(inv_n18),
        .B(pwdata_1),
        .C(pwdata_2),
        .D(pwdata_3),
        .Y(n257)
    );

    sky130_fd_sc_hd__nand2_1 U48 (
        .A(pwdata_4),
        .B(n257),
        .Y(n258)
    );

    sky130_fd_sc_hd__nor2_1 U49 (
        .A(pwdata_5),
        .B(n258),
        .Y(n259)
    );

    sky130_fd_sc_hd__nand2_1 U50 (
        .A(pwdata_6),
        .B(n259),
        .Y(n260)
    );

    sky130_fd_sc_hd__nor2_1 U51 (
        .A(pwdata_7),
        .B(n260),
        .Y(n261)
    );

    sky130_fd_sc_hd__nand2_1 U52 (
        .A(pwdata_8),
        .B(n261),
        .Y(n262)
    );

    sky130_fd_sc_hd__nor2_1 U53 (
        .A(pwdata_9),
        .B(n262),
        .Y(n263)
    );

    sky130_fd_sc_hd__nand2_1 U54 (
        .A(pwdata_10),
        .B(n263),
        .Y(n264)
    );

    sky130_fd_sc_hd__nor2_1 U55 (
        .A(pwdata_11),
        .B(n264),
        .Y(n265)
    );

    sky130_fd_sc_hd__nor2_1 U56 (
        .A(pwdata_12),
        .B(n265),
        .Y(n266)
    );

    sky130_fd_sc_hd__nand2_1 U57 (
        .A(pwdata_13),
        .B(n266),
        .Y(n267)
    );

    sky130_fd_sc_hd__nand2_1 U58 (
        .A(pwdata_14),
        .B(n267),
        .Y(n268)
    );

    sky130_fd_sc_hd__nand2_1 U59 (
        .A(pwdata_15),
        .B(n268),
        .Y(n269)
    );

    sky130_fd_sc_hd__nor2_1 U60 (
        .A(pwdata_16),
        .B(n269),
        .Y(n270)
    );

    sky130_fd_sc_hd__nor2_1 U61 (
        .A(pwdata_17),
        .B(n270),
        .Y(n271)
    );

    sky130_fd_sc_hd__nand2_1 U62 (
        .A(pwdata_18),
        .B(n271),
        .Y(n272)
    );

    sky130_fd_sc_hd__nand2_1 U63 (
        .A(pwdata_19),
        .B(n272),
        .Y(n273)
    );

    sky130_fd_sc_hd__nor2_1 U64 (
        .A(pwdata_20),
        .B(n273),
        .Y(n274)
    );

    sky130_fd_sc_hd__nor2_1 U65 (
        .A(pwdata_21),
        .B(n274),
        .Y(n275)
    );

    sky130_fd_sc_hd__nand2_1 U66 (
        .A(pwdata_22),
        .B(n275),
        .Y(n276)
    );

    sky130_fd_sc_hd__nand2_1 U67 (
        .A(pwdata_23),
        .B(n276),
        .Y(n277)
    );

    sky130_fd_sc_hd__nor2_1 U68 (
        .A(pwdata_24),
        .B(n277),
        .Y(n278)
    );

    sky130_fd_sc_hd__nand2_1 U69 (
        .A(pwdata_25),
        .B(n278),
        .Y(n279)
    );

    sky130_fd_sc_hd__nor2_1 U70 (
        .A(pwdata_26),
        .B(n279),
        .Y(n280)
    );

    sky130_fd_sc_hd__nand2_1 U71 (
        .A(pwdata_27),
        .B(n280),
        .Y(n281)
    );

    sky130_fd_sc_hd__nand2_1 U72 (
        .A(pwdata_28),
        .B(n281),
        .Y(n282)
    );

    sky130_fd_sc_hd__nor2_1 U73 (
        .A(pwdata_29),
        .B(n282),
        .Y(n283)
    );

    sky130_fd_sc_hd__nor2_1 U74 (
        .A(pwdata_30),
        .B(n283),
        .Y(n284)
    );

    sky130_fd_sc_hd__nor2_1 U75 (
        .A(pwdata_31),
        .B(n284),
        .Y(n285)
    );

    sky130_fd_sc_hd__nand3_1 U76 (
        .A(n249),
        .B(n251),
        .C(n285),
        .Y(n286)
    );

    sky130_fd_sc_hd__nor2_1 U77 (
        .A(n253),
        .B(n286),
        .Y(n287)
    );

    sky130_fd_sc_hd__nor2b_1 U78 (
        .A(n287),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff199)
    );

    sky130_fd_sc_hd__nand4_1 U79 (
        .A(psel),
        .B(penable),
        .C(pwrite),
        .D(key_valid),
        .Y(n289)
    );

    sky130_fd_sc_hd__nand2_1 U80 (
        .A(n126),
        .B(n289),
        .Y(n290)
    );

    sky130_fd_sc_hd__nand2_1 U81 (
        .A(reg_ctrl_0),
        .B(buf_n290_0),
        .Y(n291)
    );

    sky130_fd_sc_hd__nor2_4 U82 (
        .A(reg_count_0),
        .B(reg_count_1),
        .Y(n294)
    );

    sky130_fd_sc_hd__nor2_1 U83 (
        .A(reg_count_3),
        .B(reg_count_4),
        .Y(n295)
    );

    sky130_fd_sc_hd__nor4_1 U84 (
        .A(reg_count_2),
        .B(reg_count_5),
        .C(n294),
        .D(n295),
        .Y(n298)
    );

    sky130_fd_sc_hd__nor2_1 U85 (
        .A(reg_count_6),
        .B(clone_92),
        .Y(n299)
    );

    sky130_fd_sc_hd__nor3_1 U86 (
        .A(reg_count_7),
        .B(reg_count_8),
        .C(clone_94),
        .Y(n301)
    );

    sky130_fd_sc_hd__nor2_1 U87 (
        .A(reg_count_9),
        .B(clone_96),
        .Y(n302)
    );

    sky130_fd_sc_hd__nor4_2 U88 (
        .A(reg_count_10),
        .B(reg_count_11),
        .C(reg_count_12),
        .D(clone_98),
        .Y(n305)
    );

    sky130_fd_sc_hd__nor2_4 U89 (
        .A(reg_count_13),
        .B(n305),
        .Y(n306)
    );

    sky130_fd_sc_hd__nor2_4 U90 (
        .A(reg_count_14),
        .B(n306),
        .Y(n307)
    );

    sky130_fd_sc_hd__nor2_4 U91 (
        .A(reg_count_15),
        .B(n307),
        .Y(n308)
    );

    sky130_fd_sc_hd__nor2_4 U92 (
        .A(reg_count_16),
        .B(n308),
        .Y(n309)
    );

    sky130_fd_sc_hd__nor2_4 U93 (
        .A(reg_count_17),
        .B(n309),
        .Y(n310)
    );

    sky130_fd_sc_hd__nor2_4 U94 (
        .A(reg_count_18),
        .B(n310),
        .Y(n311)
    );

    sky130_fd_sc_hd__nor2_4 U95 (
        .A(reg_count_19),
        .B(n311),
        .Y(n312)
    );

    sky130_fd_sc_hd__nor2_4 U96 (
        .A(reg_count_20),
        .B(n312),
        .Y(n313)
    );

    sky130_fd_sc_hd__nor2_4 U97 (
        .A(reg_count_21),
        .B(n313),
        .Y(n314)
    );

    sky130_fd_sc_hd__nor2_4 U98 (
        .A(reg_count_22),
        .B(n314),
        .Y(n315)
    );

    sky130_fd_sc_hd__nor2_4 U99 (
        .A(reg_count_23),
        .B(n315),
        .Y(n316)
    );

    sky130_fd_sc_hd__nor2_4 U100 (
        .A(reg_count_24),
        .B(n316),
        .Y(n317)
    );

    sky130_fd_sc_hd__nor2_4 U101 (
        .A(reg_count_25),
        .B(n317),
        .Y(n318)
    );

    sky130_fd_sc_hd__nor2_4 U102 (
        .A(reg_count_26),
        .B(n318),
        .Y(n319)
    );

    sky130_fd_sc_hd__nor2_4 U103 (
        .A(reg_count_27),
        .B(n319),
        .Y(n320)
    );

    sky130_fd_sc_hd__nor2_4 U104 (
        .A(reg_count_28),
        .B(n320),
        .Y(n321)
    );

    sky130_fd_sc_hd__nor2_4 U105 (
        .A(reg_count_29),
        .B(n321),
        .Y(n322)
    );

    sky130_fd_sc_hd__nor2_4 U106 (
        .A(reg_count_30),
        .B(n322),
        .Y(n323)
    );

    sky130_fd_sc_hd__nor2_1 U107 (
        .A(reg_count_31),
        .B(n323),
        .Y(n324)
    );

    sky130_fd_sc_hd__inv_1 U108 (
        .A(reg_ctrl_0),
        .Y(inv_n84)
    );

    sky130_fd_sc_hd__a21oi_1 U109 (
        .A1(reg_load_0),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .Y(n327)
    );

    sky130_fd_sc_hd__o21a_1 U110 (
        .A1(reg_count_0),
        .A2(buf_n324_0),
        .B1(n327),
        .X(n328)
    );

    sky130_fd_sc_hd__o21a_1 U111 (
        .A1(reg_count_0),
        .A2(reg_ctrl_0),
        .B1(n328),
        .X(n329)
    );

    sky130_fd_sc_hd__nor2_1 U112 (
        .A(n291),
        .B(n329),
        .Y(n330)
    );

    sky130_fd_sc_hd__a21oi_1 U113 (
        .A1(pwdata_0),
        .A2(n291),
        .B1(n330),
        .Y(n331)
    );

    sky130_fd_sc_hd__nor4_1 U114 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(reg_load_1),
        .D(clone_126),
        .Y(n334)
    );

    sky130_fd_sc_hd__nand3_1 U115 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(clone_126),
        .Y(n336)
    );

    sky130_fd_sc_hd__a21oi_1 U116 (
        .A1(reg_load_1),
        .A2(buf_n324_0),
        .B1(n336),
        .Y(n338)
    );

    sky130_fd_sc_hd__o21a_1 U117 (
        .A1(reg_count_0),
        .A2(reg_count_1),
        .B1(n338),
        .X(n339)
    );

    sky130_fd_sc_hd__nor2_1 U118 (
        .A(n334),
        .B(n339),
        .Y(n340)
    );

    sky130_fd_sc_hd__mux2_1 U119 (
        .A0(reg_count_1),
        .A1(n340),
        .S(inv_n84),
        .X(n343)
    );

    sky130_fd_sc_hd__mux2_1 U120 (
        .A0(pwdata_1),
        .A1(n343),
        .S(n291),
        .X(n348)
    );

    sky130_fd_sc_hd__nor2b_1 U121 (
        .A(n348),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff2012)
    );

    sky130_fd_sc_hd__nor3b_1 U122 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C_N(reg_ctrl_0),
        .Y(n352)
    );

    sky130_fd_sc_hd__a211oi_1 U123 (
        .A1(reg_load_2),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .C1(n294),
        .Y(n353)
    );

    sky130_fd_sc_hd__nor2b_1 U124 (
        .A(n353),
        .B_N(reg_count_2),
        .Y(n354)
    );

    sky130_fd_sc_hd__inv_1 U125 (
        .A(reg_load_2),
        .Y(inv_n90)
    );

    sky130_fd_sc_hd__a211oi_1 U126 (
        .A1(inv_n90),
        .A2(buf_n324_0),
        .B1(reg_count_2),
        .C1(n352),
        .Y(n357)
    );

    sky130_fd_sc_hd__nor2_1 U127 (
        .A(n354),
        .B(n357),
        .Y(n358)
    );

    sky130_fd_sc_hd__nor2_1 U128 (
        .A(n291),
        .B(n358),
        .Y(n359)
    );

    sky130_fd_sc_hd__a21oi_1 U129 (
        .A1(pwdata_2),
        .A2(n291),
        .B1(n359),
        .Y(n360)
    );

    sky130_fd_sc_hd__nor4_1 U130 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(reg_count_2),
        .D(inv_n84),
        .Y(n366)
    );

    sky130_fd_sc_hd__a21oi_1 U131 (
        .A1(reg_load_3),
        .A2(buf_n324_0),
        .B1(n366),
        .Y(n367)
    );

    sky130_fd_sc_hd__nor2b_1 U132 (
        .A(n367),
        .B_N(reg_count_3),
        .Y(n368)
    );

    sky130_fd_sc_hd__inv_1 U133 (
        .A(reg_load_3),
        .Y(inv_n91)
    );

    sky130_fd_sc_hd__a211oi_1 U134 (
        .A1(inv_n91),
        .A2(buf_n324_0),
        .B1(reg_count_3),
        .C1(n366),
        .Y(n371)
    );

    sky130_fd_sc_hd__nor2_1 U135 (
        .A(n368),
        .B(n371),
        .Y(n372)
    );

    sky130_fd_sc_hd__nor2_1 U136 (
        .A(n291),
        .B(n372),
        .Y(n373)
    );

    sky130_fd_sc_hd__a21oi_1 U137 (
        .A1(pwdata_3),
        .A2(n291),
        .B1(n373),
        .Y(n374)
    );

    sky130_fd_sc_hd__nor4_1 U138 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(reg_count_2),
        .D(reg_count_3),
        .Y(n379)
    );

    sky130_fd_sc_hd__nand2_1 U139 (
        .A(reg_ctrl_0),
        .B(n379),
        .Y(n380)
    );

    sky130_fd_sc_hd__a211oi_1 U140 (
        .A1(reg_load_4),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .C1(clone_157),
        .Y(n381)
    );

    sky130_fd_sc_hd__nor2b_1 U141 (
        .A(n381),
        .B_N(reg_count_4),
        .Y(n382)
    );

    sky130_fd_sc_hd__inv_1 U142 (
        .A(reg_load_4),
        .Y(inv_n92)
    );

    sky130_fd_sc_hd__a211oi_1 U143 (
        .A1(inv_n92),
        .A2(buf_n324_0),
        .B1(reg_count_4),
        .C1(n380),
        .Y(n385)
    );

    sky130_fd_sc_hd__nor2_1 U144 (
        .A(n382),
        .B(n385),
        .Y(n386)
    );

    sky130_fd_sc_hd__nor2_1 U145 (
        .A(n291),
        .B(n386),
        .Y(n387)
    );

    sky130_fd_sc_hd__a21oi_1 U146 (
        .A1(pwdata_4),
        .A2(n291),
        .B1(n387),
        .Y(n388)
    );

    sky130_fd_sc_hd__nor4_1 U147 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(reg_count_2),
        .D(n295),
        .Y(n393)
    );

    sky130_fd_sc_hd__nand2_1 U148 (
        .A(reg_ctrl_0),
        .B(n393),
        .Y(n394)
    );

    sky130_fd_sc_hd__a21oi_1 U149 (
        .A1(reg_load_5),
        .A2(buf_n324_0),
        .B1(n394),
        .Y(n395)
    );

    sky130_fd_sc_hd__nor2b_1 U150 (
        .A(n395),
        .B_N(reg_count_5),
        .Y(n396)
    );

    sky130_fd_sc_hd__inv_1 U151 (
        .A(reg_load_5),
        .Y(inv_n93)
    );

    sky130_fd_sc_hd__a211oi_1 U152 (
        .A1(inv_n93),
        .A2(buf_n324_0),
        .B1(reg_count_5),
        .C1(n394),
        .Y(n399)
    );

    sky130_fd_sc_hd__nor2_1 U153 (
        .A(n396),
        .B(n399),
        .Y(n400)
    );

    sky130_fd_sc_hd__nor2_1 U154 (
        .A(n291),
        .B(n400),
        .Y(n401)
    );

    sky130_fd_sc_hd__a21oi_1 U155 (
        .A1(pwdata_5),
        .A2(n291),
        .B1(n401),
        .Y(n402)
    );

    sky130_fd_sc_hd__nand2_1 U156 (
        .A(reg_ctrl_0),
        .B(n298),
        .Y(n407)
    );

    sky130_fd_sc_hd__a211oi_1 U157 (
        .A1(reg_load_6),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .C1(clone_92),
        .Y(n408)
    );

    sky130_fd_sc_hd__nor2b_1 U158 (
        .A(n408),
        .B_N(reg_count_6),
        .Y(n409)
    );

    sky130_fd_sc_hd__inv_1 U159 (
        .A(reg_load_6),
        .Y(inv_n94)
    );

    sky130_fd_sc_hd__a211oi_1 U160 (
        .A1(inv_n94),
        .A2(buf_n324_0),
        .B1(reg_count_6),
        .C1(n407),
        .Y(n412)
    );

    sky130_fd_sc_hd__nor2_1 U161 (
        .A(n409),
        .B(n412),
        .Y(n413)
    );

    sky130_fd_sc_hd__nor2_1 U162 (
        .A(n291),
        .B(n413),
        .Y(n414)
    );

    sky130_fd_sc_hd__a21oi_1 U163 (
        .A1(pwdata_6),
        .A2(n291),
        .B1(n414),
        .Y(n415)
    );

    sky130_fd_sc_hd__nor2_1 U164 (
        .A(reg_count_5),
        .B(reg_count_6),
        .Y(n419)
    );

    sky130_fd_sc_hd__nand2_1 U165 (
        .A(reg_ctrl_0),
        .B(n299),
        .Y(n421)
    );

    sky130_fd_sc_hd__a211oi_1 U166 (
        .A1(reg_load_7),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .C1(clone_94),
        .Y(n422)
    );

    sky130_fd_sc_hd__nor2b_1 U167 (
        .A(n422),
        .B_N(reg_count_7),
        .Y(n423)
    );

    sky130_fd_sc_hd__inv_1 U168 (
        .A(reg_load_7),
        .Y(inv_n95)
    );

    sky130_fd_sc_hd__a211oi_1 U169 (
        .A1(inv_n95),
        .A2(buf_n324_0),
        .B1(reg_count_7),
        .C1(n421),
        .Y(n426)
    );

    sky130_fd_sc_hd__nor2_1 U170 (
        .A(n423),
        .B(n426),
        .Y(n427)
    );

    sky130_fd_sc_hd__nor2_1 U171 (
        .A(n291),
        .B(n427),
        .Y(n428)
    );

    sky130_fd_sc_hd__a21oi_1 U172 (
        .A1(pwdata_7),
        .A2(n291),
        .B1(n428),
        .Y(n429)
    );

    sky130_fd_sc_hd__nor2_1 U173 (
        .A(reg_count_6),
        .B(reg_count_7),
        .Y(n433)
    );

    sky130_fd_sc_hd__nor4_1 U174 (
        .A(reg_count_4),
        .B(reg_count_5),
        .C(reg_count_6),
        .D(reg_count_7),
        .Y(n434)
    );

    sky130_fd_sc_hd__nand2_1 U175 (
        .A(n379),
        .B(n434),
        .Y(n435)
    );

    sky130_fd_sc_hd__o21a_1 U176 (
        .A1(buf_n324_0),
        .A2(n435),
        .B1(reg_ctrl_0),
        .X(n437)
    );

    sky130_fd_sc_hd__a21oi_1 U177 (
        .A1(reg_load_8),
        .A2(buf_n324_0),
        .B1(n437),
        .Y(n438)
    );

    sky130_fd_sc_hd__nor2b_1 U178 (
        .A(n438),
        .B_N(reg_count_8),
        .Y(n439)
    );

    sky130_fd_sc_hd__inv_1 U179 (
        .A(reg_load_8),
        .Y(inv_n96)
    );

    sky130_fd_sc_hd__a211oi_1 U180 (
        .A1(inv_n96),
        .A2(buf_n324_0),
        .B1(reg_count_8),
        .C1(n437),
        .Y(n442)
    );

    sky130_fd_sc_hd__nor2_1 U181 (
        .A(n439),
        .B(n442),
        .Y(n443)
    );

    sky130_fd_sc_hd__nor2_1 U182 (
        .A(n291),
        .B(n443),
        .Y(n444)
    );

    sky130_fd_sc_hd__a21oi_1 U183 (
        .A1(pwdata_8),
        .A2(n291),
        .B1(n444),
        .Y(n445)
    );

    sky130_fd_sc_hd__nand2_1 U184 (
        .A(reg_ctrl_0),
        .B(n301),
        .Y(n451)
    );

    sky130_fd_sc_hd__a211oi_1 U185 (
        .A1(reg_load_9),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .C1(clone_96),
        .Y(n452)
    );

    sky130_fd_sc_hd__nor2b_1 U186 (
        .A(n452),
        .B_N(reg_count_9),
        .Y(n453)
    );

    sky130_fd_sc_hd__inv_1 U187 (
        .A(reg_load_9),
        .Y(inv_n97)
    );

    sky130_fd_sc_hd__a211oi_1 U188 (
        .A1(inv_n97),
        .A2(buf_n324_0),
        .B1(reg_count_9),
        .C1(n451),
        .Y(n456)
    );

    sky130_fd_sc_hd__nor2_1 U189 (
        .A(n453),
        .B(n456),
        .Y(n457)
    );

    sky130_fd_sc_hd__nor2_1 U190 (
        .A(n291),
        .B(n457),
        .Y(n458)
    );

    sky130_fd_sc_hd__a21oi_1 U191 (
        .A1(pwdata_9),
        .A2(n291),
        .B1(n458),
        .Y(n459)
    );

    sky130_fd_sc_hd__nand2_1 U192 (
        .A(reg_ctrl_0),
        .B(n302),
        .Y(n465)
    );

    sky130_fd_sc_hd__a211oi_1 U193 (
        .A1(reg_load_10),
        .A2(buf_n324_0),
        .B1(inv_n84),
        .C1(clone_98),
        .Y(n466)
    );

    sky130_fd_sc_hd__nor2b_1 U194 (
        .A(n466),
        .B_N(reg_count_10),
        .Y(n467)
    );

    sky130_fd_sc_hd__inv_1 U195 (
        .A(reg_load_10),
        .Y(inv_n98)
    );

    sky130_fd_sc_hd__a211oi_1 U196 (
        .A1(inv_n98),
        .A2(buf_n324_0),
        .B1(reg_count_10),
        .C1(n465),
        .Y(n470)
    );

    sky130_fd_sc_hd__nor2_1 U197 (
        .A(n467),
        .B(n470),
        .Y(n471)
    );

    sky130_fd_sc_hd__nor2_1 U198 (
        .A(n291),
        .B(n471),
        .Y(n472)
    );

    sky130_fd_sc_hd__a21oi_1 U199 (
        .A1(pwdata_10),
        .A2(n291),
        .B1(n472),
        .Y(n473)
    );

    sky130_fd_sc_hd__nor4_1 U200 (
        .A(reg_count_7),
        .B(reg_count_8),
        .C(reg_count_9),
        .D(reg_count_10),
        .Y(n478)
    );

    sky130_fd_sc_hd__nor4_1 U201 (
        .A(reg_count_5),
        .B(reg_count_6),
        .C(n295),
        .D(clone_233),
        .Y(n479)
    );

    sky130_fd_sc_hd__nor4_1 U202 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(reg_count_2),
        .D(n479),
        .Y(n480)
    );

    sky130_fd_sc_hd__o21a_1 U203 (
        .A1(buf_n324_0),
        .A2(n480),
        .B1(reg_ctrl_0),
        .X(n482)
    );

    sky130_fd_sc_hd__a21oi_1 U204 (
        .A1(reg_load_11),
        .A2(buf_n324_0),
        .B1(n482),
        .Y(n483)
    );

    sky130_fd_sc_hd__nor2b_1 U205 (
        .A(n483),
        .B_N(reg_count_11),
        .Y(n484)
    );

    sky130_fd_sc_hd__inv_1 U206 (
        .A(reg_load_11),
        .Y(inv_n99)
    );

    sky130_fd_sc_hd__a211oi_1 U207 (
        .A1(inv_n99),
        .A2(buf_n324_0),
        .B1(reg_count_11),
        .C1(n482),
        .Y(n487)
    );

    sky130_fd_sc_hd__nor2_1 U208 (
        .A(n484),
        .B(n487),
        .Y(n488)
    );

    sky130_fd_sc_hd__nor2_1 U209 (
        .A(n291),
        .B(n488),
        .Y(n489)
    );

    sky130_fd_sc_hd__a21oi_1 U210 (
        .A1(pwdata_11),
        .A2(n291),
        .B1(n489),
        .Y(n490)
    );

    sky130_fd_sc_hd__nor4_1 U211 (
        .A(reg_count_8),
        .B(reg_count_9),
        .C(reg_count_10),
        .D(reg_count_11),
        .Y(n495)
    );

    sky130_fd_sc_hd__nand2_1 U212 (
        .A(n434),
        .B(n495),
        .Y(n496)
    );

    sky130_fd_sc_hd__nand2_1 U213 (
        .A(n379),
        .B(n496),
        .Y(n497)
    );

    sky130_fd_sc_hd__o21a_1 U214 (
        .A1(buf_n324_0),
        .A2(n497),
        .B1(reg_ctrl_0),
        .X(n499)
    );

    sky130_fd_sc_hd__a21oi_1 U215 (
        .A1(reg_load_12),
        .A2(buf_n324_0),
        .B1(n499),
        .Y(n500)
    );

    sky130_fd_sc_hd__nor2b_1 U216 (
        .A(n500),
        .B_N(reg_count_12),
        .Y(n501)
    );

    sky130_fd_sc_hd__inv_1 U217 (
        .A(reg_load_12),
        .Y(inv_n100)
    );

    sky130_fd_sc_hd__a211oi_1 U218 (
        .A1(inv_n100),
        .A2(buf_n324_0),
        .B1(reg_count_12),
        .C1(n499),
        .Y(n504)
    );

    sky130_fd_sc_hd__nor2_1 U219 (
        .A(n501),
        .B(n504),
        .Y(n505)
    );

    sky130_fd_sc_hd__nor2_1 U220 (
        .A(n291),
        .B(n505),
        .Y(n506)
    );

    sky130_fd_sc_hd__a21oi_1 U221 (
        .A1(pwdata_12),
        .A2(n291),
        .B1(n506),
        .Y(n507)
    );

    sky130_fd_sc_hd__nor4_1 U222 (
        .A(reg_count_9),
        .B(reg_count_10),
        .C(reg_count_11),
        .D(reg_count_12),
        .Y(n512)
    );

    sky130_fd_sc_hd__nor4_1 U223 (
        .A(reg_count_7),
        .B(reg_count_8),
        .C(n419),
        .D(clone_260),
        .Y(n513)
    );

    sky130_fd_sc_hd__nand2_1 U224 (
        .A(n393),
        .B(n513),
        .Y(n514)
    );

    sky130_fd_sc_hd__o21a_1 U225 (
        .A1(buf_n324_0),
        .A2(n514),
        .B1(reg_ctrl_0),
        .X(n516)
    );

    sky130_fd_sc_hd__a21oi_1 U226 (
        .A1(reg_load_13),
        .A2(buf_n324_0),
        .B1(n516),
        .Y(n517)
    );

    sky130_fd_sc_hd__nor2b_1 U227 (
        .A(n517),
        .B_N(reg_count_13),
        .Y(n518)
    );

    sky130_fd_sc_hd__inv_1 U228 (
        .A(reg_load_13),
        .Y(inv_n101)
    );

    sky130_fd_sc_hd__a211oi_1 U229 (
        .A1(inv_n101),
        .A2(buf_n324_0),
        .B1(reg_count_13),
        .C1(n516),
        .Y(n521)
    );

    sky130_fd_sc_hd__nor2_1 U230 (
        .A(n518),
        .B(n521),
        .Y(n522)
    );

    sky130_fd_sc_hd__nor2_1 U231 (
        .A(n291),
        .B(n522),
        .Y(n523)
    );

    sky130_fd_sc_hd__a21oi_1 U232 (
        .A1(pwdata_13),
        .A2(n291),
        .B1(n523),
        .Y(n524)
    );

    sky130_fd_sc_hd__nor4_1 U233 (
        .A(reg_count_10),
        .B(reg_count_11),
        .C(reg_count_12),
        .D(reg_count_13),
        .Y(n529)
    );

    sky130_fd_sc_hd__nor4_1 U234 (
        .A(reg_count_8),
        .B(reg_count_9),
        .C(n433),
        .D(clone_274),
        .Y(n530)
    );

    sky130_fd_sc_hd__nand2_1 U235 (
        .A(n298),
        .B(n530),
        .Y(n531)
    );

    sky130_fd_sc_hd__o21a_1 U236 (
        .A1(buf_n324_0),
        .A2(n531),
        .B1(reg_ctrl_0),
        .X(n533)
    );

    sky130_fd_sc_hd__a21oi_1 U237 (
        .A1(reg_load_14),
        .A2(buf_n324_0),
        .B1(n533),
        .Y(n534)
    );

    sky130_fd_sc_hd__nor2b_1 U238 (
        .A(n534),
        .B_N(reg_count_14),
        .Y(n535)
    );

    sky130_fd_sc_hd__inv_1 U239 (
        .A(reg_load_14),
        .Y(inv_n102)
    );

    sky130_fd_sc_hd__a211oi_1 U240 (
        .A1(inv_n102),
        .A2(buf_n324_0),
        .B1(reg_count_14),
        .C1(n533),
        .Y(n538)
    );

    sky130_fd_sc_hd__nor2_1 U241 (
        .A(n535),
        .B(n538),
        .Y(n539)
    );

    sky130_fd_sc_hd__nor2_1 U242 (
        .A(n291),
        .B(n539),
        .Y(n540)
    );

    sky130_fd_sc_hd__a21oi_1 U243 (
        .A1(pwdata_14),
        .A2(n291),
        .B1(n540),
        .Y(n541)
    );

    sky130_fd_sc_hd__nor4_1 U244 (
        .A(reg_count_11),
        .B(reg_count_12),
        .C(reg_count_13),
        .D(reg_count_14),
        .Y(n546)
    );

    sky130_fd_sc_hd__nand2_1 U245 (
        .A(n478),
        .B(n546),
        .Y(n547)
    );

    sky130_fd_sc_hd__nand2_1 U246 (
        .A(n299),
        .B(n547),
        .Y(n548)
    );

    sky130_fd_sc_hd__o21a_1 U247 (
        .A1(buf_n324_0),
        .A2(n548),
        .B1(reg_ctrl_0),
        .X(n550)
    );

    sky130_fd_sc_hd__a21oi_1 U248 (
        .A1(reg_load_15),
        .A2(buf_n324_0),
        .B1(n550),
        .Y(n551)
    );

    sky130_fd_sc_hd__nor2b_1 U249 (
        .A(n551),
        .B_N(reg_count_15),
        .Y(n552)
    );

    sky130_fd_sc_hd__inv_1 U250 (
        .A(reg_load_15),
        .Y(inv_n103)
    );

    sky130_fd_sc_hd__a211oi_1 U251 (
        .A1(inv_n103),
        .A2(buf_n324_0),
        .B1(reg_count_15),
        .C1(n550),
        .Y(n555)
    );

    sky130_fd_sc_hd__nor2_1 U252 (
        .A(n552),
        .B(n555),
        .Y(n556)
    );

    sky130_fd_sc_hd__nor2_1 U253 (
        .A(n291),
        .B(n556),
        .Y(n557)
    );

    sky130_fd_sc_hd__a21oi_1 U254 (
        .A1(pwdata_15),
        .A2(n291),
        .B1(n557),
        .Y(n558)
    );

    sky130_fd_sc_hd__nor4_1 U255 (
        .A(reg_count_12),
        .B(reg_count_13),
        .C(reg_count_14),
        .D(reg_count_15),
        .Y(n563)
    );

    sky130_fd_sc_hd__nand2_1 U256 (
        .A(n495),
        .B(n563),
        .Y(n564)
    );

    sky130_fd_sc_hd__nand2_1 U257 (
        .A(n435),
        .B(n564),
        .Y(n565)
    );

    sky130_fd_sc_hd__o21a_1 U258 (
        .A1(buf_n324_0),
        .A2(n565),
        .B1(reg_ctrl_0),
        .X(n567)
    );

    sky130_fd_sc_hd__a21oi_1 U259 (
        .A1(reg_load_16),
        .A2(buf_n324_0),
        .B1(n567),
        .Y(n568)
    );

    sky130_fd_sc_hd__nor2b_1 U260 (
        .A(n568),
        .B_N(reg_count_16),
        .Y(n569)
    );

    sky130_fd_sc_hd__inv_1 U261 (
        .A(reg_load_16),
        .Y(inv_n104)
    );

    sky130_fd_sc_hd__a211oi_1 U262 (
        .A1(inv_n104),
        .A2(buf_n324_0),
        .B1(reg_count_16),
        .C1(n567),
        .Y(n572)
    );

    sky130_fd_sc_hd__nor2_1 U263 (
        .A(n569),
        .B(n572),
        .Y(n573)
    );

    sky130_fd_sc_hd__nor2_1 U264 (
        .A(n291),
        .B(n573),
        .Y(n574)
    );

    sky130_fd_sc_hd__a21oi_1 U265 (
        .A1(pwdata_16),
        .A2(n291),
        .B1(n574),
        .Y(n575)
    );

    sky130_fd_sc_hd__nor4_1 U266 (
        .A(reg_count_13),
        .B(reg_count_14),
        .C(reg_count_15),
        .D(reg_count_16),
        .Y(n580)
    );

    sky130_fd_sc_hd__nand2_1 U267 (
        .A(n512),
        .B(n580),
        .Y(n581)
    );

    sky130_fd_sc_hd__nand2_1 U268 (
        .A(n301),
        .B(n581),
        .Y(n582)
    );

    sky130_fd_sc_hd__o21a_1 U269 (
        .A1(buf_n324_0),
        .A2(n582),
        .B1(reg_ctrl_0),
        .X(n584)
    );

    sky130_fd_sc_hd__a21oi_1 U270 (
        .A1(reg_load_17),
        .A2(buf_n324_0),
        .B1(n584),
        .Y(n585)
    );

    sky130_fd_sc_hd__nor2b_1 U271 (
        .A(n585),
        .B_N(reg_count_17),
        .Y(n586)
    );

    sky130_fd_sc_hd__inv_1 U272 (
        .A(reg_load_17),
        .Y(inv_n105)
    );

    sky130_fd_sc_hd__a211oi_1 U273 (
        .A1(inv_n105),
        .A2(buf_n324_0),
        .B1(reg_count_17),
        .C1(n584),
        .Y(n589)
    );

    sky130_fd_sc_hd__nor2_1 U274 (
        .A(n586),
        .B(n589),
        .Y(n590)
    );

    sky130_fd_sc_hd__nor2_1 U275 (
        .A(n291),
        .B(n590),
        .Y(n591)
    );

    sky130_fd_sc_hd__a21oi_1 U276 (
        .A1(pwdata_17),
        .A2(n291),
        .B1(n591),
        .Y(n592)
    );

    sky130_fd_sc_hd__nor4_1 U277 (
        .A(reg_count_14),
        .B(reg_count_15),
        .C(reg_count_16),
        .D(reg_count_17),
        .Y(n597)
    );

    sky130_fd_sc_hd__nand2_1 U278 (
        .A(n529),
        .B(n597),
        .Y(n598)
    );

    sky130_fd_sc_hd__nand2_1 U279 (
        .A(n302),
        .B(n598),
        .Y(n599)
    );

    sky130_fd_sc_hd__o21a_1 U280 (
        .A1(buf_n324_0),
        .A2(n599),
        .B1(reg_ctrl_0),
        .X(n601)
    );

    sky130_fd_sc_hd__a21oi_1 U281 (
        .A1(reg_load_18),
        .A2(buf_n324_0),
        .B1(n601),
        .Y(n602)
    );

    sky130_fd_sc_hd__nor2b_1 U282 (
        .A(n602),
        .B_N(reg_count_18),
        .Y(n603)
    );

    sky130_fd_sc_hd__inv_1 U283 (
        .A(reg_load_18),
        .Y(inv_n106)
    );

    sky130_fd_sc_hd__a211oi_1 U284 (
        .A1(inv_n106),
        .A2(buf_n324_0),
        .B1(reg_count_18),
        .C1(n601),
        .Y(n606)
    );

    sky130_fd_sc_hd__nor2_1 U285 (
        .A(n603),
        .B(n606),
        .Y(n607)
    );

    sky130_fd_sc_hd__nor2_1 U286 (
        .A(n291),
        .B(n607),
        .Y(n608)
    );

    sky130_fd_sc_hd__a21oi_1 U287 (
        .A1(pwdata_18),
        .A2(n291),
        .B1(n608),
        .Y(n609)
    );

    sky130_fd_sc_hd__nor4_1 U288 (
        .A(reg_count_15),
        .B(reg_count_16),
        .C(reg_count_17),
        .D(reg_count_18),
        .Y(n614)
    );

    sky130_fd_sc_hd__nand2_1 U289 (
        .A(n546),
        .B(n614),
        .Y(n615)
    );

    sky130_fd_sc_hd__nand2_1 U290 (
        .A(n480),
        .B(n615),
        .Y(n616)
    );

    sky130_fd_sc_hd__o21a_1 U291 (
        .A1(buf_n324_0),
        .A2(n616),
        .B1(reg_ctrl_0),
        .X(n618)
    );

    sky130_fd_sc_hd__a21oi_1 U292 (
        .A1(reg_load_19),
        .A2(buf_n324_0),
        .B1(n618),
        .Y(n619)
    );

    sky130_fd_sc_hd__nor2b_1 U293 (
        .A(n619),
        .B_N(reg_count_19),
        .Y(n620)
    );

    sky130_fd_sc_hd__inv_1 U294 (
        .A(reg_load_19),
        .Y(inv_n107)
    );

    sky130_fd_sc_hd__a211oi_1 U295 (
        .A1(inv_n107),
        .A2(buf_n324_0),
        .B1(reg_count_19),
        .C1(n618),
        .Y(n623)
    );

    sky130_fd_sc_hd__nor2_1 U296 (
        .A(n620),
        .B(n623),
        .Y(n624)
    );

    sky130_fd_sc_hd__nor2_1 U297 (
        .A(n291),
        .B(n624),
        .Y(n625)
    );

    sky130_fd_sc_hd__a21oi_1 U298 (
        .A1(pwdata_19),
        .A2(n291),
        .B1(n625),
        .Y(n626)
    );

    sky130_fd_sc_hd__nor4_1 U299 (
        .A(reg_count_16),
        .B(reg_count_17),
        .C(reg_count_18),
        .D(reg_count_19),
        .Y(n631)
    );

    sky130_fd_sc_hd__nand2_1 U300 (
        .A(n563),
        .B(n631),
        .Y(n632)
    );

    sky130_fd_sc_hd__nand2_1 U301 (
        .A(n497),
        .B(n632),
        .Y(n633)
    );

    sky130_fd_sc_hd__o21a_1 U302 (
        .A1(buf_n324_0),
        .A2(n633),
        .B1(reg_ctrl_0),
        .X(n635)
    );

    sky130_fd_sc_hd__a21oi_1 U303 (
        .A1(reg_load_20),
        .A2(buf_n324_0),
        .B1(n635),
        .Y(n636)
    );

    sky130_fd_sc_hd__nor2b_1 U304 (
        .A(n636),
        .B_N(reg_count_20),
        .Y(n637)
    );

    sky130_fd_sc_hd__inv_1 U305 (
        .A(reg_load_20),
        .Y(inv_n108)
    );

    sky130_fd_sc_hd__a211oi_1 U306 (
        .A1(inv_n108),
        .A2(buf_n324_0),
        .B1(reg_count_20),
        .C1(n635),
        .Y(n640)
    );

    sky130_fd_sc_hd__nor2_1 U307 (
        .A(n637),
        .B(n640),
        .Y(n641)
    );

    sky130_fd_sc_hd__nor2_1 U308 (
        .A(n291),
        .B(n641),
        .Y(n642)
    );

    sky130_fd_sc_hd__a21oi_1 U309 (
        .A1(pwdata_20),
        .A2(n291),
        .B1(n642),
        .Y(n643)
    );

    sky130_fd_sc_hd__nor4_1 U310 (
        .A(reg_count_17),
        .B(reg_count_18),
        .C(reg_count_19),
        .D(reg_count_20),
        .Y(n648)
    );

    sky130_fd_sc_hd__nand2_1 U311 (
        .A(n580),
        .B(n648),
        .Y(n649)
    );

    sky130_fd_sc_hd__nand2_1 U312 (
        .A(n514),
        .B(n649),
        .Y(n650)
    );

    sky130_fd_sc_hd__o21a_1 U313 (
        .A1(buf_n324_0),
        .A2(n650),
        .B1(reg_ctrl_0),
        .X(n652)
    );

    sky130_fd_sc_hd__a21oi_1 U314 (
        .A1(reg_load_21),
        .A2(buf_n324_0),
        .B1(n652),
        .Y(n653)
    );

    sky130_fd_sc_hd__nor2b_1 U315 (
        .A(n653),
        .B_N(reg_count_21),
        .Y(n654)
    );

    sky130_fd_sc_hd__inv_1 U316 (
        .A(reg_load_21),
        .Y(inv_n109)
    );

    sky130_fd_sc_hd__a211oi_1 U317 (
        .A1(inv_n109),
        .A2(buf_n324_0),
        .B1(reg_count_21),
        .C1(n652),
        .Y(n657)
    );

    sky130_fd_sc_hd__nor2_1 U318 (
        .A(n654),
        .B(n657),
        .Y(n658)
    );

    sky130_fd_sc_hd__nor2_1 U319 (
        .A(n291),
        .B(n658),
        .Y(n659)
    );

    sky130_fd_sc_hd__a21oi_1 U320 (
        .A1(pwdata_21),
        .A2(n291),
        .B1(n659),
        .Y(n660)
    );

    sky130_fd_sc_hd__nor4_1 U321 (
        .A(reg_count_18),
        .B(reg_count_19),
        .C(reg_count_20),
        .D(reg_count_21),
        .Y(n665)
    );

    sky130_fd_sc_hd__nand2_1 U322 (
        .A(n597),
        .B(n665),
        .Y(n666)
    );

    sky130_fd_sc_hd__nand2_1 U323 (
        .A(n531),
        .B(n666),
        .Y(n667)
    );

    sky130_fd_sc_hd__o21a_1 U324 (
        .A1(buf_n324_0),
        .A2(n667),
        .B1(reg_ctrl_0),
        .X(n669)
    );

    sky130_fd_sc_hd__a21oi_1 U325 (
        .A1(reg_load_22),
        .A2(buf_n324_0),
        .B1(n669),
        .Y(n670)
    );

    sky130_fd_sc_hd__nor2b_1 U326 (
        .A(n670),
        .B_N(reg_count_22),
        .Y(n671)
    );

    sky130_fd_sc_hd__inv_1 U327 (
        .A(reg_load_22),
        .Y(inv_n110)
    );

    sky130_fd_sc_hd__a211oi_1 U328 (
        .A1(inv_n110),
        .A2(buf_n324_0),
        .B1(reg_count_22),
        .C1(n669),
        .Y(n674)
    );

    sky130_fd_sc_hd__nor2_1 U329 (
        .A(n671),
        .B(n674),
        .Y(n675)
    );

    sky130_fd_sc_hd__nor2_1 U330 (
        .A(n291),
        .B(n675),
        .Y(n676)
    );

    sky130_fd_sc_hd__a21oi_1 U331 (
        .A1(pwdata_22),
        .A2(n291),
        .B1(n676),
        .Y(n677)
    );

    sky130_fd_sc_hd__nor4_1 U332 (
        .A(reg_count_19),
        .B(reg_count_20),
        .C(reg_count_21),
        .D(reg_count_22),
        .Y(n682)
    );

    sky130_fd_sc_hd__nand2_1 U333 (
        .A(n614),
        .B(n682),
        .Y(n683)
    );

    sky130_fd_sc_hd__nand2_1 U334 (
        .A(n548),
        .B(n683),
        .Y(n684)
    );

    sky130_fd_sc_hd__o21a_1 U335 (
        .A1(buf_n324_0),
        .A2(n684),
        .B1(reg_ctrl_0),
        .X(n686)
    );

    sky130_fd_sc_hd__a21oi_1 U336 (
        .A1(reg_load_23),
        .A2(buf_n324_0),
        .B1(n686),
        .Y(n687)
    );

    sky130_fd_sc_hd__nor2b_1 U337 (
        .A(n687),
        .B_N(reg_count_23),
        .Y(n688)
    );

    sky130_fd_sc_hd__inv_1 U338 (
        .A(reg_load_23),
        .Y(inv_n111)
    );

    sky130_fd_sc_hd__a211oi_1 U339 (
        .A1(inv_n111),
        .A2(buf_n324_0),
        .B1(reg_count_23),
        .C1(n686),
        .Y(n691)
    );

    sky130_fd_sc_hd__nor2_1 U340 (
        .A(n688),
        .B(n691),
        .Y(n692)
    );

    sky130_fd_sc_hd__nor2_1 U341 (
        .A(n291),
        .B(n692),
        .Y(n693)
    );

    sky130_fd_sc_hd__a21oi_1 U342 (
        .A1(pwdata_23),
        .A2(n291),
        .B1(n693),
        .Y(n694)
    );

    sky130_fd_sc_hd__nor4_1 U343 (
        .A(reg_count_20),
        .B(reg_count_21),
        .C(reg_count_22),
        .D(reg_count_23),
        .Y(n699)
    );

    sky130_fd_sc_hd__nand2_1 U344 (
        .A(n631),
        .B(n699),
        .Y(n700)
    );

    sky130_fd_sc_hd__nand2_1 U345 (
        .A(n565),
        .B(n700),
        .Y(n701)
    );

    sky130_fd_sc_hd__o21a_1 U346 (
        .A1(buf_n324_0),
        .A2(n701),
        .B1(reg_ctrl_0),
        .X(n703)
    );

    sky130_fd_sc_hd__a21oi_1 U347 (
        .A1(reg_load_24),
        .A2(buf_n324_0),
        .B1(n703),
        .Y(n704)
    );

    sky130_fd_sc_hd__nor2b_1 U348 (
        .A(n704),
        .B_N(reg_count_24),
        .Y(n705)
    );

    sky130_fd_sc_hd__inv_1 U349 (
        .A(reg_load_24),
        .Y(inv_n112)
    );

    sky130_fd_sc_hd__a211oi_1 U350 (
        .A1(inv_n112),
        .A2(buf_n324_0),
        .B1(reg_count_24),
        .C1(n703),
        .Y(n708)
    );

    sky130_fd_sc_hd__nor2_1 U351 (
        .A(n705),
        .B(n708),
        .Y(n709)
    );

    sky130_fd_sc_hd__nor2_1 U352 (
        .A(n291),
        .B(n709),
        .Y(n710)
    );

    sky130_fd_sc_hd__a21oi_1 U353 (
        .A1(pwdata_24),
        .A2(n291),
        .B1(n710),
        .Y(n711)
    );

    sky130_fd_sc_hd__nor4_1 U354 (
        .A(reg_count_21),
        .B(reg_count_22),
        .C(reg_count_23),
        .D(reg_count_24),
        .Y(n716)
    );

    sky130_fd_sc_hd__nand2_1 U355 (
        .A(n648),
        .B(n716),
        .Y(n717)
    );

    sky130_fd_sc_hd__nand2_1 U356 (
        .A(n582),
        .B(n717),
        .Y(n718)
    );

    sky130_fd_sc_hd__o21a_1 U357 (
        .A1(buf_n324_1),
        .A2(n718),
        .B1(reg_ctrl_0),
        .X(n720)
    );

    sky130_fd_sc_hd__a21oi_1 U358 (
        .A1(reg_load_25),
        .A2(buf_n324_1),
        .B1(n720),
        .Y(n721)
    );

    sky130_fd_sc_hd__nor2b_1 U359 (
        .A(n721),
        .B_N(reg_count_25),
        .Y(n722)
    );

    sky130_fd_sc_hd__inv_1 U360 (
        .A(reg_load_25),
        .Y(inv_n113)
    );

    sky130_fd_sc_hd__a211oi_1 U361 (
        .A1(inv_n113),
        .A2(buf_n324_1),
        .B1(reg_count_25),
        .C1(n720),
        .Y(n725)
    );

    sky130_fd_sc_hd__nor2_1 U362 (
        .A(n722),
        .B(n725),
        .Y(n726)
    );

    sky130_fd_sc_hd__nor2_1 U363 (
        .A(n291),
        .B(n726),
        .Y(n727)
    );

    sky130_fd_sc_hd__a21oi_1 U364 (
        .A1(pwdata_25),
        .A2(n291),
        .B1(n727),
        .Y(n728)
    );

    sky130_fd_sc_hd__nor4_1 U365 (
        .A(reg_count_22),
        .B(reg_count_23),
        .C(reg_count_24),
        .D(reg_count_25),
        .Y(n733)
    );

    sky130_fd_sc_hd__nand2_1 U366 (
        .A(n665),
        .B(n733),
        .Y(n734)
    );

    sky130_fd_sc_hd__nand2_1 U367 (
        .A(n599),
        .B(n734),
        .Y(n735)
    );

    sky130_fd_sc_hd__o21a_1 U368 (
        .A1(buf_n324_1),
        .A2(n735),
        .B1(reg_ctrl_0),
        .X(n737)
    );

    sky130_fd_sc_hd__a21oi_1 U369 (
        .A1(reg_load_26),
        .A2(buf_n324_1),
        .B1(n737),
        .Y(n738)
    );

    sky130_fd_sc_hd__nor2b_1 U370 (
        .A(n738),
        .B_N(reg_count_26),
        .Y(n739)
    );

    sky130_fd_sc_hd__inv_1 U371 (
        .A(reg_load_26),
        .Y(inv_n114)
    );

    sky130_fd_sc_hd__a211oi_1 U372 (
        .A1(inv_n114),
        .A2(buf_n324_1),
        .B1(reg_count_26),
        .C1(n737),
        .Y(n742)
    );

    sky130_fd_sc_hd__nor2_1 U373 (
        .A(n739),
        .B(n742),
        .Y(n743)
    );

    sky130_fd_sc_hd__nor2_1 U374 (
        .A(n291),
        .B(n743),
        .Y(n744)
    );

    sky130_fd_sc_hd__a21oi_1 U375 (
        .A1(pwdata_26),
        .A2(n291),
        .B1(n744),
        .Y(n745)
    );

    sky130_fd_sc_hd__nor4_1 U376 (
        .A(reg_count_23),
        .B(reg_count_24),
        .C(reg_count_25),
        .D(reg_count_26),
        .Y(n750)
    );

    sky130_fd_sc_hd__nand2_1 U377 (
        .A(n682),
        .B(n750),
        .Y(n751)
    );

    sky130_fd_sc_hd__nand2_1 U378 (
        .A(n616),
        .B(n751),
        .Y(n752)
    );

    sky130_fd_sc_hd__o21a_1 U379 (
        .A1(buf_n324_1),
        .A2(n752),
        .B1(reg_ctrl_0),
        .X(n754)
    );

    sky130_fd_sc_hd__a21oi_1 U380 (
        .A1(reg_load_27),
        .A2(buf_n324_1),
        .B1(n754),
        .Y(n755)
    );

    sky130_fd_sc_hd__nor2b_1 U381 (
        .A(n755),
        .B_N(reg_count_27),
        .Y(n756)
    );

    sky130_fd_sc_hd__inv_1 U382 (
        .A(reg_load_27),
        .Y(inv_n115)
    );

    sky130_fd_sc_hd__a211oi_1 U383 (
        .A1(inv_n115),
        .A2(buf_n324_1),
        .B1(reg_count_27),
        .C1(n754),
        .Y(n759)
    );

    sky130_fd_sc_hd__nor2_1 U384 (
        .A(n756),
        .B(n759),
        .Y(n760)
    );

    sky130_fd_sc_hd__nor2_1 U385 (
        .A(n291),
        .B(n760),
        .Y(n761)
    );

    sky130_fd_sc_hd__a21oi_1 U386 (
        .A1(pwdata_27),
        .A2(n291),
        .B1(n761),
        .Y(n762)
    );

    sky130_fd_sc_hd__nor2_1 U387 (
        .A(reg_count_26),
        .B(reg_count_27),
        .Y(n766)
    );

    sky130_fd_sc_hd__nand2_1 U388 (
        .A(n632),
        .B(n699),
        .Y(n768)
    );

    sky130_fd_sc_hd__nor4_1 U389 (
        .A(reg_count_24),
        .B(reg_count_25),
        .C(n766),
        .D(n768),
        .Y(n769)
    );

    sky130_fd_sc_hd__nand2_1 U390 (
        .A(n497),
        .B(n769),
        .Y(n770)
    );

    sky130_fd_sc_hd__o21a_1 U391 (
        .A1(buf_n324_1),
        .A2(n770),
        .B1(reg_ctrl_0),
        .X(n772)
    );

    sky130_fd_sc_hd__a21oi_1 U392 (
        .A1(reg_load_28),
        .A2(buf_n324_1),
        .B1(n772),
        .Y(n773)
    );

    sky130_fd_sc_hd__nor2b_1 U393 (
        .A(n773),
        .B_N(reg_count_28),
        .Y(n774)
    );

    sky130_fd_sc_hd__inv_1 U394 (
        .A(reg_load_28),
        .Y(inv_n116)
    );

    sky130_fd_sc_hd__a211oi_1 U395 (
        .A1(inv_n116),
        .A2(buf_n324_1),
        .B1(reg_count_28),
        .C1(n772),
        .Y(n777)
    );

    sky130_fd_sc_hd__nor2_1 U396 (
        .A(n774),
        .B(n777),
        .Y(n778)
    );

    sky130_fd_sc_hd__nor2_1 U397 (
        .A(n291),
        .B(n778),
        .Y(n779)
    );

    sky130_fd_sc_hd__a21oi_1 U398 (
        .A1(pwdata_28),
        .A2(n291),
        .B1(n779),
        .Y(n780)
    );

    sky130_fd_sc_hd__nor2_1 U399 (
        .A(reg_count_27),
        .B(reg_count_28),
        .Y(n784)
    );

    sky130_fd_sc_hd__nand2_1 U400 (
        .A(n649),
        .B(n716),
        .Y(n786)
    );

    sky130_fd_sc_hd__nor4_1 U401 (
        .A(reg_count_25),
        .B(reg_count_26),
        .C(n784),
        .D(n786),
        .Y(n787)
    );

    sky130_fd_sc_hd__nand2_1 U402 (
        .A(n514),
        .B(n787),
        .Y(n788)
    );

    sky130_fd_sc_hd__o21a_1 U403 (
        .A1(buf_n324_1),
        .A2(n788),
        .B1(reg_ctrl_0),
        .X(n790)
    );

    sky130_fd_sc_hd__a21oi_1 U404 (
        .A1(reg_load_29),
        .A2(buf_n324_1),
        .B1(n790),
        .Y(n791)
    );

    sky130_fd_sc_hd__nor2b_1 U405 (
        .A(n791),
        .B_N(reg_count_29),
        .Y(n792)
    );

    sky130_fd_sc_hd__inv_1 U406 (
        .A(reg_load_29),
        .Y(inv_n117)
    );

    sky130_fd_sc_hd__a211oi_1 U407 (
        .A1(inv_n117),
        .A2(buf_n324_1),
        .B1(reg_count_29),
        .C1(n790),
        .Y(n795)
    );

    sky130_fd_sc_hd__nor2_1 U408 (
        .A(n792),
        .B(n795),
        .Y(n796)
    );

    sky130_fd_sc_hd__nor2_1 U409 (
        .A(n291),
        .B(n796),
        .Y(n797)
    );

    sky130_fd_sc_hd__a21oi_1 U410 (
        .A1(pwdata_29),
        .A2(n291),
        .B1(n797),
        .Y(n798)
    );

    sky130_fd_sc_hd__nor3_1 U411 (
        .A(reg_count_26),
        .B(reg_count_27),
        .C(clone_484),
        .Y(n803)
    );

    sky130_fd_sc_hd__nor3_1 U412 (
        .A(reg_count_28),
        .B(reg_count_29),
        .C(n803),
        .Y(n804)
    );

    sky130_fd_sc_hd__nand2_1 U413 (
        .A(n666),
        .B(n804),
        .Y(n805)
    );

    sky130_fd_sc_hd__nand2_1 U414 (
        .A(n531),
        .B(n805),
        .Y(n806)
    );

    sky130_fd_sc_hd__o21a_1 U415 (
        .A1(buf_n324_1),
        .A2(n806),
        .B1(reg_ctrl_0),
        .X(n808)
    );

    sky130_fd_sc_hd__a21oi_1 U416 (
        .A1(reg_load_30),
        .A2(buf_n324_1),
        .B1(n808),
        .Y(n809)
    );

    sky130_fd_sc_hd__nor2b_1 U417 (
        .A(n809),
        .B_N(reg_count_30),
        .Y(n810)
    );

    sky130_fd_sc_hd__inv_1 U418 (
        .A(reg_load_30),
        .Y(inv_n118)
    );

    sky130_fd_sc_hd__a211oi_1 U419 (
        .A1(inv_n118),
        .A2(buf_n324_1),
        .B1(reg_count_30),
        .C1(n808),
        .Y(n813)
    );

    sky130_fd_sc_hd__nor2_1 U420 (
        .A(n810),
        .B(n813),
        .Y(n814)
    );

    sky130_fd_sc_hd__nor2_1 U421 (
        .A(n291),
        .B(n814),
        .Y(n815)
    );

    sky130_fd_sc_hd__a21oi_1 U422 (
        .A1(pwdata_30),
        .A2(n291),
        .B1(n815),
        .Y(n816)
    );

    sky130_fd_sc_hd__nor3_1 U423 (
        .A(reg_count_27),
        .B(reg_count_28),
        .C(clone_499),
        .Y(n821)
    );

    sky130_fd_sc_hd__nor3_1 U424 (
        .A(reg_count_29),
        .B(reg_count_30),
        .C(n821),
        .Y(n822)
    );

    sky130_fd_sc_hd__nor3_1 U425 (
        .A(reg_count_29),
        .B(reg_count_30),
        .C(n822),
        .Y(n824)
    );

    sky130_fd_sc_hd__nand2_1 U426 (
        .A(n683),
        .B(n824),
        .Y(n825)
    );

    sky130_fd_sc_hd__nand2_1 U427 (
        .A(n548),
        .B(n825),
        .Y(n826)
    );

    sky130_fd_sc_hd__o21a_1 U428 (
        .A1(buf_n324_1),
        .A2(n826),
        .B1(reg_ctrl_0),
        .X(n828)
    );

    sky130_fd_sc_hd__a21oi_1 U429 (
        .A1(reg_load_31),
        .A2(buf_n324_1),
        .B1(n828),
        .Y(n829)
    );

    sky130_fd_sc_hd__nor2b_1 U430 (
        .A(n829),
        .B_N(reg_count_31),
        .Y(n830)
    );

    sky130_fd_sc_hd__inv_1 U431 (
        .A(reg_load_31),
        .Y(inv_n119)
    );

    sky130_fd_sc_hd__a211oi_1 U432 (
        .A1(inv_n119),
        .A2(buf_n324_1),
        .B1(reg_count_31),
        .C1(n828),
        .Y(n833)
    );

    sky130_fd_sc_hd__nor2_1 U433 (
        .A(n830),
        .B(n833),
        .Y(n834)
    );

    sky130_fd_sc_hd__nor2_1 U434 (
        .A(n291),
        .B(n834),
        .Y(n835)
    );

    sky130_fd_sc_hd__a21oi_1 U435 (
        .A1(pwdata_31),
        .A2(n291),
        .B1(n835),
        .Y(n836)
    );

    sky130_fd_sc_hd__nand2_1 U436 (
        .A(n123),
        .B(n289),
        .Y(n838)
    );

    sky130_fd_sc_hd__o21a_1 U437 (
        .A1(reg_ctrl_0),
        .A2(n838),
        .B1(buf_rst_n_0),
        .X(n841)
    );

    sky130_fd_sc_hd__o21a_1 U438 (
        .A1(pwdata_3),
        .A2(clone_517),
        .B1(n841),
        .X(__dff_d_ff2043)
    );

    sky130_fd_sc_hd__o21a_1 U439 (
        .A1(reg_ctrl_1),
        .A2(n838),
        .B1(buf_rst_n_0),
        .X(n845)
    );

    sky130_fd_sc_hd__o21a_1 U440 (
        .A1(pwdata_2),
        .A2(clone_517),
        .B1(n845),
        .X(__dff_d_ff2044)
    );

    sky130_fd_sc_hd__o21a_1 U441 (
        .A1(reg_ctrl_2),
        .A2(n838),
        .B1(buf_rst_n_0),
        .X(n849)
    );

    sky130_fd_sc_hd__o21a_1 U442 (
        .A1(pwdata_1),
        .A2(clone_517),
        .B1(n849),
        .X(__dff_d_ff2045)
    );

    sky130_fd_sc_hd__o21a_1 U443 (
        .A1(reg_ctrl_3),
        .A2(n838),
        .B1(buf_rst_n_0),
        .X(n853)
    );

    sky130_fd_sc_hd__o21a_1 U444 (
        .A1(pwdata_0),
        .A2(clone_517),
        .B1(n853),
        .X(__dff_d_ff2046)
    );

    sky130_fd_sc_hd__inv_1 U445 (
        .A(reg_load_0),
        .Y(inv_n88)
    );

    sky130_fd_sc_hd__o21a_1 U446 (
        .A1(inv_n88),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n857)
    );

    sky130_fd_sc_hd__a21oi_1 U447 (
        .A1(pwdata_0),
        .A2(buf_n290_0),
        .B1(n857),
        .Y(__dff_d_ff2047)
    );

    sky130_fd_sc_hd__inv_1 U448 (
        .A(reg_load_1),
        .Y(inv_n89)
    );

    sky130_fd_sc_hd__o21a_1 U449 (
        .A1(inv_n89),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n861)
    );

    sky130_fd_sc_hd__a21oi_1 U450 (
        .A1(pwdata_1),
        .A2(buf_n290_0),
        .B1(n861),
        .Y(__dff_d_ff2048)
    );

    sky130_fd_sc_hd__o21a_1 U451 (
        .A1(inv_n90),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n865)
    );

    sky130_fd_sc_hd__a21oi_1 U452 (
        .A1(pwdata_2),
        .A2(buf_n290_0),
        .B1(n865),
        .Y(__dff_d_ff2049)
    );

    sky130_fd_sc_hd__o21a_1 U453 (
        .A1(inv_n91),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n869)
    );

    sky130_fd_sc_hd__a21oi_1 U454 (
        .A1(pwdata_3),
        .A2(buf_n290_0),
        .B1(n869),
        .Y(__dff_d_ff2050)
    );

    sky130_fd_sc_hd__o21a_1 U455 (
        .A1(inv_n92),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n873)
    );

    sky130_fd_sc_hd__a21oi_1 U456 (
        .A1(pwdata_4),
        .A2(buf_n290_0),
        .B1(n873),
        .Y(__dff_d_ff2051)
    );

    sky130_fd_sc_hd__o21a_1 U457 (
        .A1(inv_n93),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n877)
    );

    sky130_fd_sc_hd__a21oi_1 U458 (
        .A1(pwdata_5),
        .A2(buf_n290_0),
        .B1(n877),
        .Y(__dff_d_ff2052)
    );

    sky130_fd_sc_hd__o21a_1 U459 (
        .A1(inv_n94),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n881)
    );

    sky130_fd_sc_hd__a21oi_1 U460 (
        .A1(pwdata_6),
        .A2(buf_n290_0),
        .B1(n881),
        .Y(__dff_d_ff2053)
    );

    sky130_fd_sc_hd__o21a_1 U461 (
        .A1(inv_n95),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n885)
    );

    sky130_fd_sc_hd__a21oi_1 U462 (
        .A1(pwdata_7),
        .A2(buf_n290_0),
        .B1(n885),
        .Y(__dff_d_ff2054)
    );

    sky130_fd_sc_hd__o21a_1 U463 (
        .A1(inv_n96),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n889)
    );

    sky130_fd_sc_hd__a21oi_1 U464 (
        .A1(pwdata_8),
        .A2(buf_n290_0),
        .B1(n889),
        .Y(__dff_d_ff2055)
    );

    sky130_fd_sc_hd__o21a_1 U465 (
        .A1(inv_n97),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n893)
    );

    sky130_fd_sc_hd__a21oi_1 U466 (
        .A1(pwdata_9),
        .A2(buf_n290_0),
        .B1(n893),
        .Y(__dff_d_ff2056)
    );

    sky130_fd_sc_hd__o21a_1 U467 (
        .A1(inv_n98),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n897)
    );

    sky130_fd_sc_hd__a21oi_1 U468 (
        .A1(pwdata_10),
        .A2(buf_n290_0),
        .B1(n897),
        .Y(__dff_d_ff2057)
    );

    sky130_fd_sc_hd__o21a_1 U469 (
        .A1(inv_n99),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n901)
    );

    sky130_fd_sc_hd__a21oi_1 U470 (
        .A1(pwdata_11),
        .A2(buf_n290_0),
        .B1(n901),
        .Y(__dff_d_ff2058)
    );

    sky130_fd_sc_hd__o21a_1 U471 (
        .A1(inv_n100),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n905)
    );

    sky130_fd_sc_hd__a21oi_1 U472 (
        .A1(pwdata_12),
        .A2(buf_n290_0),
        .B1(n905),
        .Y(__dff_d_ff2059)
    );

    sky130_fd_sc_hd__o21a_1 U473 (
        .A1(inv_n101),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n909)
    );

    sky130_fd_sc_hd__a21oi_1 U474 (
        .A1(pwdata_13),
        .A2(buf_n290_0),
        .B1(n909),
        .Y(__dff_d_ff2060)
    );

    sky130_fd_sc_hd__o21a_1 U475 (
        .A1(inv_n102),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n913)
    );

    sky130_fd_sc_hd__a21oi_1 U476 (
        .A1(pwdata_14),
        .A2(buf_n290_0),
        .B1(n913),
        .Y(__dff_d_ff2061)
    );

    sky130_fd_sc_hd__o21a_1 U477 (
        .A1(inv_n103),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n917)
    );

    sky130_fd_sc_hd__a21oi_1 U478 (
        .A1(pwdata_15),
        .A2(buf_n290_0),
        .B1(n917),
        .Y(__dff_d_ff2062)
    );

    sky130_fd_sc_hd__o21a_1 U479 (
        .A1(inv_n104),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n921)
    );

    sky130_fd_sc_hd__a21oi_1 U480 (
        .A1(pwdata_16),
        .A2(buf_n290_0),
        .B1(n921),
        .Y(__dff_d_ff2063)
    );

    sky130_fd_sc_hd__o21a_1 U481 (
        .A1(inv_n105),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n925)
    );

    sky130_fd_sc_hd__a21oi_1 U482 (
        .A1(pwdata_17),
        .A2(buf_n290_0),
        .B1(n925),
        .Y(__dff_d_ff2064)
    );

    sky130_fd_sc_hd__o21a_1 U483 (
        .A1(inv_n106),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n929)
    );

    sky130_fd_sc_hd__a21oi_1 U484 (
        .A1(pwdata_18),
        .A2(buf_n290_0),
        .B1(n929),
        .Y(__dff_d_ff2065)
    );

    sky130_fd_sc_hd__o21a_1 U485 (
        .A1(inv_n107),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n933)
    );

    sky130_fd_sc_hd__a21oi_1 U486 (
        .A1(pwdata_19),
        .A2(buf_n290_0),
        .B1(n933),
        .Y(__dff_d_ff2066)
    );

    sky130_fd_sc_hd__o21a_1 U487 (
        .A1(inv_n108),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n937)
    );

    sky130_fd_sc_hd__a21oi_1 U488 (
        .A1(pwdata_20),
        .A2(buf_n290_0),
        .B1(n937),
        .Y(__dff_d_ff2067)
    );

    sky130_fd_sc_hd__o21a_1 U489 (
        .A1(inv_n109),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n941)
    );

    sky130_fd_sc_hd__a21oi_1 U490 (
        .A1(pwdata_21),
        .A2(buf_n290_0),
        .B1(n941),
        .Y(__dff_d_ff2068)
    );

    sky130_fd_sc_hd__o21a_1 U491 (
        .A1(inv_n110),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n945)
    );

    sky130_fd_sc_hd__a21oi_1 U492 (
        .A1(pwdata_22),
        .A2(buf_n290_0),
        .B1(n945),
        .Y(__dff_d_ff2069)
    );

    sky130_fd_sc_hd__o21a_1 U493 (
        .A1(inv_n111),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n949)
    );

    sky130_fd_sc_hd__a21oi_1 U494 (
        .A1(pwdata_23),
        .A2(buf_n290_0),
        .B1(n949),
        .Y(__dff_d_ff2070)
    );

    sky130_fd_sc_hd__o21a_1 U495 (
        .A1(inv_n112),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n953)
    );

    sky130_fd_sc_hd__a21oi_1 U496 (
        .A1(pwdata_24),
        .A2(buf_n290_0),
        .B1(n953),
        .Y(__dff_d_ff2071)
    );

    sky130_fd_sc_hd__o21a_1 U497 (
        .A1(inv_n113),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n957)
    );

    sky130_fd_sc_hd__a21oi_1 U498 (
        .A1(pwdata_25),
        .A2(buf_n290_0),
        .B1(n957),
        .Y(__dff_d_ff2072)
    );

    sky130_fd_sc_hd__o21a_1 U499 (
        .A1(inv_n114),
        .A2(buf_n290_0),
        .B1(buf_rst_n_0),
        .X(n961)
    );

    sky130_fd_sc_hd__a21oi_1 U500 (
        .A1(pwdata_26),
        .A2(buf_n290_0),
        .B1(n961),
        .Y(__dff_d_ff2073)
    );

    sky130_fd_sc_hd__o21a_1 U501 (
        .A1(inv_n115),
        .A2(buf_n290_0),
        .B1(buf_rst_n_1),
        .X(n965)
    );

    sky130_fd_sc_hd__a21oi_1 U502 (
        .A1(pwdata_27),
        .A2(buf_n290_0),
        .B1(n965),
        .Y(__dff_d_ff2074)
    );

    sky130_fd_sc_hd__o21a_1 U503 (
        .A1(inv_n116),
        .A2(buf_n290_0),
        .B1(buf_rst_n_1),
        .X(n969)
    );

    sky130_fd_sc_hd__a21oi_1 U504 (
        .A1(pwdata_28),
        .A2(buf_n290_0),
        .B1(n969),
        .Y(__dff_d_ff2075)
    );

    sky130_fd_sc_hd__o21a_1 U505 (
        .A1(inv_n117),
        .A2(buf_n290_0),
        .B1(buf_rst_n_1),
        .X(n973)
    );

    sky130_fd_sc_hd__a21oi_1 U506 (
        .A1(pwdata_29),
        .A2(buf_n290_0),
        .B1(n973),
        .Y(__dff_d_ff2076)
    );

    sky130_fd_sc_hd__o21a_1 U507 (
        .A1(inv_n118),
        .A2(buf_n290_0),
        .B1(buf_rst_n_1),
        .X(n977)
    );

    sky130_fd_sc_hd__a21oi_1 U508 (
        .A1(pwdata_30),
        .A2(buf_n290_0),
        .B1(n977),
        .Y(__dff_d_ff2077)
    );

    sky130_fd_sc_hd__o21a_1 U509 (
        .A1(inv_n119),
        .A2(buf_n290_0),
        .B1(buf_rst_n_1),
        .X(n981)
    );

    sky130_fd_sc_hd__a21oi_1 U510 (
        .A1(pwdata_31),
        .A2(n290),
        .B1(n981),
        .Y(__dff_d_ff2078)
    );

    sky130_fd_sc_hd__nand4_1 U511 (
        .A(psel),
        .B(penable),
        .C(pwrite),
        .D(n127),
        .Y(n983)
    );

    sky130_fd_sc_hd__nand2_1 U512 (
        .A(pwdata_1),
        .B(n983),
        .Y(n984)
    );

    sky130_fd_sc_hd__inv_1 U513 (
        .A(reg_status_0),
        .Y(inv_n120)
    );

    sky130_fd_sc_hd__a211oi_1 U514 (
        .A1(inv_n84),
        .A2(inv_n120),
        .B1(inv_n2),
        .C1(n984),
        .Y(__dff_d_ff2079)
    );

    sky130_fd_sc_hd__inv_1 U515 (
        .A(reg_status_1),
        .Y(inv_n121)
    );

    sky130_fd_sc_hd__a211oi_1 U516 (
        .A1(pwdata_0),
        .A2(n983),
        .B1(inv_n2),
        .C1(inv_n121),
        .Y(__dff_d_ff2080)
    );

    sky130_fd_sc_hd__buf_1 U517 (
        .A(GND),
        .X(pslverr)
    );

    sky130_fd_sc_hd__and3_1 U518 (
        .A(psel),
        .B(penable),
        .C(pwrite),
        .X(clone_50)
    );

    sky130_fd_sc_hd__and4_1 U519 (
        .A(reg_count_2),
        .B(reg_count_5),
        .C(n294),
        .D(n295),
        .X(clone_92)
    );

    sky130_fd_sc_hd__or2_1 U520 (
        .A(reg_count_6),
        .B(clone_92),
        .X(clone_94)
    );

    sky130_fd_sc_hd__or3_1 U521 (
        .A(reg_count_7),
        .B(reg_count_8),
        .C(clone_94),
        .X(clone_96)
    );

    sky130_fd_sc_hd__or2_1 U522 (
        .A(reg_count_9),
        .B(clone_96),
        .X(clone_98)
    );

    sky130_fd_sc_hd__or2_1 U523 (
        .A(reg_count_31),
        .B(n323),
        .X(clone_126)
    );

    sky130_fd_sc_hd__and4_1 U524 (
        .A(reg_count_0),
        .B(reg_count_1),
        .C(reg_count_2),
        .D(reg_count_3),
        .X(clone_157)
    );

    sky130_fd_sc_hd__and4_1 U525 (
        .A(reg_count_7),
        .B(reg_count_8),
        .C(reg_count_9),
        .D(reg_count_10),
        .X(clone_233)
    );

    sky130_fd_sc_hd__and4_1 U526 (
        .A(reg_count_9),
        .B(reg_count_10),
        .C(reg_count_11),
        .D(reg_count_12),
        .X(clone_260)
    );

    sky130_fd_sc_hd__and4_1 U527 (
        .A(reg_count_10),
        .B(reg_count_11),
        .C(reg_count_12),
        .D(reg_count_13),
        .X(clone_274)
    );

    sky130_fd_sc_hd__and4_1 U528 (
        .A(reg_count_22),
        .B(reg_count_23),
        .C(reg_count_24),
        .D(reg_count_25),
        .X(clone_484)
    );

    sky130_fd_sc_hd__and4_1 U529 (
        .A(reg_count_23),
        .B(reg_count_24),
        .C(reg_count_25),
        .D(reg_count_26),
        .X(clone_499)
    );

    sky130_fd_sc_hd__and2_1 U530 (
        .A(n123),
        .B(n289),
        .X(clone_517)
    );

    sky130_fd_sc_hd__buf_1 U531 (
        .A(rst_n),
        .X(buf_rst_n_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U532 (
        .D(__dff_d_ff199),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(key_valid)
    );

    sky130_fd_sc_hd__dfrtp_1 U533 (
        .D(__dff_d_ff2012),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_count_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U534 (
        .D(__dff_d_ff2043),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_ctrl_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U535 (
        .D(__dff_d_ff2044),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_ctrl_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U536 (
        .D(__dff_d_ff2045),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_ctrl_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U537 (
        .D(__dff_d_ff2046),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_ctrl_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U538 (
        .D(__dff_d_ff2047),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U539 (
        .D(__dff_d_ff2048),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U540 (
        .D(__dff_d_ff2049),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U541 (
        .D(__dff_d_ff2050),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U542 (
        .D(__dff_d_ff2051),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U543 (
        .D(__dff_d_ff2052),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U544 (
        .D(__dff_d_ff2053),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U545 (
        .D(__dff_d_ff2054),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U546 (
        .D(__dff_d_ff2055),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U547 (
        .D(__dff_d_ff2056),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U548 (
        .D(__dff_d_ff2057),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U549 (
        .D(__dff_d_ff2058),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U550 (
        .D(__dff_d_ff2059),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U551 (
        .D(__dff_d_ff2060),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U552 (
        .D(__dff_d_ff2061),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U553 (
        .D(__dff_d_ff2062),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U554 (
        .D(__dff_d_ff2063),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U555 (
        .D(__dff_d_ff2064),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U556 (
        .D(__dff_d_ff2065),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U557 (
        .D(__dff_d_ff2066),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U558 (
        .D(__dff_d_ff2067),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U559 (
        .D(__dff_d_ff2068),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U560 (
        .D(__dff_d_ff2069),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U561 (
        .D(__dff_d_ff2070),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U562 (
        .D(__dff_d_ff2071),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U563 (
        .D(__dff_d_ff2072),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U564 (
        .D(__dff_d_ff2073),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U565 (
        .D(__dff_d_ff2074),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U566 (
        .D(__dff_d_ff2075),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U567 (
        .D(__dff_d_ff2076),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U568 (
        .D(__dff_d_ff2077),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U569 (
        .D(__dff_d_ff2078),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_load_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U570 (
        .D(__dff_d_ff2079),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_status_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U571 (
        .D(__dff_d_ff2080),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(reg_status_1)
    );

    sky130_fd_sc_hd__conb_1 UTIE_0 (.LO(buf_n290_0));
    sky130_fd_sc_hd__conb_1 UTIE_1 (.LO(buf_n324_0));
    sky130_fd_sc_hd__conb_1 UTIE_2 (.LO(buf_n324_1));
    sky130_fd_sc_hd__conb_1 UTIE_3 (.LO(buf_rst_n_0));
    sky130_fd_sc_hd__conb_1 UTIE_4 (.LO(inv_n2));
    sky130_fd_sc_hd__conb_1 UTIE_5 (.LO(reg_count_0));
    sky130_fd_sc_hd__conb_1 UTIE_6 (.LO(reg_count_10));
    sky130_fd_sc_hd__conb_1 UTIE_7 (.LO(reg_count_11));
    sky130_fd_sc_hd__conb_1 UTIE_8 (.LO(reg_count_12));
    sky130_fd_sc_hd__conb_1 UTIE_9 (.LO(reg_count_13));
    sky130_fd_sc_hd__conb_1 UTIE_10 (.LO(reg_count_14));
    sky130_fd_sc_hd__conb_1 UTIE_11 (.LO(reg_count_15));
    sky130_fd_sc_hd__conb_1 UTIE_12 (.LO(reg_count_16));
    sky130_fd_sc_hd__conb_1 UTIE_13 (.LO(reg_count_17));
    sky130_fd_sc_hd__conb_1 UTIE_14 (.LO(reg_count_18));
    sky130_fd_sc_hd__conb_1 UTIE_15 (.LO(reg_count_19));
    sky130_fd_sc_hd__conb_1 UTIE_16 (.LO(reg_count_2));
    sky130_fd_sc_hd__conb_1 UTIE_17 (.LO(reg_count_20));
    sky130_fd_sc_hd__conb_1 UTIE_18 (.LO(reg_count_21));
    sky130_fd_sc_hd__conb_1 UTIE_19 (.LO(reg_count_22));
    sky130_fd_sc_hd__conb_1 UTIE_20 (.LO(reg_count_23));
    sky130_fd_sc_hd__conb_1 UTIE_21 (.LO(reg_count_24));
    sky130_fd_sc_hd__conb_1 UTIE_22 (.LO(reg_count_25));
    sky130_fd_sc_hd__conb_1 UTIE_23 (.LO(reg_count_26));
    sky130_fd_sc_hd__conb_1 UTIE_24 (.LO(reg_count_27));
    sky130_fd_sc_hd__conb_1 UTIE_25 (.LO(reg_count_28));
    sky130_fd_sc_hd__conb_1 UTIE_26 (.LO(reg_count_29));
    sky130_fd_sc_hd__conb_1 UTIE_27 (.LO(reg_count_3));
    sky130_fd_sc_hd__conb_1 UTIE_28 (.LO(reg_count_30));
    sky130_fd_sc_hd__conb_1 UTIE_29 (.LO(reg_count_31));
    sky130_fd_sc_hd__conb_1 UTIE_30 (.LO(reg_count_4));
    sky130_fd_sc_hd__conb_1 UTIE_31 (.LO(reg_count_5));
    sky130_fd_sc_hd__conb_1 UTIE_32 (.LO(reg_count_6));
    sky130_fd_sc_hd__conb_1 UTIE_33 (.LO(reg_count_7));
    sky130_fd_sc_hd__conb_1 UTIE_34 (.LO(reg_count_8));
    sky130_fd_sc_hd__conb_1 UTIE_35 (.LO(reg_count_9));
endmodule
