// Generated by My Own Flow — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module dcache (
    input clk,
    input rst_n,
    input cpu_addr_0,
    input cpu_addr_1,
    input cpu_addr_2,
    input cpu_addr_3,
    input cpu_addr_4,
    input cpu_addr_5,
    input cpu_addr_6,
    input cpu_addr_7,
    input cpu_addr_8,
    input cpu_addr_9,
    input cpu_addr_10,
    input cpu_addr_11,
    input cpu_addr_12,
    input cpu_addr_13,
    input cpu_addr_14,
    input cpu_addr_15,
    input cpu_addr_16,
    input cpu_addr_17,
    input cpu_addr_18,
    input cpu_addr_19,
    input cpu_addr_20,
    input cpu_addr_21,
    input cpu_addr_22,
    input cpu_addr_23,
    input cpu_addr_24,
    input cpu_addr_25,
    input cpu_addr_26,
    input cpu_addr_27,
    input cpu_addr_28,
    input cpu_addr_29,
    input cpu_addr_30,
    input cpu_addr_31,
    input cpu_wdata_0,
    input cpu_wdata_1,
    input cpu_wdata_2,
    input cpu_wdata_3,
    input cpu_wdata_4,
    input cpu_wdata_5,
    input cpu_wdata_6,
    input cpu_wdata_7,
    input cpu_wdata_8,
    input cpu_wdata_9,
    input cpu_wdata_10,
    input cpu_wdata_11,
    input cpu_wdata_12,
    input cpu_wdata_13,
    input cpu_wdata_14,
    input cpu_wdata_15,
    input cpu_wdata_16,
    input cpu_wdata_17,
    input cpu_wdata_18,
    input cpu_wdata_19,
    input cpu_wdata_20,
    input cpu_wdata_21,
    input cpu_wdata_22,
    input cpu_wdata_23,
    input cpu_wdata_24,
    input cpu_wdata_25,
    input cpu_wdata_26,
    input cpu_wdata_27,
    input cpu_wdata_28,
    input cpu_wdata_29,
    input cpu_wdata_30,
    input cpu_wdata_31,
    input cpu_wstrb_0,
    input cpu_wstrb_1,
    input cpu_wstrb_2,
    input cpu_wstrb_3,
    input cpu_req,
    input mem_rdata_0,
    input mem_rdata_1,
    input mem_rdata_2,
    input mem_rdata_3,
    input mem_rdata_4,
    input mem_rdata_5,
    input mem_rdata_6,
    input mem_rdata_7,
    input mem_rdata_8,
    input mem_rdata_9,
    input mem_rdata_10,
    input mem_rdata_11,
    input mem_rdata_12,
    input mem_rdata_13,
    input mem_rdata_14,
    input mem_rdata_15,
    input mem_rdata_16,
    input mem_rdata_17,
    input mem_rdata_18,
    input mem_rdata_19,
    input mem_rdata_20,
    input mem_rdata_21,
    input mem_rdata_22,
    input mem_rdata_23,
    input mem_rdata_24,
    input mem_rdata_25,
    input mem_rdata_26,
    input mem_rdata_27,
    input mem_rdata_28,
    input mem_rdata_29,
    input mem_rdata_30,
    input mem_rdata_31,
    input mem_ready,
    input flush,
    output cache_hit,
    output cache_miss,
    output cpu_rdata_0,
    output cpu_rdata_1,
    output cpu_rdata_2,
    output cpu_rdata_3,
    output cpu_rdata_4,
    output cpu_rdata_5,
    output cpu_rdata_6,
    output cpu_rdata_7,
    output cpu_rdata_8,
    output cpu_rdata_9,
    output cpu_rdata_10,
    output cpu_rdata_11,
    output cpu_rdata_12,
    output cpu_rdata_13,
    output cpu_rdata_14,
    output cpu_rdata_15,
    output cpu_rdata_16,
    output cpu_rdata_17,
    output cpu_rdata_18,
    output cpu_rdata_19,
    output cpu_rdata_20,
    output cpu_rdata_21,
    output cpu_rdata_22,
    output cpu_rdata_23,
    output cpu_rdata_24,
    output cpu_rdata_25,
    output cpu_rdata_26,
    output cpu_rdata_27,
    output cpu_rdata_28,
    output cpu_rdata_29,
    output cpu_rdata_30,
    output cpu_rdata_31,
    output cpu_ready,
    output mem_addr_0,
    output mem_addr_1,
    output mem_addr_2,
    output mem_addr_3,
    output mem_addr_4,
    output mem_addr_5,
    output mem_addr_6,
    output mem_addr_7,
    output mem_addr_8,
    output mem_addr_9,
    output mem_addr_10,
    output mem_addr_11,
    output mem_addr_12,
    output mem_addr_13,
    output mem_addr_14,
    output mem_addr_15,
    output mem_addr_16,
    output mem_addr_17,
    output mem_addr_18,
    output mem_addr_19,
    output mem_addr_20,
    output mem_addr_21,
    output mem_addr_22,
    output mem_addr_23,
    output mem_addr_24,
    output mem_addr_25,
    output mem_addr_26,
    output mem_addr_27,
    output mem_addr_28,
    output mem_addr_29,
    output mem_addr_30,
    output mem_addr_31,
    output mem_req,
    output mem_wdata_0,
    output mem_wdata_1,
    output mem_wdata_2,
    output mem_wdata_3,
    output mem_wdata_4,
    output mem_wdata_5,
    output mem_wdata_6,
    output mem_wdata_7,
    output mem_wdata_8,
    output mem_wdata_9,
    output mem_wdata_10,
    output mem_wdata_11,
    output mem_wdata_12,
    output mem_wdata_13,
    output mem_wdata_14,
    output mem_wdata_15,
    output mem_wdata_16,
    output mem_wdata_17,
    output mem_wdata_18,
    output mem_wdata_19,
    output mem_wdata_20,
    output mem_wdata_21,
    output mem_wdata_22,
    output mem_wdata_23,
    output mem_wdata_24,
    output mem_wdata_25,
    output mem_wdata_26,
    output mem_wdata_27,
    output mem_wdata_28,
    output mem_wdata_29,
    output mem_wdata_30,
    output mem_wdata_31,
    output mem_wstrb_0,
    output mem_wstrb_1,
    output mem_wstrb_2,
    output mem_wstrb_3,
    output busy
);

    wire state_0;
    wire state_1;
    wire state_2;
    wire state_3;
    wire __dff_d_ff9171;
    wire __dff_d_ff9172;
    wire __dff_d_ff9173;
    wire __dff_d_ff9174;
    wire __dff_d_ff9175;
    wire __dff_d_ff9176;
    wire __dff_d_ff9177;
    wire __dff_d_ff9178;
    wire __dff_d_ff9179;
    wire __dff_d_ff9180;
    wire __dff_d_ff9181;
    wire __dff_d_ff9182;
    wire __dff_d_ff9183;
    wire __dff_d_ff9184;
    wire __dff_d_ff9185;
    wire __dff_d_ff9186;
    wire __dff_d_ff9187;
    wire __dff_d_ff9188;
    wire __dff_d_ff9189;
    wire __dff_d_ff9190;
    wire __dff_d_ff9191;
    wire __dff_d_ff9192;
    wire __dff_d_ff9193;
    wire __dff_d_ff9194;
    wire __dff_d_ff9195;
    wire __dff_d_ff9196;
    wire __dff_d_ff9197;
    wire __dff_d_ff9198;
    wire __dff_d_ff9199;
    wire __dff_d_ff9200;
    wire __dff_d_ff9201;
    wire __dff_d_ff9202;
    wire __dff_d_ff9203;
    wire __dff_d_ff9204;
    wire __dff_d_ff9205;
    wire __dff_d_ff9206;
    wire __dff_d_ff9207;
    wire __dff_d_ff9208;
    wire __dff_d_ff9209;
    wire __dff_d_ff9210;
    wire __dff_d_ff9211;
    wire __dff_d_ff9212;
    wire __dff_d_ff9213;
    wire __dff_d_ff9214;
    wire __dff_d_ff9215;
    wire __dff_d_ff9216;
    wire __dff_d_ff9217;
    wire __dff_d_ff9218;
    wire __dff_d_ff9219;
    wire __dff_d_ff9220;
    wire __dff_d_ff9221;
    wire __dff_d_ff9222;
    wire __dff_d_ff9223;
    wire __dff_d_ff9224;
    wire __dff_d_ff9225;
    wire __dff_d_ff9226;
    wire __dff_d_ff9227;
    wire __dff_d_ff9228;
    wire __dff_d_ff9229;
    wire __dff_d_ff9230;
    wire __dff_d_ff9231;
    wire __dff_d_ff9232;
    wire __dff_d_ff9233;
    wire __dff_d_ff9234;
    wire __dff_d_ff9235;
    wire __dff_d_ff9236;
    wire fill_word_cnt;
    wire flush_line_cnt;
    wire flush_word_cnt;
    wire latched_addr_0;
    wire latched_addr_1;
    wire latched_addr_2;
    wire latched_addr_3;
    wire latched_addr_4;
    wire latched_addr_5;
    wire latched_addr_6;
    wire latched_addr_7;
    wire latched_addr_8;
    wire latched_addr_9;
    wire latched_addr_10;
    wire latched_addr_11;
    wire latched_addr_12;
    wire latched_addr_13;
    wire latched_addr_14;
    wire latched_addr_15;
    wire latched_addr_16;
    wire latched_addr_17;
    wire latched_addr_18;
    wire latched_addr_19;
    wire latched_addr_20;
    wire latched_addr_21;
    wire latched_addr_22;
    wire latched_addr_23;
    wire latched_addr_24;
    wire latched_addr_25;
    wire latched_addr_26;
    wire latched_addr_27;
    wire latched_addr_28;
    wire latched_addr_29;
    wire latched_addr_30;
    wire latched_addr_31;
    wire latched_index;
    wire latched_is_write;
    wire latched_tag;
    wire latched_wdata_0;
    wire latched_wdata_1;
    wire latched_wdata_2;
    wire latched_wdata_3;
    wire latched_wdata_4;
    wire latched_wdata_5;
    wire latched_wdata_6;
    wire latched_wdata_7;
    wire latched_wdata_8;
    wire latched_wdata_9;
    wire latched_wdata_10;
    wire latched_wdata_11;
    wire latched_wdata_12;
    wire latched_wdata_13;
    wire latched_wdata_14;
    wire latched_wdata_15;
    wire latched_wdata_16;
    wire latched_wdata_17;
    wire latched_wdata_18;
    wire latched_wdata_19;
    wire latched_wdata_20;
    wire latched_wdata_21;
    wire latched_wdata_22;
    wire latched_wdata_23;
    wire latched_wdata_24;
    wire latched_wdata_25;
    wire latched_wdata_26;
    wire latched_wdata_27;
    wire latched_wdata_28;
    wire latched_wdata_29;
    wire latched_wdata_30;
    wire latched_wdata_31;
    wire latched_word_off;
    wire latched_wstrb_0;
    wire latched_wstrb_1;
    wire latched_wstrb_2;
    wire latched_wstrb_3;
    wire tag_mem_0;
    wire tag_mem_1;
    wire valid_0;
    wire valid_1;
    wire wb_word_cnt;
    wire n362;
    wire n365;
    wire inv_n71;
    wire inv_n105;
    wire inv_n106;
    wire __dff_d_ff150;
    wire n368;
    wire inv_n107;
    wire n370;
    wire __dff_d_ff151;
    wire __dff_d_ff9138;
    wire __dff_d_ff9139;
    wire __dff_d_ff9140;
    wire __dff_d_ff9141;
    wire __dff_d_ff9142;
    wire __dff_d_ff9143;
    wire __dff_d_ff9144;
    wire __dff_d_ff9145;
    wire __dff_d_ff9146;
    wire __dff_d_ff9147;
    wire __dff_d_ff9148;
    wire __dff_d_ff9149;
    wire __dff_d_ff9150;
    wire __dff_d_ff9151;
    wire __dff_d_ff9152;
    wire __dff_d_ff9153;
    wire __dff_d_ff9154;
    wire __dff_d_ff9155;
    wire __dff_d_ff9156;
    wire __dff_d_ff9157;
    wire __dff_d_ff9158;
    wire __dff_d_ff9159;
    wire __dff_d_ff9160;
    wire __dff_d_ff9161;
    wire __dff_d_ff9162;
    wire __dff_d_ff9163;
    wire __dff_d_ff9164;
    wire __dff_d_ff9165;
    wire __dff_d_ff9166;
    wire __dff_d_ff9167;
    wire __dff_d_ff9168;
    wire __dff_d_ff9169;
    wire __dff_d_ff9237;
    wire __dff_d_ff9238;
    wire __dff_d_ff9239;
    wire n411;
    wire n414;
    wire __dff_d_ff9240;
    wire inv_n2;
    wire n418;
    wire __dff_d_ff9241;
    wire n422;
    wire __dff_d_ff9242;
    wire n426;
    wire __dff_d_ff9243;
    wire n430;
    wire __dff_d_ff9244;
    wire n434;
    wire __dff_d_ff9245;
    wire n438;
    wire __dff_d_ff9246;
    wire n442;
    wire __dff_d_ff9247;
    wire n446;
    wire __dff_d_ff9248;
    wire n450;
    wire __dff_d_ff9249;
    wire n454;
    wire __dff_d_ff9250;
    wire n458;
    wire __dff_d_ff9251;
    wire n462;
    wire __dff_d_ff9252;
    wire n466;
    wire __dff_d_ff9253;
    wire n470;
    wire __dff_d_ff9254;
    wire n474;
    wire __dff_d_ff9255;
    wire n478;
    wire __dff_d_ff9256;
    wire n482;
    wire __dff_d_ff9257;
    wire n486;
    wire __dff_d_ff9258;
    wire n490;
    wire __dff_d_ff9259;
    wire n494;
    wire __dff_d_ff9260;
    wire n498;
    wire __dff_d_ff9261;
    wire n502;
    wire __dff_d_ff9262;
    wire n506;
    wire __dff_d_ff9263;
    wire n510;
    wire __dff_d_ff9264;
    wire n514;
    wire __dff_d_ff9265;
    wire n518;
    wire __dff_d_ff9266;
    wire n522;
    wire __dff_d_ff9267;
    wire n526;
    wire __dff_d_ff9268;
    wire n530;
    wire __dff_d_ff9269;
    wire n534;
    wire __dff_d_ff9270;
    wire n538;
    wire __dff_d_ff9271;
    wire __dff_d_ff9272;
    wire n547;
    wire n548;
    wire n549;
    wire n550;
    wire n551;
    wire n552;
    wire n553;
    wire __dff_d_ff9273;
    wire n556;
    wire __dff_d_ff9274;
    wire n560;
    wire __dff_d_ff9275;
    wire n564;
    wire __dff_d_ff9276;
    wire n568;
    wire __dff_d_ff9277;
    wire n572;
    wire __dff_d_ff9278;
    wire n576;
    wire __dff_d_ff9279;
    wire n580;
    wire __dff_d_ff9280;
    wire n584;
    wire __dff_d_ff9281;
    wire n588;
    wire __dff_d_ff9282;
    wire n592;
    wire __dff_d_ff9283;
    wire n596;
    wire __dff_d_ff9284;
    wire n600;
    wire __dff_d_ff9285;
    wire n604;
    wire __dff_d_ff9286;
    wire n608;
    wire __dff_d_ff9287;
    wire n612;
    wire __dff_d_ff9288;
    wire n616;
    wire __dff_d_ff9289;
    wire n620;
    wire __dff_d_ff9290;
    wire n624;
    wire __dff_d_ff9291;
    wire n628;
    wire __dff_d_ff9292;
    wire n632;
    wire __dff_d_ff9293;
    wire n636;
    wire __dff_d_ff9294;
    wire n640;
    wire __dff_d_ff9295;
    wire n644;
    wire __dff_d_ff9296;
    wire n648;
    wire __dff_d_ff9297;
    wire n652;
    wire __dff_d_ff9298;
    wire n656;
    wire __dff_d_ff9299;
    wire n660;
    wire __dff_d_ff9300;
    wire n664;
    wire __dff_d_ff9301;
    wire n668;
    wire __dff_d_ff9302;
    wire n672;
    wire __dff_d_ff9303;
    wire n676;
    wire __dff_d_ff9304;
    wire n680;
    wire __dff_d_ff9305;
    wire n684;
    wire __dff_d_ff9306;
    wire __dff_d_ff9307;
    wire n690;
    wire __dff_d_ff9308;
    wire n694;
    wire __dff_d_ff9309;
    wire n698;
    wire __dff_d_ff9310;
    wire n702;
    wire __dff_d_ff9311;
    wire __dff_d_ff9312;
    wire __dff_d_ff9313;
    wire n710;
    wire __dff_d_ff9314;
    wire n714;
    wire __dff_d_ff9315;
    wire n718;
    wire __dff_d_ff9316;
    wire n722;
    wire __dff_d_ff9317;
    wire n726;
    wire __dff_d_ff9318;
    wire n730;
    wire __dff_d_ff9319;
    wire n734;
    wire __dff_d_ff9320;
    wire n738;
    wire __dff_d_ff9321;
    wire n742;
    wire __dff_d_ff9322;
    wire n746;
    wire __dff_d_ff9323;
    wire n750;
    wire __dff_d_ff9324;
    wire n754;
    wire __dff_d_ff9325;
    wire n758;
    wire __dff_d_ff9326;
    wire n762;
    wire __dff_d_ff9327;
    wire n766;
    wire __dff_d_ff9328;
    wire n770;
    wire __dff_d_ff9329;
    wire n774;
    wire __dff_d_ff9330;
    wire n778;
    wire __dff_d_ff9331;
    wire n782;
    wire __dff_d_ff9332;
    wire n786;
    wire __dff_d_ff9333;
    wire n790;
    wire __dff_d_ff9334;
    wire n794;
    wire __dff_d_ff9335;
    wire n798;
    wire __dff_d_ff9336;
    wire n802;
    wire __dff_d_ff9337;
    wire n806;
    wire __dff_d_ff9338;
    wire n810;
    wire __dff_d_ff9339;
    wire n814;
    wire __dff_d_ff9340;
    wire n818;
    wire __dff_d_ff9341;
    wire n822;
    wire __dff_d_ff9342;
    wire n826;
    wire __dff_d_ff9343;
    wire __dff_d_ff9345;
    wire __dff_d_ff9346;
    wire __dff_d_ff9347;
    wire __dff_d_ff9348;
    wire __dff_d_ff9349;
    wire __dff_d_ff9350;
    wire __dff_d_ff9351;
    wire __dff_d_ff9352;
    wire __dff_d_ff9353;
    wire __dff_d_ff9354;
    wire __dff_d_ff9355;
    wire __dff_d_ff9356;
    wire __dff_d_ff9357;
    wire __dff_d_ff9358;
    wire __dff_d_ff9359;
    wire __dff_d_ff9360;
    wire __dff_d_ff9361;
    wire __dff_d_ff9362;
    wire __dff_d_ff9363;
    wire __dff_d_ff9364;
    wire __dff_d_ff9365;
    wire __dff_d_ff9366;
    wire __dff_d_ff9367;
    wire __dff_d_ff9368;
    wire __dff_d_ff9369;
    wire __dff_d_ff9370;
    wire __dff_d_ff9371;
    wire __dff_d_ff9372;
    wire __dff_d_ff9373;
    wire __dff_d_ff9374;
    wire __dff_d_ff9375;
    wire __dff_d_ff9376;
    wire n861;
    wire inv_n211;
    wire n862;
    wire n865;
    wire inv_n246;
    wire n866;
    wire __dff_d_ff9381;
    wire n871;
    wire n872;
    wire __dff_d_ff9382;
    wire n877;
    wire __dff_d_ff9383;
    wire __dff_d_ff9384;
    wire __dff_d_ff9385;
    wire __dff_d_ff152;
    wire __dff_d_ff153;
    wire __dff_d_ff9136;
    wire __dff_d_ff9137;
    wire __dff_d_ff9170;
    wire __dff_d_ff9344;
    wire __dff_d_ff9377;
    wire __dff_d_ff9378;
    wire __dff_d_ff9379;
    wire __dff_d_ff9380;
    wire clone_9;
    wire clone_11;
    wire clone_53;
    wire buf_rst_n_0;
    wire buf_rst_n_1;
    wire buf_rst_n_2;
    wire buf_n411_0;
    wire buf_n411_1;
    wire buf_clone_53_0;
    wire buf_clone_53_1;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(busy));
    sky130_fd_sc_hd__nor4_1 U0 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .D(state_3),
        .Y(n362)
    );

    sky130_fd_sc_hd__inv_1 U1 (
        .A(cpu_req),
        .Y(inv_n71)
    );

    sky130_fd_sc_hd__inv_1 U2 (
        .A(flush),
        .Y(inv_n105)
    );

    sky130_fd_sc_hd__inv_1 U3 (
        .A(state_0),
        .Y(inv_n106)
    );

    sky130_fd_sc_hd__a31oi_1 U4 (
        .A1(inv_n71),
        .A2(inv_n105),
        .A3(inv_n106),
        .B1(n362),
        .Y(n365)
    );

    sky130_fd_sc_hd__inv_1 U5 (
        .A(state_1),
        .Y(inv_n107)
    );

    sky130_fd_sc_hd__a21oi_1 U6 (
        .A1(cpu_req),
        .A2(mem_ready),
        .B1(inv_n107),
        .Y(n368)
    );

    sky130_fd_sc_hd__o21a_1 U7 (
        .A1(flush),
        .A2(n368),
        .B1(clone_9),
        .X(n370)
    );

    sky130_fd_sc_hd__nand3b_1 U8 (
        .A_N(flush),
        .B(cpu_req),
        .C(clone_9),
        .Y(n411)
    );

    sky130_fd_sc_hd__mux2_1 U9 (
        .A0(cpu_addr_0),
        .A1(latched_addr_0),
        .S(buf_n411_0),
        .X(n414)
    );

    sky130_fd_sc_hd__nor2b_1 U10 (
        .A(n414),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff9240)
    );

    sky130_fd_sc_hd__o21a_1 U11 (
        .A1(latched_addr_1),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n418)
    );

    sky130_fd_sc_hd__o21a_1 U12 (
        .A1(cpu_addr_1),
        .A2(buf_clone_53_0),
        .B1(n418),
        .X(__dff_d_ff9241)
    );

    sky130_fd_sc_hd__o21a_1 U13 (
        .A1(latched_addr_2),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n422)
    );

    sky130_fd_sc_hd__o21a_1 U14 (
        .A1(cpu_addr_2),
        .A2(buf_clone_53_0),
        .B1(n422),
        .X(__dff_d_ff9242)
    );

    sky130_fd_sc_hd__o21a_1 U15 (
        .A1(latched_addr_3),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n426)
    );

    sky130_fd_sc_hd__o21a_1 U16 (
        .A1(cpu_addr_3),
        .A2(buf_clone_53_0),
        .B1(n426),
        .X(__dff_d_ff9243)
    );

    sky130_fd_sc_hd__o21a_1 U17 (
        .A1(latched_addr_4),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n430)
    );

    sky130_fd_sc_hd__o21a_1 U18 (
        .A1(cpu_addr_4),
        .A2(buf_clone_53_0),
        .B1(n430),
        .X(__dff_d_ff9244)
    );

    sky130_fd_sc_hd__o21a_1 U19 (
        .A1(latched_addr_5),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n434)
    );

    sky130_fd_sc_hd__o21a_1 U20 (
        .A1(cpu_addr_5),
        .A2(buf_clone_53_0),
        .B1(n434),
        .X(__dff_d_ff9245)
    );

    sky130_fd_sc_hd__o21a_1 U21 (
        .A1(latched_addr_6),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n438)
    );

    sky130_fd_sc_hd__o21a_1 U22 (
        .A1(cpu_addr_6),
        .A2(buf_clone_53_0),
        .B1(n438),
        .X(__dff_d_ff9246)
    );

    sky130_fd_sc_hd__o21a_1 U23 (
        .A1(latched_addr_7),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n442)
    );

    sky130_fd_sc_hd__o21a_1 U24 (
        .A1(cpu_addr_7),
        .A2(buf_clone_53_0),
        .B1(n442),
        .X(__dff_d_ff9247)
    );

    sky130_fd_sc_hd__o21a_1 U25 (
        .A1(latched_addr_8),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n446)
    );

    sky130_fd_sc_hd__o21a_1 U26 (
        .A1(cpu_addr_8),
        .A2(buf_clone_53_0),
        .B1(n446),
        .X(__dff_d_ff9248)
    );

    sky130_fd_sc_hd__o21a_1 U27 (
        .A1(latched_addr_9),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n450)
    );

    sky130_fd_sc_hd__o21a_1 U28 (
        .A1(cpu_addr_9),
        .A2(buf_clone_53_0),
        .B1(n450),
        .X(__dff_d_ff9249)
    );

    sky130_fd_sc_hd__o21a_1 U29 (
        .A1(latched_addr_10),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n454)
    );

    sky130_fd_sc_hd__o21a_1 U30 (
        .A1(cpu_addr_10),
        .A2(buf_clone_53_0),
        .B1(n454),
        .X(__dff_d_ff9250)
    );

    sky130_fd_sc_hd__o21a_1 U31 (
        .A1(latched_addr_11),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n458)
    );

    sky130_fd_sc_hd__o21a_1 U32 (
        .A1(cpu_addr_11),
        .A2(buf_clone_53_0),
        .B1(n458),
        .X(__dff_d_ff9251)
    );

    sky130_fd_sc_hd__o21a_1 U33 (
        .A1(latched_addr_12),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n462)
    );

    sky130_fd_sc_hd__o21a_1 U34 (
        .A1(cpu_addr_12),
        .A2(buf_clone_53_0),
        .B1(n462),
        .X(__dff_d_ff9252)
    );

    sky130_fd_sc_hd__o21a_1 U35 (
        .A1(latched_addr_13),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n466)
    );

    sky130_fd_sc_hd__o21a_1 U36 (
        .A1(cpu_addr_13),
        .A2(buf_clone_53_0),
        .B1(n466),
        .X(__dff_d_ff9253)
    );

    sky130_fd_sc_hd__o21a_1 U37 (
        .A1(latched_addr_14),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n470)
    );

    sky130_fd_sc_hd__o21a_1 U38 (
        .A1(cpu_addr_14),
        .A2(buf_clone_53_0),
        .B1(n470),
        .X(__dff_d_ff9254)
    );

    sky130_fd_sc_hd__o21a_1 U39 (
        .A1(latched_addr_15),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n474)
    );

    sky130_fd_sc_hd__o21a_1 U40 (
        .A1(cpu_addr_15),
        .A2(buf_clone_53_0),
        .B1(n474),
        .X(__dff_d_ff9255)
    );

    sky130_fd_sc_hd__o21a_1 U41 (
        .A1(latched_addr_16),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n478)
    );

    sky130_fd_sc_hd__o21a_1 U42 (
        .A1(cpu_addr_16),
        .A2(buf_clone_53_0),
        .B1(n478),
        .X(__dff_d_ff9256)
    );

    sky130_fd_sc_hd__o21a_1 U43 (
        .A1(latched_addr_17),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n482)
    );

    sky130_fd_sc_hd__o21a_1 U44 (
        .A1(cpu_addr_17),
        .A2(buf_clone_53_0),
        .B1(n482),
        .X(__dff_d_ff9257)
    );

    sky130_fd_sc_hd__o21a_1 U45 (
        .A1(latched_addr_18),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n486)
    );

    sky130_fd_sc_hd__o21a_1 U46 (
        .A1(cpu_addr_18),
        .A2(buf_clone_53_0),
        .B1(n486),
        .X(__dff_d_ff9258)
    );

    sky130_fd_sc_hd__o21a_1 U47 (
        .A1(latched_addr_19),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n490)
    );

    sky130_fd_sc_hd__o21a_1 U48 (
        .A1(cpu_addr_19),
        .A2(buf_clone_53_0),
        .B1(n490),
        .X(__dff_d_ff9259)
    );

    sky130_fd_sc_hd__o21a_1 U49 (
        .A1(latched_addr_20),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n494)
    );

    sky130_fd_sc_hd__o21a_1 U50 (
        .A1(cpu_addr_20),
        .A2(buf_clone_53_0),
        .B1(n494),
        .X(__dff_d_ff9260)
    );

    sky130_fd_sc_hd__o21a_1 U51 (
        .A1(latched_addr_21),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n498)
    );

    sky130_fd_sc_hd__o21a_1 U52 (
        .A1(cpu_addr_21),
        .A2(buf_clone_53_0),
        .B1(n498),
        .X(__dff_d_ff9261)
    );

    sky130_fd_sc_hd__o21a_1 U53 (
        .A1(latched_addr_22),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n502)
    );

    sky130_fd_sc_hd__o21a_1 U54 (
        .A1(cpu_addr_22),
        .A2(buf_clone_53_0),
        .B1(n502),
        .X(__dff_d_ff9262)
    );

    sky130_fd_sc_hd__o21a_1 U55 (
        .A1(latched_addr_23),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n506)
    );

    sky130_fd_sc_hd__o21a_1 U56 (
        .A1(cpu_addr_23),
        .A2(buf_clone_53_0),
        .B1(n506),
        .X(__dff_d_ff9263)
    );

    sky130_fd_sc_hd__o21a_1 U57 (
        .A1(latched_addr_24),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n510)
    );

    sky130_fd_sc_hd__o21a_1 U58 (
        .A1(cpu_addr_24),
        .A2(buf_clone_53_0),
        .B1(n510),
        .X(__dff_d_ff9264)
    );

    sky130_fd_sc_hd__o21a_1 U59 (
        .A1(latched_addr_25),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n514)
    );

    sky130_fd_sc_hd__o21a_1 U60 (
        .A1(cpu_addr_25),
        .A2(buf_clone_53_0),
        .B1(n514),
        .X(__dff_d_ff9265)
    );

    sky130_fd_sc_hd__o21a_1 U61 (
        .A1(latched_addr_26),
        .A2(buf_n411_0),
        .B1(buf_rst_n_0),
        .X(n518)
    );

    sky130_fd_sc_hd__o21a_1 U62 (
        .A1(cpu_addr_26),
        .A2(buf_clone_53_0),
        .B1(n518),
        .X(__dff_d_ff9266)
    );

    sky130_fd_sc_hd__o21a_1 U63 (
        .A1(latched_addr_27),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n522)
    );

    sky130_fd_sc_hd__o21a_1 U64 (
        .A1(cpu_addr_27),
        .A2(buf_clone_53_0),
        .B1(n522),
        .X(__dff_d_ff9267)
    );

    sky130_fd_sc_hd__o21a_1 U65 (
        .A1(latched_addr_28),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n526)
    );

    sky130_fd_sc_hd__o21a_1 U66 (
        .A1(cpu_addr_28),
        .A2(buf_clone_53_0),
        .B1(n526),
        .X(__dff_d_ff9268)
    );

    sky130_fd_sc_hd__o21a_1 U67 (
        .A1(latched_addr_29),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n530)
    );

    sky130_fd_sc_hd__o21a_1 U68 (
        .A1(cpu_addr_29),
        .A2(buf_clone_53_0),
        .B1(n530),
        .X(__dff_d_ff9269)
    );

    sky130_fd_sc_hd__o21a_1 U69 (
        .A1(latched_addr_30),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n534)
    );

    sky130_fd_sc_hd__o21a_1 U70 (
        .A1(cpu_addr_30),
        .A2(buf_clone_53_0),
        .B1(n534),
        .X(__dff_d_ff9270)
    );

    sky130_fd_sc_hd__o21a_1 U71 (
        .A1(latched_addr_31),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n538)
    );

    sky130_fd_sc_hd__o21a_1 U72 (
        .A1(cpu_addr_31),
        .A2(buf_clone_53_0),
        .B1(n538),
        .X(__dff_d_ff9271)
    );

    sky130_fd_sc_hd__nand3_1 U73 (
        .A(buf_rst_n_1),
        .B(latched_index),
        .C(buf_clone_53_0),
        .Y(__dff_d_ff9272)
    );

    sky130_fd_sc_hd__nor4_1 U74 (
        .A(cpu_wstrb_0),
        .B(cpu_wstrb_1),
        .C(cpu_wstrb_2),
        .D(cpu_wstrb_3),
        .Y(n547)
    );

    sky130_fd_sc_hd__nor2b_1 U75 (
        .A(n547),
        .B_N(cpu_req),
        .Y(n548)
    );

    sky130_fd_sc_hd__a21oi_1 U76 (
        .A1(inv_n71),
        .A2(latched_is_write),
        .B1(n548),
        .Y(n549)
    );

    sky130_fd_sc_hd__nor2_1 U77 (
        .A(flush),
        .B(n549),
        .Y(n550)
    );

    sky130_fd_sc_hd__a21oi_1 U78 (
        .A1(flush),
        .A2(latched_is_write),
        .B1(n550),
        .Y(n551)
    );

    sky130_fd_sc_hd__nor2_1 U79 (
        .A(n362),
        .B(n551),
        .Y(n552)
    );

    sky130_fd_sc_hd__a21oi_1 U80 (
        .A1(latched_is_write),
        .A2(n362),
        .B1(n552),
        .Y(n553)
    );

    sky130_fd_sc_hd__nor2b_1 U81 (
        .A(n553),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff9273)
    );

    sky130_fd_sc_hd__mux2_1 U82 (
        .A0(cpu_addr_0),
        .A1(latched_tag),
        .S(buf_n411_0),
        .X(n556)
    );

    sky130_fd_sc_hd__nor2b_1 U83 (
        .A(n556),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff9274)
    );

    sky130_fd_sc_hd__o21a_1 U84 (
        .A1(latched_wdata_0),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n560)
    );

    sky130_fd_sc_hd__o21a_1 U85 (
        .A1(cpu_wdata_0),
        .A2(buf_clone_53_0),
        .B1(n560),
        .X(__dff_d_ff9275)
    );

    sky130_fd_sc_hd__o21a_1 U86 (
        .A1(latched_wdata_1),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n564)
    );

    sky130_fd_sc_hd__o21a_1 U87 (
        .A1(cpu_wdata_1),
        .A2(buf_clone_53_0),
        .B1(n564),
        .X(__dff_d_ff9276)
    );

    sky130_fd_sc_hd__o21a_1 U88 (
        .A1(latched_wdata_2),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n568)
    );

    sky130_fd_sc_hd__o21a_1 U89 (
        .A1(cpu_wdata_2),
        .A2(buf_clone_53_0),
        .B1(n568),
        .X(__dff_d_ff9277)
    );

    sky130_fd_sc_hd__o21a_1 U90 (
        .A1(latched_wdata_3),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n572)
    );

    sky130_fd_sc_hd__o21a_1 U91 (
        .A1(cpu_wdata_3),
        .A2(buf_clone_53_0),
        .B1(n572),
        .X(__dff_d_ff9278)
    );

    sky130_fd_sc_hd__o21a_1 U92 (
        .A1(latched_wdata_4),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n576)
    );

    sky130_fd_sc_hd__o21a_1 U93 (
        .A1(cpu_wdata_4),
        .A2(buf_clone_53_0),
        .B1(n576),
        .X(__dff_d_ff9279)
    );

    sky130_fd_sc_hd__o21a_1 U94 (
        .A1(latched_wdata_5),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n580)
    );

    sky130_fd_sc_hd__o21a_1 U95 (
        .A1(cpu_wdata_5),
        .A2(buf_clone_53_0),
        .B1(n580),
        .X(__dff_d_ff9280)
    );

    sky130_fd_sc_hd__o21a_1 U96 (
        .A1(latched_wdata_6),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n584)
    );

    sky130_fd_sc_hd__o21a_1 U97 (
        .A1(cpu_wdata_6),
        .A2(buf_clone_53_0),
        .B1(n584),
        .X(__dff_d_ff9281)
    );

    sky130_fd_sc_hd__o21a_1 U98 (
        .A1(latched_wdata_7),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n588)
    );

    sky130_fd_sc_hd__o21a_1 U99 (
        .A1(cpu_wdata_7),
        .A2(buf_clone_53_0),
        .B1(n588),
        .X(__dff_d_ff9282)
    );

    sky130_fd_sc_hd__o21a_1 U100 (
        .A1(latched_wdata_8),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n592)
    );

    sky130_fd_sc_hd__o21a_1 U101 (
        .A1(cpu_wdata_8),
        .A2(buf_clone_53_0),
        .B1(n592),
        .X(__dff_d_ff9283)
    );

    sky130_fd_sc_hd__o21a_1 U102 (
        .A1(latched_wdata_9),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n596)
    );

    sky130_fd_sc_hd__o21a_1 U103 (
        .A1(cpu_wdata_9),
        .A2(buf_clone_53_0),
        .B1(n596),
        .X(__dff_d_ff9284)
    );

    sky130_fd_sc_hd__o21a_1 U104 (
        .A1(latched_wdata_10),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n600)
    );

    sky130_fd_sc_hd__o21a_1 U105 (
        .A1(cpu_wdata_10),
        .A2(buf_clone_53_0),
        .B1(n600),
        .X(__dff_d_ff9285)
    );

    sky130_fd_sc_hd__o21a_1 U106 (
        .A1(latched_wdata_11),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n604)
    );

    sky130_fd_sc_hd__o21a_1 U107 (
        .A1(cpu_wdata_11),
        .A2(buf_clone_53_0),
        .B1(n604),
        .X(__dff_d_ff9286)
    );

    sky130_fd_sc_hd__o21a_1 U108 (
        .A1(latched_wdata_12),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n608)
    );

    sky130_fd_sc_hd__o21a_1 U109 (
        .A1(cpu_wdata_12),
        .A2(buf_clone_53_0),
        .B1(n608),
        .X(__dff_d_ff9287)
    );

    sky130_fd_sc_hd__o21a_1 U110 (
        .A1(latched_wdata_13),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n612)
    );

    sky130_fd_sc_hd__o21a_1 U111 (
        .A1(cpu_wdata_13),
        .A2(buf_clone_53_0),
        .B1(n612),
        .X(__dff_d_ff9288)
    );

    sky130_fd_sc_hd__o21a_1 U112 (
        .A1(latched_wdata_14),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n616)
    );

    sky130_fd_sc_hd__o21a_1 U113 (
        .A1(cpu_wdata_14),
        .A2(buf_clone_53_0),
        .B1(n616),
        .X(__dff_d_ff9289)
    );

    sky130_fd_sc_hd__o21a_1 U114 (
        .A1(latched_wdata_15),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n620)
    );

    sky130_fd_sc_hd__o21a_1 U115 (
        .A1(cpu_wdata_15),
        .A2(buf_clone_53_0),
        .B1(n620),
        .X(__dff_d_ff9290)
    );

    sky130_fd_sc_hd__o21a_1 U116 (
        .A1(latched_wdata_16),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n624)
    );

    sky130_fd_sc_hd__o21a_1 U117 (
        .A1(cpu_wdata_16),
        .A2(buf_clone_53_0),
        .B1(n624),
        .X(__dff_d_ff9291)
    );

    sky130_fd_sc_hd__o21a_1 U118 (
        .A1(latched_wdata_17),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n628)
    );

    sky130_fd_sc_hd__o21a_1 U119 (
        .A1(cpu_wdata_17),
        .A2(buf_clone_53_0),
        .B1(n628),
        .X(__dff_d_ff9292)
    );

    sky130_fd_sc_hd__o21a_1 U120 (
        .A1(latched_wdata_18),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n632)
    );

    sky130_fd_sc_hd__o21a_1 U121 (
        .A1(cpu_wdata_18),
        .A2(buf_clone_53_0),
        .B1(n632),
        .X(__dff_d_ff9293)
    );

    sky130_fd_sc_hd__o21a_1 U122 (
        .A1(latched_wdata_19),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n636)
    );

    sky130_fd_sc_hd__o21a_1 U123 (
        .A1(cpu_wdata_19),
        .A2(buf_clone_53_0),
        .B1(n636),
        .X(__dff_d_ff9294)
    );

    sky130_fd_sc_hd__o21a_1 U124 (
        .A1(latched_wdata_20),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n640)
    );

    sky130_fd_sc_hd__o21a_1 U125 (
        .A1(cpu_wdata_20),
        .A2(buf_clone_53_0),
        .B1(n640),
        .X(__dff_d_ff9295)
    );

    sky130_fd_sc_hd__o21a_1 U126 (
        .A1(latched_wdata_21),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n644)
    );

    sky130_fd_sc_hd__o21a_1 U127 (
        .A1(cpu_wdata_21),
        .A2(buf_clone_53_0),
        .B1(n644),
        .X(__dff_d_ff9296)
    );

    sky130_fd_sc_hd__o21a_1 U128 (
        .A1(latched_wdata_22),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n648)
    );

    sky130_fd_sc_hd__o21a_1 U129 (
        .A1(cpu_wdata_22),
        .A2(buf_clone_53_0),
        .B1(n648),
        .X(__dff_d_ff9297)
    );

    sky130_fd_sc_hd__o21a_1 U130 (
        .A1(latched_wdata_23),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n652)
    );

    sky130_fd_sc_hd__o21a_1 U131 (
        .A1(cpu_wdata_23),
        .A2(buf_clone_53_0),
        .B1(n652),
        .X(__dff_d_ff9298)
    );

    sky130_fd_sc_hd__o21a_1 U132 (
        .A1(latched_wdata_24),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n656)
    );

    sky130_fd_sc_hd__o21a_1 U133 (
        .A1(cpu_wdata_24),
        .A2(buf_clone_53_0),
        .B1(n656),
        .X(__dff_d_ff9299)
    );

    sky130_fd_sc_hd__o21a_1 U134 (
        .A1(latched_wdata_25),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n660)
    );

    sky130_fd_sc_hd__o21a_1 U135 (
        .A1(cpu_wdata_25),
        .A2(buf_clone_53_0),
        .B1(n660),
        .X(__dff_d_ff9300)
    );

    sky130_fd_sc_hd__o21a_1 U136 (
        .A1(latched_wdata_26),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n664)
    );

    sky130_fd_sc_hd__o21a_1 U137 (
        .A1(cpu_wdata_26),
        .A2(buf_clone_53_0),
        .B1(n664),
        .X(__dff_d_ff9301)
    );

    sky130_fd_sc_hd__o21a_1 U138 (
        .A1(latched_wdata_27),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n668)
    );

    sky130_fd_sc_hd__o21a_1 U139 (
        .A1(cpu_wdata_27),
        .A2(buf_clone_53_0),
        .B1(n668),
        .X(__dff_d_ff9302)
    );

    sky130_fd_sc_hd__o21a_1 U140 (
        .A1(latched_wdata_28),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n672)
    );

    sky130_fd_sc_hd__o21a_1 U141 (
        .A1(cpu_wdata_28),
        .A2(buf_clone_53_0),
        .B1(n672),
        .X(__dff_d_ff9303)
    );

    sky130_fd_sc_hd__o21a_1 U142 (
        .A1(latched_wdata_29),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n676)
    );

    sky130_fd_sc_hd__o21a_1 U143 (
        .A1(cpu_wdata_29),
        .A2(buf_clone_53_0),
        .B1(n676),
        .X(__dff_d_ff9304)
    );

    sky130_fd_sc_hd__o21a_1 U144 (
        .A1(latched_wdata_30),
        .A2(buf_n411_0),
        .B1(buf_rst_n_1),
        .X(n680)
    );

    sky130_fd_sc_hd__o21a_1 U145 (
        .A1(cpu_wdata_30),
        .A2(buf_clone_53_0),
        .B1(n680),
        .X(__dff_d_ff9305)
    );

    sky130_fd_sc_hd__o21a_1 U146 (
        .A1(latched_wdata_31),
        .A2(buf_n411_1),
        .B1(buf_rst_n_1),
        .X(n684)
    );

    sky130_fd_sc_hd__o21a_1 U147 (
        .A1(cpu_wdata_31),
        .A2(buf_clone_53_0),
        .B1(n684),
        .X(__dff_d_ff9306)
    );

    sky130_fd_sc_hd__nand3_1 U148 (
        .A(buf_rst_n_1),
        .B(latched_word_off),
        .C(buf_clone_53_1),
        .Y(__dff_d_ff9307)
    );

    sky130_fd_sc_hd__o21a_1 U149 (
        .A1(latched_wstrb_0),
        .A2(buf_n411_1),
        .B1(buf_rst_n_1),
        .X(n690)
    );

    sky130_fd_sc_hd__o21a_1 U150 (
        .A1(cpu_wstrb_0),
        .A2(buf_clone_53_1),
        .B1(n690),
        .X(__dff_d_ff9308)
    );

    sky130_fd_sc_hd__o21a_1 U151 (
        .A1(latched_wstrb_1),
        .A2(buf_n411_1),
        .B1(buf_rst_n_1),
        .X(n694)
    );

    sky130_fd_sc_hd__o21a_1 U152 (
        .A1(cpu_wstrb_1),
        .A2(buf_clone_53_1),
        .B1(n694),
        .X(__dff_d_ff9309)
    );

    sky130_fd_sc_hd__o21a_1 U153 (
        .A1(latched_wstrb_2),
        .A2(buf_n411_1),
        .B1(buf_rst_n_1),
        .X(n698)
    );

    sky130_fd_sc_hd__o21a_1 U154 (
        .A1(cpu_wstrb_2),
        .A2(buf_clone_53_1),
        .B1(n698),
        .X(__dff_d_ff9310)
    );

    sky130_fd_sc_hd__o21a_1 U155 (
        .A1(latched_wstrb_3),
        .A2(buf_n411_1),
        .B1(buf_rst_n_1),
        .X(n702)
    );

    sky130_fd_sc_hd__o21a_1 U156 (
        .A1(cpu_wstrb_3),
        .A2(buf_clone_53_1),
        .B1(n702),
        .X(__dff_d_ff9311)
    );

    sky130_fd_sc_hd__nand3_1 U157 (
        .A(buf_rst_n_1),
        .B(mem_addr_0),
        .C(n362),
        .Y(__dff_d_ff9312)
    );

    sky130_fd_sc_hd__nand3_1 U158 (
        .A(buf_rst_n_1),
        .B(mem_addr_1),
        .C(n362),
        .Y(__dff_d_ff9313)
    );

    sky130_fd_sc_hd__o21a_1 U159 (
        .A1(mem_addr_2),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n710)
    );

    sky130_fd_sc_hd__o21a_1 U160 (
        .A1(latched_addr_31),
        .A2(n362),
        .B1(n710),
        .X(__dff_d_ff9314)
    );

    sky130_fd_sc_hd__o21a_1 U161 (
        .A1(mem_addr_3),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n714)
    );

    sky130_fd_sc_hd__o21a_1 U162 (
        .A1(latched_addr_30),
        .A2(n362),
        .B1(n714),
        .X(__dff_d_ff9315)
    );

    sky130_fd_sc_hd__o21a_1 U163 (
        .A1(mem_addr_4),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n718)
    );

    sky130_fd_sc_hd__o21a_1 U164 (
        .A1(latched_addr_29),
        .A2(n362),
        .B1(n718),
        .X(__dff_d_ff9316)
    );

    sky130_fd_sc_hd__o21a_1 U165 (
        .A1(mem_addr_5),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n722)
    );

    sky130_fd_sc_hd__o21a_1 U166 (
        .A1(latched_addr_28),
        .A2(n362),
        .B1(n722),
        .X(__dff_d_ff9317)
    );

    sky130_fd_sc_hd__o21a_1 U167 (
        .A1(mem_addr_6),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n726)
    );

    sky130_fd_sc_hd__o21a_1 U168 (
        .A1(latched_addr_27),
        .A2(n362),
        .B1(n726),
        .X(__dff_d_ff9318)
    );

    sky130_fd_sc_hd__o21a_1 U169 (
        .A1(mem_addr_7),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n730)
    );

    sky130_fd_sc_hd__o21a_1 U170 (
        .A1(latched_addr_26),
        .A2(n362),
        .B1(n730),
        .X(__dff_d_ff9319)
    );

    sky130_fd_sc_hd__o21a_1 U171 (
        .A1(mem_addr_8),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n734)
    );

    sky130_fd_sc_hd__o21a_1 U172 (
        .A1(latched_addr_25),
        .A2(n362),
        .B1(n734),
        .X(__dff_d_ff9320)
    );

    sky130_fd_sc_hd__o21a_1 U173 (
        .A1(mem_addr_9),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n738)
    );

    sky130_fd_sc_hd__o21a_1 U174 (
        .A1(latched_addr_24),
        .A2(n362),
        .B1(n738),
        .X(__dff_d_ff9321)
    );

    sky130_fd_sc_hd__o21a_1 U175 (
        .A1(mem_addr_10),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n742)
    );

    sky130_fd_sc_hd__o21a_1 U176 (
        .A1(latched_addr_23),
        .A2(n362),
        .B1(n742),
        .X(__dff_d_ff9322)
    );

    sky130_fd_sc_hd__o21a_1 U177 (
        .A1(mem_addr_11),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n746)
    );

    sky130_fd_sc_hd__o21a_1 U178 (
        .A1(latched_addr_22),
        .A2(n362),
        .B1(n746),
        .X(__dff_d_ff9323)
    );

    sky130_fd_sc_hd__o21a_1 U179 (
        .A1(mem_addr_12),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n750)
    );

    sky130_fd_sc_hd__o21a_1 U180 (
        .A1(latched_addr_21),
        .A2(n362),
        .B1(n750),
        .X(__dff_d_ff9324)
    );

    sky130_fd_sc_hd__o21a_1 U181 (
        .A1(mem_addr_13),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n754)
    );

    sky130_fd_sc_hd__o21a_1 U182 (
        .A1(latched_addr_20),
        .A2(n362),
        .B1(n754),
        .X(__dff_d_ff9325)
    );

    sky130_fd_sc_hd__o21a_1 U183 (
        .A1(mem_addr_14),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n758)
    );

    sky130_fd_sc_hd__o21a_1 U184 (
        .A1(latched_addr_19),
        .A2(n362),
        .B1(n758),
        .X(__dff_d_ff9326)
    );

    sky130_fd_sc_hd__o21a_1 U185 (
        .A1(mem_addr_15),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n762)
    );

    sky130_fd_sc_hd__o21a_1 U186 (
        .A1(latched_addr_18),
        .A2(n362),
        .B1(n762),
        .X(__dff_d_ff9327)
    );

    sky130_fd_sc_hd__o21a_1 U187 (
        .A1(mem_addr_16),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n766)
    );

    sky130_fd_sc_hd__o21a_1 U188 (
        .A1(latched_addr_17),
        .A2(n362),
        .B1(n766),
        .X(__dff_d_ff9328)
    );

    sky130_fd_sc_hd__o21a_1 U189 (
        .A1(mem_addr_17),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n770)
    );

    sky130_fd_sc_hd__o21a_1 U190 (
        .A1(latched_addr_16),
        .A2(n362),
        .B1(n770),
        .X(__dff_d_ff9329)
    );

    sky130_fd_sc_hd__o21a_1 U191 (
        .A1(mem_addr_18),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n774)
    );

    sky130_fd_sc_hd__o21a_1 U192 (
        .A1(latched_addr_15),
        .A2(n362),
        .B1(n774),
        .X(__dff_d_ff9330)
    );

    sky130_fd_sc_hd__o21a_1 U193 (
        .A1(mem_addr_19),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n778)
    );

    sky130_fd_sc_hd__o21a_1 U194 (
        .A1(latched_addr_14),
        .A2(n362),
        .B1(n778),
        .X(__dff_d_ff9331)
    );

    sky130_fd_sc_hd__o21a_1 U195 (
        .A1(mem_addr_20),
        .A2(clone_9),
        .B1(buf_rst_n_1),
        .X(n782)
    );

    sky130_fd_sc_hd__o21a_1 U196 (
        .A1(latched_addr_13),
        .A2(n362),
        .B1(n782),
        .X(__dff_d_ff9332)
    );

    sky130_fd_sc_hd__o21a_1 U197 (
        .A1(mem_addr_21),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n786)
    );

    sky130_fd_sc_hd__o21a_1 U198 (
        .A1(latched_addr_12),
        .A2(n362),
        .B1(n786),
        .X(__dff_d_ff9333)
    );

    sky130_fd_sc_hd__o21a_1 U199 (
        .A1(mem_addr_22),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n790)
    );

    sky130_fd_sc_hd__o21a_1 U200 (
        .A1(latched_addr_11),
        .A2(n362),
        .B1(n790),
        .X(__dff_d_ff9334)
    );

    sky130_fd_sc_hd__o21a_1 U201 (
        .A1(mem_addr_23),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n794)
    );

    sky130_fd_sc_hd__o21a_1 U202 (
        .A1(latched_addr_10),
        .A2(n362),
        .B1(n794),
        .X(__dff_d_ff9335)
    );

    sky130_fd_sc_hd__o21a_1 U203 (
        .A1(mem_addr_24),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n798)
    );

    sky130_fd_sc_hd__o21a_1 U204 (
        .A1(latched_addr_9),
        .A2(n362),
        .B1(n798),
        .X(__dff_d_ff9336)
    );

    sky130_fd_sc_hd__o21a_1 U205 (
        .A1(mem_addr_25),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n802)
    );

    sky130_fd_sc_hd__o21a_1 U206 (
        .A1(latched_addr_8),
        .A2(n362),
        .B1(n802),
        .X(__dff_d_ff9337)
    );

    sky130_fd_sc_hd__o21a_1 U207 (
        .A1(mem_addr_26),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n806)
    );

    sky130_fd_sc_hd__o21a_1 U208 (
        .A1(latched_addr_7),
        .A2(n362),
        .B1(n806),
        .X(__dff_d_ff9338)
    );

    sky130_fd_sc_hd__o21a_1 U209 (
        .A1(mem_addr_27),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n810)
    );

    sky130_fd_sc_hd__o21a_1 U210 (
        .A1(latched_addr_6),
        .A2(n362),
        .B1(n810),
        .X(__dff_d_ff9339)
    );

    sky130_fd_sc_hd__o21a_1 U211 (
        .A1(mem_addr_28),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n814)
    );

    sky130_fd_sc_hd__o21a_1 U212 (
        .A1(latched_addr_5),
        .A2(n362),
        .B1(n814),
        .X(__dff_d_ff9340)
    );

    sky130_fd_sc_hd__o21a_1 U213 (
        .A1(mem_addr_29),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n818)
    );

    sky130_fd_sc_hd__o21a_1 U214 (
        .A1(latched_addr_4),
        .A2(n362),
        .B1(n818),
        .X(__dff_d_ff9341)
    );

    sky130_fd_sc_hd__o21a_1 U215 (
        .A1(mem_addr_30),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n822)
    );

    sky130_fd_sc_hd__o21a_1 U216 (
        .A1(latched_addr_3),
        .A2(n362),
        .B1(n822),
        .X(__dff_d_ff9342)
    );

    sky130_fd_sc_hd__o21a_1 U217 (
        .A1(mem_addr_31),
        .A2(clone_9),
        .B1(buf_rst_n_2),
        .X(n826)
    );

    sky130_fd_sc_hd__o21a_1 U218 (
        .A1(latched_addr_2),
        .A2(n362),
        .B1(n826),
        .X(__dff_d_ff9343)
    );

    sky130_fd_sc_hd__nand2_1 U219 (
        .A(buf_rst_n_2),
        .B(mem_wdata_0),
        .Y(__dff_d_ff9345)
    );

    sky130_fd_sc_hd__nand2_1 U220 (
        .A(buf_rst_n_2),
        .B(mem_wdata_1),
        .Y(__dff_d_ff9346)
    );

    sky130_fd_sc_hd__nand2_1 U221 (
        .A(buf_rst_n_2),
        .B(mem_wdata_2),
        .Y(__dff_d_ff9347)
    );

    sky130_fd_sc_hd__nand2_1 U222 (
        .A(buf_rst_n_2),
        .B(mem_wdata_3),
        .Y(__dff_d_ff9348)
    );

    sky130_fd_sc_hd__nand2_1 U223 (
        .A(buf_rst_n_2),
        .B(mem_wdata_4),
        .Y(__dff_d_ff9349)
    );

    sky130_fd_sc_hd__nand2_1 U224 (
        .A(buf_rst_n_2),
        .B(mem_wdata_5),
        .Y(__dff_d_ff9350)
    );

    sky130_fd_sc_hd__nand2_1 U225 (
        .A(buf_rst_n_2),
        .B(mem_wdata_6),
        .Y(__dff_d_ff9351)
    );

    sky130_fd_sc_hd__nand2_1 U226 (
        .A(buf_rst_n_2),
        .B(mem_wdata_7),
        .Y(__dff_d_ff9352)
    );

    sky130_fd_sc_hd__nand2_1 U227 (
        .A(buf_rst_n_2),
        .B(mem_wdata_8),
        .Y(__dff_d_ff9353)
    );

    sky130_fd_sc_hd__nand2_1 U228 (
        .A(buf_rst_n_2),
        .B(mem_wdata_9),
        .Y(__dff_d_ff9354)
    );

    sky130_fd_sc_hd__nand2_1 U229 (
        .A(buf_rst_n_2),
        .B(mem_wdata_10),
        .Y(__dff_d_ff9355)
    );

    sky130_fd_sc_hd__nand2_1 U230 (
        .A(buf_rst_n_2),
        .B(mem_wdata_11),
        .Y(__dff_d_ff9356)
    );

    sky130_fd_sc_hd__nand2_1 U231 (
        .A(buf_rst_n_2),
        .B(mem_wdata_12),
        .Y(__dff_d_ff9357)
    );

    sky130_fd_sc_hd__nand2_1 U232 (
        .A(buf_rst_n_2),
        .B(mem_wdata_13),
        .Y(__dff_d_ff9358)
    );

    sky130_fd_sc_hd__nand2_1 U233 (
        .A(buf_rst_n_2),
        .B(mem_wdata_14),
        .Y(__dff_d_ff9359)
    );

    sky130_fd_sc_hd__nand2_1 U234 (
        .A(buf_rst_n_2),
        .B(mem_wdata_15),
        .Y(__dff_d_ff9360)
    );

    sky130_fd_sc_hd__nand2_1 U235 (
        .A(buf_rst_n_2),
        .B(mem_wdata_16),
        .Y(__dff_d_ff9361)
    );

    sky130_fd_sc_hd__nand2_1 U236 (
        .A(buf_rst_n_2),
        .B(mem_wdata_17),
        .Y(__dff_d_ff9362)
    );

    sky130_fd_sc_hd__nand2_1 U237 (
        .A(buf_rst_n_2),
        .B(mem_wdata_18),
        .Y(__dff_d_ff9363)
    );

    sky130_fd_sc_hd__nand2_1 U238 (
        .A(buf_rst_n_2),
        .B(mem_wdata_19),
        .Y(__dff_d_ff9364)
    );

    sky130_fd_sc_hd__nand2_1 U239 (
        .A(buf_rst_n_2),
        .B(mem_wdata_20),
        .Y(__dff_d_ff9365)
    );

    sky130_fd_sc_hd__nand2_1 U240 (
        .A(buf_rst_n_2),
        .B(mem_wdata_21),
        .Y(__dff_d_ff9366)
    );

    sky130_fd_sc_hd__nand2_1 U241 (
        .A(buf_rst_n_2),
        .B(mem_wdata_22),
        .Y(__dff_d_ff9367)
    );

    sky130_fd_sc_hd__nand2_1 U242 (
        .A(buf_rst_n_2),
        .B(mem_wdata_23),
        .Y(__dff_d_ff9368)
    );

    sky130_fd_sc_hd__nand2_1 U243 (
        .A(buf_rst_n_2),
        .B(mem_wdata_24),
        .Y(__dff_d_ff9369)
    );

    sky130_fd_sc_hd__nand2_1 U244 (
        .A(buf_rst_n_2),
        .B(mem_wdata_25),
        .Y(__dff_d_ff9370)
    );

    sky130_fd_sc_hd__nand2_1 U245 (
        .A(buf_rst_n_2),
        .B(mem_wdata_26),
        .Y(__dff_d_ff9371)
    );

    sky130_fd_sc_hd__nand2_1 U246 (
        .A(buf_rst_n_2),
        .B(mem_wdata_27),
        .Y(__dff_d_ff9372)
    );

    sky130_fd_sc_hd__nand2_1 U247 (
        .A(buf_rst_n_2),
        .B(mem_wdata_28),
        .Y(__dff_d_ff9373)
    );

    sky130_fd_sc_hd__nand2_1 U248 (
        .A(buf_rst_n_2),
        .B(mem_wdata_29),
        .Y(__dff_d_ff9374)
    );

    sky130_fd_sc_hd__nand2_1 U249 (
        .A(buf_rst_n_2),
        .B(mem_wdata_30),
        .Y(__dff_d_ff9375)
    );

    sky130_fd_sc_hd__nand2_1 U250 (
        .A(buf_rst_n_2),
        .B(mem_wdata_31),
        .Y(__dff_d_ff9376)
    );

    sky130_fd_sc_hd__inv_1 U251 (
        .A(fill_word_cnt),
        .Y(inv_n211)
    );

    sky130_fd_sc_hd__nand3b_1 U252 (
        .A_N(fill_word_cnt),
        .B(mem_ready),
        .C(clone_9),
        .Y(n861)
    );

    sky130_fd_sc_hd__nand4_1 U253 (
        .A(mem_ready),
        .B(inv_n211),
        .C(latched_tag),
        .D(clone_9),
        .Y(n862)
    );

    sky130_fd_sc_hd__inv_1 U254 (
        .A(latched_index),
        .Y(inv_n246)
    );

    sky130_fd_sc_hd__a22oi_1 U255 (
        .A1(inv_n246),
        .A2(n862),
        .B1(tag_mem_0),
        .B2(n861),
        .Y(n865)
    );

    sky130_fd_sc_hd__nand2_1 U256 (
        .A(buf_rst_n_2),
        .B(n865),
        .Y(n866)
    );

    sky130_fd_sc_hd__o21a_1 U257 (
        .A1(buf_rst_n_2),
        .A2(tag_mem_0),
        .B1(n866),
        .X(__dff_d_ff9381)
    );

    sky130_fd_sc_hd__a22oi_1 U258 (
        .A1(latched_index),
        .A2(n862),
        .B1(tag_mem_1),
        .B2(n861),
        .Y(n871)
    );

    sky130_fd_sc_hd__nand2_1 U259 (
        .A(buf_rst_n_2),
        .B(n871),
        .Y(n872)
    );

    sky130_fd_sc_hd__o21a_1 U260 (
        .A1(buf_rst_n_2),
        .A2(tag_mem_1),
        .B1(n872),
        .X(__dff_d_ff9382)
    );

    sky130_fd_sc_hd__nand4_1 U261 (
        .A(buf_rst_n_2),
        .B(mem_ready),
        .C(inv_n211),
        .D(clone_9),
        .Y(n877)
    );

    sky130_fd_sc_hd__mux2_1 U262 (
        .A0(inv_n246),
        .A1(valid_0),
        .S(n877),
        .X(__dff_d_ff9383)
    );

    sky130_fd_sc_hd__mux2_1 U263 (
        .A0(latched_index),
        .A1(valid_1),
        .S(n877),
        .X(__dff_d_ff9384)
    );

    sky130_fd_sc_hd__nand2_1 U264 (
        .A(buf_rst_n_2),
        .B(wb_word_cnt),
        .Y(__dff_d_ff9385)
    );

    sky130_fd_sc_hd__buf_1 U265 (
        .A(busy),
        .X(__dff_d_ff153)
    );

    sky130_fd_sc_hd__buf_1 U266 (
        .A(busy),
        .X(__dff_d_ff9136)
    );

    sky130_fd_sc_hd__buf_1 U267 (
        .A(busy),
        .X(__dff_d_ff9137)
    );

    sky130_fd_sc_hd__buf_1 U268 (
        .A(busy),
        .X(__dff_d_ff9170)
    );

    sky130_fd_sc_hd__buf_1 U269 (
        .A(busy),
        .X(__dff_d_ff9344)
    );

    sky130_fd_sc_hd__buf_1 U270 (
        .A(busy),
        .X(__dff_d_ff9377)
    );

    sky130_fd_sc_hd__buf_1 U271 (
        .A(busy),
        .X(__dff_d_ff9378)
    );

    sky130_fd_sc_hd__buf_1 U272 (
        .A(busy),
        .X(__dff_d_ff9379)
    );

    sky130_fd_sc_hd__buf_1 U273 (
        .A(busy),
        .X(__dff_d_ff9380)
    );

    sky130_fd_sc_hd__and4_1 U274 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .D(state_3),
        .X(clone_9)
    );

    sky130_fd_sc_hd__nand3_1 U275 (
        .A(flush),
        .B(n368),
        .C(clone_9),
        .Y(clone_11)
    );

    sky130_fd_sc_hd__and3b_1 U276 (
        .A_N(flush),
        .B(cpu_req),
        .C(clone_9),
        .X(clone_53)
    );

    sky130_fd_sc_hd__buf_1 U277 (
        .A(n411),
        .X(buf_n411_1)
    );

    sky130_fd_sc_hd__buf_1 U278 (
        .A(clone_53),
        .X(buf_clone_53_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U279 (
        .D(__dff_d_ff153),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(state_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U280 (
        .D(__dff_d_ff9136),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cache_hit)
    );

    sky130_fd_sc_hd__dfrtp_1 U281 (
        .D(__dff_d_ff9137),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cache_miss)
    );

    sky130_fd_sc_hd__dfrtp_1 U282 (
        .D(__dff_d_ff9170),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cpu_ready)
    );

    sky130_fd_sc_hd__dfrtp_1 U283 (
        .D(__dff_d_ff9171),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9171)
    );

    sky130_fd_sc_hd__dfrtp_1 U284 (
        .D(__dff_d_ff9172),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9172)
    );

    sky130_fd_sc_hd__dfrtp_1 U285 (
        .D(__dff_d_ff9173),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9173)
    );

    sky130_fd_sc_hd__dfrtp_1 U286 (
        .D(__dff_d_ff9174),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9174)
    );

    sky130_fd_sc_hd__dfrtp_1 U287 (
        .D(__dff_d_ff9175),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9175)
    );

    sky130_fd_sc_hd__dfrtp_1 U288 (
        .D(__dff_d_ff9176),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9176)
    );

    sky130_fd_sc_hd__dfrtp_1 U289 (
        .D(__dff_d_ff9177),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9177)
    );

    sky130_fd_sc_hd__dfrtp_1 U290 (
        .D(__dff_d_ff9178),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9178)
    );

    sky130_fd_sc_hd__dfrtp_1 U291 (
        .D(__dff_d_ff9179),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9179)
    );

    sky130_fd_sc_hd__dfrtp_1 U292 (
        .D(__dff_d_ff9180),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9180)
    );

    sky130_fd_sc_hd__dfrtp_1 U293 (
        .D(__dff_d_ff9181),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9181)
    );

    sky130_fd_sc_hd__dfrtp_1 U294 (
        .D(__dff_d_ff9182),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9182)
    );

    sky130_fd_sc_hd__dfrtp_1 U295 (
        .D(__dff_d_ff9183),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9183)
    );

    sky130_fd_sc_hd__dfrtp_1 U296 (
        .D(__dff_d_ff9184),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9184)
    );

    sky130_fd_sc_hd__dfrtp_1 U297 (
        .D(__dff_d_ff9185),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9185)
    );

    sky130_fd_sc_hd__dfrtp_1 U298 (
        .D(__dff_d_ff9186),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9186)
    );

    sky130_fd_sc_hd__dfrtp_1 U299 (
        .D(__dff_d_ff9187),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9187)
    );

    sky130_fd_sc_hd__dfrtp_1 U300 (
        .D(__dff_d_ff9188),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9188)
    );

    sky130_fd_sc_hd__dfrtp_1 U301 (
        .D(__dff_d_ff9189),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9189)
    );

    sky130_fd_sc_hd__dfrtp_1 U302 (
        .D(__dff_d_ff9190),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9190)
    );

    sky130_fd_sc_hd__dfrtp_1 U303 (
        .D(__dff_d_ff9191),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9191)
    );

    sky130_fd_sc_hd__dfrtp_1 U304 (
        .D(__dff_d_ff9192),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9192)
    );

    sky130_fd_sc_hd__dfrtp_1 U305 (
        .D(__dff_d_ff9193),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9193)
    );

    sky130_fd_sc_hd__dfrtp_1 U306 (
        .D(__dff_d_ff9194),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9194)
    );

    sky130_fd_sc_hd__dfrtp_1 U307 (
        .D(__dff_d_ff9195),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9195)
    );

    sky130_fd_sc_hd__dfrtp_1 U308 (
        .D(__dff_d_ff9196),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9196)
    );

    sky130_fd_sc_hd__dfrtp_1 U309 (
        .D(__dff_d_ff9197),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9197)
    );

    sky130_fd_sc_hd__dfrtp_1 U310 (
        .D(__dff_d_ff9198),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9198)
    );

    sky130_fd_sc_hd__dfrtp_1 U311 (
        .D(__dff_d_ff9199),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9199)
    );

    sky130_fd_sc_hd__dfrtp_1 U312 (
        .D(__dff_d_ff9200),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9200)
    );

    sky130_fd_sc_hd__dfrtp_1 U313 (
        .D(__dff_d_ff9201),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9201)
    );

    sky130_fd_sc_hd__dfrtp_1 U314 (
        .D(__dff_d_ff9202),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9202)
    );

    sky130_fd_sc_hd__dfrtp_1 U315 (
        .D(__dff_d_ff9203),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9203)
    );

    sky130_fd_sc_hd__dfrtp_1 U316 (
        .D(__dff_d_ff9204),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9204)
    );

    sky130_fd_sc_hd__dfrtp_1 U317 (
        .D(__dff_d_ff9205),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9205)
    );

    sky130_fd_sc_hd__dfrtp_1 U318 (
        .D(__dff_d_ff9206),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9206)
    );

    sky130_fd_sc_hd__dfrtp_1 U319 (
        .D(__dff_d_ff9207),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9207)
    );

    sky130_fd_sc_hd__dfrtp_1 U320 (
        .D(__dff_d_ff9208),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9208)
    );

    sky130_fd_sc_hd__dfrtp_1 U321 (
        .D(__dff_d_ff9209),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9209)
    );

    sky130_fd_sc_hd__dfrtp_1 U322 (
        .D(__dff_d_ff9210),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9210)
    );

    sky130_fd_sc_hd__dfrtp_1 U323 (
        .D(__dff_d_ff9211),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9211)
    );

    sky130_fd_sc_hd__dfrtp_1 U324 (
        .D(__dff_d_ff9212),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9212)
    );

    sky130_fd_sc_hd__dfrtp_1 U325 (
        .D(__dff_d_ff9213),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9213)
    );

    sky130_fd_sc_hd__dfrtp_1 U326 (
        .D(__dff_d_ff9214),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9214)
    );

    sky130_fd_sc_hd__dfrtp_1 U327 (
        .D(__dff_d_ff9215),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9215)
    );

    sky130_fd_sc_hd__dfrtp_1 U328 (
        .D(__dff_d_ff9216),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9216)
    );

    sky130_fd_sc_hd__dfrtp_1 U329 (
        .D(__dff_d_ff9217),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9217)
    );

    sky130_fd_sc_hd__dfrtp_1 U330 (
        .D(__dff_d_ff9218),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9218)
    );

    sky130_fd_sc_hd__dfrtp_1 U331 (
        .D(__dff_d_ff9219),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9219)
    );

    sky130_fd_sc_hd__dfrtp_1 U332 (
        .D(__dff_d_ff9220),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9220)
    );

    sky130_fd_sc_hd__dfrtp_1 U333 (
        .D(__dff_d_ff9221),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9221)
    );

    sky130_fd_sc_hd__dfrtp_1 U334 (
        .D(__dff_d_ff9222),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9222)
    );

    sky130_fd_sc_hd__dfrtp_1 U335 (
        .D(__dff_d_ff9223),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9223)
    );

    sky130_fd_sc_hd__dfrtp_1 U336 (
        .D(__dff_d_ff9224),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9224)
    );

    sky130_fd_sc_hd__dfrtp_1 U337 (
        .D(__dff_d_ff9225),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9225)
    );

    sky130_fd_sc_hd__dfrtp_1 U338 (
        .D(__dff_d_ff9226),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9226)
    );

    sky130_fd_sc_hd__dfrtp_1 U339 (
        .D(__dff_d_ff9227),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9227)
    );

    sky130_fd_sc_hd__dfrtp_1 U340 (
        .D(__dff_d_ff9228),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9228)
    );

    sky130_fd_sc_hd__dfrtp_1 U341 (
        .D(__dff_d_ff9229),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9229)
    );

    sky130_fd_sc_hd__dfrtp_1 U342 (
        .D(__dff_d_ff9230),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9230)
    );

    sky130_fd_sc_hd__dfrtp_1 U343 (
        .D(__dff_d_ff9231),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9231)
    );

    sky130_fd_sc_hd__dfrtp_1 U344 (
        .D(__dff_d_ff9232),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9232)
    );

    sky130_fd_sc_hd__dfrtp_1 U345 (
        .D(__dff_d_ff9233),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9233)
    );

    sky130_fd_sc_hd__dfrtp_1 U346 (
        .D(__dff_d_ff9234),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9234)
    );

    sky130_fd_sc_hd__dfrtp_1 U347 (
        .D(__dff_d_ff9235),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9235)
    );

    sky130_fd_sc_hd__dfrtp_1 U348 (
        .D(__dff_d_ff9236),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff9236)
    );

    sky130_fd_sc_hd__dfrtp_1 U349 (
        .D(__dff_d_ff9240),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U350 (
        .D(__dff_d_ff9241),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U351 (
        .D(__dff_d_ff9242),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U352 (
        .D(__dff_d_ff9243),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U353 (
        .D(__dff_d_ff9244),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U354 (
        .D(__dff_d_ff9245),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U355 (
        .D(__dff_d_ff9246),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U356 (
        .D(__dff_d_ff9247),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U357 (
        .D(__dff_d_ff9248),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U358 (
        .D(__dff_d_ff9249),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U359 (
        .D(__dff_d_ff9250),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U360 (
        .D(__dff_d_ff9251),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U361 (
        .D(__dff_d_ff9252),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U362 (
        .D(__dff_d_ff9253),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U363 (
        .D(__dff_d_ff9254),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U364 (
        .D(__dff_d_ff9255),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U365 (
        .D(__dff_d_ff9256),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U366 (
        .D(__dff_d_ff9257),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U367 (
        .D(__dff_d_ff9258),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U368 (
        .D(__dff_d_ff9259),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U369 (
        .D(__dff_d_ff9260),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U370 (
        .D(__dff_d_ff9261),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U371 (
        .D(__dff_d_ff9262),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U372 (
        .D(__dff_d_ff9263),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U373 (
        .D(__dff_d_ff9264),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U374 (
        .D(__dff_d_ff9265),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U375 (
        .D(__dff_d_ff9266),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U376 (
        .D(__dff_d_ff9267),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U377 (
        .D(__dff_d_ff9268),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U378 (
        .D(__dff_d_ff9269),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U379 (
        .D(__dff_d_ff9270),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U380 (
        .D(__dff_d_ff9271),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U381 (
        .D(__dff_d_ff9272),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_index)
    );

    sky130_fd_sc_hd__dfrtp_1 U382 (
        .D(__dff_d_ff9273),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_is_write)
    );

    sky130_fd_sc_hd__dfrtp_1 U383 (
        .D(__dff_d_ff9274),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_tag)
    );

    sky130_fd_sc_hd__dfrtp_1 U384 (
        .D(__dff_d_ff9275),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U385 (
        .D(__dff_d_ff9276),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U386 (
        .D(__dff_d_ff9277),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U387 (
        .D(__dff_d_ff9278),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U388 (
        .D(__dff_d_ff9279),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U389 (
        .D(__dff_d_ff9280),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U390 (
        .D(__dff_d_ff9281),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U391 (
        .D(__dff_d_ff9282),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U392 (
        .D(__dff_d_ff9283),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U393 (
        .D(__dff_d_ff9284),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U394 (
        .D(__dff_d_ff9285),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U395 (
        .D(__dff_d_ff9286),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U396 (
        .D(__dff_d_ff9287),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U397 (
        .D(__dff_d_ff9288),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U398 (
        .D(__dff_d_ff9289),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U399 (
        .D(__dff_d_ff9290),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U400 (
        .D(__dff_d_ff9291),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U401 (
        .D(__dff_d_ff9292),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U402 (
        .D(__dff_d_ff9293),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U403 (
        .D(__dff_d_ff9294),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U404 (
        .D(__dff_d_ff9295),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U405 (
        .D(__dff_d_ff9296),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U406 (
        .D(__dff_d_ff9297),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U407 (
        .D(__dff_d_ff9298),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U408 (
        .D(__dff_d_ff9299),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U409 (
        .D(__dff_d_ff9300),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U410 (
        .D(__dff_d_ff9301),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U411 (
        .D(__dff_d_ff9302),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U412 (
        .D(__dff_d_ff9303),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U413 (
        .D(__dff_d_ff9304),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U414 (
        .D(__dff_d_ff9305),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U415 (
        .D(__dff_d_ff9306),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wdata_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U416 (
        .D(__dff_d_ff9307),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_word_off)
    );

    sky130_fd_sc_hd__dfrtp_1 U417 (
        .D(__dff_d_ff9308),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wstrb_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U418 (
        .D(__dff_d_ff9309),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wstrb_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U419 (
        .D(__dff_d_ff9310),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wstrb_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U420 (
        .D(__dff_d_ff9311),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_wstrb_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U421 (
        .D(__dff_d_ff9312),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U422 (
        .D(__dff_d_ff9313),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U423 (
        .D(__dff_d_ff9314),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U424 (
        .D(__dff_d_ff9315),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U425 (
        .D(__dff_d_ff9316),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U426 (
        .D(__dff_d_ff9317),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U427 (
        .D(__dff_d_ff9318),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U428 (
        .D(__dff_d_ff9319),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U429 (
        .D(__dff_d_ff9320),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U430 (
        .D(__dff_d_ff9321),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U431 (
        .D(__dff_d_ff9322),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U432 (
        .D(__dff_d_ff9323),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U433 (
        .D(__dff_d_ff9324),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U434 (
        .D(__dff_d_ff9325),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U435 (
        .D(__dff_d_ff9326),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U436 (
        .D(__dff_d_ff9327),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U437 (
        .D(__dff_d_ff9328),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U438 (
        .D(__dff_d_ff9329),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U439 (
        .D(__dff_d_ff9330),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U440 (
        .D(__dff_d_ff9331),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U441 (
        .D(__dff_d_ff9332),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U442 (
        .D(__dff_d_ff9333),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U443 (
        .D(__dff_d_ff9334),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U444 (
        .D(__dff_d_ff9335),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U445 (
        .D(__dff_d_ff9336),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U446 (
        .D(__dff_d_ff9337),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U447 (
        .D(__dff_d_ff9338),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U448 (
        .D(__dff_d_ff9339),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U449 (
        .D(__dff_d_ff9340),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U450 (
        .D(__dff_d_ff9341),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U451 (
        .D(__dff_d_ff9342),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U452 (
        .D(__dff_d_ff9343),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U453 (
        .D(__dff_d_ff9344),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_req)
    );

    sky130_fd_sc_hd__dfrtp_1 U454 (
        .D(__dff_d_ff9345),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U455 (
        .D(__dff_d_ff9346),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U456 (
        .D(__dff_d_ff9347),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U457 (
        .D(__dff_d_ff9348),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U458 (
        .D(__dff_d_ff9349),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U459 (
        .D(__dff_d_ff9350),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U460 (
        .D(__dff_d_ff9351),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U461 (
        .D(__dff_d_ff9352),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U462 (
        .D(__dff_d_ff9353),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U463 (
        .D(__dff_d_ff9354),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U464 (
        .D(__dff_d_ff9355),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U465 (
        .D(__dff_d_ff9356),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U466 (
        .D(__dff_d_ff9357),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U467 (
        .D(__dff_d_ff9358),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U468 (
        .D(__dff_d_ff9359),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U469 (
        .D(__dff_d_ff9360),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U470 (
        .D(__dff_d_ff9361),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U471 (
        .D(__dff_d_ff9362),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U472 (
        .D(__dff_d_ff9363),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U473 (
        .D(__dff_d_ff9364),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U474 (
        .D(__dff_d_ff9365),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U475 (
        .D(__dff_d_ff9366),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U476 (
        .D(__dff_d_ff9367),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U477 (
        .D(__dff_d_ff9368),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U478 (
        .D(__dff_d_ff9369),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U479 (
        .D(__dff_d_ff9370),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U480 (
        .D(__dff_d_ff9371),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U481 (
        .D(__dff_d_ff9372),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U482 (
        .D(__dff_d_ff9373),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U483 (
        .D(__dff_d_ff9374),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U484 (
        .D(__dff_d_ff9375),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U485 (
        .D(__dff_d_ff9376),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wdata_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U486 (
        .D(__dff_d_ff9377),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wstrb_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U487 (
        .D(__dff_d_ff9378),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wstrb_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U488 (
        .D(__dff_d_ff9379),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wstrb_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U489 (
        .D(__dff_d_ff9380),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_wstrb_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U490 (
        .D(__dff_d_ff9381),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(tag_mem_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U491 (
        .D(__dff_d_ff9382),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(tag_mem_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U492 (
        .D(__dff_d_ff9383),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(valid_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U493 (
        .D(__dff_d_ff9384),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(valid_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U494 (
        .D(__dff_d_ff9385),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wb_word_cnt)
    );

    sky130_fd_sc_hd__conb_1 UTIE_0 (.LO(buf_clone_53_0));
    sky130_fd_sc_hd__conb_1 UTIE_1 (.LO(buf_n411_0));
    sky130_fd_sc_hd__conb_1 UTIE_2 (.LO(buf_rst_n_0));
    sky130_fd_sc_hd__conb_1 UTIE_3 (.LO(buf_rst_n_1));
    sky130_fd_sc_hd__conb_1 UTIE_4 (.LO(buf_rst_n_2));
    sky130_fd_sc_hd__conb_1 UTIE_5 (.LO(fill_word_cnt));
    sky130_fd_sc_hd__conb_1 UTIE_6 (.LO(state_0));
    sky130_fd_sc_hd__conb_1 UTIE_7 (.LO(state_1));
    sky130_fd_sc_hd__conb_1 UTIE_8 (.LO(state_2));
endmodule
