// Generated by My Own Flow — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module icache (
    input clk,
    input rst_n,
    input cpu_addr_0,
    input cpu_addr_1,
    input cpu_addr_2,
    input cpu_addr_3,
    input cpu_addr_4,
    input cpu_addr_5,
    input cpu_addr_6,
    input cpu_addr_7,
    input cpu_addr_8,
    input cpu_addr_9,
    input cpu_addr_10,
    input cpu_addr_11,
    input cpu_addr_12,
    input cpu_addr_13,
    input cpu_addr_14,
    input cpu_addr_15,
    input cpu_addr_16,
    input cpu_addr_17,
    input cpu_addr_18,
    input cpu_addr_19,
    input cpu_addr_20,
    input cpu_addr_21,
    input cpu_addr_22,
    input cpu_addr_23,
    input cpu_addr_24,
    input cpu_addr_25,
    input cpu_addr_26,
    input cpu_addr_27,
    input cpu_addr_28,
    input cpu_addr_29,
    input cpu_addr_30,
    input cpu_addr_31,
    input cpu_req,
    input mem_rdata_0,
    input mem_rdata_1,
    input mem_rdata_2,
    input mem_rdata_3,
    input mem_rdata_4,
    input mem_rdata_5,
    input mem_rdata_6,
    input mem_rdata_7,
    input mem_rdata_8,
    input mem_rdata_9,
    input mem_rdata_10,
    input mem_rdata_11,
    input mem_rdata_12,
    input mem_rdata_13,
    input mem_rdata_14,
    input mem_rdata_15,
    input mem_rdata_16,
    input mem_rdata_17,
    input mem_rdata_18,
    input mem_rdata_19,
    input mem_rdata_20,
    input mem_rdata_21,
    input mem_rdata_22,
    input mem_rdata_23,
    input mem_rdata_24,
    input mem_rdata_25,
    input mem_rdata_26,
    input mem_rdata_27,
    input mem_rdata_28,
    input mem_rdata_29,
    input mem_rdata_30,
    input mem_rdata_31,
    input mem_ready,
    input flush,
    output cache_hit,
    output cache_miss,
    output cpu_rdata_0,
    output cpu_rdata_1,
    output cpu_rdata_2,
    output cpu_rdata_3,
    output cpu_rdata_4,
    output cpu_rdata_5,
    output cpu_rdata_6,
    output cpu_rdata_7,
    output cpu_rdata_8,
    output cpu_rdata_9,
    output cpu_rdata_10,
    output cpu_rdata_11,
    output cpu_rdata_12,
    output cpu_rdata_13,
    output cpu_rdata_14,
    output cpu_rdata_15,
    output cpu_rdata_16,
    output cpu_rdata_17,
    output cpu_rdata_18,
    output cpu_rdata_19,
    output cpu_rdata_20,
    output cpu_rdata_21,
    output cpu_rdata_22,
    output cpu_rdata_23,
    output cpu_rdata_24,
    output cpu_rdata_25,
    output cpu_rdata_26,
    output cpu_rdata_27,
    output cpu_rdata_28,
    output cpu_rdata_29,
    output cpu_rdata_30,
    output cpu_rdata_31,
    output cpu_ready,
    output mem_addr_0,
    output mem_addr_1,
    output mem_addr_2,
    output mem_addr_3,
    output mem_addr_4,
    output mem_addr_5,
    output mem_addr_6,
    output mem_addr_7,
    output mem_addr_8,
    output mem_addr_9,
    output mem_addr_10,
    output mem_addr_11,
    output mem_addr_12,
    output mem_addr_13,
    output mem_addr_14,
    output mem_addr_15,
    output mem_addr_16,
    output mem_addr_17,
    output mem_addr_18,
    output mem_addr_19,
    output mem_addr_20,
    output mem_addr_21,
    output mem_addr_22,
    output mem_addr_23,
    output mem_addr_24,
    output mem_addr_25,
    output mem_addr_26,
    output mem_addr_27,
    output mem_addr_28,
    output mem_addr_29,
    output mem_addr_30,
    output mem_addr_31,
    output mem_req
);

    wire state_0;
    wire state_1;
    wire state_2;
    wire data_mem_0_0;
    wire data_mem_0_1;
    wire data_mem_0_2;
    wire data_mem_0_3;
    wire data_mem_0_4;
    wire data_mem_0_5;
    wire data_mem_0_6;
    wire data_mem_0_7;
    wire data_mem_0_8;
    wire data_mem_0_9;
    wire data_mem_0_10;
    wire data_mem_0_11;
    wire data_mem_0_12;
    wire data_mem_0_13;
    wire data_mem_0_14;
    wire data_mem_0_15;
    wire data_mem_0_16;
    wire data_mem_0_17;
    wire data_mem_0_18;
    wire data_mem_0_19;
    wire data_mem_0_20;
    wire data_mem_0_21;
    wire data_mem_0_22;
    wire data_mem_0_23;
    wire data_mem_0_24;
    wire data_mem_0_25;
    wire data_mem_0_26;
    wire data_mem_0_27;
    wire data_mem_0_28;
    wire data_mem_0_29;
    wire data_mem_0_30;
    wire data_mem_0_31;
    wire data_mem_1_0;
    wire data_mem_1_1;
    wire data_mem_1_2;
    wire data_mem_1_3;
    wire data_mem_1_4;
    wire data_mem_1_5;
    wire data_mem_1_6;
    wire data_mem_1_7;
    wire data_mem_1_8;
    wire data_mem_1_9;
    wire data_mem_1_10;
    wire data_mem_1_11;
    wire data_mem_1_12;
    wire data_mem_1_13;
    wire data_mem_1_14;
    wire data_mem_1_15;
    wire data_mem_1_16;
    wire data_mem_1_17;
    wire data_mem_1_18;
    wire data_mem_1_19;
    wire data_mem_1_20;
    wire data_mem_1_21;
    wire data_mem_1_22;
    wire data_mem_1_23;
    wire data_mem_1_24;
    wire data_mem_1_25;
    wire data_mem_1_26;
    wire data_mem_1_27;
    wire data_mem_1_28;
    wire data_mem_1_29;
    wire data_mem_1_30;
    wire data_mem_1_31;
    wire fill_word_cnt;
    wire flush_cnt;
    wire flush_done;
    wire latched_addr_0;
    wire latched_addr_1;
    wire latched_addr_2;
    wire latched_addr_3;
    wire latched_addr_4;
    wire latched_addr_5;
    wire latched_addr_6;
    wire latched_addr_7;
    wire latched_addr_8;
    wire latched_addr_9;
    wire latched_addr_10;
    wire latched_addr_11;
    wire latched_addr_12;
    wire latched_addr_13;
    wire latched_addr_14;
    wire latched_addr_15;
    wire latched_addr_16;
    wire latched_addr_17;
    wire latched_addr_18;
    wire latched_addr_19;
    wire latched_addr_20;
    wire latched_addr_21;
    wire latched_addr_22;
    wire latched_addr_23;
    wire latched_addr_24;
    wire latched_addr_25;
    wire latched_addr_26;
    wire latched_addr_27;
    wire latched_addr_28;
    wire latched_addr_29;
    wire latched_addr_30;
    wire latched_addr_31;
    wire latched_index;
    wire latched_tag;
    wire latched_word_off;
    wire tag_mem_0;
    wire tag_mem_1;
    wire valid_0;
    wire valid_1;
    wire __dff_d_ff21;
    wire n248;
    wire n251;
    wire inv_n35;
    wire inv_n69;
    wire inv_n70;
    wire __dff_d_ff20;
    wire n254;
    wire n255;
    wire __dff_d_ff22;
    wire __dff_d_ff2807;
    wire __dff_d_ff2808;
    wire __dff_d_ff2809;
    wire __dff_d_ff2810;
    wire __dff_d_ff2811;
    wire __dff_d_ff2812;
    wire __dff_d_ff2813;
    wire __dff_d_ff2814;
    wire __dff_d_ff2815;
    wire __dff_d_ff2816;
    wire __dff_d_ff2817;
    wire __dff_d_ff2818;
    wire __dff_d_ff2819;
    wire __dff_d_ff2820;
    wire __dff_d_ff2821;
    wire __dff_d_ff2822;
    wire __dff_d_ff2823;
    wire __dff_d_ff2824;
    wire __dff_d_ff2825;
    wire __dff_d_ff2826;
    wire __dff_d_ff2827;
    wire __dff_d_ff2828;
    wire __dff_d_ff2829;
    wire __dff_d_ff2830;
    wire __dff_d_ff2831;
    wire __dff_d_ff2832;
    wire __dff_d_ff2833;
    wire __dff_d_ff2834;
    wire __dff_d_ff2835;
    wire __dff_d_ff2836;
    wire __dff_d_ff2837;
    wire __dff_d_ff2838;
    wire n290;
    wire inv_n207;
    wire n291;
    wire __dff_d_ff2840;
    wire __dff_d_ff2841;
    wire __dff_d_ff2842;
    wire __dff_d_ff2843;
    wire __dff_d_ff2844;
    wire __dff_d_ff2845;
    wire __dff_d_ff2846;
    wire __dff_d_ff2847;
    wire __dff_d_ff2848;
    wire __dff_d_ff2849;
    wire __dff_d_ff2850;
    wire __dff_d_ff2851;
    wire __dff_d_ff2852;
    wire __dff_d_ff2853;
    wire __dff_d_ff2854;
    wire __dff_d_ff2855;
    wire __dff_d_ff2856;
    wire __dff_d_ff2857;
    wire __dff_d_ff2858;
    wire __dff_d_ff2859;
    wire __dff_d_ff2860;
    wire __dff_d_ff2861;
    wire __dff_d_ff2862;
    wire __dff_d_ff2863;
    wire __dff_d_ff2864;
    wire __dff_d_ff2865;
    wire __dff_d_ff2866;
    wire __dff_d_ff2867;
    wire __dff_d_ff2868;
    wire __dff_d_ff2869;
    wire __dff_d_ff2870;
    wire __dff_d_ff2871;
    wire n388;
    wire n389;
    wire __dff_d_ff2872;
    wire __dff_d_ff2873;
    wire __dff_d_ff2874;
    wire __dff_d_ff2875;
    wire __dff_d_ff2876;
    wire __dff_d_ff2877;
    wire __dff_d_ff2878;
    wire __dff_d_ff2879;
    wire __dff_d_ff2880;
    wire __dff_d_ff2881;
    wire __dff_d_ff2882;
    wire __dff_d_ff2883;
    wire __dff_d_ff2884;
    wire __dff_d_ff2885;
    wire __dff_d_ff2886;
    wire __dff_d_ff2887;
    wire __dff_d_ff2888;
    wire __dff_d_ff2889;
    wire __dff_d_ff2890;
    wire __dff_d_ff2891;
    wire __dff_d_ff2892;
    wire __dff_d_ff2893;
    wire __dff_d_ff2894;
    wire __dff_d_ff2895;
    wire __dff_d_ff2896;
    wire __dff_d_ff2897;
    wire __dff_d_ff2898;
    wire __dff_d_ff2899;
    wire __dff_d_ff2900;
    wire __dff_d_ff2901;
    wire __dff_d_ff2902;
    wire __dff_d_ff2903;
    wire __dff_d_ff2904;
    wire __dff_d_ff2905;
    wire __dff_d_ff2906;
    wire n493;
    wire n496;
    wire __dff_d_ff2907;
    wire inv_n2;
    wire n500;
    wire __dff_d_ff2908;
    wire n504;
    wire __dff_d_ff2909;
    wire n508;
    wire __dff_d_ff2910;
    wire n512;
    wire __dff_d_ff2911;
    wire n516;
    wire __dff_d_ff2912;
    wire n520;
    wire __dff_d_ff2913;
    wire n524;
    wire __dff_d_ff2914;
    wire n528;
    wire __dff_d_ff2915;
    wire n532;
    wire __dff_d_ff2916;
    wire n536;
    wire __dff_d_ff2917;
    wire n540;
    wire __dff_d_ff2918;
    wire n544;
    wire __dff_d_ff2919;
    wire n548;
    wire __dff_d_ff2920;
    wire n552;
    wire __dff_d_ff2921;
    wire n556;
    wire __dff_d_ff2922;
    wire n560;
    wire __dff_d_ff2923;
    wire n564;
    wire __dff_d_ff2924;
    wire n568;
    wire __dff_d_ff2925;
    wire n572;
    wire __dff_d_ff2926;
    wire n576;
    wire __dff_d_ff2927;
    wire n580;
    wire __dff_d_ff2928;
    wire n584;
    wire __dff_d_ff2929;
    wire n588;
    wire __dff_d_ff2930;
    wire n592;
    wire __dff_d_ff2931;
    wire n596;
    wire __dff_d_ff2932;
    wire n600;
    wire __dff_d_ff2933;
    wire n604;
    wire __dff_d_ff2934;
    wire n608;
    wire __dff_d_ff2935;
    wire n612;
    wire __dff_d_ff2936;
    wire n616;
    wire __dff_d_ff2937;
    wire n620;
    wire __dff_d_ff2938;
    wire __dff_d_ff2939;
    wire n625;
    wire __dff_d_ff2940;
    wire __dff_d_ff2941;
    wire __dff_d_ff2942;
    wire __dff_d_ff2943;
    wire n635;
    wire __dff_d_ff2944;
    wire n639;
    wire __dff_d_ff2945;
    wire n643;
    wire __dff_d_ff2946;
    wire n647;
    wire __dff_d_ff2947;
    wire n651;
    wire __dff_d_ff2948;
    wire n655;
    wire __dff_d_ff2949;
    wire n659;
    wire __dff_d_ff2950;
    wire n663;
    wire __dff_d_ff2951;
    wire n667;
    wire __dff_d_ff2952;
    wire n671;
    wire __dff_d_ff2953;
    wire n675;
    wire __dff_d_ff2954;
    wire n679;
    wire __dff_d_ff2955;
    wire n683;
    wire __dff_d_ff2956;
    wire n687;
    wire __dff_d_ff2957;
    wire n691;
    wire __dff_d_ff2958;
    wire n695;
    wire __dff_d_ff2959;
    wire n699;
    wire __dff_d_ff2960;
    wire n703;
    wire __dff_d_ff2961;
    wire n707;
    wire __dff_d_ff2962;
    wire n711;
    wire __dff_d_ff2963;
    wire n715;
    wire __dff_d_ff2964;
    wire n719;
    wire __dff_d_ff2965;
    wire n723;
    wire __dff_d_ff2966;
    wire n727;
    wire __dff_d_ff2967;
    wire n731;
    wire __dff_d_ff2968;
    wire n735;
    wire __dff_d_ff2969;
    wire n739;
    wire __dff_d_ff2970;
    wire n743;
    wire __dff_d_ff2971;
    wire n747;
    wire __dff_d_ff2972;
    wire n751;
    wire __dff_d_ff2973;
    wire n754;
    wire inv_n172;
    wire n755;
    wire n758;
    wire n759;
    wire __dff_d_ff2975;
    wire n764;
    wire n765;
    wire __dff_d_ff2976;
    wire n769;
    wire n772;
    wire __dff_d_ff2977;
    wire n776;
    wire __dff_d_ff2978;
    wire __dff_d_ff2805;
    wire __dff_d_ff2806;
    wire __dff_d_ff2839;
    wire __dff_d_ff2974;
    wire clone_5;
    wire clone_10;
    wire clone_120;
    wire clone_260;
    wire buf_rst_n_0;
    wire buf_rst_n_1;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(__dff_d_ff21));
    sky130_fd_sc_hd__nor3_1 U0 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .Y(n248)
    );

    sky130_fd_sc_hd__inv_1 U1 (
        .A(cpu_req),
        .Y(inv_n35)
    );

    sky130_fd_sc_hd__inv_1 U2 (
        .A(flush),
        .Y(inv_n69)
    );

    sky130_fd_sc_hd__inv_1 U3 (
        .A(state_0),
        .Y(inv_n70)
    );

    sky130_fd_sc_hd__a31oi_1 U4 (
        .A1(inv_n35),
        .A2(inv_n69),
        .A3(inv_n70),
        .B1(clone_5),
        .Y(n251)
    );

    sky130_fd_sc_hd__a21oi_1 U5 (
        .A1(inv_n35),
        .A2(state_2),
        .B1(flush),
        .Y(n254)
    );

    sky130_fd_sc_hd__nor4_1 U6 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .D(n254),
        .Y(n255)
    );

    sky130_fd_sc_hd__inv_1 U7 (
        .A(latched_index),
        .Y(inv_n207)
    );

    sky130_fd_sc_hd__nand3b_1 U8 (
        .A_N(latched_index),
        .B(mem_ready),
        .C(n248),
        .Y(n290)
    );

    sky130_fd_sc_hd__mux2_1 U9 (
        .A0(mem_rdata_0),
        .A1(data_mem_0_0),
        .S(n291),
        .X(__dff_d_ff2840)
    );

    sky130_fd_sc_hd__mux2_1 U10 (
        .A0(mem_rdata_1),
        .A1(data_mem_0_1),
        .S(n291),
        .X(__dff_d_ff2841)
    );

    sky130_fd_sc_hd__mux2_1 U11 (
        .A0(mem_rdata_2),
        .A1(data_mem_0_2),
        .S(n291),
        .X(__dff_d_ff2842)
    );

    sky130_fd_sc_hd__mux2_1 U12 (
        .A0(mem_rdata_3),
        .A1(data_mem_0_3),
        .S(n291),
        .X(__dff_d_ff2843)
    );

    sky130_fd_sc_hd__mux2_1 U13 (
        .A0(mem_rdata_4),
        .A1(data_mem_0_4),
        .S(n291),
        .X(__dff_d_ff2844)
    );

    sky130_fd_sc_hd__mux2_1 U14 (
        .A0(mem_rdata_5),
        .A1(data_mem_0_5),
        .S(n291),
        .X(__dff_d_ff2845)
    );

    sky130_fd_sc_hd__mux2_1 U15 (
        .A0(mem_rdata_6),
        .A1(data_mem_0_6),
        .S(n291),
        .X(__dff_d_ff2846)
    );

    sky130_fd_sc_hd__mux2_1 U16 (
        .A0(mem_rdata_7),
        .A1(data_mem_0_7),
        .S(n291),
        .X(__dff_d_ff2847)
    );

    sky130_fd_sc_hd__mux2_1 U17 (
        .A0(mem_rdata_8),
        .A1(data_mem_0_8),
        .S(n291),
        .X(__dff_d_ff2848)
    );

    sky130_fd_sc_hd__mux2_1 U18 (
        .A0(mem_rdata_9),
        .A1(data_mem_0_9),
        .S(n291),
        .X(__dff_d_ff2849)
    );

    sky130_fd_sc_hd__mux2_1 U19 (
        .A0(mem_rdata_10),
        .A1(data_mem_0_10),
        .S(n291),
        .X(__dff_d_ff2850)
    );

    sky130_fd_sc_hd__mux2_1 U20 (
        .A0(mem_rdata_11),
        .A1(data_mem_0_11),
        .S(n291),
        .X(__dff_d_ff2851)
    );

    sky130_fd_sc_hd__mux2_1 U21 (
        .A0(mem_rdata_12),
        .A1(data_mem_0_12),
        .S(n291),
        .X(__dff_d_ff2852)
    );

    sky130_fd_sc_hd__mux2_1 U22 (
        .A0(mem_rdata_13),
        .A1(data_mem_0_13),
        .S(n291),
        .X(__dff_d_ff2853)
    );

    sky130_fd_sc_hd__mux2_1 U23 (
        .A0(mem_rdata_14),
        .A1(data_mem_0_14),
        .S(n291),
        .X(__dff_d_ff2854)
    );

    sky130_fd_sc_hd__mux2_1 U24 (
        .A0(mem_rdata_15),
        .A1(data_mem_0_15),
        .S(n291),
        .X(__dff_d_ff2855)
    );

    sky130_fd_sc_hd__mux2_1 U25 (
        .A0(mem_rdata_16),
        .A1(data_mem_0_16),
        .S(n291),
        .X(__dff_d_ff2856)
    );

    sky130_fd_sc_hd__mux2_1 U26 (
        .A0(mem_rdata_17),
        .A1(data_mem_0_17),
        .S(n291),
        .X(__dff_d_ff2857)
    );

    sky130_fd_sc_hd__mux2_1 U27 (
        .A0(mem_rdata_18),
        .A1(data_mem_0_18),
        .S(n291),
        .X(__dff_d_ff2858)
    );

    sky130_fd_sc_hd__mux2_1 U28 (
        .A0(mem_rdata_19),
        .A1(data_mem_0_19),
        .S(n291),
        .X(__dff_d_ff2859)
    );

    sky130_fd_sc_hd__mux2_1 U29 (
        .A0(mem_rdata_20),
        .A1(data_mem_0_20),
        .S(n291),
        .X(__dff_d_ff2860)
    );

    sky130_fd_sc_hd__mux2_1 U30 (
        .A0(mem_rdata_21),
        .A1(data_mem_0_21),
        .S(n291),
        .X(__dff_d_ff2861)
    );

    sky130_fd_sc_hd__mux2_1 U31 (
        .A0(mem_rdata_22),
        .A1(data_mem_0_22),
        .S(n291),
        .X(__dff_d_ff2862)
    );

    sky130_fd_sc_hd__mux2_1 U32 (
        .A0(mem_rdata_23),
        .A1(data_mem_0_23),
        .S(n291),
        .X(__dff_d_ff2863)
    );

    sky130_fd_sc_hd__mux2_1 U33 (
        .A0(mem_rdata_24),
        .A1(data_mem_0_24),
        .S(n291),
        .X(__dff_d_ff2864)
    );

    sky130_fd_sc_hd__mux2_1 U34 (
        .A0(mem_rdata_25),
        .A1(data_mem_0_25),
        .S(n291),
        .X(__dff_d_ff2865)
    );

    sky130_fd_sc_hd__mux2_1 U35 (
        .A0(mem_rdata_26),
        .A1(data_mem_0_26),
        .S(n291),
        .X(__dff_d_ff2866)
    );

    sky130_fd_sc_hd__mux2_1 U36 (
        .A0(mem_rdata_27),
        .A1(data_mem_0_27),
        .S(n291),
        .X(__dff_d_ff2867)
    );

    sky130_fd_sc_hd__mux2_1 U37 (
        .A0(mem_rdata_28),
        .A1(data_mem_0_28),
        .S(n291),
        .X(__dff_d_ff2868)
    );

    sky130_fd_sc_hd__mux2_1 U38 (
        .A0(mem_rdata_29),
        .A1(data_mem_0_29),
        .S(n291),
        .X(__dff_d_ff2869)
    );

    sky130_fd_sc_hd__mux2_1 U39 (
        .A0(mem_rdata_30),
        .A1(data_mem_0_30),
        .S(n291),
        .X(__dff_d_ff2870)
    );

    sky130_fd_sc_hd__mux2_1 U40 (
        .A0(mem_rdata_31),
        .A1(data_mem_0_31),
        .S(n291),
        .X(__dff_d_ff2871)
    );

    sky130_fd_sc_hd__nand3_1 U41 (
        .A(mem_ready),
        .B(latched_index),
        .C(n248),
        .Y(n388)
    );

    sky130_fd_sc_hd__mux2_1 U42 (
        .A0(mem_rdata_0),
        .A1(data_mem_1_0),
        .S(n389),
        .X(__dff_d_ff2872)
    );

    sky130_fd_sc_hd__mux2_1 U43 (
        .A0(mem_rdata_1),
        .A1(data_mem_1_1),
        .S(n389),
        .X(__dff_d_ff2873)
    );

    sky130_fd_sc_hd__mux2_1 U44 (
        .A0(mem_rdata_2),
        .A1(data_mem_1_2),
        .S(n389),
        .X(__dff_d_ff2874)
    );

    sky130_fd_sc_hd__mux2_1 U45 (
        .A0(mem_rdata_3),
        .A1(data_mem_1_3),
        .S(n389),
        .X(__dff_d_ff2875)
    );

    sky130_fd_sc_hd__mux2_1 U46 (
        .A0(mem_rdata_4),
        .A1(data_mem_1_4),
        .S(n389),
        .X(__dff_d_ff2876)
    );

    sky130_fd_sc_hd__mux2_1 U47 (
        .A0(mem_rdata_5),
        .A1(data_mem_1_5),
        .S(n389),
        .X(__dff_d_ff2877)
    );

    sky130_fd_sc_hd__mux2_1 U48 (
        .A0(mem_rdata_6),
        .A1(data_mem_1_6),
        .S(n389),
        .X(__dff_d_ff2878)
    );

    sky130_fd_sc_hd__mux2_1 U49 (
        .A0(mem_rdata_7),
        .A1(data_mem_1_7),
        .S(n389),
        .X(__dff_d_ff2879)
    );

    sky130_fd_sc_hd__mux2_1 U50 (
        .A0(mem_rdata_8),
        .A1(data_mem_1_8),
        .S(n389),
        .X(__dff_d_ff2880)
    );

    sky130_fd_sc_hd__mux2_1 U51 (
        .A0(mem_rdata_9),
        .A1(data_mem_1_9),
        .S(n389),
        .X(__dff_d_ff2881)
    );

    sky130_fd_sc_hd__mux2_1 U52 (
        .A0(mem_rdata_10),
        .A1(data_mem_1_10),
        .S(n389),
        .X(__dff_d_ff2882)
    );

    sky130_fd_sc_hd__mux2_1 U53 (
        .A0(mem_rdata_11),
        .A1(data_mem_1_11),
        .S(n389),
        .X(__dff_d_ff2883)
    );

    sky130_fd_sc_hd__mux2_1 U54 (
        .A0(mem_rdata_12),
        .A1(data_mem_1_12),
        .S(n389),
        .X(__dff_d_ff2884)
    );

    sky130_fd_sc_hd__mux2_1 U55 (
        .A0(mem_rdata_13),
        .A1(data_mem_1_13),
        .S(n389),
        .X(__dff_d_ff2885)
    );

    sky130_fd_sc_hd__mux2_1 U56 (
        .A0(mem_rdata_14),
        .A1(data_mem_1_14),
        .S(n389),
        .X(__dff_d_ff2886)
    );

    sky130_fd_sc_hd__mux2_1 U57 (
        .A0(mem_rdata_15),
        .A1(data_mem_1_15),
        .S(n389),
        .X(__dff_d_ff2887)
    );

    sky130_fd_sc_hd__mux2_1 U58 (
        .A0(mem_rdata_16),
        .A1(data_mem_1_16),
        .S(n389),
        .X(__dff_d_ff2888)
    );

    sky130_fd_sc_hd__mux2_1 U59 (
        .A0(mem_rdata_17),
        .A1(data_mem_1_17),
        .S(n389),
        .X(__dff_d_ff2889)
    );

    sky130_fd_sc_hd__mux2_1 U60 (
        .A0(mem_rdata_18),
        .A1(data_mem_1_18),
        .S(n389),
        .X(__dff_d_ff2890)
    );

    sky130_fd_sc_hd__mux2_1 U61 (
        .A0(mem_rdata_19),
        .A1(data_mem_1_19),
        .S(n389),
        .X(__dff_d_ff2891)
    );

    sky130_fd_sc_hd__mux2_1 U62 (
        .A0(mem_rdata_20),
        .A1(data_mem_1_20),
        .S(n389),
        .X(__dff_d_ff2892)
    );

    sky130_fd_sc_hd__mux2_1 U63 (
        .A0(mem_rdata_21),
        .A1(data_mem_1_21),
        .S(n389),
        .X(__dff_d_ff2893)
    );

    sky130_fd_sc_hd__mux2_1 U64 (
        .A0(mem_rdata_22),
        .A1(data_mem_1_22),
        .S(n389),
        .X(__dff_d_ff2894)
    );

    sky130_fd_sc_hd__mux2_1 U65 (
        .A0(mem_rdata_23),
        .A1(data_mem_1_23),
        .S(n389),
        .X(__dff_d_ff2895)
    );

    sky130_fd_sc_hd__mux2_1 U66 (
        .A0(mem_rdata_24),
        .A1(data_mem_1_24),
        .S(n389),
        .X(__dff_d_ff2896)
    );

    sky130_fd_sc_hd__mux2_1 U67 (
        .A0(mem_rdata_25),
        .A1(data_mem_1_25),
        .S(n389),
        .X(__dff_d_ff2897)
    );

    sky130_fd_sc_hd__mux2_1 U68 (
        .A0(mem_rdata_26),
        .A1(data_mem_1_26),
        .S(n389),
        .X(__dff_d_ff2898)
    );

    sky130_fd_sc_hd__mux2_1 U69 (
        .A0(mem_rdata_27),
        .A1(data_mem_1_27),
        .S(n389),
        .X(__dff_d_ff2899)
    );

    sky130_fd_sc_hd__mux2_1 U70 (
        .A0(mem_rdata_28),
        .A1(data_mem_1_28),
        .S(n389),
        .X(__dff_d_ff2900)
    );

    sky130_fd_sc_hd__mux2_1 U71 (
        .A0(mem_rdata_29),
        .A1(data_mem_1_29),
        .S(n389),
        .X(__dff_d_ff2901)
    );

    sky130_fd_sc_hd__mux2_1 U72 (
        .A0(mem_rdata_30),
        .A1(data_mem_1_30),
        .S(n389),
        .X(__dff_d_ff2902)
    );

    sky130_fd_sc_hd__mux2_1 U73 (
        .A0(mem_rdata_31),
        .A1(data_mem_1_31),
        .S(n389),
        .X(__dff_d_ff2903)
    );

    sky130_fd_sc_hd__nand3b_1 U74 (
        .A_N(flush),
        .B(cpu_req),
        .C(n248),
        .Y(n493)
    );

    sky130_fd_sc_hd__mux2_1 U75 (
        .A0(cpu_addr_0),
        .A1(latched_addr_0),
        .S(n493),
        .X(n496)
    );

    sky130_fd_sc_hd__nor2b_1 U76 (
        .A(n496),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff2907)
    );

    sky130_fd_sc_hd__o21a_1 U77 (
        .A1(cpu_addr_1),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n500)
    );

    sky130_fd_sc_hd__o21a_1 U78 (
        .A1(latched_addr_1),
        .A2(n493),
        .B1(n500),
        .X(__dff_d_ff2908)
    );

    sky130_fd_sc_hd__o21a_1 U79 (
        .A1(cpu_addr_2),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n504)
    );

    sky130_fd_sc_hd__o21a_1 U80 (
        .A1(latched_addr_2),
        .A2(n493),
        .B1(n504),
        .X(__dff_d_ff2909)
    );

    sky130_fd_sc_hd__o21a_1 U81 (
        .A1(cpu_addr_3),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n508)
    );

    sky130_fd_sc_hd__o21a_1 U82 (
        .A1(latched_addr_3),
        .A2(n493),
        .B1(n508),
        .X(__dff_d_ff2910)
    );

    sky130_fd_sc_hd__o21a_1 U83 (
        .A1(cpu_addr_4),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n512)
    );

    sky130_fd_sc_hd__o21a_1 U84 (
        .A1(latched_addr_4),
        .A2(n493),
        .B1(n512),
        .X(__dff_d_ff2911)
    );

    sky130_fd_sc_hd__o21a_1 U85 (
        .A1(cpu_addr_5),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n516)
    );

    sky130_fd_sc_hd__o21a_1 U86 (
        .A1(latched_addr_5),
        .A2(n493),
        .B1(n516),
        .X(__dff_d_ff2912)
    );

    sky130_fd_sc_hd__o21a_1 U87 (
        .A1(cpu_addr_6),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n520)
    );

    sky130_fd_sc_hd__o21a_1 U88 (
        .A1(latched_addr_6),
        .A2(n493),
        .B1(n520),
        .X(__dff_d_ff2913)
    );

    sky130_fd_sc_hd__o21a_1 U89 (
        .A1(cpu_addr_7),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n524)
    );

    sky130_fd_sc_hd__o21a_1 U90 (
        .A1(latched_addr_7),
        .A2(n493),
        .B1(n524),
        .X(__dff_d_ff2914)
    );

    sky130_fd_sc_hd__o21a_1 U91 (
        .A1(cpu_addr_8),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n528)
    );

    sky130_fd_sc_hd__o21a_1 U92 (
        .A1(latched_addr_8),
        .A2(n493),
        .B1(n528),
        .X(__dff_d_ff2915)
    );

    sky130_fd_sc_hd__o21a_1 U93 (
        .A1(cpu_addr_9),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n532)
    );

    sky130_fd_sc_hd__o21a_1 U94 (
        .A1(latched_addr_9),
        .A2(n493),
        .B1(n532),
        .X(__dff_d_ff2916)
    );

    sky130_fd_sc_hd__o21a_1 U95 (
        .A1(cpu_addr_10),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n536)
    );

    sky130_fd_sc_hd__o21a_1 U96 (
        .A1(latched_addr_10),
        .A2(n493),
        .B1(n536),
        .X(__dff_d_ff2917)
    );

    sky130_fd_sc_hd__o21a_1 U97 (
        .A1(cpu_addr_11),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n540)
    );

    sky130_fd_sc_hd__o21a_1 U98 (
        .A1(latched_addr_11),
        .A2(n493),
        .B1(n540),
        .X(__dff_d_ff2918)
    );

    sky130_fd_sc_hd__o21a_1 U99 (
        .A1(cpu_addr_12),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n544)
    );

    sky130_fd_sc_hd__o21a_1 U100 (
        .A1(latched_addr_12),
        .A2(n493),
        .B1(n544),
        .X(__dff_d_ff2919)
    );

    sky130_fd_sc_hd__o21a_1 U101 (
        .A1(cpu_addr_13),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n548)
    );

    sky130_fd_sc_hd__o21a_1 U102 (
        .A1(latched_addr_13),
        .A2(n493),
        .B1(n548),
        .X(__dff_d_ff2920)
    );

    sky130_fd_sc_hd__o21a_1 U103 (
        .A1(cpu_addr_14),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n552)
    );

    sky130_fd_sc_hd__o21a_1 U104 (
        .A1(latched_addr_14),
        .A2(n493),
        .B1(n552),
        .X(__dff_d_ff2921)
    );

    sky130_fd_sc_hd__o21a_1 U105 (
        .A1(cpu_addr_15),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n556)
    );

    sky130_fd_sc_hd__o21a_1 U106 (
        .A1(latched_addr_15),
        .A2(n493),
        .B1(n556),
        .X(__dff_d_ff2922)
    );

    sky130_fd_sc_hd__o21a_1 U107 (
        .A1(cpu_addr_16),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n560)
    );

    sky130_fd_sc_hd__o21a_1 U108 (
        .A1(latched_addr_16),
        .A2(n493),
        .B1(n560),
        .X(__dff_d_ff2923)
    );

    sky130_fd_sc_hd__o21a_1 U109 (
        .A1(cpu_addr_17),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n564)
    );

    sky130_fd_sc_hd__o21a_1 U110 (
        .A1(latched_addr_17),
        .A2(n493),
        .B1(n564),
        .X(__dff_d_ff2924)
    );

    sky130_fd_sc_hd__o21a_1 U111 (
        .A1(cpu_addr_18),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n568)
    );

    sky130_fd_sc_hd__o21a_1 U112 (
        .A1(latched_addr_18),
        .A2(n493),
        .B1(n568),
        .X(__dff_d_ff2925)
    );

    sky130_fd_sc_hd__o21a_1 U113 (
        .A1(cpu_addr_19),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n572)
    );

    sky130_fd_sc_hd__o21a_1 U114 (
        .A1(latched_addr_19),
        .A2(n493),
        .B1(n572),
        .X(__dff_d_ff2926)
    );

    sky130_fd_sc_hd__o21a_1 U115 (
        .A1(cpu_addr_20),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n576)
    );

    sky130_fd_sc_hd__o21a_1 U116 (
        .A1(latched_addr_20),
        .A2(n493),
        .B1(n576),
        .X(__dff_d_ff2927)
    );

    sky130_fd_sc_hd__o21a_1 U117 (
        .A1(cpu_addr_21),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n580)
    );

    sky130_fd_sc_hd__o21a_1 U118 (
        .A1(latched_addr_21),
        .A2(n493),
        .B1(n580),
        .X(__dff_d_ff2928)
    );

    sky130_fd_sc_hd__o21a_1 U119 (
        .A1(cpu_addr_22),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n584)
    );

    sky130_fd_sc_hd__o21a_1 U120 (
        .A1(latched_addr_22),
        .A2(n493),
        .B1(n584),
        .X(__dff_d_ff2929)
    );

    sky130_fd_sc_hd__o21a_1 U121 (
        .A1(cpu_addr_23),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n588)
    );

    sky130_fd_sc_hd__o21a_1 U122 (
        .A1(latched_addr_23),
        .A2(n493),
        .B1(n588),
        .X(__dff_d_ff2930)
    );

    sky130_fd_sc_hd__o21a_1 U123 (
        .A1(cpu_addr_24),
        .A2(clone_120),
        .B1(buf_rst_n_0),
        .X(n592)
    );

    sky130_fd_sc_hd__o21a_1 U124 (
        .A1(latched_addr_24),
        .A2(n493),
        .B1(n592),
        .X(__dff_d_ff2931)
    );

    sky130_fd_sc_hd__o21a_1 U125 (
        .A1(cpu_addr_25),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n596)
    );

    sky130_fd_sc_hd__o21a_1 U126 (
        .A1(latched_addr_25),
        .A2(n493),
        .B1(n596),
        .X(__dff_d_ff2932)
    );

    sky130_fd_sc_hd__o21a_1 U127 (
        .A1(cpu_addr_26),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n600)
    );

    sky130_fd_sc_hd__o21a_1 U128 (
        .A1(latched_addr_26),
        .A2(n493),
        .B1(n600),
        .X(__dff_d_ff2933)
    );

    sky130_fd_sc_hd__o21a_1 U129 (
        .A1(cpu_addr_27),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n604)
    );

    sky130_fd_sc_hd__o21a_1 U130 (
        .A1(latched_addr_27),
        .A2(n493),
        .B1(n604),
        .X(__dff_d_ff2934)
    );

    sky130_fd_sc_hd__o21a_1 U131 (
        .A1(cpu_addr_28),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n608)
    );

    sky130_fd_sc_hd__o21a_1 U132 (
        .A1(latched_addr_28),
        .A2(n493),
        .B1(n608),
        .X(__dff_d_ff2935)
    );

    sky130_fd_sc_hd__o21a_1 U133 (
        .A1(cpu_addr_29),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n612)
    );

    sky130_fd_sc_hd__o21a_1 U134 (
        .A1(latched_addr_29),
        .A2(n493),
        .B1(n612),
        .X(__dff_d_ff2936)
    );

    sky130_fd_sc_hd__o21a_1 U135 (
        .A1(cpu_addr_30),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n616)
    );

    sky130_fd_sc_hd__o21a_1 U136 (
        .A1(latched_addr_30),
        .A2(n493),
        .B1(n616),
        .X(__dff_d_ff2937)
    );

    sky130_fd_sc_hd__o21a_1 U137 (
        .A1(cpu_addr_31),
        .A2(clone_120),
        .B1(buf_rst_n_1),
        .X(n620)
    );

    sky130_fd_sc_hd__o21a_1 U138 (
        .A1(latched_addr_31),
        .A2(n493),
        .B1(n620),
        .X(__dff_d_ff2938)
    );

    sky130_fd_sc_hd__nand3_1 U139 (
        .A(buf_rst_n_1),
        .B(latched_index),
        .C(clone_120),
        .Y(__dff_d_ff2939)
    );

    sky130_fd_sc_hd__mux2_1 U140 (
        .A0(cpu_addr_0),
        .A1(latched_tag),
        .S(n493),
        .X(n625)
    );

    sky130_fd_sc_hd__nor2b_1 U141 (
        .A(n625),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff2940)
    );

    sky130_fd_sc_hd__nand3_1 U142 (
        .A(buf_rst_n_1),
        .B(latched_word_off),
        .C(clone_120),
        .Y(__dff_d_ff2941)
    );

    sky130_fd_sc_hd__nand3_1 U143 (
        .A(buf_rst_n_1),
        .B(mem_addr_0),
        .C(clone_5),
        .Y(__dff_d_ff2942)
    );

    sky130_fd_sc_hd__nand3_1 U144 (
        .A(buf_rst_n_1),
        .B(mem_addr_1),
        .C(clone_5),
        .Y(__dff_d_ff2943)
    );

    sky130_fd_sc_hd__o21a_1 U145 (
        .A1(mem_addr_2),
        .A2(n248),
        .B1(buf_rst_n_1),
        .X(n635)
    );

    sky130_fd_sc_hd__o21a_1 U146 (
        .A1(latched_addr_31),
        .A2(clone_5),
        .B1(n635),
        .X(__dff_d_ff2944)
    );

    sky130_fd_sc_hd__o21a_1 U147 (
        .A1(latched_addr_30),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n639)
    );

    sky130_fd_sc_hd__o21a_1 U148 (
        .A1(mem_addr_3),
        .A2(n248),
        .B1(n639),
        .X(__dff_d_ff2945)
    );

    sky130_fd_sc_hd__o21a_1 U149 (
        .A1(latched_addr_29),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n643)
    );

    sky130_fd_sc_hd__o21a_1 U150 (
        .A1(mem_addr_4),
        .A2(n248),
        .B1(n643),
        .X(__dff_d_ff2946)
    );

    sky130_fd_sc_hd__o21a_1 U151 (
        .A1(latched_addr_28),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n647)
    );

    sky130_fd_sc_hd__o21a_1 U152 (
        .A1(mem_addr_5),
        .A2(n248),
        .B1(n647),
        .X(__dff_d_ff2947)
    );

    sky130_fd_sc_hd__o21a_1 U153 (
        .A1(latched_addr_27),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n651)
    );

    sky130_fd_sc_hd__o21a_1 U154 (
        .A1(mem_addr_6),
        .A2(n248),
        .B1(n651),
        .X(__dff_d_ff2948)
    );

    sky130_fd_sc_hd__o21a_1 U155 (
        .A1(latched_addr_26),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n655)
    );

    sky130_fd_sc_hd__o21a_1 U156 (
        .A1(mem_addr_7),
        .A2(n248),
        .B1(n655),
        .X(__dff_d_ff2949)
    );

    sky130_fd_sc_hd__o21a_1 U157 (
        .A1(latched_addr_25),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n659)
    );

    sky130_fd_sc_hd__o21a_1 U158 (
        .A1(mem_addr_8),
        .A2(n248),
        .B1(n659),
        .X(__dff_d_ff2950)
    );

    sky130_fd_sc_hd__o21a_1 U159 (
        .A1(latched_addr_24),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n663)
    );

    sky130_fd_sc_hd__o21a_1 U160 (
        .A1(mem_addr_9),
        .A2(n248),
        .B1(n663),
        .X(__dff_d_ff2951)
    );

    sky130_fd_sc_hd__o21a_1 U161 (
        .A1(latched_addr_23),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n667)
    );

    sky130_fd_sc_hd__o21a_1 U162 (
        .A1(mem_addr_10),
        .A2(n248),
        .B1(n667),
        .X(__dff_d_ff2952)
    );

    sky130_fd_sc_hd__o21a_1 U163 (
        .A1(latched_addr_22),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n671)
    );

    sky130_fd_sc_hd__o21a_1 U164 (
        .A1(mem_addr_11),
        .A2(n248),
        .B1(n671),
        .X(__dff_d_ff2953)
    );

    sky130_fd_sc_hd__o21a_1 U165 (
        .A1(latched_addr_21),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n675)
    );

    sky130_fd_sc_hd__o21a_1 U166 (
        .A1(mem_addr_12),
        .A2(n248),
        .B1(n675),
        .X(__dff_d_ff2954)
    );

    sky130_fd_sc_hd__o21a_1 U167 (
        .A1(latched_addr_20),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n679)
    );

    sky130_fd_sc_hd__o21a_1 U168 (
        .A1(mem_addr_13),
        .A2(n248),
        .B1(n679),
        .X(__dff_d_ff2955)
    );

    sky130_fd_sc_hd__o21a_1 U169 (
        .A1(latched_addr_19),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n683)
    );

    sky130_fd_sc_hd__o21a_1 U170 (
        .A1(mem_addr_14),
        .A2(n248),
        .B1(n683),
        .X(__dff_d_ff2956)
    );

    sky130_fd_sc_hd__o21a_1 U171 (
        .A1(latched_addr_18),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n687)
    );

    sky130_fd_sc_hd__o21a_1 U172 (
        .A1(mem_addr_15),
        .A2(n248),
        .B1(n687),
        .X(__dff_d_ff2957)
    );

    sky130_fd_sc_hd__o21a_1 U173 (
        .A1(latched_addr_17),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n691)
    );

    sky130_fd_sc_hd__o21a_1 U174 (
        .A1(mem_addr_16),
        .A2(n248),
        .B1(n691),
        .X(__dff_d_ff2958)
    );

    sky130_fd_sc_hd__o21a_1 U175 (
        .A1(latched_addr_16),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n695)
    );

    sky130_fd_sc_hd__o21a_1 U176 (
        .A1(mem_addr_17),
        .A2(n248),
        .B1(n695),
        .X(__dff_d_ff2959)
    );

    sky130_fd_sc_hd__o21a_1 U177 (
        .A1(latched_addr_15),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n699)
    );

    sky130_fd_sc_hd__o21a_1 U178 (
        .A1(mem_addr_18),
        .A2(n248),
        .B1(n699),
        .X(__dff_d_ff2960)
    );

    sky130_fd_sc_hd__o21a_1 U179 (
        .A1(latched_addr_14),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n703)
    );

    sky130_fd_sc_hd__o21a_1 U180 (
        .A1(mem_addr_19),
        .A2(n248),
        .B1(n703),
        .X(__dff_d_ff2961)
    );

    sky130_fd_sc_hd__o21a_1 U181 (
        .A1(latched_addr_13),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n707)
    );

    sky130_fd_sc_hd__o21a_1 U182 (
        .A1(mem_addr_20),
        .A2(n248),
        .B1(n707),
        .X(__dff_d_ff2962)
    );

    sky130_fd_sc_hd__o21a_1 U183 (
        .A1(latched_addr_12),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n711)
    );

    sky130_fd_sc_hd__o21a_1 U184 (
        .A1(mem_addr_21),
        .A2(n248),
        .B1(n711),
        .X(__dff_d_ff2963)
    );

    sky130_fd_sc_hd__o21a_1 U185 (
        .A1(latched_addr_11),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n715)
    );

    sky130_fd_sc_hd__o21a_1 U186 (
        .A1(mem_addr_22),
        .A2(n248),
        .B1(n715),
        .X(__dff_d_ff2964)
    );

    sky130_fd_sc_hd__o21a_1 U187 (
        .A1(latched_addr_10),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n719)
    );

    sky130_fd_sc_hd__o21a_1 U188 (
        .A1(mem_addr_23),
        .A2(n248),
        .B1(n719),
        .X(__dff_d_ff2965)
    );

    sky130_fd_sc_hd__o21a_1 U189 (
        .A1(latched_addr_9),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n723)
    );

    sky130_fd_sc_hd__o21a_1 U190 (
        .A1(mem_addr_24),
        .A2(n248),
        .B1(n723),
        .X(__dff_d_ff2966)
    );

    sky130_fd_sc_hd__o21a_1 U191 (
        .A1(latched_addr_8),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n727)
    );

    sky130_fd_sc_hd__o21a_1 U192 (
        .A1(mem_addr_25),
        .A2(n248),
        .B1(n727),
        .X(__dff_d_ff2967)
    );

    sky130_fd_sc_hd__o21a_1 U193 (
        .A1(latched_addr_7),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n731)
    );

    sky130_fd_sc_hd__o21a_1 U194 (
        .A1(mem_addr_26),
        .A2(n248),
        .B1(n731),
        .X(__dff_d_ff2968)
    );

    sky130_fd_sc_hd__o21a_1 U195 (
        .A1(latched_addr_6),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n735)
    );

    sky130_fd_sc_hd__o21a_1 U196 (
        .A1(mem_addr_27),
        .A2(n248),
        .B1(n735),
        .X(__dff_d_ff2969)
    );

    sky130_fd_sc_hd__o21a_1 U197 (
        .A1(latched_addr_5),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n739)
    );

    sky130_fd_sc_hd__o21a_1 U198 (
        .A1(mem_addr_28),
        .A2(n248),
        .B1(n739),
        .X(__dff_d_ff2970)
    );

    sky130_fd_sc_hd__o21a_1 U199 (
        .A1(latched_addr_4),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n743)
    );

    sky130_fd_sc_hd__o21a_1 U200 (
        .A1(mem_addr_29),
        .A2(n248),
        .B1(n743),
        .X(__dff_d_ff2971)
    );

    sky130_fd_sc_hd__o21a_1 U201 (
        .A1(latched_addr_3),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n747)
    );

    sky130_fd_sc_hd__o21a_1 U202 (
        .A1(mem_addr_30),
        .A2(n248),
        .B1(n747),
        .X(__dff_d_ff2972)
    );

    sky130_fd_sc_hd__o21a_1 U203 (
        .A1(latched_addr_2),
        .A2(clone_5),
        .B1(buf_rst_n_1),
        .X(n751)
    );

    sky130_fd_sc_hd__o21a_1 U204 (
        .A1(mem_addr_31),
        .A2(n248),
        .B1(n751),
        .X(__dff_d_ff2973)
    );

    sky130_fd_sc_hd__inv_1 U205 (
        .A(fill_word_cnt),
        .Y(inv_n172)
    );

    sky130_fd_sc_hd__nand3b_1 U206 (
        .A_N(fill_word_cnt),
        .B(mem_ready),
        .C(n248),
        .Y(n754)
    );

    sky130_fd_sc_hd__nand4_1 U207 (
        .A(mem_ready),
        .B(inv_n172),
        .C(latched_tag),
        .D(n248),
        .Y(n755)
    );

    sky130_fd_sc_hd__a22oi_1 U208 (
        .A1(inv_n207),
        .A2(n755),
        .B1(tag_mem_0),
        .B2(n754),
        .Y(n758)
    );

    sky130_fd_sc_hd__nor2b_1 U209 (
        .A(n758),
        .B_N(buf_rst_n_0),
        .Y(n759)
    );

    sky130_fd_sc_hd__a21oi_1 U210 (
        .A1(inv_n2),
        .A2(tag_mem_0),
        .B1(n759),
        .Y(__dff_d_ff2975)
    );

    sky130_fd_sc_hd__a22oi_1 U211 (
        .A1(latched_index),
        .A2(n755),
        .B1(tag_mem_1),
        .B2(n754),
        .Y(n764)
    );

    sky130_fd_sc_hd__nor2b_1 U212 (
        .A(n764),
        .B_N(buf_rst_n_0),
        .Y(n765)
    );

    sky130_fd_sc_hd__a21oi_1 U213 (
        .A1(inv_n2),
        .A2(tag_mem_1),
        .B1(n765),
        .Y(__dff_d_ff2976)
    );

    sky130_fd_sc_hd__nand3b_1 U214 (
        .A_N(fill_word_cnt),
        .B(buf_rst_n_1),
        .C(n388),
        .Y(n769)
    );

    sky130_fd_sc_hd__nand3b_1 U215 (
        .A_N(fill_word_cnt),
        .B(buf_rst_n_1),
        .C(n290),
        .Y(n772)
    );

    sky130_fd_sc_hd__mux2_1 U216 (
        .A0(clone_260),
        .A1(n772),
        .S(valid_0),
        .X(__dff_d_ff2977)
    );

    sky130_fd_sc_hd__nor2_1 U217 (
        .A(valid_1),
        .B(n769),
        .Y(n776)
    );

    sky130_fd_sc_hd__a21oi_1 U218 (
        .A1(valid_1),
        .A2(n772),
        .B1(n776),
        .Y(__dff_d_ff2978)
    );

    sky130_fd_sc_hd__buf_1 U219 (
        .A(__dff_d_ff21),
        .X(__dff_d_ff2805)
    );

    sky130_fd_sc_hd__buf_1 U220 (
        .A(__dff_d_ff21),
        .X(__dff_d_ff2806)
    );

    sky130_fd_sc_hd__buf_1 U221 (
        .A(__dff_d_ff21),
        .X(__dff_d_ff2839)
    );

    sky130_fd_sc_hd__buf_1 U222 (
        .A(__dff_d_ff21),
        .X(__dff_d_ff2974)
    );

    sky130_fd_sc_hd__or3_1 U223 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .X(clone_5)
    );

    sky130_fd_sc_hd__and4_1 U224 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .D(n254),
        .X(clone_10)
    );

    sky130_fd_sc_hd__and3b_1 U225 (
        .A_N(flush),
        .B(cpu_req),
        .C(n248),
        .X(clone_120)
    );

    sky130_fd_sc_hd__and3b_1 U226 (
        .A_N(fill_word_cnt),
        .B(buf_rst_n_1),
        .C(n388),
        .X(clone_260)
    );

    sky130_fd_sc_hd__dfrtp_1 U227 (
        .D(__dff_d_ff21),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(state_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U228 (
        .D(__dff_d_ff2805),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cache_hit)
    );

    sky130_fd_sc_hd__dfrtp_1 U229 (
        .D(__dff_d_ff2806),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cache_miss)
    );

    sky130_fd_sc_hd__dfrtp_1 U230 (
        .D(__dff_d_ff2839),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cpu_ready)
    );

    sky130_fd_sc_hd__dfrtp_1 U231 (
        .D(__dff_d_ff2840),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U232 (
        .D(__dff_d_ff2841),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U233 (
        .D(__dff_d_ff2842),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U234 (
        .D(__dff_d_ff2843),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U235 (
        .D(__dff_d_ff2844),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U236 (
        .D(__dff_d_ff2845),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U237 (
        .D(__dff_d_ff2846),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U238 (
        .D(__dff_d_ff2847),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U239 (
        .D(__dff_d_ff2848),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U240 (
        .D(__dff_d_ff2849),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U241 (
        .D(__dff_d_ff2850),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U242 (
        .D(__dff_d_ff2851),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U243 (
        .D(__dff_d_ff2852),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U244 (
        .D(__dff_d_ff2853),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U245 (
        .D(__dff_d_ff2854),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U246 (
        .D(__dff_d_ff2855),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U247 (
        .D(__dff_d_ff2856),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U248 (
        .D(__dff_d_ff2857),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U249 (
        .D(__dff_d_ff2858),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U250 (
        .D(__dff_d_ff2859),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U251 (
        .D(__dff_d_ff2860),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U252 (
        .D(__dff_d_ff2861),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U253 (
        .D(__dff_d_ff2862),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U254 (
        .D(__dff_d_ff2863),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U255 (
        .D(__dff_d_ff2864),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U256 (
        .D(__dff_d_ff2865),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U257 (
        .D(__dff_d_ff2866),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U258 (
        .D(__dff_d_ff2867),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U259 (
        .D(__dff_d_ff2868),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U260 (
        .D(__dff_d_ff2869),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U261 (
        .D(__dff_d_ff2870),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U262 (
        .D(__dff_d_ff2871),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_0_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U263 (
        .D(__dff_d_ff2872),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U264 (
        .D(__dff_d_ff2873),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U265 (
        .D(__dff_d_ff2874),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U266 (
        .D(__dff_d_ff2875),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U267 (
        .D(__dff_d_ff2876),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U268 (
        .D(__dff_d_ff2877),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U269 (
        .D(__dff_d_ff2878),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U270 (
        .D(__dff_d_ff2879),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U271 (
        .D(__dff_d_ff2880),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U272 (
        .D(__dff_d_ff2881),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U273 (
        .D(__dff_d_ff2882),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U274 (
        .D(__dff_d_ff2883),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U275 (
        .D(__dff_d_ff2884),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U276 (
        .D(__dff_d_ff2885),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U277 (
        .D(__dff_d_ff2886),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U278 (
        .D(__dff_d_ff2887),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U279 (
        .D(__dff_d_ff2888),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U280 (
        .D(__dff_d_ff2889),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U281 (
        .D(__dff_d_ff2890),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U282 (
        .D(__dff_d_ff2891),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U283 (
        .D(__dff_d_ff2892),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U284 (
        .D(__dff_d_ff2893),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U285 (
        .D(__dff_d_ff2894),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U286 (
        .D(__dff_d_ff2895),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U287 (
        .D(__dff_d_ff2896),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U288 (
        .D(__dff_d_ff2897),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U289 (
        .D(__dff_d_ff2898),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U290 (
        .D(__dff_d_ff2899),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U291 (
        .D(__dff_d_ff2900),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U292 (
        .D(__dff_d_ff2901),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U293 (
        .D(__dff_d_ff2902),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U294 (
        .D(__dff_d_ff2903),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(data_mem_1_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U295 (
        .D(__dff_d_ff2907),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U296 (
        .D(__dff_d_ff2908),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U297 (
        .D(__dff_d_ff2909),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U298 (
        .D(__dff_d_ff2910),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U299 (
        .D(__dff_d_ff2911),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U300 (
        .D(__dff_d_ff2912),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U301 (
        .D(__dff_d_ff2913),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U302 (
        .D(__dff_d_ff2914),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U303 (
        .D(__dff_d_ff2915),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U304 (
        .D(__dff_d_ff2916),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U305 (
        .D(__dff_d_ff2917),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U306 (
        .D(__dff_d_ff2918),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U307 (
        .D(__dff_d_ff2919),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U308 (
        .D(__dff_d_ff2920),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U309 (
        .D(__dff_d_ff2921),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U310 (
        .D(__dff_d_ff2922),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U311 (
        .D(__dff_d_ff2923),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U312 (
        .D(__dff_d_ff2924),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U313 (
        .D(__dff_d_ff2925),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U314 (
        .D(__dff_d_ff2926),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U315 (
        .D(__dff_d_ff2927),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U316 (
        .D(__dff_d_ff2928),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U317 (
        .D(__dff_d_ff2929),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U318 (
        .D(__dff_d_ff2930),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U319 (
        .D(__dff_d_ff2931),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U320 (
        .D(__dff_d_ff2932),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U321 (
        .D(__dff_d_ff2933),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U322 (
        .D(__dff_d_ff2934),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U323 (
        .D(__dff_d_ff2935),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U324 (
        .D(__dff_d_ff2936),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U325 (
        .D(__dff_d_ff2937),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U326 (
        .D(__dff_d_ff2938),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_addr_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U327 (
        .D(__dff_d_ff2939),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_index)
    );

    sky130_fd_sc_hd__dfrtp_1 U328 (
        .D(__dff_d_ff2940),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_tag)
    );

    sky130_fd_sc_hd__dfrtp_1 U329 (
        .D(__dff_d_ff2941),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(latched_word_off)
    );

    sky130_fd_sc_hd__dfrtp_1 U330 (
        .D(__dff_d_ff2942),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U331 (
        .D(__dff_d_ff2943),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U332 (
        .D(__dff_d_ff2944),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U333 (
        .D(__dff_d_ff2945),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U334 (
        .D(__dff_d_ff2946),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U335 (
        .D(__dff_d_ff2947),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U336 (
        .D(__dff_d_ff2948),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U337 (
        .D(__dff_d_ff2949),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U338 (
        .D(__dff_d_ff2950),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U339 (
        .D(__dff_d_ff2951),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U340 (
        .D(__dff_d_ff2952),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U341 (
        .D(__dff_d_ff2953),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U342 (
        .D(__dff_d_ff2954),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U343 (
        .D(__dff_d_ff2955),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U344 (
        .D(__dff_d_ff2956),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U345 (
        .D(__dff_d_ff2957),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U346 (
        .D(__dff_d_ff2958),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U347 (
        .D(__dff_d_ff2959),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U348 (
        .D(__dff_d_ff2960),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U349 (
        .D(__dff_d_ff2961),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U350 (
        .D(__dff_d_ff2962),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U351 (
        .D(__dff_d_ff2963),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U352 (
        .D(__dff_d_ff2964),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U353 (
        .D(__dff_d_ff2965),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U354 (
        .D(__dff_d_ff2966),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U355 (
        .D(__dff_d_ff2967),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U356 (
        .D(__dff_d_ff2968),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U357 (
        .D(__dff_d_ff2969),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U358 (
        .D(__dff_d_ff2970),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U359 (
        .D(__dff_d_ff2971),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U360 (
        .D(__dff_d_ff2972),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U361 (
        .D(__dff_d_ff2973),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_addr_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U362 (
        .D(__dff_d_ff2974),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_req)
    );

    sky130_fd_sc_hd__dfrtp_1 U363 (
        .D(__dff_d_ff2975),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(tag_mem_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U364 (
        .D(__dff_d_ff2976),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(tag_mem_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U365 (
        .D(__dff_d_ff2977),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(valid_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U366 (
        .D(__dff_d_ff2978),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(valid_1)
    );

    sky130_fd_sc_hd__conb_1 UTIE_0 (.LO(buf_rst_n_0));
    sky130_fd_sc_hd__conb_1 UTIE_1 (.LO(buf_rst_n_1));
    sky130_fd_sc_hd__conb_1 UTIE_2 (.LO(fill_word_cnt));
    sky130_fd_sc_hd__conb_1 UTIE_3 (.LO(inv_n2));
    sky130_fd_sc_hd__conb_1 UTIE_4 (.LO(n291));
    sky130_fd_sc_hd__conb_1 UTIE_5 (.LO(n389));
    sky130_fd_sc_hd__conb_1 UTIE_6 (.LO(state_0));
    sky130_fd_sc_hd__conb_1 UTIE_7 (.LO(state_2));
endmodule
