// Generated by My Own Flow — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module pmu (
    input clk,
    input rst_n,
    input s_axi_awaddr_0,
    input s_axi_awaddr_1,
    input s_axi_awaddr_2,
    input s_axi_awaddr_3,
    input s_axi_awaddr_4,
    input s_axi_awaddr_5,
    input s_axi_awaddr_6,
    input s_axi_awaddr_7,
    input s_axi_awaddr_8,
    input s_axi_awaddr_9,
    input s_axi_awaddr_10,
    input s_axi_awaddr_11,
    input s_axi_awaddr_12,
    input s_axi_awaddr_13,
    input s_axi_awaddr_14,
    input s_axi_awaddr_15,
    input s_axi_awaddr_16,
    input s_axi_awaddr_17,
    input s_axi_awaddr_18,
    input s_axi_awaddr_19,
    input s_axi_awaddr_20,
    input s_axi_awaddr_21,
    input s_axi_awaddr_22,
    input s_axi_awaddr_23,
    input s_axi_awaddr_24,
    input s_axi_awaddr_25,
    input s_axi_awaddr_26,
    input s_axi_awaddr_27,
    input s_axi_awaddr_28,
    input s_axi_awaddr_29,
    input s_axi_awaddr_30,
    input s_axi_awaddr_31,
    input s_axi_awvalid,
    input s_axi_wdata_0,
    input s_axi_wdata_1,
    input s_axi_wdata_2,
    input s_axi_wdata_3,
    input s_axi_wdata_4,
    input s_axi_wdata_5,
    input s_axi_wdata_6,
    input s_axi_wdata_7,
    input s_axi_wdata_8,
    input s_axi_wdata_9,
    input s_axi_wdata_10,
    input s_axi_wdata_11,
    input s_axi_wdata_12,
    input s_axi_wdata_13,
    input s_axi_wdata_14,
    input s_axi_wdata_15,
    input s_axi_wdata_16,
    input s_axi_wdata_17,
    input s_axi_wdata_18,
    input s_axi_wdata_19,
    input s_axi_wdata_20,
    input s_axi_wdata_21,
    input s_axi_wdata_22,
    input s_axi_wdata_23,
    input s_axi_wdata_24,
    input s_axi_wdata_25,
    input s_axi_wdata_26,
    input s_axi_wdata_27,
    input s_axi_wdata_28,
    input s_axi_wdata_29,
    input s_axi_wdata_30,
    input s_axi_wdata_31,
    input s_axi_wstrb_0,
    input s_axi_wstrb_1,
    input s_axi_wstrb_2,
    input s_axi_wstrb_3,
    input s_axi_wvalid,
    input s_axi_bready,
    input s_axi_araddr_0,
    input s_axi_araddr_1,
    input s_axi_araddr_2,
    input s_axi_araddr_3,
    input s_axi_araddr_4,
    input s_axi_araddr_5,
    input s_axi_araddr_6,
    input s_axi_araddr_7,
    input s_axi_araddr_8,
    input s_axi_araddr_9,
    input s_axi_araddr_10,
    input s_axi_araddr_11,
    input s_axi_araddr_12,
    input s_axi_araddr_13,
    input s_axi_araddr_14,
    input s_axi_araddr_15,
    input s_axi_araddr_16,
    input s_axi_araddr_17,
    input s_axi_araddr_18,
    input s_axi_araddr_19,
    input s_axi_araddr_20,
    input s_axi_araddr_21,
    input s_axi_araddr_22,
    input s_axi_araddr_23,
    input s_axi_araddr_24,
    input s_axi_araddr_25,
    input s_axi_araddr_26,
    input s_axi_araddr_27,
    input s_axi_araddr_28,
    input s_axi_araddr_29,
    input s_axi_araddr_30,
    input s_axi_araddr_31,
    input s_axi_arvalid,
    input s_axi_rready,
    input timer_wake,
    input uart_wake,
    input gpio_wake,
    input ext_wake_0,
    input ext_wake_1,
    input ext_wake_2,
    input ext_wake_3,
    output accel_clk_en,
    output accel_iso,
    output cpu_clk_en,
    output cpu_iso,
    output mem_clk_en,
    output periph_clk_en,
    output periph_iso,
    output sram_ret_en,
    output s_axi_awready,
    output s_axi_bresp_0,
    output s_axi_bresp_1,
    output s_axi_bvalid,
    output s_axi_wready,
    output s_axi_arready,
    output s_axi_rdata_0,
    output s_axi_rdata_1,
    output s_axi_rdata_2,
    output s_axi_rdata_3,
    output s_axi_rdata_4,
    output s_axi_rdata_5,
    output s_axi_rdata_6,
    output s_axi_rdata_7,
    output s_axi_rdata_8,
    output s_axi_rdata_9,
    output s_axi_rdata_10,
    output s_axi_rdata_11,
    output s_axi_rdata_12,
    output s_axi_rdata_13,
    output s_axi_rdata_14,
    output s_axi_rdata_15,
    output s_axi_rdata_16,
    output s_axi_rdata_17,
    output s_axi_rdata_18,
    output s_axi_rdata_19,
    output s_axi_rdata_20,
    output s_axi_rdata_21,
    output s_axi_rdata_22,
    output s_axi_rdata_23,
    output s_axi_rdata_24,
    output s_axi_rdata_25,
    output s_axi_rdata_26,
    output s_axi_rdata_27,
    output s_axi_rdata_28,
    output s_axi_rdata_29,
    output s_axi_rdata_30,
    output s_axi_rdata_31,
    output s_axi_rresp_0,
    output s_axi_rresp_1,
    output s_axi_rvalid,
    output wake_irq
);

    wire current_state_0;
    wire current_state_1;
    wire domain_power_good_0;
    wire domain_power_good_1;
    wire domain_power_good_2;
    wire domain_power_good_3;
    wire seq_counter_0;
    wire seq_counter_1;
    wire seq_counter_2;
    wire seq_counter_3;
    wire seq_counter_4;
    wire seq_counter_5;
    wire seq_counter_6;
    wire seq_counter_7;
    wire seq_counter_8;
    wire seq_counter_9;
    wire seq_counter_10;
    wire seq_counter_11;
    wire seq_powering_down;
    wire seq_state_0;
    wire seq_state_1;
    wire seq_state_2;
    wire transitioning;
    wire abort_req_n157;
    wire aw_done;
    wire clk_gate_reg_0;
    wire clk_gate_reg_1;
    wire clk_gate_reg_2;
    wire clk_gate_reg_3;
    wire clk_gate_reg_4;
    wire iso_ctrl_reg_0;
    wire iso_ctrl_reg_1;
    wire iso_ctrl_reg_2;
    wire pwr_dn_delay_0;
    wire pwr_dn_delay_1;
    wire pwr_dn_delay_2;
    wire pwr_dn_delay_3;
    wire pwr_dn_delay_4;
    wire pwr_dn_delay_5;
    wire pwr_dn_delay_6;
    wire pwr_dn_delay_7;
    wire pwr_up_delay_0;
    wire pwr_up_delay_1;
    wire pwr_up_delay_2;
    wire pwr_up_delay_3;
    wire pwr_up_delay_4;
    wire pwr_up_delay_5;
    wire pwr_up_delay_6;
    wire pwr_up_delay_7;
    wire ret_ctrl_reg;
    wire __dff_d_ff2270;
    wire __dff_d_ff2271;
    wire transition_req_n191;
    wire w_done;
    wire wake_en_reg_0;
    wire wake_en_reg_1;
    wire wake_en_reg_2;
    wire wake_en_reg_3;
    wire wake_en_reg_4;
    wire wake_en_reg_5;
    wire wake_en_reg_6;
    wire wake_en_reg_7;
    wire wake_stat_reg_0_n201;
    wire wake_stat_reg_1_n202;
    wire wake_stat_reg_2_n203;
    wire wake_stat_reg_3_n204;
    wire wake_stat_reg_4_n205;
    wire wake_stat_reg_5_n206;
    wire wake_stat_reg_6_n207;
    wire wake_stat_reg_7_n208;
    wire wr_addr_0;
    wire wr_addr_1;
    wire wr_addr_2;
    wire wr_addr_3;
    wire wr_addr_4;
    wire wr_addr_5;
    wire wr_addr_6;
    wire wr_addr_7;
    wire wr_addr_8;
    wire wr_addr_9;
    wire wr_addr_10;
    wire wr_addr_11;
    wire wr_addr_12;
    wire wr_addr_13;
    wire wr_addr_14;
    wire wr_addr_15;
    wire wr_addr_16;
    wire wr_addr_17;
    wire wr_addr_18;
    wire wr_addr_19;
    wire wr_addr_20;
    wire wr_addr_21;
    wire wr_addr_22;
    wire wr_addr_23;
    wire wr_addr_24;
    wire wr_addr_25;
    wire wr_addr_26;
    wire wr_addr_27;
    wire wr_addr_28;
    wire wr_addr_29;
    wire wr_addr_30;
    wire wr_addr_31;
    wire n279;
    wire n281;
    wire inv_n149;
    wire n285;
    wire n287;
    wire inv_n121;
    wire n288;
    wire inv_n120;
    wire n290;
    wire inv_n191;
    wire n291;
    wire inv_n190;
    wire n292;
    wire n293;
    wire n294;
    wire n295;
    wire __dff_d_ff2239;
    wire inv_n158;
    wire n298;
    wire inv_n2;
    wire n302;
    wire n304;
    wire n305;
    wire n308;
    wire n310;
    wire n311;
    wire n314;
    wire n316;
    wire n317;
    wire n320;
    wire n322;
    wire n323;
    wire n326;
    wire n328;
    wire n329;
    wire n332;
    wire n334;
    wire n335;
    wire n338;
    wire n340;
    wire n341;
    wire n344;
    wire n346;
    wire n347;
    wire n350;
    wire n351;
    wire n352;
    wire n353;
    wire n354;
    wire n355;
    wire n356;
    wire n357;
    wire n358;
    wire n359;
    wire n360;
    wire n361;
    wire n362;
    wire n363;
    wire n364;
    wire n365;
    wire n366;
    wire n367;
    wire n368;
    wire n369;
    wire n370;
    wire n371;
    wire n372;
    wire n373;
    wire n374;
    wire n375;
    wire n376;
    wire n377;
    wire n378;
    wire n379;
    wire n381;
    wire n382;
    wire n383;
    wire n384;
    wire n386;
    wire __dff_d_ff2240;
    wire inv_n116;
    wire n390;
    wire n391;
    wire n393;
    wire __dff_d_ff2241;
    wire __dff_d_ff2242;
    wire inv_n118;
    wire n400;
    wire __dff_d_ff2243;
    wire n405;
    wire n406;
    wire n408;
    wire n409;
    wire n410;
    wire __dff_d_ff2244;
    wire n412;
    wire n415;
    wire __dff_d_ff2245;
    wire n419;
    wire n422;
    wire __dff_d_ff2246;
    wire __dff_d_ff2247;
    wire __dff_d_ff2248;
    wire __dff_d_ff2249;
    wire n431;
    wire n433;
    wire inv_n126;
    wire n434;
    wire __dff_d_ff2250;
    wire __dff_d_ff2251;
    wire inv_n127;
    wire n441;
    wire __dff_d_ff2252;
    wire __dff_d_ff2253;
    wire n448;
    wire inv_n192;
    wire __dff_d_ff2254;
    wire inv_n130;
    wire __dff_d_ff2255;
    wire inv_n131;
    wire __dff_d_ff2256;
    wire inv_n132;
    wire __dff_d_ff2257;
    wire inv_n133;
    wire __dff_d_ff2258;
    wire inv_n134;
    wire __dff_d_ff2259;
    wire inv_n135;
    wire __dff_d_ff2260;
    wire inv_n136;
    wire __dff_d_ff2261;
    wire inv_n137;
    wire __dff_d_ff2262;
    wire inv_n138;
    wire __dff_d_ff2263;
    wire inv_n139;
    wire __dff_d_ff2264;
    wire inv_n140;
    wire n460;
    wire n461;
    wire n463;
    wire __dff_d_ff2265;
    wire __dff_d_ff2266;
    wire __dff_d_ff2268;
    wire n471;
    wire __dff_d_ff2269;
    wire __dff_d_ff2272;
    wire __dff_d_ff2273;
    wire n478;
    wire __dff_d_ff2274;
    wire n481;
    wire __dff_d_ff2275;
    wire n484;
    wire __dff_d_ff2276;
    wire __dff_d_ff2277;
    wire n488;
    wire __dff_d_ff2278;
    wire n491;
    wire __dff_d_ff2279;
    wire n494;
    wire __dff_d_ff2280;
    wire n497;
    wire __dff_d_ff2281;
    wire n500;
    wire inv_n35;
    wire n503;
    wire n506;
    wire n509;
    wire n512;
    wire n515;
    wire n518;
    wire n519;
    wire n522;
    wire n525;
    wire n526;
    wire n527;
    wire n528;
    wire n529;
    wire n530;
    wire n531;
    wire n535;
    wire n536;
    wire n537;
    wire n538;
    wire n539;
    wire n541;
    wire n542;
    wire n543;
    wire n544;
    wire __dff_d_ff3315;
    wire __dff_d_ff3316;
    wire inv_n159;
    wire n550;
    wire n551;
    wire n552;
    wire n554;
    wire __dff_d_ff3317;
    wire inv_n160;
    wire n557;
    wire n559;
    wire inv_n68;
    wire n562;
    wire n564;
    wire n566;
    wire __dff_d_ff3318;
    wire n569;
    wire n571;
    wire inv_n38;
    wire inv_n162;
    wire n572;
    wire n574;
    wire n575;
    wire n576;
    wire __dff_d_ff3319;
    wire n582;
    wire inv_n37;
    wire inv_n163;
    wire n583;
    wire n585;
    wire n586;
    wire n587;
    wire __dff_d_ff3320;
    wire n591;
    wire n593;
    wire inv_n36;
    wire inv_n164;
    wire n594;
    wire n596;
    wire n597;
    wire n598;
    wire __dff_d_ff3321;
    wire n603;
    wire n605;
    wire __dff_d_ff3322;
    wire n609;
    wire n611;
    wire n613;
    wire n614;
    wire __dff_d_ff3323;
    wire n618;
    wire n620;
    wire n622;
    wire n624;
    wire __dff_d_ff3324;
    wire n627;
    wire n630;
    wire n631;
    wire inv_n51;
    wire n632;
    wire __dff_d_ff3325;
    wire n635;
    wire n637;
    wire n638;
    wire inv_n169;
    wire n639;
    wire n641;
    wire __dff_d_ff3326;
    wire n645;
    wire inv_n49;
    wire n648;
    wire n649;
    wire n650;
    wire __dff_d_ff3327;
    wire inv_n170;
    wire n654;
    wire n655;
    wire inv_n171;
    wire n657;
    wire __dff_d_ff3328;
    wire n660;
    wire n661;
    wire inv_n172;
    wire n663;
    wire __dff_d_ff3329;
    wire n666;
    wire n667;
    wire inv_n173;
    wire n669;
    wire __dff_d_ff3330;
    wire n672;
    wire n673;
    wire inv_n174;
    wire n675;
    wire __dff_d_ff3331;
    wire n678;
    wire n679;
    wire inv_n175;
    wire n681;
    wire __dff_d_ff3332;
    wire n683;
    wire n684;
    wire n687;
    wire n688;
    wire inv_n176;
    wire n690;
    wire __dff_d_ff3333;
    wire n692;
    wire n693;
    wire n695;
    wire n696;
    wire inv_n177;
    wire n698;
    wire __dff_d_ff3334;
    wire n700;
    wire n702;
    wire inv_n41;
    wire inv_n178;
    wire n704;
    wire n705;
    wire n706;
    wire __dff_d_ff3335;
    wire n711;
    wire n713;
    wire __dff_d_ff3336;
    wire n718;
    wire n720;
    wire __dff_d_ff3337;
    wire __dff_d_ff3338;
    wire __dff_d_ff3339;
    wire __dff_d_ff3340;
    wire __dff_d_ff3341;
    wire __dff_d_ff3342;
    wire __dff_d_ff3343;
    wire __dff_d_ff3344;
    wire __dff_d_ff3345;
    wire inv_n188;
    wire __dff_d_ff3346;
    wire inv_n193;
    wire n746;
    wire n747;
    wire __dff_d_ff3347;
    wire __dff_d_ff3348;
    wire __dff_d_ff3349;
    wire __dff_d_ff3350;
    wire inv_n72;
    wire n758;
    wire n761;
    wire inv_n194;
    wire n762;
    wire n763;
    wire __dff_d_ff3351;
    wire n766;
    wire n769;
    wire inv_n195;
    wire n770;
    wire n771;
    wire __dff_d_ff3352;
    wire n776;
    wire n777;
    wire inv_n196;
    wire n779;
    wire __dff_d_ff3353;
    wire __dff_d_ff3354;
    wire __dff_d_ff3355;
    wire __dff_d_ff3356;
    wire __dff_d_ff3357;
    wire __dff_d_ff3358;
    wire __dff_d_ff3359;
    wire inv_n202;
    wire __dff_d_ff3360;
    wire inv_n203;
    wire __dff_d_ff3361;
    wire inv_n204;
    wire __dff_d_ff3362;
    wire inv_n205;
    wire __dff_d_ff3363;
    wire inv_n206;
    wire __dff_d_ff3364;
    wire inv_n207;
    wire __dff_d_ff3365;
    wire inv_n208;
    wire __dff_d_ff3366;
    wire inv_n209;
    wire __dff_d_ff3367;
    wire __dff_d_ff3368;
    wire __dff_d_ff3369;
    wire __dff_d_ff3370;
    wire __dff_d_ff3371;
    wire __dff_d_ff3372;
    wire __dff_d_ff3373;
    wire __dff_d_ff3374;
    wire n818;
    wire __dff_d_ff3375;
    wire n822;
    wire __dff_d_ff3376;
    wire n826;
    wire __dff_d_ff3377;
    wire n830;
    wire __dff_d_ff3378;
    wire n834;
    wire __dff_d_ff3379;
    wire n838;
    wire __dff_d_ff3380;
    wire n842;
    wire __dff_d_ff3381;
    wire n846;
    wire __dff_d_ff3382;
    wire n850;
    wire __dff_d_ff3383;
    wire n854;
    wire __dff_d_ff3384;
    wire n858;
    wire __dff_d_ff3385;
    wire n862;
    wire __dff_d_ff3386;
    wire n866;
    wire __dff_d_ff3387;
    wire n870;
    wire __dff_d_ff3388;
    wire n874;
    wire __dff_d_ff3389;
    wire n878;
    wire __dff_d_ff3390;
    wire n882;
    wire __dff_d_ff3391;
    wire n886;
    wire __dff_d_ff3392;
    wire n890;
    wire __dff_d_ff3393;
    wire n894;
    wire __dff_d_ff3394;
    wire n898;
    wire __dff_d_ff3395;
    wire n902;
    wire __dff_d_ff3396;
    wire n906;
    wire __dff_d_ff3397;
    wire n910;
    wire __dff_d_ff3398;
    wire n912;
    wire inv_n106;
    wire __dff_d_ff4720;
    wire n917;
    wire n918;
    wire n919;
    wire n920;
    wire n921;
    wire n922;
    wire n924;
    wire __dff_d_ff4721;
    wire n928;
    wire __dff_d_ff4722;
    wire __dff_d_ff4723;
    wire __dff_d_ff4724;
    wire n936;
    wire __dff_d_ff4725;
    wire n940;
    wire __dff_d_ff4726;
    wire __dff_d_ff4727;
    wire __dff_d_ff4728;
    wire __dff_d_ff4729;
    wire __dff_d_ff4730;
    wire __dff_d_ff4731;
    wire __dff_d_ff4732;
    wire __dff_d_ff4733;
    wire __dff_d_ff4734;
    wire __dff_d_ff4735;
    wire __dff_d_ff4736;
    wire __dff_d_ff4737;
    wire __dff_d_ff4738;
    wire __dff_d_ff4739;
    wire __dff_d_ff4740;
    wire __dff_d_ff4741;
    wire __dff_d_ff4742;
    wire __dff_d_ff4743;
    wire __dff_d_ff4744;
    wire __dff_d_ff4745;
    wire __dff_d_ff4746;
    wire __dff_d_ff4747;
    wire __dff_d_ff4748;
    wire __dff_d_ff4749;
    wire __dff_d_ff4750;
    wire __dff_d_ff4751;
    wire __dff_d_ff4752;
    wire __dff_d_ff4753;
    wire __dff_d_ff4754;
    wire __dff_d_ff4755;
    wire inv_n277;
    wire __dff_d_ff2267;
    wire clone_13;
    wire clone_57;
    wire clone_60;
    wire clone_63;
    wire clone_66;
    wire clone_69;
    wire clone_72;
    wire clone_85;
    wire clone_87;
    wire clone_93;
    wire clone_100;
    wire clone_109;
    wire clone_111;
    wire clone_154;
    wire clone_157;
    wire clone_201;
    wire clone_212;
    wire clone_249;
    wire clone_250;
    wire clone_311;
    wire clone_319;
    wire clone_329;
    wire clone_405;
    wire clone_455;
    wire buf_rst_n_0;
    wire buf_rst_n_1;
    wire glitch_bal_112_1_n;
    wire glitch_bal_83_0_n;
    wire glitch_bal_113_0_n;
    wire glitch_bal_118_1_n;
    wire glitch_bal_112_2_n;
    wire glitch_bal_113_2_n;
    wire glitch_bal_106_1_n;
    wire glitch_bal_108_2_n;
    wire glitch_bal_121_1_n;
    wire glitch_bal_105_1_n;
    wire glitch_bal_74_0_n;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(wake_irq));
    sky130_fd_sc_hd__nor3_1 U0 (
        .A(seq_state_0),
        .B(seq_state_1),
        .C(seq_state_2),
        .Y(n279)
    );

    sky130_fd_sc_hd__inv_1 U1 (
        .A(transitioning),
        .Y(inv_n149)
    );

    sky130_fd_sc_hd__nand3b_1 U2 (
        .A_N(transitioning),
        .B(transition_req_n191),
        .C(n279),
        .Y(n281)
    );

    sky130_fd_sc_hd__xnor2_1 U3 (
        .A(current_state_0),
        .B(__dff_d_ff2270),
        .Y(n285)
    );

    sky130_fd_sc_hd__nand3b_1 U4 (
        .A_N(current_state_1),
        .B(__dff_d_ff2271),
        .C(n285),
        .Y(n287)
    );

    sky130_fd_sc_hd__inv_1 U5 (
        .A(current_state_0),
        .Y(inv_n120)
    );

    sky130_fd_sc_hd__a21oi_1 U6 (
        .A1(inv_n120),
        .A2(__dff_d_ff2270),
        .B1(n287),
        .Y(n288)
    );

    sky130_fd_sc_hd__nand3b_1 U7 (
        .A_N(__dff_d_ff2271),
        .B(current_state_1),
        .C(n285),
        .Y(n290)
    );

    sky130_fd_sc_hd__inv_1 U8 (
        .A(__dff_d_ff2270),
        .Y(inv_n190)
    );

    sky130_fd_sc_hd__a21oi_1 U9 (
        .A1(current_state_0),
        .A2(inv_n190),
        .B1(n290),
        .Y(n291)
    );

    sky130_fd_sc_hd__nand2_1 U10 (
        .A(clone_13),
        .B(n291),
        .Y(n292)
    );

    sky130_fd_sc_hd__nand2_1 U11 (
        .A(n288),
        .B(n292),
        .Y(n293)
    );

    sky130_fd_sc_hd__o21a_1 U12 (
        .A1(transitioning),
        .A2(clone_13),
        .B1(n293),
        .X(n294)
    );

    sky130_fd_sc_hd__nand2_1 U13 (
        .A(abort_req_n157),
        .B(n294),
        .Y(n295)
    );

    sky130_fd_sc_hd__inv_1 U14 (
        .A(abort_req_n157),
        .Y(inv_n158)
    );

    sky130_fd_sc_hd__a21oi_1 U15 (
        .A1(buf_rst_n_0),
        .A2(n295),
        .B1(inv_n158),
        .Y(__dff_d_ff2239)
    );

    sky130_fd_sc_hd__nor2b_1 U16 (
        .A(n295),
        .B_N(buf_rst_n_0),
        .Y(n298)
    );

    sky130_fd_sc_hd__mux2_1 U17 (
        .A0(pwr_dn_delay_7),
        .A1(pwr_up_delay_7),
        .S(seq_powering_down),
        .X(n302)
    );

    sky130_fd_sc_hd__nand2_1 U18 (
        .A(seq_counter_11),
        .B(n302),
        .Y(n304)
    );

    sky130_fd_sc_hd__xor2_1 U19 (
        .A(seq_counter_11),
        .B(n302),
        .X(n305)
    );

    sky130_fd_sc_hd__mux2_1 U20 (
        .A0(pwr_dn_delay_6),
        .A1(pwr_up_delay_6),
        .S(seq_powering_down),
        .X(n308)
    );

    sky130_fd_sc_hd__nand2_1 U21 (
        .A(seq_counter_10),
        .B(n308),
        .Y(n310)
    );

    sky130_fd_sc_hd__xor2_1 U22 (
        .A(seq_counter_10),
        .B(n308),
        .X(n311)
    );

    sky130_fd_sc_hd__mux2_1 U23 (
        .A0(pwr_dn_delay_5),
        .A1(pwr_up_delay_5),
        .S(seq_powering_down),
        .X(n314)
    );

    sky130_fd_sc_hd__nand2_1 U24 (
        .A(seq_counter_9),
        .B(n314),
        .Y(n316)
    );

    sky130_fd_sc_hd__xor2_1 U25 (
        .A(seq_counter_9),
        .B(n314),
        .X(n317)
    );

    sky130_fd_sc_hd__mux2_1 U26 (
        .A0(pwr_dn_delay_4),
        .A1(pwr_up_delay_4),
        .S(seq_powering_down),
        .X(n320)
    );

    sky130_fd_sc_hd__nand2_1 U27 (
        .A(seq_counter_8),
        .B(n320),
        .Y(n322)
    );

    sky130_fd_sc_hd__xor2_1 U28 (
        .A(seq_counter_8),
        .B(n320),
        .X(n323)
    );

    sky130_fd_sc_hd__mux2_1 U29 (
        .A0(pwr_dn_delay_3),
        .A1(pwr_up_delay_3),
        .S(seq_powering_down),
        .X(n326)
    );

    sky130_fd_sc_hd__nand2_1 U30 (
        .A(seq_counter_7),
        .B(n326),
        .Y(n328)
    );

    sky130_fd_sc_hd__xor2_1 U31 (
        .A(seq_counter_7),
        .B(n326),
        .X(n329)
    );

    sky130_fd_sc_hd__mux2_1 U32 (
        .A0(pwr_dn_delay_2),
        .A1(pwr_up_delay_2),
        .S(seq_powering_down),
        .X(n332)
    );

    sky130_fd_sc_hd__nand2_1 U33 (
        .A(seq_counter_6),
        .B(n332),
        .Y(n334)
    );

    sky130_fd_sc_hd__xor2_1 U34 (
        .A(seq_counter_6),
        .B(n332),
        .X(n335)
    );

    sky130_fd_sc_hd__mux2_1 U35 (
        .A0(pwr_dn_delay_1),
        .A1(pwr_up_delay_1),
        .S(seq_powering_down),
        .X(n338)
    );

    sky130_fd_sc_hd__nand2_1 U36 (
        .A(seq_counter_5),
        .B(n338),
        .Y(n340)
    );

    sky130_fd_sc_hd__xor2_1 U37 (
        .A(seq_counter_5),
        .B(n338),
        .X(n341)
    );

    sky130_fd_sc_hd__mux2_1 U38 (
        .A0(pwr_dn_delay_0),
        .A1(pwr_up_delay_0),
        .S(seq_powering_down),
        .X(n344)
    );

    sky130_fd_sc_hd__nand2_1 U39 (
        .A(seq_counter_4),
        .B(n344),
        .Y(n346)
    );

    sky130_fd_sc_hd__xor2_1 U40 (
        .A(seq_counter_4),
        .B(n344),
        .X(n347)
    );

    sky130_fd_sc_hd__nor4_1 U41 (
        .A(seq_counter_0),
        .B(seq_counter_1),
        .C(seq_counter_2),
        .D(seq_counter_3),
        .Y(n350)
    );

    sky130_fd_sc_hd__nand2_1 U42 (
        .A(n347),
        .B(n350),
        .Y(n351)
    );

    sky130_fd_sc_hd__nand2_1 U43 (
        .A(n341),
        .B(n351),
        .Y(n352)
    );

    sky130_fd_sc_hd__nand2_1 U44 (
        .A(n335),
        .B(n352),
        .Y(n353)
    );

    sky130_fd_sc_hd__nand2_1 U45 (
        .A(n329),
        .B(n353),
        .Y(n354)
    );

    sky130_fd_sc_hd__nand2_1 U46 (
        .A(n323),
        .B(n354),
        .Y(n355)
    );

    sky130_fd_sc_hd__nand2_1 U47 (
        .A(n317),
        .B(n355),
        .Y(n356)
    );

    sky130_fd_sc_hd__nand2_1 U48 (
        .A(n311),
        .B(n356),
        .Y(n357)
    );

    sky130_fd_sc_hd__nand2_1 U49 (
        .A(n305),
        .B(n357),
        .Y(n358)
    );

    sky130_fd_sc_hd__nand2_1 U50 (
        .A(n304),
        .B(n311),
        .Y(n359)
    );

    sky130_fd_sc_hd__nor2_1 U51 (
        .A(n310),
        .B(n359),
        .Y(n360)
    );

    sky130_fd_sc_hd__nor2_1 U52 (
        .A(clone_57),
        .B(n360),
        .Y(n361)
    );

    sky130_fd_sc_hd__nor2_1 U53 (
        .A(n316),
        .B(n361),
        .Y(n362)
    );

    sky130_fd_sc_hd__nor2_1 U54 (
        .A(clone_60),
        .B(n362),
        .Y(n363)
    );

    sky130_fd_sc_hd__nor2_1 U55 (
        .A(n322),
        .B(n363),
        .Y(n364)
    );

    sky130_fd_sc_hd__nor2_1 U56 (
        .A(clone_63),
        .B(n364),
        .Y(n365)
    );

    sky130_fd_sc_hd__nor2_1 U57 (
        .A(n328),
        .B(n365),
        .Y(n366)
    );

    sky130_fd_sc_hd__nor2_1 U58 (
        .A(clone_66),
        .B(n366),
        .Y(n367)
    );

    sky130_fd_sc_hd__nor2_1 U59 (
        .A(n334),
        .B(n367),
        .Y(n368)
    );

    sky130_fd_sc_hd__nor2_1 U60 (
        .A(clone_69),
        .B(n368),
        .Y(n369)
    );

    sky130_fd_sc_hd__nor2_1 U61 (
        .A(n340),
        .B(n369),
        .Y(n370)
    );

    sky130_fd_sc_hd__nor2_1 U62 (
        .A(clone_72),
        .B(n370),
        .Y(n371)
    );

    sky130_fd_sc_hd__nor2_1 U63 (
        .A(glitch_bal_74_0_n),
        .B(n371),
        .Y(n372)
    );

    sky130_fd_sc_hd__nor2_1 U64 (
        .A(seq_counter_3),
        .B(n372),
        .Y(n373)
    );

    sky130_fd_sc_hd__nor2_1 U65 (
        .A(seq_counter_3),
        .B(n373),
        .Y(n374)
    );

    sky130_fd_sc_hd__nor2_1 U66 (
        .A(seq_counter_2),
        .B(n374),
        .Y(n375)
    );

    sky130_fd_sc_hd__nor2_1 U67 (
        .A(seq_counter_2),
        .B(n375),
        .Y(n376)
    );

    sky130_fd_sc_hd__nor2_1 U68 (
        .A(seq_counter_1),
        .B(n376),
        .Y(n377)
    );

    sky130_fd_sc_hd__nor2_1 U69 (
        .A(seq_counter_1),
        .B(n377),
        .Y(n378)
    );

    sky130_fd_sc_hd__nor2_1 U70 (
        .A(seq_counter_0),
        .B(n378),
        .Y(n379)
    );

    sky130_fd_sc_hd__nor3_1 U71 (
        .A(seq_counter_0),
        .B(n358),
        .C(n379),
        .Y(n381)
    );

    sky130_fd_sc_hd__nand2_1 U72 (
        .A(glitch_bal_83_0_n),
        .B(n381),
        .Y(n382)
    );

    sky130_fd_sc_hd__nor2_1 U73 (
        .A(__dff_d_ff2270),
        .B(__dff_d_ff2271),
        .Y(n383)
    );

    sky130_fd_sc_hd__nor3_1 U74 (
        .A(__dff_d_ff2270),
        .B(__dff_d_ff2271),
        .C(clone_85),
        .Y(n384)
    );

    sky130_fd_sc_hd__nand4_1 U75 (
        .A(n279),
        .B(n298),
        .C(clone_87),
        .D(n383),
        .Y(n386)
    );

    sky130_fd_sc_hd__inv_1 U76 (
        .A(accel_clk_en),
        .Y(inv_n116)
    );

    sky130_fd_sc_hd__mux2_1 U77 (
        .A0(n298),
        .A1(n386),
        .S(inv_n116),
        .X(__dff_d_ff2240)
    );

    sky130_fd_sc_hd__nor4_1 U78 (
        .A(seq_state_0),
        .B(seq_state_1),
        .C(seq_state_2),
        .D(n295),
        .Y(n390)
    );

    sky130_fd_sc_hd__nor4_1 U79 (
        .A(__dff_d_ff2270),
        .B(__dff_d_ff2271),
        .C(clone_85),
        .D(n295),
        .Y(n391)
    );

    sky130_fd_sc_hd__mux2_1 U80 (
        .A0(clone_93),
        .A1(n391),
        .S(accel_iso),
        .X(n393)
    );

    sky130_fd_sc_hd__nor2b_1 U81 (
        .A(n393),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff2241)
    );

    sky130_fd_sc_hd__inv_1 U82 (
        .A(cpu_clk_en),
        .Y(inv_n118)
    );

    sky130_fd_sc_hd__mux2_1 U83 (
        .A0(n298),
        .A1(n386),
        .S(inv_n118),
        .X(__dff_d_ff2242)
    );

    sky130_fd_sc_hd__o21a_1 U84 (
        .A1(cpu_iso),
        .A2(n391),
        .B1(buf_rst_n_0),
        .X(n400)
    );

    sky130_fd_sc_hd__a21oi_1 U85 (
        .A1(cpu_iso),
        .A2(n295),
        .B1(n400),
        .Y(__dff_d_ff2243)
    );

    sky130_fd_sc_hd__a211oi_1 U86 (
        .A1(inv_n190),
        .A2(n279),
        .B1(inv_n120),
        .C1(clone_100),
        .Y(n405)
    );

    sky130_fd_sc_hd__nor2_1 U87 (
        .A(n405),
        .B(n408),
        .Y(n409)
    );

    sky130_fd_sc_hd__nor2_1 U88 (
        .A(n381),
        .B(glitch_bal_105_1_n),
        .Y(n410)
    );

    sky130_fd_sc_hd__a31oi_1 U89 (
        .A1(current_state_0),
        .A2(glitch_bal_106_1_n),
        .A3(n381),
        .B1(n410),
        .Y(__dff_d_ff2244)
    );

    sky130_fd_sc_hd__nor4_1 U90 (
        .A(seq_state_0),
        .B(seq_state_1),
        .C(seq_state_2),
        .D(n381),
        .Y(n412)
    );

    sky130_fd_sc_hd__o21a_1 U91 (
        .A1(current_state_1),
        .A2(n412),
        .B1(glitch_bal_108_2_n),
        .X(n415)
    );

    sky130_fd_sc_hd__o21a_1 U92 (
        .A1(__dff_d_ff2271),
        .A2(clone_109),
        .B1(n415),
        .X(__dff_d_ff2245)
    );

    sky130_fd_sc_hd__a211oi_1 U93 (
        .A1(domain_power_good_0),
        .A2(glitch_bal_112_1_n),
        .B1(glitch_bal_112_2_n),
        .C1(clone_109),
        .Y(n419)
    );

    sky130_fd_sc_hd__nor4_1 U94 (
        .A(glitch_bal_113_0_n),
        .B(domain_power_good_0),
        .C(glitch_bal_113_2_n),
        .D(n412),
        .Y(n422)
    );

    sky130_fd_sc_hd__nor2_1 U95 (
        .A(n419),
        .B(n422),
        .Y(__dff_d_ff2246)
    );

    sky130_fd_sc_hd__nor3b_1 U96 (
        .A(domain_power_good_1),
        .B(n295),
        .C_N(buf_rst_n_0),
        .Y(__dff_d_ff2247)
    );

    sky130_fd_sc_hd__nor3b_1 U97 (
        .A(domain_power_good_2),
        .B(n295),
        .C_N(buf_rst_n_0),
        .Y(__dff_d_ff2248)
    );

    sky130_fd_sc_hd__nor3b_1 U98 (
        .A(domain_power_good_3),
        .B(n295),
        .C_N(buf_rst_n_0),
        .Y(__dff_d_ff2249)
    );

    sky130_fd_sc_hd__o21a_1 U99 (
        .A1(mem_clk_en),
        .A2(glitch_bal_118_1_n),
        .B1(n382),
        .X(n431)
    );

    sky130_fd_sc_hd__inv_1 U100 (
        .A(mem_clk_en),
        .Y(inv_n126)
    );

    sky130_fd_sc_hd__o21a_1 U101 (
        .A1(inv_n126),
        .A2(n384),
        .B1(n298),
        .X(n433)
    );

    sky130_fd_sc_hd__nor2_1 U102 (
        .A(n382),
        .B(glitch_bal_121_1_n),
        .Y(n434)
    );

    sky130_fd_sc_hd__nor2_1 U103 (
        .A(n431),
        .B(n434),
        .Y(__dff_d_ff2250)
    );

    sky130_fd_sc_hd__inv_1 U104 (
        .A(periph_clk_en),
        .Y(inv_n127)
    );

    sky130_fd_sc_hd__mux2_1 U105 (
        .A0(n298),
        .A1(n386),
        .S(inv_n127),
        .X(__dff_d_ff2251)
    );

    sky130_fd_sc_hd__o21a_1 U106 (
        .A1(periph_iso),
        .A2(n391),
        .B1(buf_rst_n_0),
        .X(n441)
    );

    sky130_fd_sc_hd__a21oi_1 U107 (
        .A1(periph_iso),
        .A2(n295),
        .B1(n441),
        .Y(__dff_d_ff2252)
    );

    sky130_fd_sc_hd__inv_1 U108 (
        .A(transition_req_n191),
        .Y(inv_n192)
    );

    sky130_fd_sc_hd__o31ai_1 U109 (
        .A1(transitioning),
        .A2(inv_n192),
        .A3(clone_85),
        .B1(buf_rst_n_0),
        .Y(n448)
    );

    sky130_fd_sc_hd__nor2b_1 U110 (
        .A(n448),
        .B_N(seq_counter_1),
        .Y(__dff_d_ff2254)
    );

    sky130_fd_sc_hd__nor2b_1 U111 (
        .A(n448),
        .B_N(seq_counter_2),
        .Y(__dff_d_ff2255)
    );

    sky130_fd_sc_hd__nor2b_1 U112 (
        .A(n448),
        .B_N(seq_counter_3),
        .Y(__dff_d_ff2256)
    );

    sky130_fd_sc_hd__nor2b_1 U113 (
        .A(n448),
        .B_N(seq_counter_4),
        .Y(__dff_d_ff2257)
    );

    sky130_fd_sc_hd__nor2b_1 U114 (
        .A(n448),
        .B_N(seq_counter_5),
        .Y(__dff_d_ff2258)
    );

    sky130_fd_sc_hd__nor2b_1 U115 (
        .A(n448),
        .B_N(seq_counter_6),
        .Y(__dff_d_ff2259)
    );

    sky130_fd_sc_hd__nor2b_1 U116 (
        .A(n448),
        .B_N(seq_counter_7),
        .Y(__dff_d_ff2260)
    );

    sky130_fd_sc_hd__nor2b_1 U117 (
        .A(n448),
        .B_N(seq_counter_8),
        .Y(__dff_d_ff2261)
    );

    sky130_fd_sc_hd__nor2b_1 U118 (
        .A(n448),
        .B_N(seq_counter_9),
        .Y(__dff_d_ff2262)
    );

    sky130_fd_sc_hd__nor2b_1 U119 (
        .A(n448),
        .B_N(seq_counter_10),
        .Y(__dff_d_ff2263)
    );

    sky130_fd_sc_hd__nor2b_1 U120 (
        .A(n448),
        .B_N(seq_counter_11),
        .Y(__dff_d_ff2264)
    );

    sky130_fd_sc_hd__nor2_1 U121 (
        .A(n281),
        .B(n288),
        .Y(n460)
    );

    sky130_fd_sc_hd__nor2_1 U122 (
        .A(n281),
        .B(n291),
        .Y(n461)
    );

    sky130_fd_sc_hd__a21oi_1 U123 (
        .A1(seq_powering_down),
        .A2(clone_154),
        .B1(n460),
        .Y(n463)
    );

    sky130_fd_sc_hd__nor2b_1 U124 (
        .A(n463),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff2265)
    );

    sky130_fd_sc_hd__nor4_1 U125 (
        .A(inv_n2),
        .B(seq_state_0),
        .C(n295),
        .D(clone_157),
        .Y(__dff_d_ff2266)
    );

    sky130_fd_sc_hd__nand2_1 U126 (
        .A(n298),
        .B(n461),
        .Y(__dff_d_ff2268)
    );

    sky130_fd_sc_hd__o21a_1 U127 (
        .A1(sram_ret_en),
        .A2(n391),
        .B1(buf_rst_n_0),
        .X(n471)
    );

    sky130_fd_sc_hd__a21oi_1 U128 (
        .A1(sram_ret_en),
        .A2(n295),
        .B1(n471),
        .Y(__dff_d_ff2269)
    );

    sky130_fd_sc_hd__a31oi_1 U129 (
        .A1(buf_rst_n_0),
        .A2(inv_n149),
        .A3(n279),
        .B1(inv_n192),
        .Y(__dff_d_ff2272)
    );

    sky130_fd_sc_hd__nand2_1 U130 (
        .A(timer_wake),
        .B(wake_en_reg_0),
        .Y(n478)
    );

    sky130_fd_sc_hd__o21a_1 U131 (
        .A1(wake_stat_reg_0_n201),
        .A2(n478),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2274)
    );

    sky130_fd_sc_hd__nand2_1 U132 (
        .A(uart_wake),
        .B(wake_en_reg_1),
        .Y(n481)
    );

    sky130_fd_sc_hd__o21a_1 U133 (
        .A1(wake_stat_reg_1_n202),
        .A2(n481),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2275)
    );

    sky130_fd_sc_hd__nand2_1 U134 (
        .A(gpio_wake),
        .B(wake_en_reg_2),
        .Y(n484)
    );

    sky130_fd_sc_hd__o21a_1 U135 (
        .A1(wake_stat_reg_2_n203),
        .A2(n484),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2276)
    );

    sky130_fd_sc_hd__nand2_1 U136 (
        .A(ext_wake_0),
        .B(wake_en_reg_4),
        .Y(n488)
    );

    sky130_fd_sc_hd__o21a_1 U137 (
        .A1(wake_stat_reg_4_n205),
        .A2(n488),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2278)
    );

    sky130_fd_sc_hd__nand2_1 U138 (
        .A(ext_wake_1),
        .B(wake_en_reg_5),
        .Y(n491)
    );

    sky130_fd_sc_hd__o21a_1 U139 (
        .A1(wake_stat_reg_5_n206),
        .A2(n491),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2279)
    );

    sky130_fd_sc_hd__nand2_1 U140 (
        .A(ext_wake_2),
        .B(wake_en_reg_6),
        .Y(n494)
    );

    sky130_fd_sc_hd__o21a_1 U141 (
        .A1(wake_stat_reg_6_n207),
        .A2(n494),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2280)
    );

    sky130_fd_sc_hd__nand2_1 U142 (
        .A(ext_wake_3),
        .B(wake_en_reg_7),
        .Y(n497)
    );

    sky130_fd_sc_hd__o21a_1 U143 (
        .A1(wake_stat_reg_7_n208),
        .A2(n497),
        .B1(buf_rst_n_0),
        .X(__dff_d_ff2281)
    );

    sky130_fd_sc_hd__inv_1 U144 (
        .A(s_axi_awvalid),
        .Y(inv_n35)
    );

    sky130_fd_sc_hd__nor2b_1 U145 (
        .A(aw_done),
        .B_N(s_axi_awvalid),
        .Y(n500)
    );

    sky130_fd_sc_hd__mux2_1 U146 (
        .A0(s_axi_awaddr_0),
        .A1(wr_addr_0),
        .S(n500),
        .X(n503)
    );

    sky130_fd_sc_hd__mux2_1 U147 (
        .A0(s_axi_awaddr_1),
        .A1(wr_addr_1),
        .S(n500),
        .X(n506)
    );

    sky130_fd_sc_hd__mux2_1 U148 (
        .A0(s_axi_awaddr_2),
        .A1(wr_addr_2),
        .S(n500),
        .X(n509)
    );

    sky130_fd_sc_hd__mux2_1 U149 (
        .A0(s_axi_awaddr_3),
        .A1(wr_addr_3),
        .S(n500),
        .X(n512)
    );

    sky130_fd_sc_hd__mux2_1 U150 (
        .A0(s_axi_awaddr_5),
        .A1(wr_addr_5),
        .S(n500),
        .X(n515)
    );

    sky130_fd_sc_hd__mux2_1 U151 (
        .A0(s_axi_awaddr_4),
        .A1(wr_addr_4),
        .S(n500),
        .X(n518)
    );

    sky130_fd_sc_hd__nand2_1 U152 (
        .A(n515),
        .B(n518),
        .Y(n519)
    );

    sky130_fd_sc_hd__mux2_1 U153 (
        .A0(s_axi_awaddr_7),
        .A1(wr_addr_7),
        .S(n500),
        .X(n522)
    );

    sky130_fd_sc_hd__mux2_1 U154 (
        .A0(s_axi_awaddr_6),
        .A1(wr_addr_6),
        .S(n500),
        .X(n525)
    );

    sky130_fd_sc_hd__nand2_1 U155 (
        .A(n522),
        .B(n525),
        .Y(n526)
    );

    sky130_fd_sc_hd__nand2_1 U156 (
        .A(n519),
        .B(n526),
        .Y(n527)
    );

    sky130_fd_sc_hd__nand2_1 U157 (
        .A(n512),
        .B(n527),
        .Y(n528)
    );

    sky130_fd_sc_hd__nand2_1 U158 (
        .A(n509),
        .B(n528),
        .Y(n529)
    );

    sky130_fd_sc_hd__nand2_1 U159 (
        .A(n506),
        .B(n529),
        .Y(n530)
    );

    sky130_fd_sc_hd__nand2_1 U160 (
        .A(n503),
        .B(n530),
        .Y(n531)
    );

    sky130_fd_sc_hd__o22a_1 U161 (
        .A1(s_axi_awvalid),
        .A2(aw_done),
        .B1(s_axi_wvalid),
        .B2(w_done),
        .X(n535)
    );

    sky130_fd_sc_hd__nor2_1 U162 (
        .A(s_axi_bvalid),
        .B(n535),
        .Y(n536)
    );

    sky130_fd_sc_hd__nand2_1 U163 (
        .A(s_axi_wdata_5),
        .B(s_axi_wstrb_0),
        .Y(n537)
    );

    sky130_fd_sc_hd__nand3_1 U164 (
        .A(s_axi_wdata_5),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n538)
    );

    sky130_fd_sc_hd__nand2_1 U165 (
        .A(s_axi_wstrb_0),
        .B(n536),
        .Y(n539)
    );

    sky130_fd_sc_hd__a21oi_1 U166 (
        .A1(abort_req_n157),
        .A2(clone_201),
        .B1(n538),
        .Y(n541)
    );

    sky130_fd_sc_hd__nor2b_1 U167 (
        .A(n541),
        .B_N(buf_rst_n_0),
        .Y(n542)
    );

    sky130_fd_sc_hd__nand2_1 U168 (
        .A(n531),
        .B(n542),
        .Y(n543)
    );

    sky130_fd_sc_hd__nor2b_1 U169 (
        .A(n531),
        .B_N(buf_rst_n_0),
        .Y(n544)
    );

    sky130_fd_sc_hd__a21oi_1 U170 (
        .A1(abort_req_n157),
        .A2(n544),
        .B1(n543),
        .Y(__dff_d_ff3315)
    );

    sky130_fd_sc_hd__inv_1 U171 (
        .A(aw_done),
        .Y(inv_n159)
    );

    sky130_fd_sc_hd__a211oi_1 U172 (
        .A1(inv_n35),
        .A2(inv_n159),
        .B1(inv_n2),
        .C1(n536),
        .Y(__dff_d_ff3316)
    );

    sky130_fd_sc_hd__nand2_1 U173 (
        .A(s_axi_wdata_4),
        .B(s_axi_wstrb_0),
        .Y(n551)
    );

    sky130_fd_sc_hd__nand3_1 U174 (
        .A(s_axi_wdata_4),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n552)
    );

    sky130_fd_sc_hd__a211oi_1 U175 (
        .A1(clk_gate_reg_0),
        .A2(clone_201),
        .B1(clone_212),
        .C1(n552),
        .Y(n554)
    );

    sky130_fd_sc_hd__inv_1 U176 (
        .A(clk_gate_reg_0),
        .Y(inv_n160)
    );

    sky130_fd_sc_hd__a21oi_1 U177 (
        .A1(inv_n160),
        .A2(n544),
        .B1(n554),
        .Y(__dff_d_ff3317)
    );

    sky130_fd_sc_hd__nor2b_1 U178 (
        .A(s_axi_wdata_3),
        .B_N(s_axi_wstrb_0),
        .Y(n559)
    );

    sky130_fd_sc_hd__nand3_1 U179 (
        .A(s_axi_wdata_3),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n564)
    );

    sky130_fd_sc_hd__a211oi_1 U180 (
        .A1(n531),
        .A2(n564),
        .B1(inv_n2),
        .C1(clk_gate_reg_1),
        .Y(n566)
    );

    sky130_fd_sc_hd__nor2_1 U181 (
        .A(n562),
        .B(n566),
        .Y(__dff_d_ff3318)
    );

    sky130_fd_sc_hd__nor2b_1 U182 (
        .A(s_axi_wdata_2),
        .B_N(s_axi_wstrb_0),
        .Y(n569)
    );

    sky130_fd_sc_hd__inv_1 U183 (
        .A(s_axi_wdata_2),
        .Y(inv_n38)
    );

    sky130_fd_sc_hd__inv_1 U184 (
        .A(clk_gate_reg_2),
        .Y(inv_n162)
    );

    sky130_fd_sc_hd__a31oi_1 U185 (
        .A1(inv_n38),
        .A2(s_axi_wstrb_0),
        .A3(n557),
        .B1(inv_n162),
        .Y(n571)
    );

    sky130_fd_sc_hd__nand3_1 U186 (
        .A(s_axi_wdata_2),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n572)
    );

    sky130_fd_sc_hd__a21oi_1 U187 (
        .A1(buf_rst_n_0),
        .A2(n572),
        .B1(clk_gate_reg_2),
        .Y(n574)
    );

    sky130_fd_sc_hd__nor2_1 U188 (
        .A(n571),
        .B(n574),
        .Y(n575)
    );

    sky130_fd_sc_hd__nand2_1 U189 (
        .A(n531),
        .B(n575),
        .Y(n576)
    );

    sky130_fd_sc_hd__a21oi_1 U190 (
        .A1(inv_n162),
        .A2(n544),
        .B1(n576),
        .Y(__dff_d_ff3319)
    );

    sky130_fd_sc_hd__inv_1 U191 (
        .A(s_axi_wdata_1),
        .Y(inv_n37)
    );

    sky130_fd_sc_hd__inv_1 U192 (
        .A(clk_gate_reg_3),
        .Y(inv_n163)
    );

    sky130_fd_sc_hd__a31oi_1 U193 (
        .A1(inv_n37),
        .A2(s_axi_wstrb_0),
        .A3(n557),
        .B1(inv_n163),
        .Y(n582)
    );

    sky130_fd_sc_hd__nand3_1 U194 (
        .A(s_axi_wdata_1),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n583)
    );

    sky130_fd_sc_hd__a21oi_1 U195 (
        .A1(buf_rst_n_0),
        .A2(n583),
        .B1(clk_gate_reg_3),
        .Y(n585)
    );

    sky130_fd_sc_hd__nor2_1 U196 (
        .A(n582),
        .B(n585),
        .Y(n586)
    );

    sky130_fd_sc_hd__nand2_1 U197 (
        .A(n531),
        .B(n586),
        .Y(n587)
    );

    sky130_fd_sc_hd__a21oi_1 U198 (
        .A1(inv_n163),
        .A2(n544),
        .B1(n587),
        .Y(__dff_d_ff3320)
    );

    sky130_fd_sc_hd__nor2b_1 U199 (
        .A(s_axi_wdata_0),
        .B_N(s_axi_wstrb_0),
        .Y(n591)
    );

    sky130_fd_sc_hd__inv_1 U200 (
        .A(s_axi_wdata_0),
        .Y(inv_n36)
    );

    sky130_fd_sc_hd__inv_1 U201 (
        .A(clk_gate_reg_4),
        .Y(inv_n164)
    );

    sky130_fd_sc_hd__a31oi_1 U202 (
        .A1(inv_n36),
        .A2(s_axi_wstrb_0),
        .A3(n557),
        .B1(inv_n164),
        .Y(n593)
    );

    sky130_fd_sc_hd__nand3_1 U203 (
        .A(s_axi_wdata_0),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n594)
    );

    sky130_fd_sc_hd__a21oi_1 U204 (
        .A1(buf_rst_n_0),
        .A2(n594),
        .B1(clk_gate_reg_4),
        .Y(n596)
    );

    sky130_fd_sc_hd__nor2_1 U205 (
        .A(n593),
        .B(n596),
        .Y(n597)
    );

    sky130_fd_sc_hd__nand2_1 U206 (
        .A(n531),
        .B(n597),
        .Y(n598)
    );

    sky130_fd_sc_hd__a21oi_1 U207 (
        .A1(inv_n164),
        .A2(n544),
        .B1(n598),
        .Y(__dff_d_ff3321)
    );

    sky130_fd_sc_hd__o31ai_1 U208 (
        .A1(clone_249),
        .A2(clone_250),
        .A3(n569),
        .B1(buf_rst_n_0),
        .Y(n603)
    );

    sky130_fd_sc_hd__mux2_1 U209 (
        .A0(n603),
        .A1(n605),
        .S(iso_ctrl_reg_0),
        .X(__dff_d_ff3322)
    );

    sky130_fd_sc_hd__a31oi_1 U210 (
        .A1(inv_n37),
        .A2(s_axi_wstrb_0),
        .A3(n536),
        .B1(inv_n2),
        .Y(n609)
    );

    sky130_fd_sc_hd__a21oi_1 U211 (
        .A1(n531),
        .A2(n609),
        .B1(n544),
        .Y(n611)
    );

    sky130_fd_sc_hd__mux2_1 U212 (
        .A0(n611),
        .A1(n614),
        .S(iso_ctrl_reg_1),
        .X(__dff_d_ff3323)
    );

    sky130_fd_sc_hd__a21o_1 U213 (
        .A1(n531),
        .A2(n536),
        .B1(inv_n2),
        .X(n618)
    );

    sky130_fd_sc_hd__mux2_1 U214 (
        .A0(n618),
        .A1(n620),
        .S(n591),
        .X(n622)
    );

    sky130_fd_sc_hd__mux2_1 U215 (
        .A0(n622),
        .A1(n624),
        .S(iso_ctrl_reg_2),
        .X(__dff_d_ff3324)
    );

    sky130_fd_sc_hd__nand2_1 U216 (
        .A(s_axi_wstrb_1),
        .B(n536),
        .Y(n627)
    );

    sky130_fd_sc_hd__o21a_1 U217 (
        .A1(pwr_dn_delay_0),
        .A2(n627),
        .B1(buf_rst_n_0),
        .X(n630)
    );

    sky130_fd_sc_hd__inv_1 U218 (
        .A(s_axi_wdata_15),
        .Y(inv_n51)
    );

    sky130_fd_sc_hd__a31oi_1 U219 (
        .A1(inv_n51),
        .A2(s_axi_wstrb_1),
        .A3(n536),
        .B1(n630),
        .Y(n631)
    );

    sky130_fd_sc_hd__nand2_1 U220 (
        .A(n531),
        .B(n631),
        .Y(n632)
    );

    sky130_fd_sc_hd__a21oi_1 U221 (
        .A1(pwr_dn_delay_0),
        .A2(n544),
        .B1(n632),
        .Y(__dff_d_ff3325)
    );

    sky130_fd_sc_hd__nand3_1 U222 (
        .A(s_axi_wstrb_1),
        .B(n531),
        .C(n536),
        .Y(n635)
    );

    sky130_fd_sc_hd__o21a_1 U223 (
        .A1(s_axi_wdata_14),
        .A2(n635),
        .B1(buf_rst_n_0),
        .X(n637)
    );

    sky130_fd_sc_hd__nor2b_1 U224 (
        .A(n637),
        .B_N(pwr_dn_delay_1),
        .Y(n638)
    );

    sky130_fd_sc_hd__a21oi_1 U225 (
        .A1(s_axi_wdata_14),
        .A2(n639),
        .B1(pwr_dn_delay_1),
        .Y(n641)
    );

    sky130_fd_sc_hd__nor2_1 U226 (
        .A(n638),
        .B(n641),
        .Y(__dff_d_ff3326)
    );

    sky130_fd_sc_hd__inv_1 U227 (
        .A(s_axi_wdata_13),
        .Y(inv_n49)
    );

    sky130_fd_sc_hd__a211oi_1 U228 (
        .A1(s_axi_wdata_13),
        .A2(n627),
        .B1(inv_n2),
        .C1(pwr_dn_delay_2),
        .Y(n648)
    );

    sky130_fd_sc_hd__nor2_1 U229 (
        .A(n645),
        .B(n648),
        .Y(n649)
    );

    sky130_fd_sc_hd__nor2_1 U230 (
        .A(clone_249),
        .B(n649),
        .Y(n650)
    );

    sky130_fd_sc_hd__inv_1 U231 (
        .A(pwr_dn_delay_2),
        .Y(inv_n170)
    );

    sky130_fd_sc_hd__a21oi_1 U232 (
        .A1(inv_n170),
        .A2(n544),
        .B1(n650),
        .Y(__dff_d_ff3327)
    );

    sky130_fd_sc_hd__o21a_1 U233 (
        .A1(s_axi_wdata_12),
        .A2(n635),
        .B1(buf_rst_n_0),
        .X(n654)
    );

    sky130_fd_sc_hd__nor2b_1 U234 (
        .A(n654),
        .B_N(pwr_dn_delay_3),
        .Y(n655)
    );

    sky130_fd_sc_hd__a21oi_1 U235 (
        .A1(s_axi_wdata_12),
        .A2(n639),
        .B1(pwr_dn_delay_3),
        .Y(n657)
    );

    sky130_fd_sc_hd__nor2_1 U236 (
        .A(n655),
        .B(n657),
        .Y(__dff_d_ff3328)
    );

    sky130_fd_sc_hd__o21a_1 U237 (
        .A1(s_axi_wdata_11),
        .A2(n635),
        .B1(buf_rst_n_0),
        .X(n660)
    );

    sky130_fd_sc_hd__nor2b_1 U238 (
        .A(n660),
        .B_N(pwr_dn_delay_4),
        .Y(n661)
    );

    sky130_fd_sc_hd__a21oi_1 U239 (
        .A1(s_axi_wdata_11),
        .A2(n639),
        .B1(pwr_dn_delay_4),
        .Y(n663)
    );

    sky130_fd_sc_hd__nor2_1 U240 (
        .A(n661),
        .B(n663),
        .Y(__dff_d_ff3329)
    );

    sky130_fd_sc_hd__o21a_1 U241 (
        .A1(s_axi_wdata_10),
        .A2(n635),
        .B1(buf_rst_n_0),
        .X(n666)
    );

    sky130_fd_sc_hd__nor2b_1 U242 (
        .A(n666),
        .B_N(pwr_dn_delay_5),
        .Y(n667)
    );

    sky130_fd_sc_hd__a21oi_1 U243 (
        .A1(s_axi_wdata_10),
        .A2(n639),
        .B1(pwr_dn_delay_5),
        .Y(n669)
    );

    sky130_fd_sc_hd__nor2_1 U244 (
        .A(n667),
        .B(n669),
        .Y(__dff_d_ff3330)
    );

    sky130_fd_sc_hd__o21a_1 U245 (
        .A1(s_axi_wdata_9),
        .A2(n635),
        .B1(buf_rst_n_0),
        .X(n672)
    );

    sky130_fd_sc_hd__nor2b_1 U246 (
        .A(n672),
        .B_N(pwr_dn_delay_6),
        .Y(n673)
    );

    sky130_fd_sc_hd__a21oi_1 U247 (
        .A1(s_axi_wdata_9),
        .A2(n639),
        .B1(pwr_dn_delay_6),
        .Y(n675)
    );

    sky130_fd_sc_hd__nor2_1 U248 (
        .A(n673),
        .B(n675),
        .Y(__dff_d_ff3331)
    );

    sky130_fd_sc_hd__o21a_1 U249 (
        .A1(s_axi_wdata_8),
        .A2(n635),
        .B1(buf_rst_n_0),
        .X(n678)
    );

    sky130_fd_sc_hd__nor2b_1 U250 (
        .A(n678),
        .B_N(pwr_dn_delay_7),
        .Y(n679)
    );

    sky130_fd_sc_hd__a21oi_1 U251 (
        .A1(s_axi_wdata_8),
        .A2(n639),
        .B1(pwr_dn_delay_7),
        .Y(n681)
    );

    sky130_fd_sc_hd__nor2_1 U252 (
        .A(n679),
        .B(n681),
        .Y(__dff_d_ff3332)
    );

    sky130_fd_sc_hd__nand2_1 U253 (
        .A(s_axi_wdata_7),
        .B(s_axi_wstrb_0),
        .Y(n683)
    );

    sky130_fd_sc_hd__nand3_1 U254 (
        .A(s_axi_wdata_7),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n684)
    );

    sky130_fd_sc_hd__a31oi_1 U255 (
        .A1(n531),
        .A2(n539),
        .A3(clone_311),
        .B1(inv_n2),
        .Y(n687)
    );

    sky130_fd_sc_hd__nor2b_1 U256 (
        .A(n687),
        .B_N(pwr_up_delay_0),
        .Y(n688)
    );

    sky130_fd_sc_hd__a31oi_1 U257 (
        .A1(buf_rst_n_0),
        .A2(n531),
        .A3(n684),
        .B1(pwr_up_delay_0),
        .Y(n690)
    );

    sky130_fd_sc_hd__nor2_1 U258 (
        .A(n688),
        .B(n690),
        .Y(__dff_d_ff3333)
    );

    sky130_fd_sc_hd__nand2_1 U259 (
        .A(s_axi_wdata_6),
        .B(s_axi_wstrb_0),
        .Y(n692)
    );

    sky130_fd_sc_hd__nand3_1 U260 (
        .A(s_axi_wdata_6),
        .B(s_axi_wstrb_0),
        .C(n536),
        .Y(n693)
    );

    sky130_fd_sc_hd__a31oi_1 U261 (
        .A1(n531),
        .A2(n539),
        .A3(clone_319),
        .B1(inv_n2),
        .Y(n695)
    );

    sky130_fd_sc_hd__nor2b_1 U262 (
        .A(n695),
        .B_N(pwr_up_delay_1),
        .Y(n696)
    );

    sky130_fd_sc_hd__a31oi_1 U263 (
        .A1(buf_rst_n_0),
        .A2(n531),
        .A3(n693),
        .B1(pwr_up_delay_1),
        .Y(n698)
    );

    sky130_fd_sc_hd__nor2_1 U264 (
        .A(n696),
        .B(n698),
        .Y(__dff_d_ff3334)
    );

    sky130_fd_sc_hd__nor2b_1 U265 (
        .A(s_axi_wdata_5),
        .B_N(s_axi_wstrb_0),
        .Y(n700)
    );

    sky130_fd_sc_hd__inv_1 U266 (
        .A(s_axi_wdata_5),
        .Y(inv_n41)
    );

    sky130_fd_sc_hd__inv_1 U267 (
        .A(pwr_up_delay_2),
        .Y(inv_n178)
    );

    sky130_fd_sc_hd__a31oi_1 U268 (
        .A1(inv_n41),
        .A2(s_axi_wstrb_0),
        .A3(n557),
        .B1(inv_n178),
        .Y(n702)
    );

    sky130_fd_sc_hd__a21oi_1 U269 (
        .A1(buf_rst_n_0),
        .A2(clone_329),
        .B1(pwr_up_delay_2),
        .Y(n704)
    );

    sky130_fd_sc_hd__nor2_1 U270 (
        .A(n702),
        .B(n704),
        .Y(n705)
    );

    sky130_fd_sc_hd__nand2_1 U271 (
        .A(n531),
        .B(n705),
        .Y(n706)
    );

    sky130_fd_sc_hd__a21oi_1 U272 (
        .A1(inv_n178),
        .A2(n544),
        .B1(n706),
        .Y(__dff_d_ff3335)
    );

    sky130_fd_sc_hd__o31ai_1 U273 (
        .A1(clone_249),
        .A2(clone_201),
        .A3(n551),
        .B1(buf_rst_n_0),
        .Y(n711)
    );

    sky130_fd_sc_hd__mux2_1 U274 (
        .A0(n711),
        .A1(n713),
        .S(pwr_up_delay_3),
        .X(__dff_d_ff3336)
    );

    sky130_fd_sc_hd__mux2_1 U275 (
        .A0(n618),
        .A1(n620),
        .S(n559),
        .X(n718)
    );

    sky130_fd_sc_hd__mux2_1 U276 (
        .A0(n718),
        .A1(n720),
        .S(pwr_up_delay_4),
        .X(__dff_d_ff3337)
    );

    sky130_fd_sc_hd__mux2_1 U277 (
        .A0(n603),
        .A1(n605),
        .S(pwr_up_delay_5),
        .X(__dff_d_ff3338)
    );

    sky130_fd_sc_hd__mux2_1 U278 (
        .A0(n611),
        .A1(n614),
        .S(pwr_up_delay_6),
        .X(__dff_d_ff3339)
    );

    sky130_fd_sc_hd__mux2_1 U279 (
        .A0(n622),
        .A1(n624),
        .S(pwr_up_delay_7),
        .X(__dff_d_ff3340)
    );

    sky130_fd_sc_hd__mux2_1 U280 (
        .A0(n622),
        .A1(n624),
        .S(ret_ctrl_reg),
        .X(__dff_d_ff3341)
    );

    sky130_fd_sc_hd__inv_1 U281 (
        .A(s_axi_bvalid),
        .Y(inv_n188)
    );

    sky130_fd_sc_hd__a211oi_1 U282 (
        .A1(inv_n188),
        .A2(clone_250),
        .B1(inv_n2),
        .C1(s_axi_bready),
        .Y(__dff_d_ff3345)
    );

    sky130_fd_sc_hd__inv_1 U283 (
        .A(w_done),
        .Y(inv_n193)
    );

    sky130_fd_sc_hd__mux2_1 U284 (
        .A0(n609),
        .A1(n613),
        .S(__dff_d_ff2270),
        .X(n746)
    );

    sky130_fd_sc_hd__nand2_1 U285 (
        .A(n531),
        .B(n746),
        .Y(n747)
    );

    sky130_fd_sc_hd__o21a_1 U286 (
        .A1(n406),
        .A2(n531),
        .B1(n747),
        .X(__dff_d_ff3347)
    );

    sky130_fd_sc_hd__mux2_1 U287 (
        .A0(n622),
        .A1(n624),
        .S(__dff_d_ff2271),
        .X(__dff_d_ff3348)
    );

    sky130_fd_sc_hd__mux2_1 U288 (
        .A0(n711),
        .A1(n713),
        .S(transition_req_n191),
        .X(__dff_d_ff3349)
    );

    sky130_fd_sc_hd__inv_1 U289 (
        .A(s_axi_wvalid),
        .Y(inv_n72)
    );

    sky130_fd_sc_hd__a211oi_1 U290 (
        .A1(inv_n72),
        .A2(inv_n193),
        .B1(inv_n2),
        .C1(n536),
        .Y(__dff_d_ff3350)
    );

    sky130_fd_sc_hd__inv_1 U291 (
        .A(wake_en_reg_0),
        .Y(inv_n194)
    );

    sky130_fd_sc_hd__a211oi_1 U292 (
        .A1(n539),
        .A2(n683),
        .B1(inv_n2),
        .C1(inv_n194),
        .Y(n761)
    );

    sky130_fd_sc_hd__nor2_1 U293 (
        .A(n758),
        .B(n761),
        .Y(n762)
    );

    sky130_fd_sc_hd__nor2_1 U294 (
        .A(clone_249),
        .B(n762),
        .Y(n763)
    );

    sky130_fd_sc_hd__a21oi_1 U295 (
        .A1(wake_en_reg_0),
        .A2(n544),
        .B1(n763),
        .Y(__dff_d_ff3351)
    );

    sky130_fd_sc_hd__inv_1 U296 (
        .A(wake_en_reg_1),
        .Y(inv_n195)
    );

    sky130_fd_sc_hd__a211oi_1 U297 (
        .A1(n539),
        .A2(n692),
        .B1(inv_n2),
        .C1(inv_n195),
        .Y(n769)
    );

    sky130_fd_sc_hd__nor2_1 U298 (
        .A(n766),
        .B(n769),
        .Y(n770)
    );

    sky130_fd_sc_hd__nor2_1 U299 (
        .A(clone_249),
        .B(n770),
        .Y(n771)
    );

    sky130_fd_sc_hd__a21oi_1 U300 (
        .A1(wake_en_reg_1),
        .A2(n544),
        .B1(n771),
        .Y(__dff_d_ff3352)
    );

    sky130_fd_sc_hd__a31oi_1 U301 (
        .A1(n531),
        .A2(n536),
        .A3(n700),
        .B1(inv_n2),
        .Y(n776)
    );

    sky130_fd_sc_hd__nor2b_1 U302 (
        .A(n776),
        .B_N(wake_en_reg_2),
        .Y(n777)
    );

    sky130_fd_sc_hd__a31oi_1 U303 (
        .A1(buf_rst_n_0),
        .A2(n531),
        .A3(n538),
        .B1(wake_en_reg_2),
        .Y(n779)
    );

    sky130_fd_sc_hd__nor2_1 U304 (
        .A(n777),
        .B(n779),
        .Y(__dff_d_ff3353)
    );

    sky130_fd_sc_hd__mux2_1 U305 (
        .A0(n711),
        .A1(n713),
        .S(wake_en_reg_3),
        .X(__dff_d_ff3354)
    );

    sky130_fd_sc_hd__mux2_1 U306 (
        .A0(n718),
        .A1(n720),
        .S(wake_en_reg_4),
        .X(__dff_d_ff3355)
    );

    sky130_fd_sc_hd__mux2_1 U307 (
        .A0(n603),
        .A1(n605),
        .S(wake_en_reg_5),
        .X(__dff_d_ff3356)
    );

    sky130_fd_sc_hd__mux2_1 U308 (
        .A0(n611),
        .A1(n614),
        .S(wake_en_reg_6),
        .X(__dff_d_ff3357)
    );

    sky130_fd_sc_hd__mux2_1 U309 (
        .A0(n622),
        .A1(n624),
        .S(wake_en_reg_7),
        .X(__dff_d_ff3358)
    );

    sky130_fd_sc_hd__inv_1 U310 (
        .A(wake_stat_reg_0_n201),
        .Y(inv_n202)
    );

    sky130_fd_sc_hd__a31oi_1 U311 (
        .A1(buf_rst_n_0),
        .A2(n531),
        .A3(n684),
        .B1(inv_n202),
        .Y(__dff_d_ff3359)
    );

    sky130_fd_sc_hd__inv_1 U312 (
        .A(wake_stat_reg_1_n202),
        .Y(inv_n203)
    );

    sky130_fd_sc_hd__a31oi_1 U313 (
        .A1(buf_rst_n_0),
        .A2(n531),
        .A3(n693),
        .B1(inv_n203),
        .Y(__dff_d_ff3360)
    );

    sky130_fd_sc_hd__inv_1 U314 (
        .A(wake_stat_reg_2_n203),
        .Y(inv_n204)
    );

    sky130_fd_sc_hd__a31oi_1 U315 (
        .A1(n531),
        .A2(n537),
        .A3(n557),
        .B1(inv_n204),
        .Y(__dff_d_ff3361)
    );

    sky130_fd_sc_hd__nor2b_1 U316 (
        .A(n713),
        .B_N(wake_stat_reg_3_n204),
        .Y(__dff_d_ff3362)
    );

    sky130_fd_sc_hd__nor2b_1 U317 (
        .A(n720),
        .B_N(wake_stat_reg_4_n205),
        .Y(__dff_d_ff3363)
    );

    sky130_fd_sc_hd__nor2b_1 U318 (
        .A(n605),
        .B_N(wake_stat_reg_5_n206),
        .Y(__dff_d_ff3364)
    );

    sky130_fd_sc_hd__nor2b_1 U319 (
        .A(n614),
        .B_N(wake_stat_reg_6_n207),
        .Y(__dff_d_ff3365)
    );

    sky130_fd_sc_hd__nor2b_1 U320 (
        .A(n624),
        .B_N(wake_stat_reg_7_n208),
        .Y(__dff_d_ff3366)
    );

    sky130_fd_sc_hd__nor2b_1 U321 (
        .A(n503),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3367)
    );

    sky130_fd_sc_hd__nor2b_1 U322 (
        .A(n506),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3368)
    );

    sky130_fd_sc_hd__nor2b_1 U323 (
        .A(n509),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3369)
    );

    sky130_fd_sc_hd__nor2b_1 U324 (
        .A(n512),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3370)
    );

    sky130_fd_sc_hd__nor2b_1 U325 (
        .A(n518),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3371)
    );

    sky130_fd_sc_hd__nor2b_1 U326 (
        .A(n515),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3372)
    );

    sky130_fd_sc_hd__nor2b_1 U327 (
        .A(n525),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3373)
    );

    sky130_fd_sc_hd__nor2b_1 U328 (
        .A(n522),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff3374)
    );

    sky130_fd_sc_hd__o21a_1 U329 (
        .A1(wr_addr_8),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n818)
    );

    sky130_fd_sc_hd__o21a_1 U330 (
        .A1(s_axi_awaddr_8),
        .A2(clone_405),
        .B1(n818),
        .X(__dff_d_ff3375)
    );

    sky130_fd_sc_hd__o21a_1 U331 (
        .A1(wr_addr_9),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n822)
    );

    sky130_fd_sc_hd__o21a_1 U332 (
        .A1(s_axi_awaddr_9),
        .A2(clone_405),
        .B1(n822),
        .X(__dff_d_ff3376)
    );

    sky130_fd_sc_hd__o21a_1 U333 (
        .A1(wr_addr_10),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n826)
    );

    sky130_fd_sc_hd__o21a_1 U334 (
        .A1(s_axi_awaddr_10),
        .A2(clone_405),
        .B1(n826),
        .X(__dff_d_ff3377)
    );

    sky130_fd_sc_hd__o21a_1 U335 (
        .A1(wr_addr_11),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n830)
    );

    sky130_fd_sc_hd__o21a_1 U336 (
        .A1(s_axi_awaddr_11),
        .A2(clone_405),
        .B1(n830),
        .X(__dff_d_ff3378)
    );

    sky130_fd_sc_hd__o21a_1 U337 (
        .A1(wr_addr_12),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n834)
    );

    sky130_fd_sc_hd__o21a_1 U338 (
        .A1(s_axi_awaddr_12),
        .A2(clone_405),
        .B1(n834),
        .X(__dff_d_ff3379)
    );

    sky130_fd_sc_hd__o21a_1 U339 (
        .A1(wr_addr_13),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n838)
    );

    sky130_fd_sc_hd__o21a_1 U340 (
        .A1(s_axi_awaddr_13),
        .A2(clone_405),
        .B1(n838),
        .X(__dff_d_ff3380)
    );

    sky130_fd_sc_hd__o21a_1 U341 (
        .A1(wr_addr_14),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n842)
    );

    sky130_fd_sc_hd__o21a_1 U342 (
        .A1(s_axi_awaddr_14),
        .A2(clone_405),
        .B1(n842),
        .X(__dff_d_ff3381)
    );

    sky130_fd_sc_hd__o21a_1 U343 (
        .A1(wr_addr_15),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n846)
    );

    sky130_fd_sc_hd__o21a_1 U344 (
        .A1(s_axi_awaddr_15),
        .A2(clone_405),
        .B1(n846),
        .X(__dff_d_ff3382)
    );

    sky130_fd_sc_hd__o21a_1 U345 (
        .A1(wr_addr_16),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n850)
    );

    sky130_fd_sc_hd__o21a_1 U346 (
        .A1(s_axi_awaddr_16),
        .A2(clone_405),
        .B1(n850),
        .X(__dff_d_ff3383)
    );

    sky130_fd_sc_hd__o21a_1 U347 (
        .A1(wr_addr_17),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n854)
    );

    sky130_fd_sc_hd__o21a_1 U348 (
        .A1(s_axi_awaddr_17),
        .A2(clone_405),
        .B1(n854),
        .X(__dff_d_ff3384)
    );

    sky130_fd_sc_hd__o21a_1 U349 (
        .A1(wr_addr_18),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n858)
    );

    sky130_fd_sc_hd__o21a_1 U350 (
        .A1(s_axi_awaddr_18),
        .A2(clone_405),
        .B1(n858),
        .X(__dff_d_ff3385)
    );

    sky130_fd_sc_hd__o21a_1 U351 (
        .A1(wr_addr_19),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n862)
    );

    sky130_fd_sc_hd__o21a_1 U352 (
        .A1(s_axi_awaddr_19),
        .A2(clone_405),
        .B1(n862),
        .X(__dff_d_ff3386)
    );

    sky130_fd_sc_hd__o21a_1 U353 (
        .A1(wr_addr_20),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n866)
    );

    sky130_fd_sc_hd__o21a_1 U354 (
        .A1(s_axi_awaddr_20),
        .A2(clone_405),
        .B1(n866),
        .X(__dff_d_ff3387)
    );

    sky130_fd_sc_hd__o21a_1 U355 (
        .A1(wr_addr_21),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n870)
    );

    sky130_fd_sc_hd__o21a_1 U356 (
        .A1(s_axi_awaddr_21),
        .A2(clone_405),
        .B1(n870),
        .X(__dff_d_ff3388)
    );

    sky130_fd_sc_hd__o21a_1 U357 (
        .A1(wr_addr_22),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n874)
    );

    sky130_fd_sc_hd__o21a_1 U358 (
        .A1(s_axi_awaddr_22),
        .A2(clone_405),
        .B1(n874),
        .X(__dff_d_ff3389)
    );

    sky130_fd_sc_hd__o21a_1 U359 (
        .A1(wr_addr_23),
        .A2(n500),
        .B1(buf_rst_n_0),
        .X(n878)
    );

    sky130_fd_sc_hd__o21a_1 U360 (
        .A1(s_axi_awaddr_23),
        .A2(clone_405),
        .B1(n878),
        .X(__dff_d_ff3390)
    );

    sky130_fd_sc_hd__o21a_1 U361 (
        .A1(wr_addr_24),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n882)
    );

    sky130_fd_sc_hd__o21a_1 U362 (
        .A1(s_axi_awaddr_24),
        .A2(clone_405),
        .B1(n882),
        .X(__dff_d_ff3391)
    );

    sky130_fd_sc_hd__o21a_1 U363 (
        .A1(wr_addr_25),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n886)
    );

    sky130_fd_sc_hd__o21a_1 U364 (
        .A1(s_axi_awaddr_25),
        .A2(clone_405),
        .B1(n886),
        .X(__dff_d_ff3392)
    );

    sky130_fd_sc_hd__o21a_1 U365 (
        .A1(wr_addr_26),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n890)
    );

    sky130_fd_sc_hd__o21a_1 U366 (
        .A1(s_axi_awaddr_26),
        .A2(clone_405),
        .B1(n890),
        .X(__dff_d_ff3393)
    );

    sky130_fd_sc_hd__o21a_1 U367 (
        .A1(wr_addr_27),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n894)
    );

    sky130_fd_sc_hd__o21a_1 U368 (
        .A1(s_axi_awaddr_27),
        .A2(clone_405),
        .B1(n894),
        .X(__dff_d_ff3394)
    );

    sky130_fd_sc_hd__o21a_1 U369 (
        .A1(wr_addr_28),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n898)
    );

    sky130_fd_sc_hd__o21a_1 U370 (
        .A1(s_axi_awaddr_28),
        .A2(clone_405),
        .B1(n898),
        .X(__dff_d_ff3395)
    );

    sky130_fd_sc_hd__o21a_1 U371 (
        .A1(wr_addr_29),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n902)
    );

    sky130_fd_sc_hd__o21a_1 U372 (
        .A1(s_axi_awaddr_29),
        .A2(clone_405),
        .B1(n902),
        .X(__dff_d_ff3396)
    );

    sky130_fd_sc_hd__o21a_1 U373 (
        .A1(wr_addr_30),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n906)
    );

    sky130_fd_sc_hd__o21a_1 U374 (
        .A1(s_axi_awaddr_30),
        .A2(clone_405),
        .B1(n906),
        .X(__dff_d_ff3397)
    );

    sky130_fd_sc_hd__o21a_1 U375 (
        .A1(wr_addr_31),
        .A2(n500),
        .B1(buf_rst_n_1),
        .X(n910)
    );

    sky130_fd_sc_hd__o21a_1 U376 (
        .A1(s_axi_awaddr_31),
        .A2(clone_405),
        .B1(n910),
        .X(__dff_d_ff3398)
    );

    sky130_fd_sc_hd__inv_1 U377 (
        .A(s_axi_arvalid),
        .Y(inv_n106)
    );

    sky130_fd_sc_hd__nor2b_1 U378 (
        .A(s_axi_rvalid),
        .B_N(s_axi_arvalid),
        .Y(n912)
    );

    sky130_fd_sc_hd__nand2_1 U379 (
        .A(buf_rst_n_1),
        .B(clone_455),
        .Y(__dff_d_ff4720)
    );

    sky130_fd_sc_hd__nor4_1 U380 (
        .A(s_axi_araddr_4),
        .B(s_axi_araddr_5),
        .C(s_axi_araddr_6),
        .D(s_axi_araddr_7),
        .Y(n917)
    );

    sky130_fd_sc_hd__nor2_1 U381 (
        .A(s_axi_araddr_2),
        .B(n917),
        .Y(n918)
    );

    sky130_fd_sc_hd__nor2_1 U382 (
        .A(s_axi_araddr_3),
        .B(n918),
        .Y(n919)
    );

    sky130_fd_sc_hd__nor2_1 U383 (
        .A(s_axi_araddr_1),
        .B(n919),
        .Y(n920)
    );

    sky130_fd_sc_hd__nor2_1 U384 (
        .A(s_axi_araddr_0),
        .B(n920),
        .Y(n921)
    );

    sky130_fd_sc_hd__nand2_1 U385 (
        .A(clone_455),
        .B(n921),
        .Y(n922)
    );

    sky130_fd_sc_hd__a22oi_1 U386 (
        .A1(__dff_d_ff2270),
        .A2(n922),
        .B1(s_axi_rdata_0),
        .B2(n912),
        .Y(n924)
    );

    sky130_fd_sc_hd__nor2b_1 U387 (
        .A(n924),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff4721)
    );

    sky130_fd_sc_hd__a22oi_1 U388 (
        .A1(__dff_d_ff2271),
        .A2(n922),
        .B1(s_axi_rdata_1),
        .B2(n912),
        .Y(n928)
    );

    sky130_fd_sc_hd__nor2b_1 U389 (
        .A(n928),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff4722)
    );

    sky130_fd_sc_hd__nand3_1 U390 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_2),
        .C(n912),
        .Y(__dff_d_ff4723)
    );

    sky130_fd_sc_hd__nand3_1 U391 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_3),
        .C(n912),
        .Y(__dff_d_ff4724)
    );

    sky130_fd_sc_hd__a22oi_1 U392 (
        .A1(transition_req_n191),
        .A2(n922),
        .B1(s_axi_rdata_4),
        .B2(n912),
        .Y(n936)
    );

    sky130_fd_sc_hd__nor2b_1 U393 (
        .A(n936),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff4725)
    );

    sky130_fd_sc_hd__a22oi_1 U394 (
        .A1(abort_req_n157),
        .A2(n922),
        .B1(s_axi_rdata_5),
        .B2(n912),
        .Y(n940)
    );

    sky130_fd_sc_hd__nor2b_1 U395 (
        .A(n940),
        .B_N(buf_rst_n_0),
        .Y(__dff_d_ff4726)
    );

    sky130_fd_sc_hd__nand3_1 U396 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_6),
        .C(n912),
        .Y(__dff_d_ff4727)
    );

    sky130_fd_sc_hd__nand3_1 U397 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_7),
        .C(n912),
        .Y(__dff_d_ff4728)
    );

    sky130_fd_sc_hd__nand3_1 U398 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_8),
        .C(n912),
        .Y(__dff_d_ff4729)
    );

    sky130_fd_sc_hd__nand3_1 U399 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_9),
        .C(n912),
        .Y(__dff_d_ff4730)
    );

    sky130_fd_sc_hd__nand3_1 U400 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_10),
        .C(n912),
        .Y(__dff_d_ff4731)
    );

    sky130_fd_sc_hd__nand3_1 U401 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_11),
        .C(n912),
        .Y(__dff_d_ff4732)
    );

    sky130_fd_sc_hd__nand3_1 U402 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_12),
        .C(n912),
        .Y(__dff_d_ff4733)
    );

    sky130_fd_sc_hd__nand3_1 U403 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_13),
        .C(n912),
        .Y(__dff_d_ff4734)
    );

    sky130_fd_sc_hd__nand3_1 U404 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_14),
        .C(n912),
        .Y(__dff_d_ff4735)
    );

    sky130_fd_sc_hd__nand3_1 U405 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_15),
        .C(n912),
        .Y(__dff_d_ff4736)
    );

    sky130_fd_sc_hd__nand3_1 U406 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_16),
        .C(n912),
        .Y(__dff_d_ff4737)
    );

    sky130_fd_sc_hd__nand3_1 U407 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_17),
        .C(n912),
        .Y(__dff_d_ff4738)
    );

    sky130_fd_sc_hd__nand3_1 U408 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_18),
        .C(n912),
        .Y(__dff_d_ff4739)
    );

    sky130_fd_sc_hd__nand3_1 U409 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_19),
        .C(n912),
        .Y(__dff_d_ff4740)
    );

    sky130_fd_sc_hd__nand3_1 U410 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_20),
        .C(n912),
        .Y(__dff_d_ff4741)
    );

    sky130_fd_sc_hd__nand3_1 U411 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_21),
        .C(n912),
        .Y(__dff_d_ff4742)
    );

    sky130_fd_sc_hd__nand3_1 U412 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_22),
        .C(n912),
        .Y(__dff_d_ff4743)
    );

    sky130_fd_sc_hd__nand3_1 U413 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_23),
        .C(n912),
        .Y(__dff_d_ff4744)
    );

    sky130_fd_sc_hd__nand3_1 U414 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_24),
        .C(n912),
        .Y(__dff_d_ff4745)
    );

    sky130_fd_sc_hd__nand3_1 U415 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_25),
        .C(n912),
        .Y(__dff_d_ff4746)
    );

    sky130_fd_sc_hd__nand3_1 U416 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_26),
        .C(n912),
        .Y(__dff_d_ff4747)
    );

    sky130_fd_sc_hd__nand3_1 U417 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_27),
        .C(n912),
        .Y(__dff_d_ff4748)
    );

    sky130_fd_sc_hd__nand3_1 U418 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_28),
        .C(n912),
        .Y(__dff_d_ff4749)
    );

    sky130_fd_sc_hd__nand3_1 U419 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_29),
        .C(n912),
        .Y(__dff_d_ff4750)
    );

    sky130_fd_sc_hd__nand3_1 U420 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_30),
        .C(n912),
        .Y(__dff_d_ff4751)
    );

    sky130_fd_sc_hd__nand3_1 U421 (
        .A(buf_rst_n_1),
        .B(s_axi_rdata_31),
        .C(n912),
        .Y(__dff_d_ff4752)
    );

    sky130_fd_sc_hd__nand3_1 U422 (
        .A(buf_rst_n_1),
        .B(s_axi_rresp_0),
        .C(n912),
        .Y(__dff_d_ff4753)
    );

    sky130_fd_sc_hd__nand3_1 U423 (
        .A(buf_rst_n_1),
        .B(s_axi_rresp_1),
        .C(n912),
        .Y(__dff_d_ff4754)
    );

    sky130_fd_sc_hd__inv_1 U424 (
        .A(s_axi_rvalid),
        .Y(inv_n277)
    );

    sky130_fd_sc_hd__a211oi_1 U425 (
        .A1(inv_n106),
        .A2(inv_n277),
        .B1(inv_n2),
        .C1(s_axi_rready),
        .Y(__dff_d_ff4755)
    );

    sky130_fd_sc_hd__buf_1 U426 (
        .A(wake_irq),
        .X(__dff_d_ff2267)
    );

    sky130_fd_sc_hd__and3b_1 U427 (
        .A_N(transitioning),
        .B(transition_req_n191),
        .C(n279),
        .X(clone_13)
    );

    sky130_fd_sc_hd__xnor2_1 U428 (
        .A(seq_counter_9),
        .B(n314),
        .Y(clone_57)
    );

    sky130_fd_sc_hd__xnor2_1 U429 (
        .A(seq_counter_8),
        .B(n320),
        .Y(clone_60)
    );

    sky130_fd_sc_hd__xnor2_1 U430 (
        .A(seq_counter_7),
        .B(n326),
        .Y(clone_63)
    );

    sky130_fd_sc_hd__xnor2_1 U431 (
        .A(seq_counter_6),
        .B(n332),
        .Y(clone_66)
    );

    sky130_fd_sc_hd__xnor2_1 U432 (
        .A(seq_counter_5),
        .B(n338),
        .Y(clone_69)
    );

    sky130_fd_sc_hd__xnor2_1 U433 (
        .A(seq_counter_4),
        .B(n344),
        .Y(clone_72)
    );

    sky130_fd_sc_hd__or3_1 U434 (
        .A(seq_state_0),
        .B(seq_state_1),
        .C(seq_state_2),
        .X(clone_85)
    );

    sky130_fd_sc_hd__or3_1 U435 (
        .A(seq_counter_0),
        .B(n358),
        .C(n379),
        .X(clone_87)
    );

    sky130_fd_sc_hd__and2_1 U436 (
        .A(abort_req_n157),
        .B(n294),
        .X(clone_93)
    );

    sky130_fd_sc_hd__or2b_1 U437 (
        .A(n295),
        .B_N(buf_rst_n_0),
        .X(clone_100)
    );

    sky130_fd_sc_hd__and4_1 U438 (
        .A(seq_state_0),
        .B(seq_state_1),
        .C(seq_state_2),
        .D(n381),
        .X(clone_109)
    );

    sky130_fd_sc_hd__or2_1 U439 (
        .A(__dff_d_ff2270),
        .B(__dff_d_ff2271),
        .X(clone_111)
    );

    sky130_fd_sc_hd__or2_1 U440 (
        .A(n281),
        .B(n291),
        .X(clone_154)
    );

    sky130_fd_sc_hd__or2_1 U441 (
        .A(n281),
        .B(n288),
        .X(clone_157)
    );

    sky130_fd_sc_hd__and2_1 U442 (
        .A(s_axi_wstrb_0),
        .B(n536),
        .X(clone_201)
    );

    sky130_fd_sc_hd__and2_1 U443 (
        .A(buf_rst_n_1),
        .B(n531),
        .X(clone_212)
    );

    sky130_fd_sc_hd__and2_1 U444 (
        .A(n503),
        .B(n530),
        .X(clone_249)
    );

    sky130_fd_sc_hd__or2_1 U445 (
        .A(s_axi_bvalid),
        .B(n535),
        .X(clone_250)
    );

    sky130_fd_sc_hd__and3_1 U446 (
        .A(s_axi_wdata_7),
        .B(s_axi_wstrb_0),
        .C(n536),
        .X(clone_311)
    );

    sky130_fd_sc_hd__and3_1 U447 (
        .A(s_axi_wdata_6),
        .B(s_axi_wstrb_0),
        .C(n536),
        .X(clone_319)
    );

    sky130_fd_sc_hd__and3_1 U448 (
        .A(s_axi_wdata_5),
        .B(s_axi_wstrb_0),
        .C(n536),
        .X(clone_329)
    );

    sky130_fd_sc_hd__or2b_1 U449 (
        .A(aw_done),
        .B_N(s_axi_awvalid),
        .X(clone_405)
    );

    sky130_fd_sc_hd__or2b_1 U450 (
        .A(s_axi_rvalid),
        .B_N(s_axi_arvalid),
        .X(clone_455)
    );

    sky130_fd_sc_hd__buf_1 U451 (
        .A(clone_111),
        .X(glitch_bal_112_1_n)
    );

    sky130_fd_sc_hd__buf_1 U452 (
        .A(n279),
        .X(glitch_bal_83_0_n)
    );

    sky130_fd_sc_hd__buf_1 U453 (
        .A(clone_100),
        .X(glitch_bal_118_1_n)
    );

    sky130_fd_sc_hd__buf_1 U454 (
        .A(clone_100),
        .X(glitch_bal_112_2_n)
    );

    sky130_fd_sc_hd__buf_1 U455 (
        .A(n295),
        .X(glitch_bal_113_2_n)
    );

    sky130_fd_sc_hd__buf_1 U456 (
        .A(n298),
        .X(glitch_bal_106_1_n)
    );

    sky130_fd_sc_hd__buf_1 U457 (
        .A(n298),
        .X(glitch_bal_108_2_n)
    );

    sky130_fd_sc_hd__buf_1 U458 (
        .A(n433),
        .X(glitch_bal_121_1_n)
    );

    sky130_fd_sc_hd__buf_1 U459 (
        .A(n409),
        .X(glitch_bal_105_1_n)
    );

    sky130_fd_sc_hd__buf_1 U460 (
        .A(n346),
        .X(glitch_bal_74_0_n)
    );

    sky130_fd_sc_hd__dfrtp_1 U461 (
        .D(__dff_d_ff2240),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(accel_clk_en)
    );

    sky130_fd_sc_hd__dfrtp_1 U462 (
        .D(__dff_d_ff2241),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(accel_iso)
    );

    sky130_fd_sc_hd__dfrtp_1 U463 (
        .D(__dff_d_ff2242),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cpu_clk_en)
    );

    sky130_fd_sc_hd__dfrtp_1 U464 (
        .D(__dff_d_ff2243),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(cpu_iso)
    );

    sky130_fd_sc_hd__dfrtp_1 U465 (
        .D(__dff_d_ff2244),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(current_state_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U466 (
        .D(__dff_d_ff2245),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(current_state_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U467 (
        .D(__dff_d_ff2246),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(domain_power_good_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U468 (
        .D(__dff_d_ff2247),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(domain_power_good_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U469 (
        .D(__dff_d_ff2248),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(domain_power_good_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U470 (
        .D(__dff_d_ff2249),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(domain_power_good_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U471 (
        .D(__dff_d_ff2250),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(mem_clk_en)
    );

    sky130_fd_sc_hd__dfrtp_1 U472 (
        .D(__dff_d_ff2251),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(periph_clk_en)
    );

    sky130_fd_sc_hd__dfrtp_1 U473 (
        .D(__dff_d_ff2252),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(periph_iso)
    );

    sky130_fd_sc_hd__dfrtp_1 U474 (
        .D(__dff_d_ff2254),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U475 (
        .D(__dff_d_ff2255),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U476 (
        .D(__dff_d_ff2256),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U477 (
        .D(__dff_d_ff2257),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U478 (
        .D(__dff_d_ff2258),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U479 (
        .D(__dff_d_ff2259),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U480 (
        .D(__dff_d_ff2260),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U481 (
        .D(__dff_d_ff2261),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U482 (
        .D(__dff_d_ff2262),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U483 (
        .D(__dff_d_ff2263),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U484 (
        .D(__dff_d_ff2264),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_counter_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U485 (
        .D(__dff_d_ff2265),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_powering_down)
    );

    sky130_fd_sc_hd__dfrtp_1 U486 (
        .D(__dff_d_ff2266),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_state_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U487 (
        .D(__dff_d_ff2267),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_state_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U488 (
        .D(__dff_d_ff2268),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(seq_state_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U489 (
        .D(__dff_d_ff2269),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(sram_ret_en)
    );

    sky130_fd_sc_hd__dfrtp_1 U490 (
        .D(__dff_d_ff3315),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(abort_req_n157)
    );

    sky130_fd_sc_hd__dfrtp_1 U491 (
        .D(__dff_d_ff3316),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(aw_done)
    );

    sky130_fd_sc_hd__dfrtp_1 U492 (
        .D(__dff_d_ff3317),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(clk_gate_reg_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U493 (
        .D(__dff_d_ff3318),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(clk_gate_reg_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U494 (
        .D(__dff_d_ff3319),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(clk_gate_reg_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U495 (
        .D(__dff_d_ff3320),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(clk_gate_reg_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U496 (
        .D(__dff_d_ff3321),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(clk_gate_reg_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U497 (
        .D(__dff_d_ff3322),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(iso_ctrl_reg_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U498 (
        .D(__dff_d_ff3323),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(iso_ctrl_reg_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U499 (
        .D(__dff_d_ff3324),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(iso_ctrl_reg_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U500 (
        .D(__dff_d_ff3325),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U501 (
        .D(__dff_d_ff3326),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U502 (
        .D(__dff_d_ff3327),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U503 (
        .D(__dff_d_ff3328),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U504 (
        .D(__dff_d_ff3329),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U505 (
        .D(__dff_d_ff3330),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U506 (
        .D(__dff_d_ff3331),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U507 (
        .D(__dff_d_ff3332),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_dn_delay_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U508 (
        .D(__dff_d_ff3333),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U509 (
        .D(__dff_d_ff3334),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U510 (
        .D(__dff_d_ff3335),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U511 (
        .D(__dff_d_ff3336),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U512 (
        .D(__dff_d_ff3337),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U513 (
        .D(__dff_d_ff3338),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U514 (
        .D(__dff_d_ff3339),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U515 (
        .D(__dff_d_ff3340),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(pwr_up_delay_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U516 (
        .D(__dff_d_ff3341),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(ret_ctrl_reg)
    );

    sky130_fd_sc_hd__dfrtp_1 U517 (
        .D(__dff_d_ff3345),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_bvalid)
    );

    sky130_fd_sc_hd__dfrtp_1 U518 (
        .D(__dff_d_ff3347),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff2270)
    );

    sky130_fd_sc_hd__dfrtp_1 U519 (
        .D(__dff_d_ff3348),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(__dff_d_ff2271)
    );

    sky130_fd_sc_hd__dfrtp_1 U520 (
        .D(__dff_d_ff3349),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(transition_req_n191)
    );

    sky130_fd_sc_hd__dfrtp_1 U521 (
        .D(__dff_d_ff3350),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(w_done)
    );

    sky130_fd_sc_hd__dfrtp_1 U522 (
        .D(__dff_d_ff3351),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U523 (
        .D(__dff_d_ff3352),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U524 (
        .D(__dff_d_ff3353),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U525 (
        .D(__dff_d_ff3354),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U526 (
        .D(__dff_d_ff3355),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U527 (
        .D(__dff_d_ff3356),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U528 (
        .D(__dff_d_ff3357),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U529 (
        .D(__dff_d_ff3358),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_en_reg_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U530 (
        .D(__dff_d_ff3359),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_0_n201)
    );

    sky130_fd_sc_hd__dfrtp_1 U531 (
        .D(__dff_d_ff3360),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_1_n202)
    );

    sky130_fd_sc_hd__dfrtp_1 U532 (
        .D(__dff_d_ff3361),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_2_n203)
    );

    sky130_fd_sc_hd__dfrtp_1 U533 (
        .D(__dff_d_ff3362),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_3_n204)
    );

    sky130_fd_sc_hd__dfrtp_1 U534 (
        .D(__dff_d_ff3363),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_4_n205)
    );

    sky130_fd_sc_hd__dfrtp_1 U535 (
        .D(__dff_d_ff3364),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_5_n206)
    );

    sky130_fd_sc_hd__dfrtp_1 U536 (
        .D(__dff_d_ff3365),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_6_n207)
    );

    sky130_fd_sc_hd__dfrtp_1 U537 (
        .D(__dff_d_ff3366),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wake_stat_reg_7_n208)
    );

    sky130_fd_sc_hd__dfrtp_1 U538 (
        .D(__dff_d_ff3367),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U539 (
        .D(__dff_d_ff3368),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U540 (
        .D(__dff_d_ff3369),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U541 (
        .D(__dff_d_ff3370),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U542 (
        .D(__dff_d_ff3371),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U543 (
        .D(__dff_d_ff3372),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U544 (
        .D(__dff_d_ff3373),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U545 (
        .D(__dff_d_ff3374),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U546 (
        .D(__dff_d_ff3375),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U547 (
        .D(__dff_d_ff3376),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U548 (
        .D(__dff_d_ff3377),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U549 (
        .D(__dff_d_ff3378),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U550 (
        .D(__dff_d_ff3379),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U551 (
        .D(__dff_d_ff3380),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U552 (
        .D(__dff_d_ff3381),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U553 (
        .D(__dff_d_ff3382),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U554 (
        .D(__dff_d_ff3383),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U555 (
        .D(__dff_d_ff3384),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U556 (
        .D(__dff_d_ff3385),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U557 (
        .D(__dff_d_ff3386),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U558 (
        .D(__dff_d_ff3387),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U559 (
        .D(__dff_d_ff3388),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U560 (
        .D(__dff_d_ff3389),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U561 (
        .D(__dff_d_ff3390),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U562 (
        .D(__dff_d_ff3391),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U563 (
        .D(__dff_d_ff3392),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U564 (
        .D(__dff_d_ff3393),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U565 (
        .D(__dff_d_ff3394),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U566 (
        .D(__dff_d_ff3395),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U567 (
        .D(__dff_d_ff3396),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U568 (
        .D(__dff_d_ff3397),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U569 (
        .D(__dff_d_ff3398),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wr_addr_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U570 (
        .D(__dff_d_ff4720),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_arready)
    );

    sky130_fd_sc_hd__dfrtp_1 U571 (
        .D(__dff_d_ff4721),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U572 (
        .D(__dff_d_ff4722),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U573 (
        .D(__dff_d_ff4723),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U574 (
        .D(__dff_d_ff4724),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U575 (
        .D(__dff_d_ff4725),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U576 (
        .D(__dff_d_ff4726),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U577 (
        .D(__dff_d_ff4727),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U578 (
        .D(__dff_d_ff4728),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U579 (
        .D(__dff_d_ff4729),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_8)
    );

    sky130_fd_sc_hd__dfrtp_1 U580 (
        .D(__dff_d_ff4730),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_9)
    );

    sky130_fd_sc_hd__dfrtp_1 U581 (
        .D(__dff_d_ff4731),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U582 (
        .D(__dff_d_ff4732),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_11)
    );

    sky130_fd_sc_hd__dfrtp_1 U583 (
        .D(__dff_d_ff4733),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_12)
    );

    sky130_fd_sc_hd__dfrtp_1 U584 (
        .D(__dff_d_ff4734),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_13)
    );

    sky130_fd_sc_hd__dfrtp_1 U585 (
        .D(__dff_d_ff4735),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_14)
    );

    sky130_fd_sc_hd__dfrtp_1 U586 (
        .D(__dff_d_ff4736),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_15)
    );

    sky130_fd_sc_hd__dfrtp_1 U587 (
        .D(__dff_d_ff4737),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_16)
    );

    sky130_fd_sc_hd__dfrtp_1 U588 (
        .D(__dff_d_ff4738),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_17)
    );

    sky130_fd_sc_hd__dfrtp_1 U589 (
        .D(__dff_d_ff4739),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_18)
    );

    sky130_fd_sc_hd__dfrtp_1 U590 (
        .D(__dff_d_ff4740),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_19)
    );

    sky130_fd_sc_hd__dfrtp_1 U591 (
        .D(__dff_d_ff4741),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_20)
    );

    sky130_fd_sc_hd__dfrtp_1 U592 (
        .D(__dff_d_ff4742),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_21)
    );

    sky130_fd_sc_hd__dfrtp_1 U593 (
        .D(__dff_d_ff4743),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_22)
    );

    sky130_fd_sc_hd__dfrtp_1 U594 (
        .D(__dff_d_ff4744),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_23)
    );

    sky130_fd_sc_hd__dfrtp_1 U595 (
        .D(__dff_d_ff4745),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_24)
    );

    sky130_fd_sc_hd__dfrtp_1 U596 (
        .D(__dff_d_ff4746),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_25)
    );

    sky130_fd_sc_hd__dfrtp_1 U597 (
        .D(__dff_d_ff4747),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_26)
    );

    sky130_fd_sc_hd__dfrtp_1 U598 (
        .D(__dff_d_ff4748),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_27)
    );

    sky130_fd_sc_hd__dfrtp_1 U599 (
        .D(__dff_d_ff4749),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_28)
    );

    sky130_fd_sc_hd__dfrtp_1 U600 (
        .D(__dff_d_ff4750),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_29)
    );

    sky130_fd_sc_hd__dfrtp_1 U601 (
        .D(__dff_d_ff4751),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_30)
    );

    sky130_fd_sc_hd__dfrtp_1 U602 (
        .D(__dff_d_ff4752),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rdata_31)
    );

    sky130_fd_sc_hd__dfrtp_1 U603 (
        .D(__dff_d_ff4753),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rresp_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U604 (
        .D(__dff_d_ff4754),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rresp_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U605 (
        .D(__dff_d_ff4755),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(s_axi_rvalid)
    );

    sky130_fd_sc_hd__conb_1 UTIE_0 (.LO(buf_rst_n_0));
    sky130_fd_sc_hd__conb_1 UTIE_1 (.LO(buf_rst_n_1));
    sky130_fd_sc_hd__conb_1 UTIE_2 (.LO(glitch_bal_113_0_n));
    sky130_fd_sc_hd__conb_1 UTIE_3 (.LO(inv_n2));
    sky130_fd_sc_hd__conb_1 UTIE_4 (.LO(n406));
    sky130_fd_sc_hd__conb_1 UTIE_5 (.LO(n408));
    sky130_fd_sc_hd__conb_1 UTIE_6 (.LO(n557));
    sky130_fd_sc_hd__conb_1 UTIE_7 (.LO(n562));
    sky130_fd_sc_hd__conb_1 UTIE_8 (.LO(n605));
    sky130_fd_sc_hd__conb_1 UTIE_9 (.LO(n613));
    sky130_fd_sc_hd__conb_1 UTIE_10 (.LO(n614));
    sky130_fd_sc_hd__conb_1 UTIE_11 (.LO(n620));
    sky130_fd_sc_hd__conb_1 UTIE_12 (.LO(n624));
    sky130_fd_sc_hd__conb_1 UTIE_13 (.LO(n639));
    sky130_fd_sc_hd__conb_1 UTIE_14 (.LO(n645));
    sky130_fd_sc_hd__conb_1 UTIE_15 (.LO(n713));
    sky130_fd_sc_hd__conb_1 UTIE_16 (.LO(n720));
    sky130_fd_sc_hd__conb_1 UTIE_17 (.LO(n758));
    sky130_fd_sc_hd__conb_1 UTIE_18 (.LO(n766));
    sky130_fd_sc_hd__conb_1 UTIE_19 (.LO(seq_counter_0));
    sky130_fd_sc_hd__conb_1 UTIE_20 (.LO(transitioning));
endmodule
