// Generated by SiliconForge — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module security_axi_mux (
    input clk,
    input rst_n,
    input s_axi_awaddr_12,
    input s_axi_awaddr_13,
    input s_axi_awaddr_14,
    input s_axi_awaddr_15,
    input s_axi_awaddr_16,
    input s_axi_awaddr_17,
    input s_axi_awaddr_18,
    input s_axi_awaddr_19,
    input s_axi_awaddr_20,
    input s_axi_awaddr_21,
    input s_axi_awaddr_22,
    input s_axi_awaddr_23,
    input s_axi_awaddr_24,
    input s_axi_awaddr_25,
    input s_axi_awaddr_26,
    input s_axi_awaddr_27,
    input s_axi_awaddr_28,
    input s_axi_awaddr_29,
    input s_axi_awaddr_30,
    input s_axi_awaddr_31,
    input s_axi_wvalid,
    input s_axi_araddr_12,
    input s_axi_araddr_13,
    input s_axi_araddr_14,
    input s_axi_araddr_15,
    input s_axi_araddr_16,
    input s_axi_araddr_17,
    input s_axi_araddr_18,
    input s_axi_araddr_19,
    input s_axi_araddr_20,
    input s_axi_araddr_21,
    input s_axi_araddr_22,
    input s_axi_araddr_23,
    input s_axi_araddr_24,
    input s_axi_araddr_25,
    input s_axi_araddr_26,
    input s_axi_araddr_27,
    input s_axi_araddr_28,
    input s_axi_araddr_29,
    input s_axi_araddr_30,
    input s_axi_araddr_31,
    input s_axi_rready,
    input p0_axi_awready,
    input p0_axi_wready,
    input p0_axi_bresp_0,
    input p0_axi_bresp_1,
    input p0_axi_bvalid,
    input p0_axi_arready,
    input p0_axi_rdata_0,
    input p0_axi_rdata_1,
    input p0_axi_rdata_2,
    input p0_axi_rdata_3,
    input p0_axi_rdata_4,
    input p0_axi_rdata_5,
    input p0_axi_rdata_6,
    input p0_axi_rdata_7,
    input p0_axi_rdata_8,
    input p0_axi_rdata_9,
    input p0_axi_rdata_10,
    input p0_axi_rdata_11,
    input p0_axi_rdata_12,
    input p0_axi_rdata_13,
    input p0_axi_rdata_14,
    input p0_axi_rdata_15,
    input p0_axi_rdata_16,
    input p0_axi_rdata_17,
    input p0_axi_rdata_18,
    input p0_axi_rdata_19,
    input p0_axi_rdata_20,
    input p0_axi_rdata_21,
    input p0_axi_rdata_22,
    input p0_axi_rdata_23,
    input p0_axi_rdata_24,
    input p0_axi_rdata_25,
    input p0_axi_rdata_26,
    input p0_axi_rdata_27,
    input p0_axi_rdata_28,
    input p0_axi_rdata_29,
    input p0_axi_rdata_30,
    input p0_axi_rdata_31,
    input p0_axi_rresp_0,
    input p0_axi_rresp_1,
    input p0_axi_rvalid,
    input p1_axi_awready,
    input p1_axi_wready,
    input p1_axi_bresp_0,
    input p1_axi_bresp_1,
    input p1_axi_bvalid,
    input p1_axi_arready,
    input p1_axi_rdata_0,
    input p1_axi_rdata_1,
    input p1_axi_rdata_2,
    input p1_axi_rdata_3,
    input p1_axi_rdata_4,
    input p1_axi_rdata_5,
    input p1_axi_rdata_6,
    input p1_axi_rdata_7,
    input p1_axi_rdata_8,
    input p1_axi_rdata_9,
    input p1_axi_rdata_10,
    input p1_axi_rdata_11,
    input p1_axi_rdata_12,
    input p1_axi_rdata_13,
    input p1_axi_rdata_14,
    input p1_axi_rdata_15,
    input p1_axi_rdata_16,
    input p1_axi_rdata_17,
    input p1_axi_rdata_18,
    input p1_axi_rdata_19,
    input p1_axi_rdata_20,
    input p1_axi_rdata_21,
    input p1_axi_rdata_22,
    input p1_axi_rdata_23,
    input p1_axi_rdata_24,
    input p1_axi_rdata_25,
    input p1_axi_rdata_26,
    input p1_axi_rdata_27,
    input p1_axi_rdata_28,
    input p1_axi_rdata_29,
    input p1_axi_rdata_30,
    input p1_axi_rdata_31,
    input p1_axi_rresp_0,
    input p1_axi_rresp_1,
    input p1_axi_rvalid,
    input p2_axi_awready,
    input p2_axi_wready,
    input p2_axi_bresp_0,
    input p2_axi_bresp_1,
    input p2_axi_bvalid,
    input p2_axi_arready,
    input p2_axi_rdata_0,
    input p2_axi_rdata_1,
    input p2_axi_rdata_2,
    input p2_axi_rdata_3,
    input p2_axi_rdata_4,
    input p2_axi_rdata_5,
    input p2_axi_rdata_6,
    input p2_axi_rdata_7,
    input p2_axi_rdata_8,
    input p2_axi_rdata_9,
    input p2_axi_rdata_10,
    input p2_axi_rdata_11,
    input p2_axi_rdata_12,
    input p2_axi_rdata_13,
    input p2_axi_rdata_14,
    input p2_axi_rdata_15,
    input p2_axi_rdata_16,
    input p2_axi_rdata_17,
    input p2_axi_rdata_18,
    input p2_axi_rdata_19,
    input p2_axi_rdata_20,
    input p2_axi_rdata_21,
    input p2_axi_rdata_22,
    input p2_axi_rdata_23,
    input p2_axi_rdata_24,
    input p2_axi_rdata_25,
    input p2_axi_rdata_26,
    input p2_axi_rdata_27,
    input p2_axi_rdata_28,
    input p2_axi_rdata_29,
    input p2_axi_rdata_30,
    input p2_axi_rdata_31,
    input p2_axi_rresp_0,
    input p2_axi_rresp_1,
    input p2_axi_rvalid,
    input p3_axi_awready,
    input p3_axi_wready,
    input p3_axi_bresp_0,
    input p3_axi_bresp_1,
    input p3_axi_bvalid,
    input p3_axi_arready,
    input p3_axi_rdata_0,
    input p3_axi_rdata_1,
    input p3_axi_rdata_2,
    input p3_axi_rdata_3,
    input p3_axi_rdata_4,
    input p3_axi_rdata_5,
    input p3_axi_rdata_6,
    input p3_axi_rdata_7,
    input p3_axi_rdata_8,
    input p3_axi_rdata_9,
    input p3_axi_rdata_10,
    input p3_axi_rdata_11,
    input p3_axi_rdata_12,
    input p3_axi_rdata_13,
    input p3_axi_rdata_14,
    input p3_axi_rdata_15,
    input p3_axi_rdata_16,
    input p3_axi_rdata_17,
    input p3_axi_rdata_18,
    input p3_axi_rdata_19,
    input p3_axi_rdata_20,
    input p3_axi_rdata_21,
    input p3_axi_rdata_22,
    input p3_axi_rdata_23,
    input p3_axi_rdata_24,
    input p3_axi_rdata_25,
    input p3_axi_rdata_26,
    input p3_axi_rdata_27,
    input p3_axi_rdata_28,
    input p3_axi_rdata_29,
    input p3_axi_rdata_30,
    input p3_axi_rdata_31,
    input p3_axi_rresp_0,
    input p3_axi_rresp_1,
    input p3_axi_rvalid,
    output p0_axi_awaddr_11,
    output p0_axi_awaddr_10,
    output p0_axi_awaddr_9,
    output p0_axi_awaddr_8,
    output p0_axi_awaddr_7,
    output p0_axi_awaddr_6,
    output p0_axi_awaddr_5,
    output p0_axi_awaddr_4,
    output p0_axi_awaddr_3,
    output p0_axi_awaddr_2,
    output p0_axi_awaddr_1,
    output p0_axi_awaddr_0,
    output p0_axi_awvalid,
    output p0_axi_wdata_0,
    output p0_axi_wdata_1,
    output p0_axi_wdata_2,
    output p0_axi_wdata_3,
    output p0_axi_wdata_4,
    output p0_axi_wdata_5,
    output p0_axi_wdata_6,
    output p0_axi_wdata_7,
    output p0_axi_wdata_8,
    output p0_axi_wdata_9,
    output p0_axi_wdata_10,
    output p0_axi_wdata_11,
    output p0_axi_wdata_12,
    output p0_axi_wdata_13,
    output p0_axi_wdata_14,
    output p0_axi_wdata_15,
    output p0_axi_wdata_16,
    output p0_axi_wdata_17,
    output p0_axi_wdata_18,
    output p0_axi_wdata_19,
    output p0_axi_wdata_20,
    output p0_axi_wdata_21,
    output p0_axi_wdata_22,
    output p0_axi_wdata_23,
    output p0_axi_wdata_24,
    output p0_axi_wdata_25,
    output p0_axi_wdata_26,
    output p0_axi_wdata_27,
    output p0_axi_wdata_28,
    output p0_axi_wdata_29,
    output p0_axi_wdata_30,
    output p0_axi_wdata_31,
    output p0_axi_wstrb_0,
    output p0_axi_wstrb_1,
    output p0_axi_wstrb_2,
    output p0_axi_wstrb_3,
    output p0_axi_bready,
    output p0_axi_araddr_11,
    output p0_axi_araddr_10,
    output p0_axi_araddr_9,
    output p0_axi_araddr_8,
    output p0_axi_araddr_7,
    output p0_axi_araddr_6,
    output p0_axi_araddr_5,
    output p0_axi_araddr_4,
    output p0_axi_araddr_3,
    output p0_axi_araddr_2,
    output p0_axi_araddr_1,
    output p0_axi_araddr_0,
    output p0_axi_arvalid,
    output s_axi_wready,
    output s_axi_arready,
    output s_axi_awready,
    output s_axi_bresp_0,
    output s_axi_bresp_1,
    output s_axi_bvalid,
    output s_axi_rdata_0,
    output s_axi_rdata_1,
    output s_axi_rdata_2,
    output s_axi_rdata_3,
    output s_axi_rdata_4,
    output s_axi_rdata_5,
    output s_axi_rdata_6,
    output s_axi_rdata_7,
    output s_axi_rdata_8,
    output s_axi_rdata_9,
    output s_axi_rdata_10,
    output s_axi_rdata_11,
    output s_axi_rdata_12,
    output s_axi_rdata_13,
    output s_axi_rdata_14,
    output s_axi_rdata_15,
    output s_axi_rdata_16,
    output s_axi_rdata_17,
    output s_axi_rdata_18,
    output s_axi_rdata_19,
    output s_axi_rdata_20,
    output s_axi_rdata_21,
    output s_axi_rdata_22,
    output s_axi_rdata_23,
    output s_axi_rdata_24,
    output s_axi_rdata_25,
    output s_axi_rdata_26,
    output s_axi_rdata_27,
    output s_axi_rdata_28,
    output s_axi_rdata_29,
    output s_axi_rdata_30,
    output s_axi_rdata_31,
    output s_axi_rresp_0,
    output s_axi_rresp_1,
    output s_axi_rvalid,
    output p0_axi_wvalid,
    output p0_axi_rready,
    output p1_axi_awaddr_0,
    output p1_axi_awaddr_1,
    output p1_axi_awaddr_2,
    output p1_axi_awaddr_3,
    output p1_axi_awaddr_4,
    output p1_axi_awaddr_5,
    output p1_axi_awaddr_6,
    output p1_axi_awaddr_7,
    output p1_axi_awaddr_8,
    output p1_axi_awaddr_9,
    output p1_axi_awaddr_10,
    output p1_axi_awaddr_11,
    output p1_axi_awvalid,
    output p1_axi_wdata_0,
    output p1_axi_wdata_1,
    output p1_axi_wdata_2,
    output p1_axi_wdata_3,
    output p1_axi_wdata_4,
    output p1_axi_wdata_5,
    output p1_axi_wdata_6,
    output p1_axi_wdata_7,
    output p1_axi_wdata_8,
    output p1_axi_wdata_9,
    output p1_axi_wdata_10,
    output p1_axi_wdata_11,
    output p1_axi_wdata_12,
    output p1_axi_wdata_13,
    output p1_axi_wdata_14,
    output p1_axi_wdata_15,
    output p1_axi_wdata_16,
    output p1_axi_wdata_17,
    output p1_axi_wdata_18,
    output p1_axi_wdata_19,
    output p1_axi_wdata_20,
    output p1_axi_wdata_21,
    output p1_axi_wdata_22,
    output p1_axi_wdata_23,
    output p1_axi_wdata_24,
    output p1_axi_wdata_25,
    output p1_axi_wdata_26,
    output p1_axi_wdata_27,
    output p1_axi_wdata_28,
    output p1_axi_wdata_29,
    output p1_axi_wdata_30,
    output p1_axi_wdata_31,
    output p1_axi_wstrb_0,
    output p1_axi_wstrb_1,
    output p1_axi_wstrb_2,
    output p1_axi_wstrb_3,
    output p1_axi_wvalid,
    output p1_axi_bready,
    output p1_axi_araddr_0,
    output p1_axi_araddr_1,
    output p1_axi_araddr_2,
    output p1_axi_araddr_3,
    output p1_axi_araddr_4,
    output p1_axi_araddr_5,
    output p1_axi_araddr_6,
    output p1_axi_araddr_7,
    output p1_axi_araddr_8,
    output p1_axi_araddr_9,
    output p1_axi_araddr_10,
    output p1_axi_araddr_11,
    output p1_axi_arvalid,
    output p1_axi_rready,
    output p2_axi_awaddr_0,
    output p2_axi_awaddr_1,
    output p2_axi_awaddr_2,
    output p2_axi_awaddr_3,
    output p2_axi_awaddr_4,
    output p2_axi_awaddr_5,
    output p2_axi_awaddr_6,
    output p2_axi_awaddr_7,
    output p2_axi_awaddr_8,
    output p2_axi_awaddr_9,
    output p2_axi_awaddr_10,
    output p2_axi_awaddr_11,
    output p2_axi_awvalid,
    output p2_axi_wdata_0,
    output p2_axi_wdata_1,
    output p2_axi_wdata_2,
    output p2_axi_wdata_3,
    output p2_axi_wdata_4,
    output p2_axi_wdata_5,
    output p2_axi_wdata_6,
    output p2_axi_wdata_7,
    output p2_axi_wdata_8,
    output p2_axi_wdata_9,
    output p2_axi_wdata_10,
    output p2_axi_wdata_11,
    output p2_axi_wdata_12,
    output p2_axi_wdata_13,
    output p2_axi_wdata_14,
    output p2_axi_wdata_15,
    output p2_axi_wdata_16,
    output p2_axi_wdata_17,
    output p2_axi_wdata_18,
    output p2_axi_wdata_19,
    output p2_axi_wdata_20,
    output p2_axi_wdata_21,
    output p2_axi_wdata_22,
    output p2_axi_wdata_23,
    output p2_axi_wdata_24,
    output p2_axi_wdata_25,
    output p2_axi_wdata_26,
    output p2_axi_wdata_27,
    output p2_axi_wdata_28,
    output p2_axi_wdata_29,
    output p2_axi_wdata_30,
    output p2_axi_wdata_31,
    output p2_axi_wstrb_0,
    output p2_axi_wstrb_1,
    output p2_axi_wstrb_2,
    output p2_axi_wstrb_3,
    output p2_axi_wvalid,
    output p2_axi_bready,
    output p2_axi_araddr_0,
    output p2_axi_araddr_1,
    output p2_axi_araddr_2,
    output p2_axi_araddr_3,
    output p2_axi_araddr_4,
    output p2_axi_araddr_5,
    output p2_axi_araddr_6,
    output p2_axi_araddr_7,
    output p2_axi_araddr_8,
    output p2_axi_araddr_9,
    output p2_axi_araddr_10,
    output p2_axi_araddr_11,
    output p2_axi_arvalid,
    output p2_axi_rready,
    output p3_axi_awaddr_0,
    output p3_axi_awaddr_1,
    output p3_axi_awaddr_2,
    output p3_axi_awaddr_3,
    output p3_axi_awaddr_4,
    output p3_axi_awaddr_5,
    output p3_axi_awaddr_6,
    output p3_axi_awaddr_7,
    output p3_axi_awaddr_8,
    output p3_axi_awaddr_9,
    output p3_axi_awaddr_10,
    output p3_axi_awaddr_11,
    output p3_axi_awvalid,
    output p3_axi_wdata_0,
    output p3_axi_wdata_1,
    output p3_axi_wdata_2,
    output p3_axi_wdata_3,
    output p3_axi_wdata_4,
    output p3_axi_wdata_5,
    output p3_axi_wdata_6,
    output p3_axi_wdata_7,
    output p3_axi_wdata_8,
    output p3_axi_wdata_9,
    output p3_axi_wdata_10,
    output p3_axi_wdata_11,
    output p3_axi_wdata_12,
    output p3_axi_wdata_13,
    output p3_axi_wdata_14,
    output p3_axi_wdata_15,
    output p3_axi_wdata_16,
    output p3_axi_wdata_17,
    output p3_axi_wdata_18,
    output p3_axi_wdata_19,
    output p3_axi_wdata_20,
    output p3_axi_wdata_21,
    output p3_axi_wdata_22,
    output p3_axi_wdata_23,
    output p3_axi_wdata_24,
    output p3_axi_wdata_25,
    output p3_axi_wdata_26,
    output p3_axi_wdata_27,
    output p3_axi_wdata_28,
    output p3_axi_wdata_29,
    output p3_axi_wdata_30,
    output p3_axi_wdata_31,
    output p3_axi_wstrb_0,
    output p3_axi_wstrb_1,
    output p3_axi_wstrb_2,
    output p3_axi_wstrb_3,
    output p3_axi_wvalid,
    output p3_axi_bready,
    output p3_axi_araddr_0,
    output p3_axi_araddr_1,
    output p3_axi_araddr_2,
    output p3_axi_araddr_3,
    output p3_axi_araddr_4,
    output p3_axi_araddr_5,
    output p3_axi_araddr_6,
    output p3_axi_araddr_7,
    output p3_axi_araddr_8,
    output p3_axi_araddr_9,
    output p3_axi_araddr_10,
    output p3_axi_araddr_11,
    output p3_axi_arvalid,
    output p3_axi_rready
);

    wire wmiss;
    wire wsel_0;
    wire wsel_1;
    wire wstate_0;
    wire wstate_1;
    wire rmiss;
    wire rsel_0;
    wire rsel_1;
    wire rstate_0;
    wire rstate_1;
    wire n284;
    wire inv_n280;
    wire inv_n281;
    wire inv_n2;
    wire __dff_d_ff1025;
    wire __dff_d_ff1024;
    wire __dff_d_ff1023;
    wire n290;
    wire inv_n275;
    wire inv_n276;
    wire __dff_d_ff766;
    wire __dff_d_ff765;
    wire __dff_d_ff764;
    wire __dff_d_ff767;
    wire __dff_d_ff768;
    wire __dff_d_ff1026;
    wire __dff_d_ff1027;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(s_axi_wready));
    sky130_fd_sc_hd__inv_1 U0 (
        .A(rstate_0),
        .Y(inv_n280)
    );

    sky130_fd_sc_hd__inv_1 U1 (
        .A(rstate_1),
        .Y(inv_n281)
    );

    sky130_fd_sc_hd__inv_1 U2 (
        .A(rst_n),
        .Y(inv_n2)
    );

    sky130_fd_sc_hd__a31oi_1 U3 (
        .A1(p0_axi_arvalid),
        .A2(inv_n280),
        .A3(inv_n281),
        .B1(inv_n2),
        .Y(n284)
    );

    sky130_fd_sc_hd__nand2_1 U4 (
        .A(rsel_1),
        .B(n284),
        .Y(__dff_d_ff1025)
    );

    sky130_fd_sc_hd__nand2_1 U5 (
        .A(rsel_0),
        .B(n284),
        .Y(__dff_d_ff1024)
    );

    sky130_fd_sc_hd__nand2_1 U6 (
        .A(rmiss),
        .B(n284),
        .Y(__dff_d_ff1023)
    );

    sky130_fd_sc_hd__inv_1 U7 (
        .A(wstate_0),
        .Y(inv_n275)
    );

    sky130_fd_sc_hd__inv_1 U8 (
        .A(wstate_1),
        .Y(inv_n276)
    );

    sky130_fd_sc_hd__a31oi_1 U9 (
        .A1(p0_axi_awvalid),
        .A2(inv_n275),
        .A3(inv_n276),
        .B1(inv_n2),
        .Y(n290)
    );

    sky130_fd_sc_hd__nand2_1 U10 (
        .A(wsel_1),
        .B(n290),
        .Y(__dff_d_ff766)
    );

    sky130_fd_sc_hd__nand2_1 U11 (
        .A(wsel_0),
        .B(n290),
        .Y(__dff_d_ff765)
    );

    sky130_fd_sc_hd__nand2_1 U12 (
        .A(wmiss),
        .B(n290),
        .Y(__dff_d_ff764)
    );

    sky130_fd_sc_hd__nand2_1 U13 (
        .A(p0_axi_arvalid),
        .B(p0_axi_arready),
        .Y(s_axi_arready)
    );

    sky130_fd_sc_hd__nand2_1 U14 (
        .A(p0_axi_awvalid),
        .B(p0_axi_awready),
        .Y(s_axi_awready)
    );

    sky130_fd_sc_hd__buf_1 U15 (
        .A(s_axi_wready),
        .X(s_axi_bresp_0)
    );

    sky130_fd_sc_hd__buf_1 U16 (
        .A(s_axi_wready),
        .X(s_axi_bresp_1)
    );

    sky130_fd_sc_hd__buf_1 U17 (
        .A(s_axi_wready),
        .X(s_axi_bvalid)
    );

    sky130_fd_sc_hd__buf_1 U18 (
        .A(s_axi_wready),
        .X(s_axi_rdata_4)
    );

    sky130_fd_sc_hd__buf_1 U19 (
        .A(s_axi_wready),
        .X(s_axi_rdata_8)
    );

    sky130_fd_sc_hd__buf_1 U20 (
        .A(s_axi_wready),
        .X(s_axi_rdata_14)
    );

    sky130_fd_sc_hd__buf_1 U21 (
        .A(s_axi_wready),
        .X(s_axi_rdata_17)
    );

    sky130_fd_sc_hd__buf_1 U22 (
        .A(s_axi_wready),
        .X(s_axi_rdata_20)
    );

    sky130_fd_sc_hd__buf_1 U23 (
        .A(s_axi_wready),
        .X(s_axi_rdata_22)
    );

    sky130_fd_sc_hd__buf_1 U24 (
        .A(s_axi_wready),
        .X(s_axi_rdata_24)
    );

    sky130_fd_sc_hd__buf_1 U25 (
        .A(s_axi_wready),
        .X(s_axi_rdata_29)
    );

    sky130_fd_sc_hd__buf_1 U26 (
        .A(s_axi_wready),
        .X(p0_axi_wvalid)
    );

    sky130_fd_sc_hd__buf_1 U27 (
        .A(s_axi_wready),
        .X(p0_axi_rready)
    );

    sky130_fd_sc_hd__buf_1 U28 (
        .A(p0_axi_awaddr_0),
        .X(p1_axi_awaddr_0)
    );

    sky130_fd_sc_hd__buf_1 U29 (
        .A(p0_axi_awaddr_1),
        .X(p1_axi_awaddr_1)
    );

    sky130_fd_sc_hd__buf_1 U30 (
        .A(p0_axi_awaddr_2),
        .X(p1_axi_awaddr_2)
    );

    sky130_fd_sc_hd__buf_1 U31 (
        .A(p0_axi_awaddr_3),
        .X(p1_axi_awaddr_3)
    );

    sky130_fd_sc_hd__buf_1 U32 (
        .A(p0_axi_awaddr_4),
        .X(p1_axi_awaddr_4)
    );

    sky130_fd_sc_hd__buf_1 U33 (
        .A(p0_axi_awaddr_5),
        .X(p1_axi_awaddr_5)
    );

    sky130_fd_sc_hd__buf_1 U34 (
        .A(p0_axi_awaddr_6),
        .X(p1_axi_awaddr_6)
    );

    sky130_fd_sc_hd__buf_1 U35 (
        .A(p0_axi_awaddr_7),
        .X(p1_axi_awaddr_7)
    );

    sky130_fd_sc_hd__buf_1 U36 (
        .A(p0_axi_awaddr_8),
        .X(p1_axi_awaddr_8)
    );

    sky130_fd_sc_hd__buf_1 U37 (
        .A(p0_axi_awaddr_9),
        .X(p1_axi_awaddr_9)
    );

    sky130_fd_sc_hd__buf_1 U38 (
        .A(p0_axi_awaddr_10),
        .X(p1_axi_awaddr_10)
    );

    sky130_fd_sc_hd__buf_1 U39 (
        .A(p0_axi_awaddr_11),
        .X(p1_axi_awaddr_11)
    );

    sky130_fd_sc_hd__buf_1 U40 (
        .A(s_axi_wready),
        .X(p1_axi_awvalid)
    );

    sky130_fd_sc_hd__buf_1 U41 (
        .A(p0_axi_wdata_0),
        .X(p1_axi_wdata_0)
    );

    sky130_fd_sc_hd__buf_1 U42 (
        .A(p0_axi_wdata_1),
        .X(p1_axi_wdata_1)
    );

    sky130_fd_sc_hd__buf_1 U43 (
        .A(p0_axi_wdata_2),
        .X(p1_axi_wdata_2)
    );

    sky130_fd_sc_hd__buf_1 U44 (
        .A(p0_axi_wdata_3),
        .X(p1_axi_wdata_3)
    );

    sky130_fd_sc_hd__buf_1 U45 (
        .A(p0_axi_wdata_4),
        .X(p1_axi_wdata_4)
    );

    sky130_fd_sc_hd__buf_1 U46 (
        .A(p0_axi_wdata_5),
        .X(p1_axi_wdata_5)
    );

    sky130_fd_sc_hd__buf_1 U47 (
        .A(p0_axi_wdata_6),
        .X(p1_axi_wdata_6)
    );

    sky130_fd_sc_hd__buf_1 U48 (
        .A(p0_axi_wdata_7),
        .X(p1_axi_wdata_7)
    );

    sky130_fd_sc_hd__buf_1 U49 (
        .A(p0_axi_wdata_8),
        .X(p1_axi_wdata_8)
    );

    sky130_fd_sc_hd__buf_1 U50 (
        .A(p0_axi_wdata_9),
        .X(p1_axi_wdata_9)
    );

    sky130_fd_sc_hd__buf_1 U51 (
        .A(p0_axi_wdata_10),
        .X(p1_axi_wdata_10)
    );

    sky130_fd_sc_hd__buf_1 U52 (
        .A(p0_axi_wdata_11),
        .X(p1_axi_wdata_11)
    );

    sky130_fd_sc_hd__buf_1 U53 (
        .A(p0_axi_wdata_12),
        .X(p1_axi_wdata_12)
    );

    sky130_fd_sc_hd__buf_1 U54 (
        .A(p0_axi_wdata_13),
        .X(p1_axi_wdata_13)
    );

    sky130_fd_sc_hd__buf_1 U55 (
        .A(p0_axi_wdata_14),
        .X(p1_axi_wdata_14)
    );

    sky130_fd_sc_hd__buf_1 U56 (
        .A(p0_axi_wdata_15),
        .X(p1_axi_wdata_15)
    );

    sky130_fd_sc_hd__buf_1 U57 (
        .A(p0_axi_wdata_16),
        .X(p1_axi_wdata_16)
    );

    sky130_fd_sc_hd__buf_1 U58 (
        .A(p0_axi_wdata_17),
        .X(p1_axi_wdata_17)
    );

    sky130_fd_sc_hd__buf_1 U59 (
        .A(p0_axi_wdata_18),
        .X(p1_axi_wdata_18)
    );

    sky130_fd_sc_hd__buf_1 U60 (
        .A(p0_axi_wdata_19),
        .X(p1_axi_wdata_19)
    );

    sky130_fd_sc_hd__buf_1 U61 (
        .A(p0_axi_wdata_20),
        .X(p1_axi_wdata_20)
    );

    sky130_fd_sc_hd__buf_1 U62 (
        .A(p0_axi_wdata_21),
        .X(p1_axi_wdata_21)
    );

    sky130_fd_sc_hd__buf_1 U63 (
        .A(p0_axi_wdata_22),
        .X(p1_axi_wdata_22)
    );

    sky130_fd_sc_hd__buf_1 U64 (
        .A(p0_axi_wdata_23),
        .X(p1_axi_wdata_23)
    );

    sky130_fd_sc_hd__buf_1 U65 (
        .A(p0_axi_wdata_24),
        .X(p1_axi_wdata_24)
    );

    sky130_fd_sc_hd__buf_1 U66 (
        .A(p0_axi_wdata_25),
        .X(p1_axi_wdata_25)
    );

    sky130_fd_sc_hd__buf_1 U67 (
        .A(p0_axi_wdata_26),
        .X(p1_axi_wdata_26)
    );

    sky130_fd_sc_hd__buf_1 U68 (
        .A(p0_axi_wdata_27),
        .X(p1_axi_wdata_27)
    );

    sky130_fd_sc_hd__buf_1 U69 (
        .A(p0_axi_wdata_28),
        .X(p1_axi_wdata_28)
    );

    sky130_fd_sc_hd__buf_1 U70 (
        .A(p0_axi_wdata_29),
        .X(p1_axi_wdata_29)
    );

    sky130_fd_sc_hd__buf_1 U71 (
        .A(p0_axi_wdata_30),
        .X(p1_axi_wdata_30)
    );

    sky130_fd_sc_hd__buf_1 U72 (
        .A(p0_axi_wdata_31),
        .X(p1_axi_wdata_31)
    );

    sky130_fd_sc_hd__buf_1 U73 (
        .A(p0_axi_wstrb_0),
        .X(p1_axi_wstrb_0)
    );

    sky130_fd_sc_hd__buf_1 U74 (
        .A(p0_axi_wstrb_1),
        .X(p1_axi_wstrb_1)
    );

    sky130_fd_sc_hd__buf_1 U75 (
        .A(p0_axi_wstrb_2),
        .X(p1_axi_wstrb_2)
    );

    sky130_fd_sc_hd__buf_1 U76 (
        .A(p0_axi_wstrb_3),
        .X(p1_axi_wstrb_3)
    );

    sky130_fd_sc_hd__buf_1 U77 (
        .A(s_axi_wready),
        .X(p1_axi_wvalid)
    );

    sky130_fd_sc_hd__buf_1 U78 (
        .A(s_axi_wready),
        .X(p1_axi_bready)
    );

    sky130_fd_sc_hd__buf_1 U79 (
        .A(p0_axi_araddr_0),
        .X(p1_axi_araddr_0)
    );

    sky130_fd_sc_hd__buf_1 U80 (
        .A(p0_axi_araddr_1),
        .X(p1_axi_araddr_1)
    );

    sky130_fd_sc_hd__buf_1 U81 (
        .A(p0_axi_araddr_2),
        .X(p1_axi_araddr_2)
    );

    sky130_fd_sc_hd__buf_1 U82 (
        .A(p0_axi_araddr_3),
        .X(p1_axi_araddr_3)
    );

    sky130_fd_sc_hd__buf_1 U83 (
        .A(p0_axi_araddr_4),
        .X(p1_axi_araddr_4)
    );

    sky130_fd_sc_hd__buf_1 U84 (
        .A(p0_axi_araddr_5),
        .X(p1_axi_araddr_5)
    );

    sky130_fd_sc_hd__buf_1 U85 (
        .A(p0_axi_araddr_6),
        .X(p1_axi_araddr_6)
    );

    sky130_fd_sc_hd__buf_1 U86 (
        .A(p0_axi_araddr_7),
        .X(p1_axi_araddr_7)
    );

    sky130_fd_sc_hd__buf_1 U87 (
        .A(p0_axi_araddr_8),
        .X(p1_axi_araddr_8)
    );

    sky130_fd_sc_hd__buf_1 U88 (
        .A(p0_axi_araddr_9),
        .X(p1_axi_araddr_9)
    );

    sky130_fd_sc_hd__buf_1 U89 (
        .A(p0_axi_araddr_10),
        .X(p1_axi_araddr_10)
    );

    sky130_fd_sc_hd__buf_1 U90 (
        .A(p0_axi_araddr_11),
        .X(p1_axi_araddr_11)
    );

    sky130_fd_sc_hd__buf_1 U91 (
        .A(s_axi_wready),
        .X(p1_axi_arvalid)
    );

    sky130_fd_sc_hd__buf_1 U92 (
        .A(s_axi_wready),
        .X(p1_axi_rready)
    );

    sky130_fd_sc_hd__buf_1 U93 (
        .A(p0_axi_awaddr_0),
        .X(p2_axi_awaddr_0)
    );

    sky130_fd_sc_hd__buf_1 U94 (
        .A(p0_axi_awaddr_1),
        .X(p2_axi_awaddr_1)
    );

    sky130_fd_sc_hd__buf_1 U95 (
        .A(p0_axi_awaddr_2),
        .X(p2_axi_awaddr_2)
    );

    sky130_fd_sc_hd__buf_1 U96 (
        .A(p0_axi_awaddr_3),
        .X(p2_axi_awaddr_3)
    );

    sky130_fd_sc_hd__buf_1 U97 (
        .A(p0_axi_awaddr_4),
        .X(p2_axi_awaddr_4)
    );

    sky130_fd_sc_hd__buf_1 U98 (
        .A(p0_axi_awaddr_5),
        .X(p2_axi_awaddr_5)
    );

    sky130_fd_sc_hd__buf_1 U99 (
        .A(p0_axi_awaddr_6),
        .X(p2_axi_awaddr_6)
    );

    sky130_fd_sc_hd__buf_1 U100 (
        .A(p0_axi_awaddr_7),
        .X(p2_axi_awaddr_7)
    );

    sky130_fd_sc_hd__buf_1 U101 (
        .A(p0_axi_awaddr_8),
        .X(p2_axi_awaddr_8)
    );

    sky130_fd_sc_hd__buf_1 U102 (
        .A(p0_axi_awaddr_9),
        .X(p2_axi_awaddr_9)
    );

    sky130_fd_sc_hd__buf_1 U103 (
        .A(p0_axi_awaddr_10),
        .X(p2_axi_awaddr_10)
    );

    sky130_fd_sc_hd__buf_1 U104 (
        .A(p0_axi_awaddr_11),
        .X(p2_axi_awaddr_11)
    );

    sky130_fd_sc_hd__buf_1 U105 (
        .A(p0_axi_awvalid),
        .X(p2_axi_awvalid)
    );

    sky130_fd_sc_hd__buf_1 U106 (
        .A(p0_axi_wdata_0),
        .X(p2_axi_wdata_0)
    );

    sky130_fd_sc_hd__buf_1 U107 (
        .A(p0_axi_wdata_1),
        .X(p2_axi_wdata_1)
    );

    sky130_fd_sc_hd__buf_1 U108 (
        .A(p0_axi_wdata_2),
        .X(p2_axi_wdata_2)
    );

    sky130_fd_sc_hd__buf_1 U109 (
        .A(p0_axi_wdata_3),
        .X(p2_axi_wdata_3)
    );

    sky130_fd_sc_hd__buf_1 U110 (
        .A(p0_axi_wdata_4),
        .X(p2_axi_wdata_4)
    );

    sky130_fd_sc_hd__buf_1 U111 (
        .A(p0_axi_wdata_5),
        .X(p2_axi_wdata_5)
    );

    sky130_fd_sc_hd__buf_1 U112 (
        .A(p0_axi_wdata_6),
        .X(p2_axi_wdata_6)
    );

    sky130_fd_sc_hd__buf_1 U113 (
        .A(p0_axi_wdata_7),
        .X(p2_axi_wdata_7)
    );

    sky130_fd_sc_hd__buf_1 U114 (
        .A(p0_axi_wdata_8),
        .X(p2_axi_wdata_8)
    );

    sky130_fd_sc_hd__buf_1 U115 (
        .A(p0_axi_wdata_9),
        .X(p2_axi_wdata_9)
    );

    sky130_fd_sc_hd__buf_1 U116 (
        .A(p0_axi_wdata_10),
        .X(p2_axi_wdata_10)
    );

    sky130_fd_sc_hd__buf_1 U117 (
        .A(p0_axi_wdata_11),
        .X(p2_axi_wdata_11)
    );

    sky130_fd_sc_hd__buf_1 U118 (
        .A(p0_axi_wdata_12),
        .X(p2_axi_wdata_12)
    );

    sky130_fd_sc_hd__buf_1 U119 (
        .A(p0_axi_wdata_13),
        .X(p2_axi_wdata_13)
    );

    sky130_fd_sc_hd__buf_1 U120 (
        .A(p0_axi_wdata_14),
        .X(p2_axi_wdata_14)
    );

    sky130_fd_sc_hd__buf_1 U121 (
        .A(p0_axi_wdata_15),
        .X(p2_axi_wdata_15)
    );

    sky130_fd_sc_hd__buf_1 U122 (
        .A(p0_axi_wdata_16),
        .X(p2_axi_wdata_16)
    );

    sky130_fd_sc_hd__buf_1 U123 (
        .A(p0_axi_wdata_17),
        .X(p2_axi_wdata_17)
    );

    sky130_fd_sc_hd__buf_1 U124 (
        .A(p0_axi_wdata_18),
        .X(p2_axi_wdata_18)
    );

    sky130_fd_sc_hd__buf_1 U125 (
        .A(p0_axi_wdata_19),
        .X(p2_axi_wdata_19)
    );

    sky130_fd_sc_hd__buf_1 U126 (
        .A(p0_axi_wdata_20),
        .X(p2_axi_wdata_20)
    );

    sky130_fd_sc_hd__buf_1 U127 (
        .A(p0_axi_wdata_21),
        .X(p2_axi_wdata_21)
    );

    sky130_fd_sc_hd__buf_1 U128 (
        .A(p0_axi_wdata_22),
        .X(p2_axi_wdata_22)
    );

    sky130_fd_sc_hd__buf_1 U129 (
        .A(p0_axi_wdata_23),
        .X(p2_axi_wdata_23)
    );

    sky130_fd_sc_hd__buf_1 U130 (
        .A(p0_axi_wdata_24),
        .X(p2_axi_wdata_24)
    );

    sky130_fd_sc_hd__buf_1 U131 (
        .A(p0_axi_wdata_25),
        .X(p2_axi_wdata_25)
    );

    sky130_fd_sc_hd__buf_1 U132 (
        .A(p0_axi_wdata_26),
        .X(p2_axi_wdata_26)
    );

    sky130_fd_sc_hd__buf_1 U133 (
        .A(p0_axi_wdata_27),
        .X(p2_axi_wdata_27)
    );

    sky130_fd_sc_hd__buf_1 U134 (
        .A(p0_axi_wdata_28),
        .X(p2_axi_wdata_28)
    );

    sky130_fd_sc_hd__buf_1 U135 (
        .A(p0_axi_wdata_29),
        .X(p2_axi_wdata_29)
    );

    sky130_fd_sc_hd__buf_1 U136 (
        .A(p0_axi_wdata_30),
        .X(p2_axi_wdata_30)
    );

    sky130_fd_sc_hd__buf_1 U137 (
        .A(p0_axi_wdata_31),
        .X(p2_axi_wdata_31)
    );

    sky130_fd_sc_hd__buf_1 U138 (
        .A(p0_axi_wstrb_0),
        .X(p2_axi_wstrb_0)
    );

    sky130_fd_sc_hd__buf_1 U139 (
        .A(p0_axi_wstrb_1),
        .X(p2_axi_wstrb_1)
    );

    sky130_fd_sc_hd__buf_1 U140 (
        .A(p0_axi_wstrb_2),
        .X(p2_axi_wstrb_2)
    );

    sky130_fd_sc_hd__buf_1 U141 (
        .A(p0_axi_wstrb_3),
        .X(p2_axi_wstrb_3)
    );

    sky130_fd_sc_hd__buf_1 U142 (
        .A(s_axi_wready),
        .X(p2_axi_wvalid)
    );

    sky130_fd_sc_hd__buf_1 U143 (
        .A(p0_axi_bready),
        .X(p2_axi_bready)
    );

    sky130_fd_sc_hd__buf_1 U144 (
        .A(p0_axi_araddr_0),
        .X(p2_axi_araddr_0)
    );

    sky130_fd_sc_hd__buf_1 U145 (
        .A(p0_axi_araddr_1),
        .X(p2_axi_araddr_1)
    );

    sky130_fd_sc_hd__buf_1 U146 (
        .A(p0_axi_araddr_2),
        .X(p2_axi_araddr_2)
    );

    sky130_fd_sc_hd__buf_1 U147 (
        .A(p0_axi_araddr_3),
        .X(p2_axi_araddr_3)
    );

    sky130_fd_sc_hd__buf_1 U148 (
        .A(p0_axi_araddr_4),
        .X(p2_axi_araddr_4)
    );

    sky130_fd_sc_hd__buf_1 U149 (
        .A(p0_axi_araddr_5),
        .X(p2_axi_araddr_5)
    );

    sky130_fd_sc_hd__buf_1 U150 (
        .A(p0_axi_araddr_6),
        .X(p2_axi_araddr_6)
    );

    sky130_fd_sc_hd__buf_1 U151 (
        .A(p0_axi_araddr_7),
        .X(p2_axi_araddr_7)
    );

    sky130_fd_sc_hd__buf_1 U152 (
        .A(p0_axi_araddr_8),
        .X(p2_axi_araddr_8)
    );

    sky130_fd_sc_hd__buf_1 U153 (
        .A(p0_axi_araddr_9),
        .X(p2_axi_araddr_9)
    );

    sky130_fd_sc_hd__buf_1 U154 (
        .A(p0_axi_araddr_10),
        .X(p2_axi_araddr_10)
    );

    sky130_fd_sc_hd__buf_1 U155 (
        .A(p0_axi_araddr_11),
        .X(p2_axi_araddr_11)
    );

    sky130_fd_sc_hd__buf_1 U156 (
        .A(p0_axi_arvalid),
        .X(p2_axi_arvalid)
    );

    sky130_fd_sc_hd__buf_1 U157 (
        .A(s_axi_wready),
        .X(p2_axi_rready)
    );

    sky130_fd_sc_hd__buf_1 U158 (
        .A(p0_axi_awaddr_0),
        .X(p3_axi_awaddr_0)
    );

    sky130_fd_sc_hd__buf_1 U159 (
        .A(p0_axi_awaddr_1),
        .X(p3_axi_awaddr_1)
    );

    sky130_fd_sc_hd__buf_1 U160 (
        .A(p0_axi_awaddr_2),
        .X(p3_axi_awaddr_2)
    );

    sky130_fd_sc_hd__buf_1 U161 (
        .A(p0_axi_awaddr_3),
        .X(p3_axi_awaddr_3)
    );

    sky130_fd_sc_hd__buf_1 U162 (
        .A(p0_axi_awaddr_4),
        .X(p3_axi_awaddr_4)
    );

    sky130_fd_sc_hd__buf_1 U163 (
        .A(p0_axi_awaddr_5),
        .X(p3_axi_awaddr_5)
    );

    sky130_fd_sc_hd__buf_1 U164 (
        .A(p0_axi_awaddr_6),
        .X(p3_axi_awaddr_6)
    );

    sky130_fd_sc_hd__buf_1 U165 (
        .A(p0_axi_awaddr_7),
        .X(p3_axi_awaddr_7)
    );

    sky130_fd_sc_hd__buf_1 U166 (
        .A(p0_axi_awaddr_8),
        .X(p3_axi_awaddr_8)
    );

    sky130_fd_sc_hd__buf_1 U167 (
        .A(p0_axi_awaddr_9),
        .X(p3_axi_awaddr_9)
    );

    sky130_fd_sc_hd__buf_1 U168 (
        .A(p0_axi_awaddr_10),
        .X(p3_axi_awaddr_10)
    );

    sky130_fd_sc_hd__buf_1 U169 (
        .A(p0_axi_awaddr_11),
        .X(p3_axi_awaddr_11)
    );

    sky130_fd_sc_hd__buf_1 U170 (
        .A(s_axi_wready),
        .X(p3_axi_awvalid)
    );

    sky130_fd_sc_hd__buf_1 U171 (
        .A(p0_axi_wdata_0),
        .X(p3_axi_wdata_0)
    );

    sky130_fd_sc_hd__buf_1 U172 (
        .A(p0_axi_wdata_1),
        .X(p3_axi_wdata_1)
    );

    sky130_fd_sc_hd__buf_1 U173 (
        .A(p0_axi_wdata_2),
        .X(p3_axi_wdata_2)
    );

    sky130_fd_sc_hd__buf_1 U174 (
        .A(p0_axi_wdata_3),
        .X(p3_axi_wdata_3)
    );

    sky130_fd_sc_hd__buf_1 U175 (
        .A(p0_axi_wdata_4),
        .X(p3_axi_wdata_4)
    );

    sky130_fd_sc_hd__buf_1 U176 (
        .A(p0_axi_wdata_5),
        .X(p3_axi_wdata_5)
    );

    sky130_fd_sc_hd__buf_1 U177 (
        .A(p0_axi_wdata_6),
        .X(p3_axi_wdata_6)
    );

    sky130_fd_sc_hd__buf_1 U178 (
        .A(p0_axi_wdata_7),
        .X(p3_axi_wdata_7)
    );

    sky130_fd_sc_hd__buf_1 U179 (
        .A(p0_axi_wdata_8),
        .X(p3_axi_wdata_8)
    );

    sky130_fd_sc_hd__buf_1 U180 (
        .A(p0_axi_wdata_9),
        .X(p3_axi_wdata_9)
    );

    sky130_fd_sc_hd__buf_1 U181 (
        .A(p0_axi_wdata_10),
        .X(p3_axi_wdata_10)
    );

    sky130_fd_sc_hd__buf_1 U182 (
        .A(p0_axi_wdata_11),
        .X(p3_axi_wdata_11)
    );

    sky130_fd_sc_hd__buf_1 U183 (
        .A(p0_axi_wdata_12),
        .X(p3_axi_wdata_12)
    );

    sky130_fd_sc_hd__buf_1 U184 (
        .A(p0_axi_wdata_13),
        .X(p3_axi_wdata_13)
    );

    sky130_fd_sc_hd__buf_1 U185 (
        .A(p0_axi_wdata_14),
        .X(p3_axi_wdata_14)
    );

    sky130_fd_sc_hd__buf_1 U186 (
        .A(p0_axi_wdata_15),
        .X(p3_axi_wdata_15)
    );

    sky130_fd_sc_hd__buf_1 U187 (
        .A(p0_axi_wdata_16),
        .X(p3_axi_wdata_16)
    );

    sky130_fd_sc_hd__buf_1 U188 (
        .A(p0_axi_wdata_17),
        .X(p3_axi_wdata_17)
    );

    sky130_fd_sc_hd__buf_1 U189 (
        .A(p0_axi_wdata_18),
        .X(p3_axi_wdata_18)
    );

    sky130_fd_sc_hd__buf_1 U190 (
        .A(p0_axi_wdata_19),
        .X(p3_axi_wdata_19)
    );

    sky130_fd_sc_hd__buf_1 U191 (
        .A(p0_axi_wdata_20),
        .X(p3_axi_wdata_20)
    );

    sky130_fd_sc_hd__buf_1 U192 (
        .A(p0_axi_wdata_21),
        .X(p3_axi_wdata_21)
    );

    sky130_fd_sc_hd__buf_1 U193 (
        .A(p0_axi_wdata_22),
        .X(p3_axi_wdata_22)
    );

    sky130_fd_sc_hd__buf_1 U194 (
        .A(p0_axi_wdata_23),
        .X(p3_axi_wdata_23)
    );

    sky130_fd_sc_hd__buf_1 U195 (
        .A(p0_axi_wdata_24),
        .X(p3_axi_wdata_24)
    );

    sky130_fd_sc_hd__buf_1 U196 (
        .A(p0_axi_wdata_25),
        .X(p3_axi_wdata_25)
    );

    sky130_fd_sc_hd__buf_1 U197 (
        .A(p0_axi_wdata_26),
        .X(p3_axi_wdata_26)
    );

    sky130_fd_sc_hd__buf_1 U198 (
        .A(p0_axi_wdata_27),
        .X(p3_axi_wdata_27)
    );

    sky130_fd_sc_hd__buf_1 U199 (
        .A(p0_axi_wdata_28),
        .X(p3_axi_wdata_28)
    );

    sky130_fd_sc_hd__buf_1 U200 (
        .A(p0_axi_wdata_29),
        .X(p3_axi_wdata_29)
    );

    sky130_fd_sc_hd__buf_1 U201 (
        .A(p0_axi_wdata_30),
        .X(p3_axi_wdata_30)
    );

    sky130_fd_sc_hd__buf_1 U202 (
        .A(p0_axi_wdata_31),
        .X(p3_axi_wdata_31)
    );

    sky130_fd_sc_hd__buf_1 U203 (
        .A(p0_axi_wstrb_0),
        .X(p3_axi_wstrb_0)
    );

    sky130_fd_sc_hd__buf_1 U204 (
        .A(p0_axi_wstrb_1),
        .X(p3_axi_wstrb_1)
    );

    sky130_fd_sc_hd__buf_1 U205 (
        .A(p0_axi_wstrb_2),
        .X(p3_axi_wstrb_2)
    );

    sky130_fd_sc_hd__buf_1 U206 (
        .A(p0_axi_wstrb_3),
        .X(p3_axi_wstrb_3)
    );

    sky130_fd_sc_hd__buf_1 U207 (
        .A(s_axi_wready),
        .X(p3_axi_wvalid)
    );

    sky130_fd_sc_hd__buf_1 U208 (
        .A(s_axi_wready),
        .X(p3_axi_bready)
    );

    sky130_fd_sc_hd__buf_1 U209 (
        .A(p0_axi_araddr_0),
        .X(p3_axi_araddr_0)
    );

    sky130_fd_sc_hd__buf_1 U210 (
        .A(p0_axi_araddr_1),
        .X(p3_axi_araddr_1)
    );

    sky130_fd_sc_hd__buf_1 U211 (
        .A(p0_axi_araddr_2),
        .X(p3_axi_araddr_2)
    );

    sky130_fd_sc_hd__buf_1 U212 (
        .A(p0_axi_araddr_3),
        .X(p3_axi_araddr_3)
    );

    sky130_fd_sc_hd__buf_1 U213 (
        .A(p0_axi_araddr_4),
        .X(p3_axi_araddr_4)
    );

    sky130_fd_sc_hd__buf_1 U214 (
        .A(p0_axi_araddr_5),
        .X(p3_axi_araddr_5)
    );

    sky130_fd_sc_hd__buf_1 U215 (
        .A(p0_axi_araddr_6),
        .X(p3_axi_araddr_6)
    );

    sky130_fd_sc_hd__buf_1 U216 (
        .A(p0_axi_araddr_7),
        .X(p3_axi_araddr_7)
    );

    sky130_fd_sc_hd__buf_1 U217 (
        .A(p0_axi_araddr_8),
        .X(p3_axi_araddr_8)
    );

    sky130_fd_sc_hd__buf_1 U218 (
        .A(p0_axi_araddr_9),
        .X(p3_axi_araddr_9)
    );

    sky130_fd_sc_hd__buf_1 U219 (
        .A(p0_axi_araddr_10),
        .X(p3_axi_araddr_10)
    );

    sky130_fd_sc_hd__buf_1 U220 (
        .A(p0_axi_araddr_11),
        .X(p3_axi_araddr_11)
    );

    sky130_fd_sc_hd__buf_1 U221 (
        .A(s_axi_wready),
        .X(p3_axi_arvalid)
    );

    sky130_fd_sc_hd__buf_1 U222 (
        .A(s_axi_wready),
        .X(p3_axi_rready)
    );

    sky130_fd_sc_hd__buf_1 U223 (
        .A(s_axi_wready),
        .X(__dff_d_ff767)
    );

    sky130_fd_sc_hd__buf_1 U224 (
        .A(s_axi_wready),
        .X(__dff_d_ff768)
    );

    sky130_fd_sc_hd__buf_1 U225 (
        .A(s_axi_wready),
        .X(__dff_d_ff1026)
    );

    sky130_fd_sc_hd__buf_1 U226 (
        .A(s_axi_wready),
        .X(__dff_d_ff1027)
    );

    sky130_fd_sc_hd__dfrtp_1 U227 (
        .D(__dff_d_ff764),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wmiss)
    );

    sky130_fd_sc_hd__dfrtp_1 U228 (
        .D(__dff_d_ff765),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wsel_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U229 (
        .D(__dff_d_ff766),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wsel_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U230 (
        .D(__dff_d_ff767),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wstate_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U231 (
        .D(__dff_d_ff768),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(wstate_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U232 (
        .D(__dff_d_ff1023),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rmiss)
    );

    sky130_fd_sc_hd__dfrtp_1 U233 (
        .D(__dff_d_ff1024),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rsel_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U234 (
        .D(__dff_d_ff1025),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rsel_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U235 (
        .D(__dff_d_ff1026),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rstate_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U236 (
        .D(__dff_d_ff1027),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rstate_1)
    );

endmodule
