// Generated by My Own Flow — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module soc_top (
    input ref_clk,
    input ext_reset_n,
    input jtag_tck,
    input jtag_tms,
    input jtag_tdi,
    input jtag_trst_n,
    input uart_rx,
    input spi_miso,
    input i2c_sda_in,
    input i2c_scl_in,
    input gpio_in_0,
    input gpio_in_1,
    input gpio_in_2,
    input gpio_in_3,
    input gpio_in_4,
    input gpio_in_5,
    input gpio_in_6,
    input gpio_in_7,
    input gpio_in_8,
    input gpio_in_9,
    input gpio_in_10,
    input gpio_in_11,
    input gpio_in_12,
    input gpio_in_13,
    input gpio_in_14,
    input gpio_in_15,
    input gpio_in_16,
    input gpio_in_17,
    input gpio_in_18,
    input gpio_in_19,
    input gpio_in_20,
    input gpio_in_21,
    input gpio_in_22,
    input gpio_in_23,
    input gpio_in_24,
    input gpio_in_25,
    input gpio_in_26,
    input gpio_in_27,
    input gpio_in_28,
    input gpio_in_29,
    input gpio_in_30,
    input gpio_in_31,
    input boot_mode_0,
    input boot_mode_1,
    input ext_wake_0,
    input ext_wake_1,
    input ext_wake_2,
    input ext_wake_3,
    output jtag_tdo,
    output uart_tx,
    output spi_sclk,
    output spi_mosi,
    output spi_cs_n,
    output i2c_scl_oe,
    output i2c_sda_oe,
    output gpio_out_0,
    output gpio_out_1,
    output gpio_out_2,
    output gpio_out_3,
    output gpio_out_4,
    output gpio_out_5,
    output gpio_out_6,
    output gpio_out_7,
    output gpio_out_8,
    output gpio_out_9,
    output gpio_out_10,
    output gpio_out_11,
    output gpio_out_12,
    output gpio_out_13,
    output gpio_out_14,
    output gpio_out_15,
    output gpio_out_16,
    output gpio_out_17,
    output gpio_out_18,
    output gpio_out_19,
    output gpio_out_20,
    output gpio_out_21,
    output gpio_out_22,
    output gpio_out_23,
    output gpio_out_24,
    output gpio_out_25,
    output gpio_out_26,
    output gpio_out_27,
    output gpio_out_28,
    output gpio_out_29,
    output gpio_out_30,
    output gpio_out_31,
    output gpio_oe_0,
    output gpio_oe_1,
    output gpio_oe_2,
    output gpio_oe_3,
    output gpio_oe_4,
    output gpio_oe_5,
    output gpio_oe_6,
    output gpio_oe_7,
    output gpio_oe_8,
    output gpio_oe_9,
    output gpio_oe_10,
    output gpio_oe_11,
    output gpio_oe_12,
    output gpio_oe_13,
    output gpio_oe_14,
    output gpio_oe_15,
    output gpio_oe_16,
    output gpio_oe_17,
    output gpio_oe_18,
    output gpio_oe_19,
    output gpio_oe_20,
    output gpio_oe_21,
    output gpio_oe_22,
    output gpio_oe_23,
    output gpio_oe_24,
    output gpio_oe_25,
    output gpio_oe_26,
    output gpio_oe_27,
    output gpio_oe_28,
    output gpio_oe_29,
    output gpio_oe_30,
    output gpio_oe_31
);

    wire buf_jtag_tdo_0;
    wire buf_jtag_tdo_1;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(jtag_tdo));
    sky130_fd_sc_hd__buf_1 U0 (
        .A(buf_jtag_tdo_0),
        .X(uart_tx)
    );

    sky130_fd_sc_hd__buf_1 U1 (
        .A(buf_jtag_tdo_0),
        .X(spi_sclk)
    );

    sky130_fd_sc_hd__buf_1 U2 (
        .A(buf_jtag_tdo_0),
        .X(spi_mosi)
    );

    sky130_fd_sc_hd__buf_1 U3 (
        .A(buf_jtag_tdo_0),
        .X(spi_cs_n)
    );

    sky130_fd_sc_hd__buf_1 U4 (
        .A(buf_jtag_tdo_0),
        .X(i2c_scl_oe)
    );

    sky130_fd_sc_hd__buf_1 U5 (
        .A(buf_jtag_tdo_0),
        .X(i2c_sda_oe)
    );

    sky130_fd_sc_hd__buf_1 U6 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_0)
    );

    sky130_fd_sc_hd__buf_1 U7 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_1)
    );

    sky130_fd_sc_hd__buf_1 U8 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_2)
    );

    sky130_fd_sc_hd__buf_1 U9 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_3)
    );

    sky130_fd_sc_hd__buf_1 U10 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_4)
    );

    sky130_fd_sc_hd__buf_1 U11 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_5)
    );

    sky130_fd_sc_hd__buf_1 U12 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_6)
    );

    sky130_fd_sc_hd__buf_1 U13 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_7)
    );

    sky130_fd_sc_hd__buf_1 U14 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_8)
    );

    sky130_fd_sc_hd__buf_1 U15 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_9)
    );

    sky130_fd_sc_hd__buf_1 U16 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_10)
    );

    sky130_fd_sc_hd__buf_1 U17 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_11)
    );

    sky130_fd_sc_hd__buf_1 U18 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_12)
    );

    sky130_fd_sc_hd__buf_1 U19 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_13)
    );

    sky130_fd_sc_hd__buf_1 U20 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_14)
    );

    sky130_fd_sc_hd__buf_1 U21 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_15)
    );

    sky130_fd_sc_hd__buf_1 U22 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_16)
    );

    sky130_fd_sc_hd__buf_1 U23 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_17)
    );

    sky130_fd_sc_hd__buf_1 U24 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_18)
    );

    sky130_fd_sc_hd__buf_1 U25 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_19)
    );

    sky130_fd_sc_hd__buf_1 U26 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_20)
    );

    sky130_fd_sc_hd__buf_1 U27 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_21)
    );

    sky130_fd_sc_hd__buf_1 U28 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_22)
    );

    sky130_fd_sc_hd__buf_1 U29 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_23)
    );

    sky130_fd_sc_hd__buf_1 U30 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_24)
    );

    sky130_fd_sc_hd__buf_1 U31 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_25)
    );

    sky130_fd_sc_hd__buf_1 U32 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_26)
    );

    sky130_fd_sc_hd__buf_1 U33 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_27)
    );

    sky130_fd_sc_hd__buf_1 U34 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_28)
    );

    sky130_fd_sc_hd__buf_1 U35 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_29)
    );

    sky130_fd_sc_hd__buf_1 U36 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_30)
    );

    sky130_fd_sc_hd__buf_1 U37 (
        .A(buf_jtag_tdo_0),
        .X(gpio_out_31)
    );

    sky130_fd_sc_hd__buf_1 U38 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_0)
    );

    sky130_fd_sc_hd__buf_1 U39 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_1)
    );

    sky130_fd_sc_hd__buf_1 U40 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_2)
    );

    sky130_fd_sc_hd__buf_1 U41 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_3)
    );

    sky130_fd_sc_hd__buf_1 U42 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_4)
    );

    sky130_fd_sc_hd__buf_1 U43 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_5)
    );

    sky130_fd_sc_hd__buf_1 U44 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_6)
    );

    sky130_fd_sc_hd__buf_1 U45 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_7)
    );

    sky130_fd_sc_hd__buf_1 U46 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_8)
    );

    sky130_fd_sc_hd__buf_1 U47 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_9)
    );

    sky130_fd_sc_hd__buf_1 U48 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_10)
    );

    sky130_fd_sc_hd__buf_1 U49 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_11)
    );

    sky130_fd_sc_hd__buf_1 U50 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_12)
    );

    sky130_fd_sc_hd__buf_1 U51 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_13)
    );

    sky130_fd_sc_hd__buf_1 U52 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_14)
    );

    sky130_fd_sc_hd__buf_1 U53 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_15)
    );

    sky130_fd_sc_hd__buf_1 U54 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_16)
    );

    sky130_fd_sc_hd__buf_1 U55 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_17)
    );

    sky130_fd_sc_hd__buf_1 U56 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_18)
    );

    sky130_fd_sc_hd__buf_1 U57 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_19)
    );

    sky130_fd_sc_hd__buf_1 U58 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_20)
    );

    sky130_fd_sc_hd__buf_1 U59 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_21)
    );

    sky130_fd_sc_hd__buf_1 U60 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_22)
    );

    sky130_fd_sc_hd__buf_1 U61 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_23)
    );

    sky130_fd_sc_hd__buf_1 U62 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_24)
    );

    sky130_fd_sc_hd__buf_1 U63 (
        .A(buf_jtag_tdo_0),
        .X(gpio_oe_25)
    );

    sky130_fd_sc_hd__buf_1 U64 (
        .A(buf_jtag_tdo_1),
        .X(gpio_oe_26)
    );

    sky130_fd_sc_hd__buf_1 U65 (
        .A(buf_jtag_tdo_1),
        .X(gpio_oe_27)
    );

    sky130_fd_sc_hd__buf_1 U66 (
        .A(buf_jtag_tdo_1),
        .X(gpio_oe_28)
    );

    sky130_fd_sc_hd__buf_1 U67 (
        .A(buf_jtag_tdo_1),
        .X(gpio_oe_29)
    );

    sky130_fd_sc_hd__buf_1 U68 (
        .A(buf_jtag_tdo_1),
        .X(gpio_oe_30)
    );

    sky130_fd_sc_hd__buf_1 U69 (
        .A(buf_jtag_tdo_1),
        .X(gpio_oe_31)
    );

    sky130_fd_sc_hd__buf_1 U70 (
        .A(jtag_tdo),
        .X(buf_jtag_tdo_1)
    );

    sky130_fd_sc_hd__conb_1 UTIE_0 (.LO(buf_jtag_tdo_0));
endmodule
