// Generated by SiliconForge — SKY130 Export for OpenLane
// Target: sky130_fd_sc_hd standard cell library

module uart_rx (
    input clk,
    input rst_n,
    input rx_in,
    output rx_data_0,
    output rx_data_1,
    output rx_data_2,
    output rx_data_3,
    output rx_data_4,
    output rx_data_5,
    output rx_data_6,
    output rx_data_7,
    output rx_error,
    output rx_valid
);

    wire rx_ff2;
    wire bit_idx;
    wire clk_cnt;
    wire parity_bit;
    wire shift_r_0;
    wire shift_r_1;
    wire shift_r_2;
    wire shift_r_3;
    wire shift_r_4;
    wire shift_r_5;
    wire shift_r_6;
    wire shift_r_7;
    wire state_0;
    wire state_1;
    wire state_2;
    wire __dff_d_ff537;
    wire __dff_d_ff11;
    wire inv_n2;
    wire n32;
    wire __dff_d_ff526;
    wire __dff_d_ff527;
    wire n37;
    wire n40;
    wire __dff_d_ff528;
    wire n44;
    wire __dff_d_ff529;
    wire n46;
    wire inv_n10;
    wire n49;
    wire __dff_d_ff530;
    wire n51;
    wire inv_n11;
    wire n54;
    wire __dff_d_ff531;
    wire n56;
    wire inv_n12;
    wire n59;
    wire __dff_d_ff532;
    wire n61;
    wire inv_n13;
    wire n64;
    wire __dff_d_ff533;
    wire n66;
    wire inv_n14;
    wire n69;
    wire __dff_d_ff534;
    wire n71;
    wire inv_n15;
    wire n74;
    wire __dff_d_ff535;
    wire n76;
    wire inv_n16;
    wire n79;
    wire __dff_d_ff536;
    wire n82;
    wire __dff_d_ff539;
    wire __dff_d_ff540;
    wire __dff_d_ff541;
    wire __dff_d_ff542;
    wire __dff_d_ff543;
    wire __dff_d_ff544;
    wire __dff_d_ff545;
    wire __dff_d_ff546;
    wire __dff_d_ff547;
    wire inv_n27;
    wire __dff_d_ff12;
    wire __dff_d_ff538;
    wire __dff_d_ff548;
    wire __dff_d_ff549;
    wire clone_4;
    wire clone_10;

    sky130_fd_sc_hd__conb_1 UTIE0_0 (.LO(__dff_d_ff537));
    sky130_fd_sc_hd__inv_1 U0 (
        .A(rst_n),
        .Y(inv_n2)
    );

    sky130_fd_sc_hd__nor2b_1 U1 (
        .A(rx_in),
        .B_N(rst_n),
        .Y(__dff_d_ff11)
    );

    sky130_fd_sc_hd__nor3_2 U2 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .Y(n32)
    );

    sky130_fd_sc_hd__nand3_1 U3 (
        .A(rst_n),
        .B(bit_idx),
        .C(clone_4),
        .Y(__dff_d_ff526)
    );

    sky130_fd_sc_hd__nand3_1 U4 (
        .A(rst_n),
        .B(clk_cnt),
        .C(clone_4),
        .Y(__dff_d_ff527)
    );

    sky130_fd_sc_hd__nand2_1 U5 (
        .A(clk_cnt),
        .B(n32),
        .Y(n37)
    );

    sky130_fd_sc_hd__mux2_1 U6 (
        .A0(rx_ff2),
        .A1(parity_bit),
        .S(n37),
        .X(n40)
    );

    sky130_fd_sc_hd__nor2b_1 U7 (
        .A(n40),
        .B_N(rst_n),
        .Y(__dff_d_ff528)
    );

    sky130_fd_sc_hd__o21a_1 U8 (
        .A1(shift_r_0),
        .A2(clone_10),
        .B1(rst_n),
        .X(n44)
    );

    sky130_fd_sc_hd__o21a_1 U9 (
        .A1(rx_data_0),
        .A2(n37),
        .B1(n44),
        .X(__dff_d_ff529)
    );

    sky130_fd_sc_hd__nor2b_1 U10 (
        .A(n37),
        .B_N(rx_data_1),
        .Y(n46)
    );

    sky130_fd_sc_hd__a31oi_1 U11 (
        .A1(clk_cnt),
        .A2(shift_r_1),
        .A3(n32),
        .B1(n46),
        .Y(n49)
    );

    sky130_fd_sc_hd__nor2b_1 U12 (
        .A(n49),
        .B_N(rst_n),
        .Y(__dff_d_ff530)
    );

    sky130_fd_sc_hd__nor2b_1 U13 (
        .A(n37),
        .B_N(rx_data_2),
        .Y(n51)
    );

    sky130_fd_sc_hd__a31oi_1 U14 (
        .A1(clk_cnt),
        .A2(shift_r_2),
        .A3(n32),
        .B1(n51),
        .Y(n54)
    );

    sky130_fd_sc_hd__nor2b_1 U15 (
        .A(n54),
        .B_N(rst_n),
        .Y(__dff_d_ff531)
    );

    sky130_fd_sc_hd__nor2b_1 U16 (
        .A(n37),
        .B_N(rx_data_3),
        .Y(n56)
    );

    sky130_fd_sc_hd__a31oi_1 U17 (
        .A1(clk_cnt),
        .A2(shift_r_3),
        .A3(n32),
        .B1(n56),
        .Y(n59)
    );

    sky130_fd_sc_hd__nor2b_1 U18 (
        .A(n59),
        .B_N(rst_n),
        .Y(__dff_d_ff532)
    );

    sky130_fd_sc_hd__nor2b_1 U19 (
        .A(n37),
        .B_N(rx_data_4),
        .Y(n61)
    );

    sky130_fd_sc_hd__a31oi_1 U20 (
        .A1(clk_cnt),
        .A2(shift_r_4),
        .A3(n32),
        .B1(n61),
        .Y(n64)
    );

    sky130_fd_sc_hd__nor2b_1 U21 (
        .A(n64),
        .B_N(rst_n),
        .Y(__dff_d_ff533)
    );

    sky130_fd_sc_hd__nor2b_1 U22 (
        .A(n37),
        .B_N(rx_data_5),
        .Y(n66)
    );

    sky130_fd_sc_hd__a31oi_1 U23 (
        .A1(clk_cnt),
        .A2(shift_r_5),
        .A3(n32),
        .B1(n66),
        .Y(n69)
    );

    sky130_fd_sc_hd__nor2b_1 U24 (
        .A(n69),
        .B_N(rst_n),
        .Y(__dff_d_ff534)
    );

    sky130_fd_sc_hd__nor2b_1 U25 (
        .A(n37),
        .B_N(rx_data_6),
        .Y(n71)
    );

    sky130_fd_sc_hd__a31oi_1 U26 (
        .A1(clk_cnt),
        .A2(shift_r_6),
        .A3(n32),
        .B1(n71),
        .Y(n74)
    );

    sky130_fd_sc_hd__nor2b_1 U27 (
        .A(n74),
        .B_N(rst_n),
        .Y(__dff_d_ff535)
    );

    sky130_fd_sc_hd__nor2b_1 U28 (
        .A(n37),
        .B_N(rx_data_7),
        .Y(n76)
    );

    sky130_fd_sc_hd__a31oi_1 U29 (
        .A1(clk_cnt),
        .A2(shift_r_7),
        .A3(n32),
        .B1(n76),
        .Y(n79)
    );

    sky130_fd_sc_hd__nor2b_1 U30 (
        .A(n79),
        .B_N(rst_n),
        .Y(__dff_d_ff536)
    );

    sky130_fd_sc_hd__mux2_1 U31 (
        .A0(rx_ff2),
        .A1(shift_r_0),
        .S(n37),
        .X(n82)
    );

    sky130_fd_sc_hd__nor2b_1 U32 (
        .A(n82),
        .B_N(rst_n),
        .Y(__dff_d_ff539)
    );

    sky130_fd_sc_hd__nand2_1 U33 (
        .A(rst_n),
        .B(shift_r_1),
        .Y(__dff_d_ff540)
    );

    sky130_fd_sc_hd__nand2_1 U34 (
        .A(rst_n),
        .B(shift_r_2),
        .Y(__dff_d_ff541)
    );

    sky130_fd_sc_hd__nand2_1 U35 (
        .A(rst_n),
        .B(shift_r_3),
        .Y(__dff_d_ff542)
    );

    sky130_fd_sc_hd__nand2_1 U36 (
        .A(rst_n),
        .B(shift_r_4),
        .Y(__dff_d_ff543)
    );

    sky130_fd_sc_hd__nand2_1 U37 (
        .A(rst_n),
        .B(shift_r_5),
        .Y(__dff_d_ff544)
    );

    sky130_fd_sc_hd__nand2_1 U38 (
        .A(rst_n),
        .B(shift_r_6),
        .Y(__dff_d_ff545)
    );

    sky130_fd_sc_hd__nand2_1 U39 (
        .A(rst_n),
        .B(shift_r_7),
        .Y(__dff_d_ff546)
    );

    sky130_fd_sc_hd__inv_1 U40 (
        .A(state_0),
        .Y(inv_n27)
    );

    sky130_fd_sc_hd__a211oi_1 U41 (
        .A1(rx_ff2),
        .A2(inv_n27),
        .B1(inv_n2),
        .C1(clone_4),
        .Y(__dff_d_ff547)
    );

    sky130_fd_sc_hd__buf_1 U42 (
        .A(__dff_d_ff11),
        .X(__dff_d_ff12)
    );

    sky130_fd_sc_hd__buf_1 U43 (
        .A(__dff_d_ff537),
        .X(__dff_d_ff538)
    );

    sky130_fd_sc_hd__buf_1 U44 (
        .A(__dff_d_ff537),
        .X(__dff_d_ff548)
    );

    sky130_fd_sc_hd__buf_1 U45 (
        .A(__dff_d_ff537),
        .X(__dff_d_ff549)
    );

    sky130_fd_sc_hd__or3_1 U46 (
        .A(state_0),
        .B(state_1),
        .C(state_2),
        .X(clone_4)
    );

    sky130_fd_sc_hd__and2_1 U47 (
        .A(clk_cnt),
        .B(n32),
        .X(clone_10)
    );

    sky130_fd_sc_hd__dfrtp_1 U48 (
        .D(__dff_d_ff12),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_ff2)
    );

    sky130_fd_sc_hd__dfrtp_1 U49 (
        .D(__dff_d_ff526),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(bit_idx)
    );

    sky130_fd_sc_hd__dfrtp_1 U50 (
        .D(__dff_d_ff527),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(clk_cnt)
    );

    sky130_fd_sc_hd__dfrtp_1 U51 (
        .D(__dff_d_ff528),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(parity_bit)
    );

    sky130_fd_sc_hd__dfrtp_1 U52 (
        .D(__dff_d_ff529),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U53 (
        .D(__dff_d_ff530),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U54 (
        .D(__dff_d_ff531),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U55 (
        .D(__dff_d_ff532),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U56 (
        .D(__dff_d_ff533),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U57 (
        .D(__dff_d_ff534),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U58 (
        .D(__dff_d_ff535),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U59 (
        .D(__dff_d_ff536),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_data_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U60 (
        .D(__dff_d_ff537),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_error)
    );

    sky130_fd_sc_hd__dfrtp_1 U61 (
        .D(__dff_d_ff538),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(rx_valid)
    );

    sky130_fd_sc_hd__dfrtp_1 U62 (
        .D(__dff_d_ff539),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U63 (
        .D(__dff_d_ff540),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U64 (
        .D(__dff_d_ff541),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_2)
    );

    sky130_fd_sc_hd__dfrtp_1 U65 (
        .D(__dff_d_ff542),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_3)
    );

    sky130_fd_sc_hd__dfrtp_1 U66 (
        .D(__dff_d_ff543),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_4)
    );

    sky130_fd_sc_hd__dfrtp_1 U67 (
        .D(__dff_d_ff544),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_5)
    );

    sky130_fd_sc_hd__dfrtp_1 U68 (
        .D(__dff_d_ff545),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_6)
    );

    sky130_fd_sc_hd__dfrtp_1 U69 (
        .D(__dff_d_ff546),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(shift_r_7)
    );

    sky130_fd_sc_hd__dfrtp_1 U70 (
        .D(__dff_d_ff547),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(state_0)
    );

    sky130_fd_sc_hd__dfrtp_1 U71 (
        .D(__dff_d_ff548),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(state_1)
    );

    sky130_fd_sc_hd__dfrtp_1 U72 (
        .D(__dff_d_ff549),
        .CLK(clk),
        .RESET_B(rst_n),
        .Q(state_2)
    );

endmodule
